### PR TITLE
Ensure shipping rate names show when multiple packages are used

### LINKED ISSUE #6437: Cart packages names and content not rendered
When the cart contents are split into multiple packages via the "woocommerce_cart_shipping_packages" PHP filter the shipping rates at checkout for each package do appear as expected however there is no defining visual aid between them at checkout. So for example if there are 2 shipping methods available on the site then both methods appear twice as they should but there's no indication as to why they appear twice. When using the regular checkout shortcode the packages are separated, the contents of each package is clearly displayed with its corresponding package name, and the shipping methods associated with each package are shown in relation to the package. See the screenshots below: 

**Checkout with shortcode (note that the package name has been filtered via the "woocommerce_shipping_package_name" hook)**

checkout1

**Checkout with block, shipping options section:** 

checkout2

Edit:
## Steps to reproduce:

1. Install this free plugin from the WP plugin repository: "Multiple Packages for WooCommerce"
2. Navigate to WooCommerce -> Settings -> Multiple Packages
3. Adjust the settings to work based on "Per Product"
4. Add two different products to the cart and typically need shipping.
5. Go the checkout page and look at the shipping options.

### PR DESCRIPTION
**Pull request by opr**
This PR will ensure shipping rate names show when multiple shipping packages are in the cart. It will also fix an issue in the editor where shipping rates don't show.

To fix shipping rates not showing in the editor: in the `useShippingData` hook, we now check if we're in the editor, and if so show the values from `previewShippingRates`, or else we get it from the `wc/store/cart` data store.

To fix the issue of names not showing, I checked the value of `packageData?.shipping_rates?.length` in `ShippingRatesControl`. This is then used in the condition that determines whether to show the name or not
https://github.com/woocommerce/woocommerce-blocks/blob/5545c38c4bef7e0d9768c29802426d4956716f2c/assets/js/base/components/cart-checkout/shipping-rates-control-package/index.tsx#L72-L76
it defaulted to false.

Fixes #6437

### Screenshots

| Before | After |
| ------ | ----- |
|  | image |

👆🏻 **note the spacing is fixed in #6740** 👆🏻

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Install the ["Multiple Packages for WooCommerce" plugin](https://wordpress.org/plugins/multiple-packages-for-woocommerce/)
2. Navigate to WooCommerce -> Settings -> Multiple Packages
3. Adjust the settings to work based on "Per Product"
4. Add two/three/four different products to the cart and typically need shipping.
5. Go the checkout page and look at the shipping options, ensure there is a title for each one.
6. Disable the plugin and reload the Checkout Block, ensure the shipping section still looks OK.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [x] Feature plugin
* [ ] Experimental

### Changelog

> Ensure shipping package names are shown correctly in the Checkout Block when a cart contains multiple packages.

### CODE REVIEW

**Review by wavvves — APPROVED** [review]
LGTM! 😎

image

File: assets/js/base/components/cart-checkout/shipping-rates-control/index.tsx [hunk 1]
```diff
@@ -65,7 +65,9 @@ const Packages = ( {
 					packageData={ packageData }
 					collapsible={ collapsible }
 					collapse={ collapse }
-					showItems={ showItems }
+					showItems={
+						showItems || packageData?.shipping_rates?.length > 1
```
Comment (senadir) [inline assets/js/base/components/cart-checkout/shipping-rates-control/index.tsx:69]: This logic will evaluate to true when you have multiple shipping rates within a single package, not overall.

Comment (senadir) [reply assets/js/base/components/cart-checkout/shipping-rates-control/index.tsx:69]: Logic should be `showItems || packages.length > 1`
