### PR TITLE
Checkout block: Full width Place Order button when Return To Cart link is disabled.

### LINKED ISSUE #9205: Inconsistent `Place Order` button placement
## Describe the bug

When a merchant hides the `Return to Cart` link within the Checkout block, the `Place Order` button is right-aligned within the post editor, but left-aligned in the frontend. This issue was reported by @kmanijak in p1682408862016089/1682354698.473329-slack-C02UBB1EPEF.

## To reproduce

1. Create a test page and add the Checkout block.
2. Open the `Document Overview`.
3. Go to `Checkout » Checkout Fields » Actions`.
Screen Shot 2023-04-26 at 09 01 52

4. Uncheck the checkbox `Show a "Return to Cart" link`.
Screen Shot 2023-04-26 at 08 51 21

5. Save the test page.
6. Verify that the `Place Order` button is right-aligned.
7. Go to the frontend and add a product to the cart.
8. Go to the test page with the Checkout block.
9. See that the `Place Order` button is left aligned.

## Expected behavior

The `Place Order` button should be right-aligned or visible in full-width.

@elizaan36 What are your thoughts regarding right-aligned or full-width `Place Order` button? If the button should be full-width, I believe we should also reflect that in the post editor. Thinking out loud here, do you think it would make sense to allow merchants to define if the `Place Order` button should be visible right-aligned or full-width if the `Return to Cart` link is not visible?

## Screenshots

<table>
<tr>
<td valign="top">

`Place Order` button when the `Return to Cart` link is visible:

Screen Shot 2023-04-26 at 09 04 13
</td>
<td valign="top">

`Place Order` button when the `Return to Cart` link is not visible:

Screen Shot 2023-04-26 at 08 59 50
</td>
</tr>
</table>

### PR DESCRIPTION
**Pull request by tjcafferkey**
When the "Return To Cart link is disabled", make "Place Order" button full width as suggested [here](https://github.com/woocommerce/woocommerce-blocks/issues/9205#issuecomment-1525553656).

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/9205

#### Accessibility

- [x] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

**Before:**
Screenshot 2023-06-05 at 13 58 45

**After:**
Screenshot 2023-06-05 at 13 58 39

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Create a test page and add the Checkout block.
2. Open the Document Overview.
3. Go to Checkout » Checkout Fields » Actions.
4. Toggle the checkbox Show a "Return to Cart" link.
5. See the button go full/half width depending on the toggle option.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Checkout block: When the "Return To Cart link is disabled", make "Place Order" button full width

### CODE REVIEW

File: assets/js/base/components/cart-checkout/place-order-button/index.tsx [hunk 1]
```diff
@@ -1,15 +1,20 @@
...
  * External dependencies
  */
+import classnames from 'classnames';
 import { useCheckoutSubmit } from '@woocommerce/base-context/hooks';
 import { Icon, check } from '@wordpress/icons';
 import Button from '@woocommerce/base-components/button';
 
 interface PlaceOrderButton {
 	label: string;
+	fullWidth?: boolean;
```
Comment (opr) [inline assets/js/base/components/cart-checkout/place-order-button/index.tsx]: Since this is an optional prop, you need to type it `fullWidth?: boolean | undefined`

This is due to [this tsconfig rule](https://github.com/woocommerce/woocommerce-blocks/blob/6f6c21cf1036ae7b5865ae43406dc0b507f7b5ef/tsconfig.base.json#L10)

```suggestion
	fullWidth?: boolean | undefined;
```

**Review by opr — APPROVED** [review]
Looks good and works well! One TS comment that is easy to resolve so approving.

File: assets/js/base/components/cart-checkout/place-order-button/index.tsx (hunk 1 above)
Comment (tjcafferkey) [reply assets/js/base/components/cart-checkout/place-order-button/index.tsx]: Done in https://github.com/woocommerce/woocommerce-blocks/pull/9721/commits/d0848f5ef2fc9a430ab0c7f224eae3c363034e10
