### PR TITLE
Fix: Exclude Mini Cart and other blocks inside the Mini Cart Contents block

### LINKED ISSUE #5579: Mini Cart: it should not be possible to add the Mini Cart block inside the Mini Cart contents block
## To reproduce
1. Go to Appearance > Editor > Template Parts.
2. Edit the Mini Cart block template part and try to insert a block inside it.
3. Notice the Mini Cart block appears in the inserter and you can add it.

## Expected behavior
It shouldn't be possible to add the Mini Cart block inside the Mini Cart block contents.

## Screenshots
imatge

### WordPress (please complete the following information):
* Core version: 5.9-RC2
* Gutenberg version (if installed): disabled
* WooCommerce version: 6.3.0-dev
* WooCommerce Blocks version: `trunk`

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #5579 

This PR excludes the Mini Cart block and other blocks from the appender of the Mini Cart Items `<InnerBlocks>`. We've already excluded the same set of blocks for the Empty Mini Cart Contents. This PR moves the logic excluding blocks from the empty view into its own file and imports it into the Empty Mini Carts Contents and Mini Cart Items block.

### Screenshots

149791757-062e21fb-7e7e-4280-a864-21502de9288d

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
### Manual Testing

How to test the changes in this Pull Request:

1. Go to Appearance > Editor > Template Parts.
2. Edit the Mini Cart block template part and try to insert a block inside it.
3. Don't see the Mini Cart block.

### User Facing Testing
These are steps for user testing (where "user" is someone interacting with this change that is not editing any code).
* [x] Same as above, or
* [ ] See steps below.

### CODE REVIEW

**Review by Aljullu — COMMENTED** [review]
Overall looking great, but I noticed that all Gutenberg core blocks have disappeared from the list as well. Ie, I can't add a paragraph block:

imatge

Can you reproduce as well @dinhtungdu?

**Comment by dinhtungdu** [comment]
@Aljullu thanks for the head-up, I can reproduce the issue as well. I fixed it in 0247f29. Can you please give this another look?

File: assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/allowed-blocks.ts [hunk 1]
```diff
@@ -0,0 +1,39 @@
+/**
+ * External dependencies
+ */
+import { getBlockTypes } from '@wordpress/blocks';
+
+const EXCLUDED_BLOCKS: readonly string[] = [
+	'woocommerce/mini-cart',
+	'woocommerce/single-product',
```
Comment (Aljullu) [inline assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/allowed-blocks.ts:10]: I would also exclude `woocommerce/cart` and `woocommerce/checkout`.

I also noted there are three additional blocks which are available from the inserter but I expected them not to be: `woocommerce/checkout-order-note-block`, `woocommerce/checkout-terms-block` and `woocommerce/cart-accepted-payment-methods-block`. I'm a bit confused by them because they [specify a parent block](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/blocks/cart-checkout/cart/inner-blocks/cart-accepted-payment-methods-block/block.json#L14), so I didn't expect them to be available in the Mini Cart context. :confused: Any clues?

**Review by Aljullu — COMMENTED** [review]
Thanks for updating this PR @dinhtungdu! This is testing alright now, I suggested a couple additional blocks to add to the excluded list. :point_down:

File: assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/allowed-blocks.ts (hunk 1 above)
Comment (dinhtungdu) [reply assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/allowed-blocks.ts:10]: > I'm a bit confused by them because they specify a parent block, so I didn't expect them to be available in the Mini Cart context.

@Aljullu We only exclude child blocks of ones we set for `EXCLUDED_BLOCKS`. I added `woocommerce/cart-totals-block` and `woocommerce/checkout-fields-block` to the excluded blocks list. Those blocks and their child blocks are excluded now. Can you please take a look?

**Review by Aljullu — APPROVED** [review]
Code looks good and everything is testing well. Thanks fixing this, @dinhtungdu!
