### PR TITLE
Account for products without variations in the On Sale Products block

### LINKED ISSUE #5417: [On Sale Products] Mysql error when no variable products are displayed, since WC 6.0
## Describe the bug
On Sale Products & Best Selling Products blocks throw Mysql error since Woocommerce 6.0 when no variable products are present.

`[20-Dec-2021 07:21:16 UTC] Chyba databáze WordPressu: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND meta_key LIKE 'attribute\\_%'' at line 1. Konkrétní dotaz: SELECT post_id as variation_id, meta_key as attribute_key, meta_value as attribute_value FROM wp_postmeta WHERE post_id IN () AND meta_key LIKE 'attribute\\_%'. Příslušná funkce: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/storefront/template-fullwidth.php'), get_template_part, locate_template, load_template, require('/themes/storefront/content-page.php'), do_action('storefront_page'), WP_Hook->do_action, WP_Hook->apply_filters, storefront_page_content, the_content, apply_filters('the_content'), WP_Hook->apply_filters, do_blocks, render_block, WP_Block->render, Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback, Automattic\WooCommerce\Blocks\BlockTypes\AbstractProductGrid->render, Automattic\WooCommerce\Blocks\BlockTypes\AbstractProductGrid->get_products, Automattic\WooCommerce\Blocks\BlockTypes\AbstractProductGrid->prime_product_variations.`

## To reproduce

On an empty store

1. Add 2 simple products on sale and publish them
2. Go to a page and add the On Sale Products block.
3. Go to the front-end and notice the warning below

Screenshot 2021-12-29 at 14 43 41

## Expected behavior
There should be no error and the block should just display the products

### WordPress (please complete the following information):

* WooCommerce version: 6.0
* WooCommerce Blocks version: 6.6
* Site language:
* Any other plugins installed: Query monitor

### PR DESCRIPTION
**Pull request by ralucaStan**
This PR accounts for the case when no product variations are present in the blocks that use the `prime_product_variations` function

Fixes #5417

### Manual Testing

How to test the changes in this Pull Request:

On a store with no products store

1. Add 2 simple products on sale and publish them
2. Go to a test page and add the On Sale Products block.
3. Visit the page on the front-end.
4. Notice that no MySQL error is present in Query Monitor.

### Changelog

> Account for products without variations in the On Sale Products block

### CODE REVIEW

File: src/BlockTypes/AbstractProductGrid.php [hunk 1]
```diff
@@ -361,14 +361,17 @@ protected function prime_product_variations( $product_ids ) {
...
-		$all_variation_meta_data = $wpdb->get_results(
-			$wpdb->prepare(
-				"SELECT post_id as variation_id, meta_key as attribute_key, meta_value as attribute_value FROM {$wpdb->postmeta} WHERE post_id IN (" . implode( ',', array_map( 'esc_sql', $prime_variation_ids ) ) . ') AND meta_key LIKE %s',
-				$wpdb->esc_like( 'attribute_' ) . '%'
-			)
-		);
-		// phpcs:enable
+		$all_variation_meta_data = [];
 
+		if ( ! empty( $prime_variation_ids ) ) {
```
Comment (mikejolley) [inline src/BlockTypes/AbstractProductGrid.php]: Since the remainder of the function deals with these returned IDs, we should return early. Like on these lines:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/b42ec5f4769610a5d1da14ca60a9697f3d90fd9c/src/BlockTypes/AbstractProductGrid.php#L354-L356

File: src/BlockTypes/AbstractProductGrid.php [hunk 2]
```diff
@@ -361,14 +361,17 @@ protected function prime_product_variations( $product_ids ) {
...
+			$all_variation_meta_data = $wpdb->get_results(
+				$wpdb->prepare(
+					"SELECT post_id as variation_id, meta_key as attribute_key, meta_value as attribute_value FROM {$wpdb->postmeta} WHERE post_id IN (" . implode( ',', array_map( 'esc_sql', $prime_variation_ids ) ) . ') AND meta_key LIKE %s',
+					$wpdb->esc_like( 'attribute_' ) . '%'
+				)
+			);
+		}
```
Comment (mikejolley) [inline src/BlockTypes/AbstractProductGrid.php]:
```suggestion
		if ( empty( $prime_variation_ids ) ) {
			return;
		}
		
		$all_variation_meta_data = $wpdb->get_results(
			$wpdb->prepare(
				"SELECT post_id as variation_id, meta_key as attribute_key, meta_value as attribute_value FROM {$wpdb->postmeta} WHERE post_id IN (" . implode( ',', array_map( 'esc_sql', $prime_variation_ids ) ) . ') AND meta_key LIKE %s',
				$wpdb->esc_like( 'attribute_' ) . '%'
			)
		);
```

**Review by mikejolley — CHANGES_REQUESTED** [review]
Good catch. I think we just need to tweak it slightly so we return earlier.

**Comment by ralucaStan** [comment]
@mikejolley changes have been addressed.

File: src/BlockTypes/AbstractProductGrid.php [hunk 3]
```diff
@@ -361,14 +361,19 @@ protected function prime_product_variations( $product_ids ) {
 		$product_variations      = $wpdb->get_results( "SELECT ID as variation_id, post_parent as product_id from {$wpdb->posts} WHERE post_parent IN ( " . implode( ',', $prime_product_ids ) . ' )', ARRAY_A );
 		$prime_variation_ids     = array_column( $product_variations, 'variation_id' );
 		$variation_ids_by_parent = array_column( $product_variations, 'product_id', 'variation_id' );
+		$all_variation_meta_data = [];
```
Comment (mikejolley) [inline src/BlockTypes/AbstractProductGrid.php]: Is there a reason for this line? It's unused as far as I can see.

**Review by mikejolley — APPROVED** [review]
