### PR TITLE
Fix the related products block result when used along a grouped product

### LINKED ISSUE #8589: Related Products Block and group products: wrong results
## Describe the bug

The Related Products block doesn't render the same result as the `Classic Template` when used on a Group Product. 

In the `Classic Template`, it seems that nothing is rendered. We should check [this logic](https://github.com/woocommerce/woocommerce/blob/ca49caabcba84ce9f60a03c6d3534ec14b350b80/plugins/woocommerce/includes/wc-template-functions.php/#L2063-L2064).

## To reproduce

1. Edit the Single Product Template.
2. Below the `WooCommerce Single Product Block`, add the `Related Products block`.
3. On the frontend side, click on a group product.
4. The products inside the `Related Products block` differ from the row generated by the `WooCommerce Single Product Block`.

## Expected behavior

The result has to be the same.

## Screenshots

image

### PR DESCRIPTION
**Pull request by gigitux**
This PR fixes the related products block result when used along a grouped product: following WC Core, the block should not show any product.

Furthermore, I put inside the Related Products block a heading block with the text: `Related Products`. This is necessary because we only want to show the `Related Products` text when the related products block shows products. For this reason, it will be necessary to update https://github.com/woocommerce/woocommerce-blocks/pull/8515

Fixes #8589 

#### User Facing Testing

1. Edit the Single Product Template.
2. Below the `WooCommerce Single Product Block`, add the `Related Products block`.
3. Save the template.
4. On the frontend side, click on a simple product.
5. Check that the products inside the `Related Products block` are equal to the row generated by the `WooCommerce Single Product Block`.
6. On the frontend side, click on a group product.
7. Check that the products inside the `Related Products block` are equal to the row generated by the `WooCommerce Single Product Block`. (no product should be displayed)

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by thealexandrelara — COMMENTED** [review]
For some reason, in my case when I try accessing the Single Product page (on the frontend side) the page is broken with the following error:

image

It seems to be related to the `$product->get_id()` call on line 152 in the RelatedProducts.php file. Can you reproduce it?

**Comment by gigitux** [comment]
> For some reason, in my case when I try accessing the Single Product page (on the frontend side) the page is broken with the following error:
> 
> image
> 
> It seems to be related to the `$product->get_id()` call on line 152 in the RelatedProducts.php file. Can you reproduce it?

Yes, I tested the block always below the Classic Single Grid Block. The issue is that the variable $product is set when the loop is started ([source code](https://github.com/woocommerce/woocommerce/blob/bec3ec18ac801875a830ddf097ba173069161c13/plugins/woocommerce/includes/wc-template-functions.php/#L133-L154)).

The filter `pre_render_block` is triggered **before** the loop starts.

This issue didn't happen when the block was below the Classic Single Grid Block because the block triggered the loop, and WC set the product in the global variable.

I fixed it via ab0f60136b5abd3a1ce9aa6d0961587791fcccb5

File: src/BlockTypes/RelatedProducts.php [hunk 1]
```diff
@@ -75,16 +83,82 @@ public function update_query( $pre_render, $parsed_block ) {
...
+	/**
+	 * If there are no related products, return an empty string.
+	 *
+	 * @param string $content The block content.
+	 * @param array  $block The block.
+	 *
+	 * @return string The block content.
+	 */
+	public function render_block( string $content, array $block ) {
+		if ( ! $this->is_related_products_block( $block ) ) {
```
Comment (thealexandrelara) [inline src/BlockTypes/RelatedProducts.php:111]: I'm wondering if this conditional is really necessary, because by default on line 120, it will always return the $content, except if the `count( $related_products_ids ) < 1` (on line 117)

Comment (gigitux) [reply src/BlockTypes/RelatedProducts.php:111]: This function is hooked to the `render_block` filter. So this means that every function hooked to the `render_block` is executed for each block that will be rendered. For this reason, I do this check.

**Review by thealexandrelara — APPROVED** [review]
Everything looks good to me. Thank you for working on this! 🚀
