### PR TITLE
Mini Cart block - added notice support 

### LINKED ISSUE #6941: Add validation mechanism to Mini Cart block
## Describe the bug

Currently, it's not possible to display errors in the Mini Cart block. That's an issue for some extensions, that have specific validation rules in the cart context.

## To reproduce

1. Add the Mini Cart block to the header of your store.
2. Install [Product Bundles](https://woocommerce.com/products/product-bundles/).
3. Create a Product bundle product with _Min Bundle Size_ and _Max Bundle Size_ values (ie: 2 and 4).

imatge

4. Go to the frontend of the site, and add the Product bundle product you just created to your cart.
5. Open the Mini Cart and change the quantities of the inner products to something bigger than the _Max Bundle Size_.

6. Notice you are allowed to do it and no error is shown.
7. Go to the Cart page.
8. Notice there is an error on top of the block:

## Expected behavior

The same error that is shown in the Cart block should be shown in the Mini Cart block.

## Additional context

That's because the Cart block has a validation mechanism while the Mini Cart block doesn't. We should add the same validation mechanism so extensions can register errors.

### PR DESCRIPTION
**Pull request by gigitux**
With this PR, the Mini Cart block will render the notice if this latter is rendered on the Cart page and the Cart block.

This PR wraps the Filled Mini Cart block with the `StoreNoticesProvider` that adds in the DOM the notice message. The `StoreNoticesContainer` get the notices data from the Redux store, so it is necessary to check if there is an error and dispatches the error in the `core/notices` store. (https://github.com/woocommerce/woocommerce-blocks/compare/fix/6941-add-validation-mini-cart?expand=1#diff-de4fd15ae837a2f5e60c3eb6f342dd7e638cacf1eadac29e27cae935d71fc95aR21-R34). 

The same logic is done for the Cart block too: https://github.com/woocommerce/woocommerce-blocks/blob/ec0a3cbccefc117038db9af0dbf217a66eb2ca89/assets/js/blocks/cart/inner-blocks/filled-cart-block/frontend.tsx/#L27-L36

Also, I added a CSS to hide the X for dismiss notice. I think that in this case, it is not necessary. What do you think?

Fixes #6941 

### Screenshots

image

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Open the FSE editor and add the Mini Cart Block in the header. Save.
2. Go to the frontend and add the product to the Cart. Be sure that on Mini Cart Block any "notice" is visible on top.
3. On the editor side, edit the product that you added and set it as out of stock. Save.
4. On the frontend side, refresh the page. Go to the Cart page and see the notice.
5. Open the Mini Cart block and be sure that the notice is visible.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Mini Cart block: Added notice support.

### CODE REVIEW

**Comment by gigitux** [comment]
I added @imanish003 as a reviewer because reviewing a PR is one of the goals for his onboarding. @danielwrobert could you still take a look? Thanks!

**Comment by imanish003** [comment]
Hi @gigitux,
I see the validation error but it's showing 2 cross icons as shown in the screenshot below:
image

**Comment by imanish003** [comment]
Hi @gigitux,
This isn't a big deal but I think `X` button position is looking a bit weird. What do you think? 

image

**Comment by gigitux** [comment]
> Hi @gigitux, This isn't a big deal but I think `X` button position is looking a bit weird. What do you think?
> 
> image

Thanks for raising this! As I explained in the description, this X belongs to the Mini Cart block, so we can't control the position. Also, the dimensions of the notice box could be different for each theme. Should it be the responsibility of the theme developer to take care of this?

Another idea could be to render only the string without the HTML (in the last days, we introduced this change #7145).

This will be the result:

image

What do you think? 
cc @danielwrobert

**Comment by imanish003** [comment]
Hi @gigitux,
I noticed a small issue. Here is a example
- Add item with quantity = 10
image
- Update the stock quantity to 9
image
- Now refresh the page & open the mini cart again. The mini cart still shows the notice even though product quantity is updated automatically to 9 as shown in the screenshot below:
image

This gets fixed if I refresh the page again but I believe the notice should not be visible after 1st refresh too. 
May I know if you are able to reproduce the issue? 🙂

File: assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx [hunk 1]
```diff
@@ -12,13 +18,33 @@ const FilledMiniCartContentsBlock = ( {
...
+
+	const { createErrorNotice } = useDispatch( 'core/notices' );
+
+	// Ensures any cart errors listed in the API response get shown.
+	useEffect( () => {
+		cartItemErrors.forEach( ( error ) => {
+			createErrorNotice( decodeEntities( error.message ), {
+				isDismissible: true,
+				id: error.code,
+				context: 'wc/cart',
```
Comment (imanish003) [inline assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx]: Hi @gigitux, I am just curious. Isn't it possible to hide the X button using `isDismissible: false,` property instead of using CSS? i.e.
```jsx
createErrorNotice( decodeEntities( error.message ), {
	isDismissible: false,
	id: error.code,
	context: 'wc/cart',
} );
```

Comment (gigitux) [reply assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx]: Good catch! I fixed the code with your suggestion. Also, I removed the not necessary SCSS 👍

**Comment by gigitux** [comment]
> Hi @gigitux, I noticed a small issue. Here is a example
> 
> * Add item with quantity = 10
>   image
> * Update the stock quantity to 9
>   image
> * Now refresh the page & open the mini cart again. The mini cart still shows the notice even though product quantity is updated automatically to 9 as shown in the screenshot below:
>   image
> 
> This gets fixed if I refresh the page again but I believe the notice should not be visible after 1st refresh too. May I know if you are able to reproduce the issue? 🙂

Good point! The Mini Cart block is the Cart block under the hood. I created a dedicated issue #7239

File: assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx (hunk 1 above)
Comment (imanish003) [reply assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx]: Awesome! Thanks 🚀

**Comment by danielwrobert** [comment]
> Thanks for raising this! As I explained in the description, this X belongs to the Mini Cart block, so we can't control the position. Also, the dimensions of the notice box could be different for each theme. Should it be the responsibility of the theme developer to take care of this?

@gigitux I see your point here. However, it seems to cause a bit of an unexpected experience with the overlapping close (`x`) button - i.e., it potentially gives the false impression that the `x` pertains to the notice.

The issue is with the absolutely positioned elements on the close button / Mini Cart drawer header. What do you think about adjusting the positioning/layout styles for that section to force the notice to appear _below_ the drawer? For example, the [block of code here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/mini-cart/style.scss#L50-L63) could be adjusted to the following:

```css
.components-modal__header {
    position: relative;
    height: calc( $gap-largest + $gap );

    button {
        margin: 0;
        right: 0;
        top: 50%;
        transform: translateY(-50%);
    }

    svg {
        display: block;
    }
}
```

I've tested this out on a few different block themes (TT2, Livro, Bricksy) and they all seem to look fairly consistent:

**Bricksy**
CleanShot 2022-09-29 at 20 09 23@2x

**TT2**
CleanShot 2022-09-29 at 20 11 23@2x

Might be good to ensure a bit of padding around the drawer notice as a baseline/default:

```css
.wc-block-components-notices {
  padding: 0 16px;
}
```

**Bricksy**
Screen Shot 2022-09-29 at 8 49 27 PM


**TT2**
Screen Shot 2022-09-29 at 8 49 59 PM

Aside from this, the code looks good and everything tests as described! Let me know if you'd prefer to handle these layout items separately and I'll go ahead and approve this PR.

**Comment by gigitux** [comment]
Thanks for the suggestion, @danielwrobert. I tried to implement your style, but I found some problems at the bottom: the checkout button goes outside of the screen.

Before continuing to spend time on it, @vivialice could you take a look at this UI issue? What do you think?

**Comment by danielwrobert** [comment]
> Thanks for the suggestion, @danielwrobert. I tried to implement your style, but I found some problems at the bottom: the checkout button goes outside of the screen.

@gigitux nice catch, I missed that! If you decide to go this route, you can fix by adjusting [this height declaration](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/mini-cart/style.scss#L76) to `height: calc(100vh - ($gap-largest + $gap));`.

**Comment by gigitux** [comment]
Thanks @danielwrobert, for helping me to figure out how to fix this! 🙏 

With [2d4a9a3](https://github.com/woocommerce/woocommerce-blocks/pull/7234/commits/2d4a9a30e18b1d83c8dad403891229efd210151f) I used your suggestion.

This is how the drawer looks:


| Before this PR | With Notice | Without Notice |
|----------------|--------------|-----------------|
|image|image|image|

With this PR and without notice, the drawer looks weird, IMHO.

Also, I noticed another issue when the Mini Cart Drawer is open on a WooCommerce page (e.g: Product Catalog), the notice has some styles:

image

otherwise, it doesn't have any styles (homepage):

image

Should we try to fix this issue in this PR? (I guess that the only way to fix it is to copy-paste the CSS from WC Core)

cc @vivialice

**Comment by vivialice** [comment]
Is the question about whether or not we fix the style inconsistency? If so, that's something we should review so it appears the same on all pages.

In general, all these notices need reviewing across the experience but using what we have works fine for now until I can take a look at it all!

**Comment by gigitux** [comment]
@vivialice, Sorry for not wasn't be clear. I'm asking for two feedback:
1. With this PR, the header of the Mini Cart will look different. Is it okay? 

image
 
2. Should we fix the style inconsistency when the notice is loaded on a WC page and when it isn't? You already replied to this question, and the answer is yes.

What about the first point?

File: assets/js/blocks/mini-cart/style.scss [hunk 2]
```diff
@@ -42,23 +42,36 @@
...
 
+	.components-modal__content .components-modal__header .components-button {
+		top: 50%;
+		padding: unset;
+		margin: unset;
+	}
+
+	.wc-block-components-notices {
+		padding: 0 16px;
+		margin-bottom: unset;
```
Comment (Aljullu) [inline assets/js/blocks/mini-cart/style.scss]: Here we set some extra margin to the notice wrapper:
```suggestion
		margin: #{$gap} #{$gap} -#{$gap};
```

File: assets/js/blocks/mini-cart/style.scss [hunk 3]
```diff
@@ -42,23 +42,36 @@
...
 		position: relative;
 	}
 
 	.components-modal__header {
-		position: absolute;
-		top: $gap-largest;
-		right: $gap;
+		position: relative;
+		height: calc( $gap-largest + $gap );
+
```
Comment (Aljullu) [inline assets/js/blocks/mini-cart/style.scss]: And here we recover the previous styles:
```suggestion
		position: absolute;
		top: $gap-largest;
		right: $gap;
```

**Review by Aljullu — COMMENTED** [review]
> 1. With this PR, the header of the Mini Cart will look different. Is it okay?

Is it intentional or a CSS issue? I did some tinkering and _(I think)_ it could be solved like this: :point_down:

**Comment by gigitux** [comment]
> > 1. With this PR, the header of the Mini Cart will look different. Is it okay?
> 
> Is it intentional or a CSS issue? I did some tinkering and _(I think)_ it could be solved like this: 👇

Mmm, the idea comes up after [some iterations](https://github.com/woocommerce/woocommerce-blocks/pull/7234#issuecomment-1262981613).

Another idea could be to follow [this approach](https://github.com/woocommerce/woocommerce-blocks/pull/7234#issuecomment-1259438066). In this way, we resolve two problems at once :D 

@Aljullu, regarding your proposal, this is what I see:

image

Not pretty sure that the position of the `X` is okay. Also, the button isn't near the bottom. There is too much white space.

**Comment by Aljullu** [comment]
> @Aljullu, regarding your proposal, this is what I see:

What theme are you using? `.wc-block-mini-cart__items` also has `$gap` for the left and right paddings, so it should be aligned on the sides. :thinking: 

> Not pretty sure that the position of the `X` is okay. 

Yup, sorry. I missed the overlapping `X`. However, it should be solvable adding more top-margin to the notices (similar to what @danielwrobert proposed [here](https://github.com/woocommerce/woocommerce-blocks/pull/7234#issuecomment-1262981613) and your [previous screenshot](https://github.com/woocommerce/woocommerce-blocks/pull/7234#issuecomment-1293315979)), no? Another option would be to increase the right margin of the notices:

imatge

I don't have a strong opinion because that's a design question. But IMO this PR shouldn't change how the Mini Cart is displayed when there are no notices.

**Comment by gigitux** [comment]
With 7abe0e2, I iterated the UI. What do you think?

## With notice

image

## Without notice
image


What do you think?

Regarding this issue:
> Also, I noticed another issue when the Mini Cart Drawer is open on a WooCommerce page (e.g: Product Catalog), the notice has some styles


I noticed that WC Core has custom CSS rules for each TT theme ([TT3](https://github.com/woocommerce/woocommerce/blob/4b23164b0321515260e0ceb36af6ed1d70220430/plugins/woocommerce/client/legacy/css/twenty-twenty-three.scss/#L100-L133)). What should we do? Should we copy-paste all the rules for all the TT themes? 
The problem is that WC core updates some rules, we may not be aware of the change :/

**Comment by imanish003** [comment]
Hi @gigitux, This looks good to me. I am no UX expert, so I can't comment on if UI looks good enough or not. 
Maybe @vivialice or @Aljullu can comment on that?

Also, I noticed that `Close mini cart` text doesn't seem to have enough space when I hover over the close button as shown below:
image

**Comment by gigitux** [comment]
> Hi @gigitux, This looks good to me. I am no UX expert, so I can't comment on if UI looks good enough or not. Maybe @vivialice or @Aljullu can comment on that?
> 
> Also, I noticed that `Close mini cart` text doesn't seem to have enough space when I hover over the close button as shown below: image

Thanks for the review! Regarding the tooltip, we already have the problem, so it isn't a regression:

image

**Comment by vivialice** [comment]
Are we able to clean up the margin a little bit on the notice? 

Screenshot 2022-11-02 at 11 46 23

Also, in regards to the `close` hover text, would it work better to just have `close` instead of `close mini cart` so it doesn't look so cramped? It is also overlapping the price which isn't ideal. Maybe we can pull it closer to the icon?

Screenshot 2022-11-02 at 11 50 03

**Comment by gigitux** [comment]
> Are we able to clean up the margin a little bit on the notice?
> 
> Screenshot 2022-11-02 at 11 46 23
> 
> Also, in regards to the `close` hover text, would it work better to just have `close` instead of `close mini cart` so it doesn't look so cramped? It is also overlapping the price which isn't ideal. Maybe we can pull it closer to the icon?
> 
> Screenshot 2022-11-02 at 11 50 03

Sorry for the late answer. I updated the PR with 9f3381fa08e36f8460d8c9c6ada760eb82241321, and I followed your feedback:

image


The last issue is that the notice has style only when it is loaded on WooCommerce Page.

image
*on the "normal" WordPress page*

image
*on the WooCommerce page*

Any idea about how can we fix it? Should we copy-paste the CSS from the WC core? The problem is that every theme has some custom CSS rules:
image

**Comment by danielwrobert** [comment]
> Any idea about how can we fix it? Should we copy-paste the CSS from the WC core? The problem is that every theme has some custom CSS rules:

@gigitux following up from our Slack chat for posterity. As we discussed, it seems worth investigating if it would be safe to remove the encapsulating `.woocommerce` part of the selector for the ruleset(s) in WC Core.

Looking at [the instances of these selectors](https://github.com/woocommerce/woocommerce/search?l=SCSS&q=.woocommerce-error), we seem to only add the extra specificity in the stylesheets for TT2, TT3, and the `woocommerce-layout.scss` file.

The other minor item we discussed was potentially considering some margin or padding to the top of the Mini Cart tray when a user/merchant is logged in so that the admin bar does not overlap and hide any of the content:

CleanShot 2022-11-23 at 15 42 55@2x

WP Core accounts for this by adding some extra margin to the root `html` element when the user is logged in. But, since our cart is set to `position: fixed` the margin does not impact the cart positioning and it gets cut off at the top underneath the admin bar.

If we wanted to account for this on the Mini Cart tray, we could add the following CSS:

```css
.admin-bar .wp-block-woocommerce-mini-cart-contents {
  margin-top: 32px;
}

.admin-bar .wp-block-woocommerce-mini-cart-contents,
.admin-bar .wp-block-woocommerce-empty-mini-cart-contents-block,
.admin-bar .wp-block-woocommerce-filled-mini-cart-contents-block {
  height: calc(100vh - 32px);
}

.admin-bar .wc-block-components-drawer .components-modal__header .components-button {
  top: 32px;
}
```

**Comment by gigitux** [comment]
Hey @danielwrobert, thanks a lot for the discussion that we had and for providing me feedback! As we decided, I created a[ PR](https://github.com/woocommerce/woocommerce/pull/35912) on WC Core that moves the CSS about the notice outside the `.woocommerce` scope.

**Comment by gigitux** [comment]
@danielwrobert The PR (https://github.com/woocommerce/woocommerce/pull/35912) on WC core has been merged 🥳

File: assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx [hunk 4]
```diff
@@ -12,13 +17,31 @@ const FilledMiniCartContentsBlock = ( {
...
-	const { cartItems } = useStoreCart();
+	const { cartItems, cartItemErrors } = useStoreCart();
+
+	const { createErrorNotice } = useDispatch( 'core/notices' );
+
+	// Ensures any cart errors listed in the API response get shown.
+	useEffect( () => {
+		cartItemErrors.forEach( ( error ) => {
+			createErrorNotice( decodeEntities( error.message ), {
+				isDismissible: false,
```
Comment (danielwrobert) [inline assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx:28]: @gigitux it seems that something about this `isDismissible` setting isn't taking. I am now seeing two `X` close buttons - one for the message and one for the cart drawer (see screenshot below). I also notice that there is a `is-dismissible` class on the rendered element. I don't recall these being present in your previous commits so this may be a regression.

CleanShot 2022-12-21 at 16 09 17

**Review by danielwrobert — CHANGES_REQUESTED** [review]

File: assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx (hunk 4 above)
Comment (gigitux) [reply assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx:28]: Not sure, but it seems that the regression is caused by [this PR](https://github.com/woocommerce/woocommerce-blocks/pull/7711) that was merged 3 days ago. Looking into 👀

Comment (gigitux) [reply assets/js/blocks/mini-cart/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx:28]: Ok, as I suspected, #7711 introduces a regression that was fixed with #8018. I merged #8018 in this branch. Also, the PR introduced some styles that override the style that we added in this PR. I fixed this with [4416792](https://github.com/woocommerce/woocommerce-blocks/pull/7234/commits/441679268bbcb79bc10b7cc8e1abea6a3113b16c).

**Review by danielwrobert — APPROVED** [review]
I confirmed that this is now working as expected, as of 4416792.

I've also tested out everything against Woo Core Nightly to confirm the presence of the styles on non-Woo pages.

Everything LGTM now, thanks for working on this! 🚀
