### PR TITLE
Product Gallery Thumbnails: Add support for cropping

### LINKED ISSUE #11699: Product Gallery Thumbnails: Fix thumbnails cropping
## Describe the bug

When #11665 is merged, the thumbnails will no longer be always cropped.

The thumbnails should also follow the `Crop images to fit` setting value.

## To reproduce

1. With a block theme, open `Appearance > Editor`.
2. Open `Templates > Single Product`.
3. Select `Convert to Blocks` if you are using the Classic Templates.
4. Add the `Product Gallery` block.
5. Ensure the Thumbnails are enabled.
6. Change the `Crop images to fit` value, notice the thumbnails are never cropped.

## Expected behavior

When `Crop images to fit` is enabled, the thumbnails should be cropped to square.

When `Crop images to fit` is disabled the thumbnails should not be cropped to square.

## Screenshots

Moto_Guzzi_v7_–_newproductgallery

### PR DESCRIPTION
**Pull request by danieldudzic**
## What

Fixes #11699

## Why

This PR adds support for cropping to thumbnails.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. With a block theme, open `Appearance > Editor`.
2. Open `Templates > Single Product`.
3. Select `Convert to Blocks` if you are using the Classic Templates.
4. Add the `Product Gallery` block.
5. Test with `Crop images to fit` enabled and disabled.
6. Make sure the thumbnails on the frontend get correctly cropped (or not cropped).

* [x] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

With **Cropping** setting:

| Disabled | Enabled |
| ------ | ----- |
|Moto_Guzzi_v7_–_newproductgallery|Moto_Guzzi_v7_–_newproductgallery|

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Product Gallery Thumbnails: Add support for cropping.

### CODE REVIEW

File: src/BlockTypes/ProductGalleryThumbnails.php [hunk 1]
```diff
@@ -133,7 +133,9 @@ protected function render( $attributes, $content, $block ) {
 
 			if ( $product ) {
 				$post_thumbnail_id      = $product->get_image_id();
-				$product_gallery_images = ProductGalleryUtils::get_product_gallery_images( $post_id, 'thumbnail', array(), 'wc-block-product-gallery-thumbnails__thumbnail' );
+				$crop_images            = $block->context['cropImages'] ?? '';
```
Comment (sunyatasattva) [inline src/BlockTypes/ProductGalleryThumbnails.php]: I believe this should default to `false` rather than empty string. Or am I missing something that made you choose empty string?

File: src/BlockTypes/ProductGalleryThumbnails.php [hunk 2]
```diff
@@ -133,7 +133,9 @@ protected function render( $attributes, $content, $block ) {
...
+				$product_gallery_images = ProductGalleryUtils::get_product_gallery_images( $post_id, 'full', array(), 'wc-block-product-gallery-thumbnails__thumbnail', $crop_images );
```
Comment (sunyatasattva) [inline src/BlockTypes/ProductGalleryThumbnails.php:137]: Would you mind explaining why the image size went from `thumbnail` to `full` when we're dealing with thumbnails?

**Review by sunyatasattva — APPROVED** [review]
I'm going to pre-approve not to block you, but there is a small change request 🙏

File: src/BlockTypes/ProductGalleryThumbnails.php (hunk 2 above)
Comment (danieldudzic) [reply src/BlockTypes/ProductGalleryThumbnails.php:137]: The `thumbnail` setting for `wp_get_attachment_image()` outputs cropped square images with max 150px/150px dimensions.

We need to support larger images for wide layouts and preserve the aspect ratio (for the cropping disabled setting).

Moto_Guzzi_v7_–_newproductgallery

File: src/BlockTypes/ProductGalleryThumbnails.php (hunk 1 above)
Comment (danieldudzic) [reply src/BlockTypes/ProductGalleryThumbnails.php]: Good catch. `false` is the default value for `get_product_gallery_images()`'s `$crop_images` parameter. I have updated it now.
