### PR TITLE
Consistent HTML entities in Store API

### LINKED ISSUE #1586: [WC 3.9 rc-3]: Inconsistent display of ampersand (&) in blocks
**Describe the bug**

Inconsistent display of ampersand (&) in blocks. I noticed it in:

- The product titles of `All Products` block (both back-end and front-end)
- In attribute name in `Filter by Attribute` block (both back-end and front-end)
- In attribute name in `Active Filters` block (both back-end and front-end)
- In the name of the attribute used in the title of the `Filter by Attribute` block (back-end only)

**To Reproduce**

1. Create a product with the title that contains an ampersand (&) - for example, `Yellow Pants (H&M)`;
2. Create an attribute that contains an ampersand (&) - for example, you can have an attribute `Brands` and it will have `H&M` & `Zara` options;
3. Create another attribute that contains an ampersand (&) - for example, you can have an attribute `Drive & Tip` and it will have `1/2-inch Hex Drive (H)` & `1/2-inch Hex Drive & Heavy Duty Tip (HD)` options;
4. Create a post or page where you can add blocks;
5. Add the `All Products block` - take note of the ampersand (&) display in the product title;
6. Add `Filter by Attributes` (select `Brands` as an attribute) - note how the options are displayed (both back-end and front-end);
7. Add another `Filter by Attributes` (select `Drive & Tip` as an attribute) - note how the options are displayed (both back-end and front-end); 
8. Add `Active Filters` block;
9. Select one of the filters at the front end that has an ampersand (&) in the name - for example `H&M` - note how the options are displayed (both back-end and front-end).

Here are the screenshots showcasing the issue:

back-end

front-end

**Expected behavior**

I expect for the ampersand (&) to be displayed correctly everywhere in blocks in both back-end and front-end. 

**Screenshots**

See above. 

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): not installed
* WooCommerce version: 3.9 rc3
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: Jetpack by WordPress.com, WooCommerce Beta Tester, WooCommerce Stripe Gateway

**Desktop (please complete the following information):**

* OS: macOS Catalina v 10.15.1
* Browser: Chrome
* Version:  79.0.3945.117 (Official Build) (64-bit)

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by mikejolley**
This is an alternative fix to #1594 cc @haszari @nerrad 

Rather than strip entities for the term name, this adds a new formatting method to the API to be used on all HTML based strings which enforces entities for the response. This ensures all text/html coming from the API has the same formatting.

As well as formatting responses, I've included the `@wordpress/html-entities` package for decoding entities for display and included that for the attribute filter and all products block to fix #1586. 

As a note on usage, if using values from the API in react, you'll need to `decodeEntities` UNLESS you are using `dangerouslySetInnerHTML`, in which case entities will render correctly.

Fixes #1586 

### How to test the changes in this Pull Request:

1. Setup some attributes with & in the name, and some products with & in the title and/or excerpt.
2. Setup all products block. You can add 'summary' to the output to test excerpt handling.
3. Setup filter by attribute and active filter blocks.
4. View the all products block and confirm & rendering in the product title, summary, and filter blocks. 
5. Confirm filter blocks work, and active filters also shows correct & handling.

### CODE REVIEW

File: assets/js/atomic/components/product/button/index.js [hunk 1]
```diff
@@ -166,7 +167,9 @@ const ProductButton = ( { product, className } ) => {
 			{ allowAddToCart ? (
 				<button
 					onClick={ addToCart }
-					aria-label={ productCartDetails.description }
+					aria-label={ decodeEntities(
+						productCartDetails.description
+					) }
```
Comment (nerrad) [inline assets/js/atomic/components/product/button/index.js]: I don't think it will be an issue, but we should probably test to make sure html attributes aren't broken if the encoded entities are quotes.  I think we'll be fine because react sanitizes that.

File: src/RestApi/StoreApi/Schemas/AbstractSchema.php [hunk 2]
```diff
@@ -176,4 +176,20 @@ protected function prepare_money_response( $amount, $decimals = 2, $rounding_mod
...
+	 * The wptexturize, convert_chars, and trim functions are also used in the `the_title` filter.
+	 * The function wp_kses_post removes disallowed HTML tags.
+	 *
+	 * @param string|array $response Data to format.
+	 * @return string|array Formatted data.
+	 */
+	protected function prepare_html_response( $response ) {
+		if ( is_array( $response ) ) {
+			return array_map( [ $this, 'prepare_html_response' ], $response );
+		}
```
Comment (nerrad) [inline src/RestApi/StoreApi/Schemas/AbstractSchema.php]: Do you think there will ever be scenarios where `response` might be an object (or the array elements might be an object?) - should we either handle or guard against that if it is? I know we specify the expectation via the jsdocs, but without typehinting (which we can't do here) it's not enforced.

Comment (mikejolley) [reply src/RestApi/StoreApi/Schemas/AbstractSchema.php]: I don't think there is currently, but we can guard by leaving objects alone.

File: assets/js/atomic/components/product/button/index.js (hunk 1 above)
Comment (mikejolley) [reply assets/js/atomic/components/product/button/index.js]: Confirmed React is re-encoding quote characters before rendering.

File: src/RestApi/StoreApi/Schemas/AbstractSchema.php (hunk 2 above)
Comment (mikejolley) [reply src/RestApi/StoreApi/Schemas/AbstractSchema.php]: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1597/commits/d50b2c24dca25918cc607744fea0b7a505a11fe0

**Comment by mikejolley** [comment]
> this impacts quite a few things using the store api (which I think is only the All Products block and the filter blocks currently right?).

Yes these were the instances I found. The cart stuff isn't using this yet and is only in master.
