### PR TITLE
Refresh the cart when using the browser back button

### LINKED ISSUE #7233: Checkout Block doesn't get empty after a successful order
## Describe the bug

The Checkout Block doesn't get empty after a successful order. 

## To reproduce

1. Add product to Cart
2. Go to the Checkout Block page.
3. Place an order.
4. After a successful order, use the back button
5. Notice, the Checkout Block still has the item in the cart
6. Place an order again
7. Notice an empty error message.

https://user-images.githubusercontent.com/11503784/192449759-74f5c1eb-a67d-48d4-96b4-93106df35945.mov

### LINKED ISSUE #7974: When navigating back to a page with the Mini Cart block using the browser buttons the quantities do not update
## Describe the bug

Using the browser navigation buttons to go back to a page with the Mini Cart block after previously modifying the cart causes the quantities to revert to the original number until you actually refresh the page.

## To reproduce

1. Add the Mini Cart block to a page, and the All Products block.
2. Add items to your cart and observe the "total" number update as you add products.
3. Open the Mini Cart and then proceed to checkout.
4. From the checkout page, press the browser back button.
5. Observe the Mini Cart block and see that the quantities are not the same as they were when you proceeded to checkout.

## Expected behavior

Quantities would be correct when navigating back using the browser buttons.

## Screenshots

https://www.loom.com/share/bb01ec49eb16430fa9dc150cf330787f

## Additional context

Reported as a comment on #3827 by @thexpand :)

### PR DESCRIPTION
**Pull request by mikejolley**
If you go back to the checkout after placing an order you still see the checkout form and invalid vart data.

This PR implements a fix whereby if the back button usage is detected, the cart is invalidated and pulled again from the API. This results in the following: 

Screenshot 2023-01-19 at 13 23 16

Note this did require some deprecated JS code to work because `persisted` is not working reliably in chrome.

Fixes #7233

For the mini cart (#7974), as well as the above code we need to `loadScripts()` when the back button is used. I've implemented the same detection code there also.

Fixes #7974

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Add items to your cart
2. Go to the checkout block page
3. Place an order
4. Press the browser back button
5. After a short delay you'll see the empty cart notice

For the Mini Cart:

1. Add mini cart to the theme header
2. Add something to your cart
3. Visit a page - note the total in mini cart
4. Visit the shop page and add another item to the cart. Note the new mini cart total
5. Press the browser back button. Without mousing over the mini cart block, confirm the total updates

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Enhancement: Refresh the cart after using the back button to return to checkout.

### CODE REVIEW

File: assets/js/base/context/hooks/cart/use-store-cart.ts [hunk 1]
```diff
@@ -138,8 +138,7 @@ export const useStoreCart = (
 	const { shouldSelect } = options;
 	const currentResults = useRef();
 
-	// This will keep track of jQuery and DOM events triggered by other blocks
-	// or components and will invalidate the store resolution accordingly.
+	// This will keep track of jQuery and DOM events that invalidates the store resolution accordingly.
```
Comment (Aljullu) [inline assets/js/base/context/hooks/cart/use-store-cart.ts]: I find the new comment a bit confusing to read. What about something like this?
```suggestion
	// This will keep track of jQuery and DOM events that invalidate the store resolution.
```

File: assets/js/base/context/hooks/cart/use-store-cart-event-listeners.ts [hunk 2]
```diff
@@ -78,10 +110,12 @@ const removeListeners = (): void => {
 	window.wcBlocksStoreCartListeners.count--;
 };
 
+/**
+ * Keeps track of jQuery and DOM events that invalidates the store resolution accordingly.
```
Comment (Aljullu) [inline assets/js/base/context/hooks/cart/use-store-cart-event-listeners.ts]: Same comment here. :upside_down_face:

**Review by Aljullu — COMMENTED** [review]
I will leave the final review to somebody from Rubik, but noting that I tested with the Mini Cart block and it works as described. Thanks @mikejolley!

File: assets/js/base/context/hooks/cart/use-store-cart-event-listeners.ts [hunk 3]
```diff
@@ -2,25 +2,50 @@
...
+/**
+ * Refreshes data if the pageshow event is triggered by the browser history.
+ *
+ * The deprecated performance object is needed in chrome since persisted is not reliable.
+ */
+const refreshDataIfPersisted = ( event: PageTransitionEvent ): void => {
+	if (
+		event?.persisted ||
+		( typeof window.performance !== undefined &&
+			window.performance.navigation.type === 2 )
```
Comment (opr) [inline assets/js/base/context/hooks/cart/use-store-cart-event-listeners.ts]: Just did some googling, wondering if we could avoid the deprecated code by using `window.performance.getEntriesByType("navigation")[0].type` instead, and checking if it equals `back_forward`? What do you think?

File: assets/js/base/context/hooks/cart/use-store-cart-event-listeners.ts [hunk 4]
```diff
@@ -2,25 +2,50 @@
...
+		dispatch( CART_STORE_KEY ).invalidateResolutionForStore();
+	}
+};
+
+/**
+ * Refreshes data if the pageshow event is triggered by the browser history.
+ *
+ * The deprecated performance object is needed in chrome since persisted is not reliable.
+ */
+const refreshDataIfPersisted = ( event: PageTransitionEvent ): void => {
```
Comment (opr) [inline assets/js/base/context/hooks/cart/use-store-cart-event-listeners.ts]: Wondering if this function's name could be more descriptive of what it's doing? I never heard of "persisted" to mean loading from a cache before now, it makes sense, but I think it might be easier to reason with if we choose a simpler name. Could something like `refreshIfLoadedFromCache` or `refreshDataIfNavigationButtonsUsed` work better?

**Review by opr — CHANGES_REQUESTED** [review]
Functionality is working great, code looks mostly good too but just a couple of comments

File: assets/js/base/context/hooks/cart/use-store-cart-event-listeners.ts (hunk 3 above)
Comment (mikejolley) [reply assets/js/base/context/hooks/cart/use-store-cart-event-listeners.ts]: Switched this now if you want to take another look.

**Review by opr — APPROVED** [review]
Working in Safari and Edge for me, checked quantity notices still work correctly when using min/max quantities.
