### PR TITLE
Prepend CSS src with correct url scheme

### LINKED ISSUE #10170: Order Confirmation template: Some styles are missing when using WordPress 6.3 or when Gutenberg is active
## Describe the bug

While testing the Order Confirmation template against WordPress 6.3, I noticed that some styles are missing in the site editor. This is in contradiction to what we presented in p6q7sZ-e1p-p2.

### Before you start

1. Install the Gutenberg plugin.
2. Install and activate the Twenty Twenty-Three theme.

### WordPress 6.2.2, Gutenberg Active

1. Install and activate WordPress 6.2.2.
2. Activate the Gutenberg plugin.
3. Look up the Order Confirmation template both in the site editor and on the frontend.
4. See the problems as highlighted in the following screenshot:

Screenshot 2023-07-11 at 18 31 40

### WordPress 6.2.2, Gutenberg Inactive

1. Install and activate WordPress 6.2.2.
2. Deactivate the Gutenberg plugin.
3. Look up the Order Confirmation template both in the site editor and on the frontend.
4. See that the styles appear as seen in the following screenshot:

Screenshot 2023-07-11 at 18 34 04

### WordPress 6.3, Gutenberg Inactive

1. Install and activate WordPress 6.3.
2. Activate the Gutenberg plugin.
3. Look up the Order Confirmation template both in the site editor and on the frontend.
4. See the problems as highlighted in the following screenshot:

Screenshot 2023-07-11 at 18 35 43

### WordPress 6.3, Gutenberg Inactive

1. Install and activate WordPress 6.3.
2. Deactivate the Gutenberg plugin.
3. Look up the Order Confirmation template both in the site editor and on the frontend.
4. See the problems as highlighted in the following screenshot:

Screenshot 2023-07-11 at 18 35 43

## Expected behavior

I expect the table borders to be visible, independent if Gutenberg is active or inactive and independent of the WordPress version.

## Environment

I tested this issue against the following variations:

| WordPress | Gutenberg (16.1.2) | Theme               |
| --------- | --------- | ------------------- |
| 6.2.2     | Active    | Twenty Twenty-Three |
| 6.2.2     | Inactive  | Twenty Twenty-Three |
| 6.3       | Active    | Twenty Twenty-Three |
| 6.3       | Inactive  | Twenty Twenty-Three |

> **Note**
> The same problem also appears when using the Twenty Twenty-Two theme.

cc: @mikejolley, @wavvves

### PR DESCRIPTION
**Pull request by mikejolley**
Styles from themes (2023 for example) were not working in the editor because the src began with `//`. This fixes the issue by ensuring there is a `https://` prefix.

Fixes #10170

### Screenshots

Screenshot 2023-07-17 at 15 04 50

#### User Facing Testing

1. With Twenty Twenty Three theme and Gutenberg plugin active, go to the site editor
2. Edit Templates > Order Confirmation
3. Check that styles match the screenshot above taking note of the borders around tables, and the lack of bullets next to list items.

* [x] Do not include in the Testing Notes 

### Changelog

> Fixed classic template appearance in the editor with some of the default themes

### CODE REVIEW

File: src/BlockTypes/ClassicTemplate.php [hunk 1]
```diff
@@ -47,10 +48,17 @@ protected function initialize() {
...
 		if ( class_exists( 'WC_Frontend_Scripts' ) && is_admin() ) {
-			$frontend_scripts = new \WC_Frontend_Scripts();
+			$frontend_scripts = new WC_Frontend_Scripts();
 			$styles           = $frontend_scripts::get_styles();
+
 			foreach ( $styles as $handle => $style ) {
-				wp_enqueue_style( $handle, $style['src'], $style['deps'], $style['version'], $style['media'] );
+				wp_enqueue_style(
+					$handle,
+					substr( $style['src'], 0, 2 ) === '//' ? 'https:' . $style['src'] : $style['src'],
```
Comment (tarhi-saad) [inline src/BlockTypes/ClassicTemplate.php]: @mikejolley, shouldn't we also handle the case of no secure websites (HTTP)? This worked fine on my Jurassic Ninja test site but not on my local development site. Maybe there is a solution to include both protocols, or we can do a check as follows:

```PHP
$protocol = strtolower( substr( $_SERVER[ "SERVER_PROTOCOL" ], 0, 5 ) ) == 'https' ? 'https' : 'http';
```

I've tested with `$_SERVER['HTTPS']`, but it doesn't return the correct values on my local server.

**Review by tarhi-saad — COMMENTED** [review]
Thank you, @mikejolley, for the fix! I've left a comment below!

File: src/BlockTypes/ClassicTemplate.php (hunk 1 above)
Comment (mikejolley) [reply src/BlockTypes/ClassicTemplate.php]: @tarhi-saad I added `set_url_scheme`. That takes care of it for us.

**Review by tarhi-saad — APPROVED** [review]
> I added set_url_scheme. That takes care of it for us.

That's awesome! It works as expected! Let's 🚢 it!
