### PR TITLE
Ensure inner content is not truncated on different widths

### LINKED ISSUE #9555: WooCommerce Just Arrived Full Hero Pattern Broken Alignment
## Describe the bug

The alignment on the `WooCommerce Just Arrived Full Hero` pattern breaks when the alignment width is adjusted.

This pattern essentially inserts a Core Cover Block, which does not have any issues with width adjustments. This issue appears to stem from a hard-coded setting in the pattern itself.

## To reproduce

1. Create a new post & add the `WooCommerce Just Arrived Full Hero` pattern.
2. The pattern inserts a core Cover Block - adjust the alignment on the Cover Block from `Full width` (the pattern's default) to either `Wide width` or `None`.
3. Note that the text (Heading, Paragraph, and Buttons blocks) are misaligned and squished to the right side of the containing Cover Block.

## Expected behavior

The text within the Cover Block should not become misaligned when the block width is adjusted. When the block is at full-width on a narrow viewport, it maintains it's position – this should be the case when the alignment is explicitly adjusted as well.

## Screenshots

**WooCommerce Just Arrived Full Hero:**

CleanShot 2023-05-19 at 13 47 33

**Core Cover Block (for comparison):**

CleanShot 2023-05-19 at 13 49 46

### WordPress (please complete the following information):

-   WordPress version: 6.2.1
-   Gutenberg version (if installed): 15.8.0
-   WooCommerce version: 7.7.0
-   WooCommerce Blocks version: 10.3.0-dev
-   Site language: English
-   Any other plugins installed:

```
➜  wp plugin list
+-----------------------------------------+----------+------------------------------+------------+
| name                                    | status   | update                       | version    |
+-----------------------------------------+----------+------------------------------+------------+
| ai-engine                               | inactive | available                    | 1.6.81     |
| akismet                                 | inactive | none                         | 5.1        |
| debug-bar                               | active   | none                         | 1.1.4      |
| debug-bar-console                       | active   | none                         | 0.3        |
| developer                               | inactive | none                         | 1.2.6      |
| gutenberg                               | active   | none                         | 15.8.0     |
| hello                                   | inactive | none                         | 1.7.2      |
| jetpack                                 | active   | none                         | 12.1       |
| log-deprecated-notices                  | inactive | none                         | 0.4.1      |
| query-monitor                           | inactive | none                         | 3.12.3     |
| smntcs-show-symlinked-plugins           | active   | none                         | 1.0        |
| woocommerce                             | active   | none                         | 7.7.0      |
| woocommerce-360-image                   | inactive | none                         | 1.2.0      |
| woocommerce-additional-variation-images | inactive | none                         | 2.3.0      |
| woocommerce-ajax-layered-nav            | inactive | none                         | 1.9.0      |
| woocommerce-blocks                      | active   | version higher than expected | 10.3.0-dev |
| woocommerce-payments                    | inactive | none                         | 5.9.0      |
| woocommerce-product-addons              | inactive | none                         | 6.2.0      |
| woocommerce-product-bundles             | inactive | none                         | 6.16.0     |
| woocommerce-products-compare            | inactive | none                         | 1.1.0      |
| woocommerce-quick-view                  | inactive | none                         | 1.6.0      |
| woocommerce-splash-popup                | inactive | none                         | 1.4.1      |
+-----------------------------------------+----------+------------------------------+------------+
```

### Desktop (please complete the following information):

-   OS: [e.g. macOS, Windows]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   Device: MacBook Pro, 14 inch, 2021
-   OS: MacOS Ventura 13.3.1
-   Browser: Chrome
-   Version: 113.0.5672.126

## Additional context

This was highlighted during our internal product walkthrough exercise.

### PR DESCRIPTION
**Pull request by roykho**
Fixes https://github.com/woocommerce/woocommerce-blocks/issues/9555

This PR fixes the issue where the inner content of the cover block gets truncated in different widths. Note that I also added a inner group so the content is easier to manipulate as a whole instead of individual content items.

### Screenshots

| Full | Wide | None |
| ------ | ----- | ----- |
||||

#### User Facing Testing

1. Create a new post & add the WooCommerce Just Arrived Full Hero pattern.
2. Adjust the alignment on the Cover Block from Full width (the pattern's default) to either Wide width or None.
3. Note that the text (Heading, Paragraph, and Buttons blocks) are not squished or truncated to the right and that they show as expected aligning towards the right side of the block.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix text alignment issue on various widths for Just arrived full hero pattern

### CODE REVIEW

File: patterns/just-arrived-full-hero.php [hunk 1]
```diff
@@ -5,19 +5,20 @@
...
+<!-- wp:cover {"useFeaturedImage":true,"dimRatio":0,"contentPosition":"center right","isDark":false,"align":"full","style":{"spacing":{"padding":{"right":"4em"}}}} -->
+<div class="wp-block-cover alignfull is-light has-custom-content-position is-position-center-right" style="padding-right:4em"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:group {"layout":{"type":"constrained"}} -->
+<div class="wp-block-group"><!-- wp:heading {"style":{"typography":{"fontStyle":"normal","fontWeight":"700"}},"fontSize":"x-large","anchor":"just-arrived"} -->
+<h2 class="wp-block-heading has-x-large-font-size" id="just-arrived" style="font-style:normal;font-weight:700">Just arrived</h2>
 <!-- /wp:heading -->
 
 <!-- wp:paragraph {"fontSize":"medium"} -->
-<p class="has-medium-font-size"><?php esc_html_e( 'Our early autumn collection is here.', 'woo-gutenberg-products-block' ); ?></p>
+<p class="has-medium-font-size">Our early autumn collection is here.</p>
```
Comment (gigitux) [inline patterns/just-arrived-full-hero.php:15]: Not sure, but I think that `esc_html_e` is necessary for the translations.

**Review by gigitux — CHANGES_REQUESTED** [review]
This PR fixes the bug, but I think that we should continue to use `esc_html_e` for the text. In this way, the patterns are translatable.

> Create a new post & add the WooCommerce Just Arrived Full Hero pattern.

Not sure that it is a bug, but I can't see this pattern in the post editor (the pattern is available in the site editor)

image

File: patterns/just-arrived-full-hero.php (hunk 1 above)
Comment (roykho) [reply patterns/just-arrived-full-hero.php:15]: So in all the newer patterns, we no longer added translatable text for them. So I just follow the same thing here. I think the reasoning is because these are just examples and the user will never be using these text and will use their own.

**Comment by roykho** [comment]
> Not sure that it is a bug, but I can't see this pattern in the post editor (the pattern is available in the site editor)

I am seeing it on my end.

File: patterns/just-arrived-full-hero.php (hunk 1 above)
Comment (gigitux) [reply patterns/just-arrived-full-hero.php:15]: TIL

**Review by gigitux — APPROVED** [review]
Thanks for this PR and answering my comments! LGTM! 🚢
