### PR TITLE
WooCommerce Classic Template block: Fix error on clearing customizations on Woo Templates

### LINKED ISSUE #9637: Block error is displayed on clearing customizations for Woo Templates
## Describe the bug

When clearing out the customizations for a WooCommerce template, an error is consistently displayed when accessing it on the editor side:

`Your site doesn’t include support for the "woocommerce/legacy-template" block. You can leave this block intact or remove it entirely.`

This error occurs with and without having the Gutenberg plugin enabled (WordPress version 6.2, WooCommerce 7.8.0 and WooCommerce Blocks 10.4.0).

https://github.com/woocommerce/woocommerce-blocks/assets/15730971/13b80991-582a-481f-aeef-b13202fe9126

## To reproduce

1. Make sure you have a block theme enabled, such as Twenty-twenty three
2. Click on Edit Site
3. Click on Templates and customize any of the Woo's templates: e.g. the Single Product and save the changes
4. Now go back to the Site Editor and under Templates > Manage all templates, click on the ellipsis button and clear all customizations for the Single Product template: wait for the success message to be displayed.
5. Now, without refreshing the page, go back to edit the Single Product template: notice how the `Your site doesn’t include support for the "woocommerce/legacy-template" block. You can leave this block intact or remove it entirely.` is displayed.
6. Now refresh the editor page and verify that the block is rendered without any problems.

## Expected behavior

No block errors should be displayed when accessing any of the Woo templates right after clearing customizations.

### WordPress (please complete the following information):

-   WordPress version: [6.2.2]
-   WooCommerce version: [7.8.0]
-   WooCommerce Blocks version: [10.4.0]

### PR DESCRIPTION
**Pull request by thealexandrelara**
## Description
When the user clears the customizations made on the Single Product template and visits the template page without refreshing the page, an error was occurring that prevented the WooCommerce Classic Template block from being rendered on the Editor.

This PR fixes that error by replacing the 'core/missing' block with the original block (WooCommerce Classic Template) when the template has support to the classic block and the block is already registered.

### <samp>🤖 Generated by Copilot at b78ab3d</samp>

* Import `parse` function to parse block content into block object ([link](https://github.com/woocommerce/woocommerce-blocks/pull/9759/files?diff=unified&w=0#diff-49cf8439043f78ee9f68b6374ef821be0b59c5804fec85e9aecf528d7fe9bcecR10))
* Import `dispatch` and `debounce` functions to dispatch actions and limit function calls ([link](https://github.com/woocommerce/woocommerce-blocks/pull/9759/files?diff=unified&w=0#diff-49cf8439043f78ee9f68b6374ef821be0b59c5804fec85e9aecf528d7fe9bcecL21-R32))
* Define and export `tryToRecoverClassicTemplateBlockWhenItFailsToRender` function to replace 'core/missing' block with original Classic Template block if it fails to render ([link](https://github.com/woocommerce/woocommerce-blocks/pull/9759/files?diff=unified&w=0#diff-49cf8439043f78ee9f68b6374ef821be0b59c5804fec85e9aecf528d7fe9bcecR344-R379))
* Remove unnecessary condition that checked previous template ID ([link](https://github.com/woocommerce/woocommerce-blocks/pull/9759/files?diff=unified&w=0#diff-49cf8439043f78ee9f68b6374ef821be0b59c5804fec85e9aecf528d7fe9bcecL344-L348))
* Replace condition that checked block undefined with variable that checked block registered and add condition that calls `tryToRecoverClassicTemplateBlockWhenItFailsToRender` if block registered and template supports Classic Template block ([link](https://github.com/woocommerce/woocommerce-blocks/pull/9759/files?diff=unified&w=0#diff-49cf8439043f78ee9f68b6374ef821be0b59c5804fec85e9aecf528d7fe9bcecL356-R409), [link](https://github.com/woocommerce/woocommerce-blocks/pull/9759/files?diff=unified&w=0#diff-49cf8439043f78ee9f68b6374ef821be0b59c5804fec85e9aecf528d7fe9bcecL374-R425))
* Wrap `subscribe` function with namespace argument of 'core/blocks-editor' to limit subscription scope to block editor store ([link](https://github.com/woocommerce/woocommerce-blocks/pull/9759/files?diff=unified&w=0#diff-49cf8439043f78ee9f68b6374ef821be0b59c5804fec85e9aecf528d7fe9bcecL382-R433))

Fixes #9637 

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
|  image  |  image |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Log in to your WordPress dashboard.
2. From your WordPress dashboard, go to Appearance > Themes. Make sure you have a block-based theme installed and activated. If not, you can install one from the Add New option. Block-based themes include "Twenty-twenty Two," "Twenty-twenty Three", etc.
3. On the left-hand side menu, click on Appearance > Editor. This will open the Site Editor.
4. On the left-hand side menu, click on Templates. This will open the list of available templates.
5. Find and select the Single Product template from the list.
6. When the template renders, modify it by adding or removing blocks. Once you finish customizing it, on the top right side, click on Save;
7. On the top left side, click on the WordPress logo;
8. On the menu, click on the "Left Arrow" icon to go back to the list of templates;
9. Click on Manage all Templates;
10. Locate the Single Product template on the list. Click on the three vertical dots and select Clear customizations
11. Wait for the message confirming that the template was reverted successfully;
12. On the templates list, click on the Single Product template;
13. Make sure that the Unsupported block is not rendered, and the WooCommerce Classic Template block is rendered instead.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

Before the changes, the code was subscribing to all events from the `@wordpress/data`, but now the subscription is restricted to the changes on the 'core/block-editor' storage so possible the performance will be better after merging these changes.

### Changelog

> Fix error on clearing customizations on Woo Templates that prevented WooCommerce Classic Template block from being displayed

### CODE REVIEW

**Review by Aljullu — COMMENTED** [review]
The PR is testing well, but I wasn't able to reproduce the issue in `trunk`. I tried with the steps from #9637 and the ones from this PR. I might be missing an important step somewhere. :confused: 

> When the template renders, modify it by adding or removing blocks. Once you finish customizing it, on the top right side, click on Save;

Does it matter if I have the blockified template or the template is using the _WooCommerce Single Product Block_? Also, does it matter if the other WC templates are blockified or using the legacy block?

**Comment by thealexandrelara** [comment]
> The PR is testing well, but I wasn't able to reproduce the issue in `trunk`. I tried with the steps from #9637 and the ones from this PR. I might be missing an important step somewhere. 😕
> 
> > When the template renders, modify it by adding or removing blocks. Once you finish customizing it, on the top right side, click on Save;


When I first tried reproducing the issue, I wasn't able to reproduce it as well. I did a fresh install using the same versions for WordPress, WooCommerce and WooCommerce blocks that are in the issue https://github.com/woocommerce/woocommerce-blocks/issues/9637 and just then I manage to reproduce it

> Does it matter if I have the blockified template or the template is using the _WooCommerce Single Product Block_? Also, does it matter if the other WC templates are blockified or using the legacy block?

In this particular case, it is important that the template have the WooCommerce Single Product Block (the block name in code is `woocommerce/legacy-template`) when clearing the customizations because this is the block in which the issue was occurring.

Providing a little bit of context, this specific block is only registered for some templates like the Single Product template. While investigating the problem, I confirmed that the block is being correctly registered (when the page is fully loaded, the block has a registered state), I think the problem is about timing. If I click on Clear all customizations button, wait for the confirmation message and visit the Single Product page, the `core/missing` block takes precedence and appears with a message saying that the block is not supported, and this probably occurs before the block have enough time to be registered. What I did was to check if the `core/missing` block appears and if the block is already registered, if so I try to restore the original block.

File: assets/js/blocks/classic-template/index.tsx [hunk 1]
```diff
@@ -333,6 +341,42 @@ const registerClassicTemplateBlock = ( {
...
+/**
+ * Attempts to recover the Classic Template block if it fails to render on the Single Product template
+ * due to the user resetting customizations without refreshing the page.
+ *
+ * When the Classic Template block fails to render, it is replaced by the 'core/missing' block, which
+ * displays an error message stating that the WooCommerce Classic template block is unsupported.
+ *
+ * This function replaces the 'core/missing' block with the original Classic Template block that failed
+ * to render, allowing the block to be displayed correctly.
+ *
```
Comment (Aljullu) [inline assets/js/blocks/classic-template/index.tsx:353]: I would add here a link to the issue or the PR, so if somebody wants more context, they can easily find where to go in GitHub.

**Review by Aljullu — APPROVED** [review]
Thanks, @thealexandrelara! I'm not sure what I was doing wrong, I think the issue was that I had the _Shop_ page as the home, so when navigating from one template to the other the Classic Template block was being registered automatically. After changing that I could reproduce the issue consistently. Sorry for the confusion!

I have to say the issue is a bit confusing, but I couldn't find a simpler way to solve it. Your solution works well and code looks good too, so approving. I just left one minor comment, I think it would be nice to add a link to the GH issue or PR for future reference, what do you think? Besides that, LGTM.

File: assets/js/blocks/classic-template/index.tsx (hunk 1 above)
Comment (thealexandrelara) [reply assets/js/blocks/classic-template/index.tsx:353]: Done!
