### PR TITLE
Avoid const and let in inline JS

### LINKED ISSUE #2439: JS error when add both Cart & Checkout blocks to a post
### To reproduce
- Edit a post or page.
- Add the `Cart` block.
- Add the `Checkout` block.
- Publish, view on front end.

Expected: works (?) or prevent adding both to same page. See also related issue for post vs. page: #2440

Actual: JavaScript error in console: `Uncaught SyntaxError: Identifier 'containers' has already been declared`

Maybe related to loading skeleton stuff, error is on this line:

```js
const containers = document.querySelectorAll( 'div.wc-block-skeleton' );
```

### PR DESCRIPTION
**Pull request by mikejolley**
Since these inline scripts can be loaded in multiple times, avoid `const` and `let`.

Fixes #2439

### How to test the changes in this Pull Request:

1. Add cart and checkout blocks to a page
2. View console errors on frontend.

### CODE REVIEW

File: src/BlockTypes/AbstractBlock.php [hunk 1]
```diff
@@ -151,12 +151,12 @@ protected function enqueue_scripts( array $attributes = [] ) {
...
 		return "<script>
-			const containers = document.querySelectorAll( 'div.wc-block-skeleton' );
+			var containers = document.querySelectorAll( 'div.wc-block-skeleton' );
 
 			if ( containers.length ) {
 				Array.prototype.forEach.call( containers, function( el, i ) {
-					const w = el.offsetWidth;
-					let classname = '';
+					var w = el.offsetWidth;
+					var classname = '';
```
Comment (Aljullu) [inline src/BlockTypes/AbstractBlock.php:159]: Actually here it would be fine using `const` and `let` because they are scoped inside the inner function. But having it as `var` makes sense as well to keep it consistent.

**Comment by senadir** [comment]
those code blocks could also be scoped in a `{}` to fix this, this also works.

File: src/BlockTypes/AbstractBlock.php (hunk 1 above)
Comment (mikejolley) [reply src/BlockTypes/AbstractBlock.php:159]: Yeah that's why I changed it. I didn't want to mix const/let with old vars.
