### PR TITLE
Fix Product SKU not being displayed on frontend

### LINKED ISSUE #9030: Single Product Block missing meta information on frontend
## Describe the bug

When the single product block is used, meta information such as SKU, categories and tags are missing on the frontend.

## To reproduce

1. Add a page.
2. Add the Single Product Block. Update save.
3. Open this page on the frontend.
4. See that the meta information is missing.

## Expected behavior

All the meta information should be shown.

## Screenshots

| Editor | Frontend |
| ------ | ----- |
| ||

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   Gutenberg version (if installed): 15.5.1
-   WooCommerce version: 7.7.0-dev
-   WooCommerce Blocks version: 10.1.0-dev
-   Site language: English
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: Chrome
-   Version: 112.0

### PR DESCRIPTION
**Pull request by thealexandrelara**
#### <samp>🤖 Generated by Copilot at bd5da9a</samp>
<samp>👨‍💻 Enhanced by @thealexandrelara </samp>

This pull request adds a custom hook `useIsDescendentOfSingleProductBlock` and uses it in the SKU block to make it compatible with both global and single product contexts. This allows the SKU block to display the correct product data and format depending on where it is inserted.

#### <samp>🤖 Generated by Copilot at bd5da9a</samp>
<samp>👨‍💻 Enhanced by @thealexandrelara </samp>

*  Add a custom hook `useIsDescendentOfSingleProductBlock` that returns a boolean indicating whether a given block is a descendent of a single product block ([link](https://github.com/woocommerce/woocommerce-blocks/pull/9446/files?diff=unified&w=0#diff-aa49fde87e5be80d4599f058ff17824385a92823312142c5e9c846be37525168R1-R30))
* Use the hook in the SKU block edit component to get the value of `isDescendentOfSingleProductBlock` for the current block ([link](https://github.com/woocommerce/woocommerce-blocks/pull/9446/files?diff=unified&w=0#diff-273af84aa585a8e5a5a1446b8e97d85242eca59f5bf0696f3111b6627794ebaeR16), [link](https://github.com/woocommerce/woocommerce-blocks/pull/9446/files?diff=unified&w=0#diff-273af84aa585a8e5a5a1446b8e97d85242eca59f5bf0696f3111b6627794ebaeR32-R33))
* Pass the value to the `useProductDataContext` hook and the `ProductSKU` component as a prop ([link](https://github.com/woocommerce/woocommerce-blocks/pull/9446/files?diff=unified&w=0#diff-273af84aa585a8e5a5a1446b8e97d85242eca59f5bf0696f3111b6627794ebaeR32-R33), [link](https://github.com/woocommerce/woocommerce-blocks/pull/9446/files?diff=unified&w=0#diff-273af84aa585a8e5a5a1446b8e97d85242eca59f5bf0696f3111b6627794ebaeR57), [link](https://github.com/woocommerce/woocommerce-blocks/pull/9446/files?diff=unified&w=0#diff-273af84aa585a8e5a5a1446b8e97d85242eca59f5bf0696f3111b6627794ebaeR63))
* Use the value to determine the product data source and the SKU value rendering in the `useProductDataContext` hook and the `ProductSKU` component respectively ([link](https://github.com/woocommerce/woocommerce-blocks/pull/9446/files?diff=unified&w=0#diff-273af84aa585a8e5a5a1446b8e97d85242eca59f5bf0696f3111b6627794ebaeR57), [link](https://github.com/woocommerce/woocommerce-blocks/pull/9446/files?diff=unified&w=0#diff-273af84aa585a8e5a5a1446b8e97d85242eca59f5bf0696f3111b6627794ebaeR63))
* Add the value to the SKU block attributes type definition in `types.ts` ([link](https://github.com/woocommerce/woocommerce-blocks/pull/9446/files?diff=unified&w=0#diff-5379610aca73c6047987a3ba4cb81dcde9c96a0944cf62b52c7c5aa0d159eb08R5))

Fixes #9030 

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
|  image  | image |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Log in to your WordPress dashboard.
2. On the left-hand side menu, click on 'Posts' and then 'Add New' to create a new post. Alternatively, if you want to add the block to an existing post, you can simply find that post and click 'Edit'.
3. Inside the post editor, click on the '+' button, usually found at the top left of the editing space or within the content area itself, to add a new block.
4. In the block library that pops up, you can search for the 'Single Product' block. You can do this by typing 'Single Product' into the search bar at the top of the block library.
5. Click on the 'Single Product' block to add it to your post. You'll be prompted to select a product from your WooCommerce store to feature in the block. Make sure to select a product that contains a SKU.
6. Once you've selected a product, the block will be inserted into your post and will display information about the product you've selected.
7. Click on the 'Single Product' block in your post to select it.
8. Once the product is selected, click on the top-right side click on the Save button;
9. Visit the post that you just created and check if the Product SKU is displayed.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental

### CODE REVIEW

File: assets/js/atomic/blocks/product-elements/shared/use-is-descendent-of-single-product-block.tsx [hunk 1]
```diff
@@ -0,0 +1,30 @@
+/**
+ * External dependencies
+ */
+import { useSelect } from '@wordpress/data';
+
+interface UseIsDescendentOfSingleProductBlockProps {
+	blockClientId: string;
+}
+
+export const useIsDescendentOfSingleProductBlock = ( {
```
Comment (nefeline) [inline assets/js/atomic/blocks/product-elements/shared/use-is-descendent-of-single-product-block.tsx:10]: 👏 glad to see this as a hook now!

**Review by nefeline — APPROVED** [review]
Great work!

✅ Confirmed that the SKU is adequately displayed on the FE and in the editor.
