### PR TITLE
Reduce number of dependencies for the product categories list block

### LINKED ISSUE #762: JavaScript errors when using a plugin that minifies JS files
Reported several times in the support forums:

- https://wordpress.org/support/topic/javascript-errors-42/
- https://wordpress.org/support/topic/error-js-and-fast-velocity-minify/
- https://wordpress.org/support/topic/update-website-sliders-javascript-referenceerror-_-is-not-defined/

**To Reproduce**

1. Install WooCommerce Blocks.
2. Install Autoptimize.
3. Create a post with a _Product Categories List_ block.
4. View the post in the frontend and notice there are JS errors in the console.

### PR DESCRIPTION
**Pull request by mikejolley**
This PR improves how JS powered blocks work on the frontend, reducing the overall number of dependencies. In testing, this reduced downloaded JS from 4.8MB to 2.2MB.

Fixes #762

The changes to the webpack config are to prevent wp.element and lodash being enqueued on the frontend - we can use React only here.

### How to test the changes in this Pull Request:

1. before checking out this branch, create some product category list blocks in a page
2. checkout and build
3. confirm `build/frontend.deps.js` only contains `["react","react-dom","wp-i18n","wp-polyfill"]`
4. check existing list blocks work in the editor and on the frontend
5. create a new product category list block - ensure it works as expected

### Changelog

> Reduced the number of JavaScript assets needed for the Product Category List block to improve performance.

### CODE REVIEW

File: assets/js/blocks/product-categories/hierarchy.js [hunk 1]
```diff
@@ -27,8 +23,8 @@ export function buildTermsTree( list = [] ) {
 	const tree = fillWithChildren( termsByParent[ '0' ] || [] );
 	delete termsByParent[ '0' ];
 
-	// anything left in termsByParent has no visible parent
-	forEach( termsByParent, ( terms ) => {
+	// anything left in termsByParent has no visible parent. Native JS instead of lodash forEach.
```
Comment (Aljullu) [inline assets/js/blocks/product-categories/hierarchy.js]: I think we can skip this comment: `Native JS instead of lodash forEach.`, in the future I think it might be more confusing than anything else, what do you think?

File: webpack.config.js [hunk 2]
```diff
@@ -101,7 +101,12 @@ const GutenbergBlocksConfig = {
 			{
 				test: /\.jsx?$/,
 				exclude: /node_modules/,
-				loader: 'babel-loader?cacheDirectory',
+				use: {
+					loader: 'babel-loader?cacheDirectory',
+					options: {
+						presets: [ '@wordpress/default' ],
```
Comment (Aljullu) [inline webpack.config.js]: What is the difference between `@wordpress/default` and `@wordpress/babel-preset-default` (which was used in `babel.config.js` before)?

File: webpack.config.js [hunk 3]
```diff
@@ -152,7 +157,25 @@ const BlocksFrontendConfig = {
 			{
 				test: /\.jsx?$/,
 				exclude: /node_modules/,
-				loader: 'babel-loader?cacheDirectory',
+				use: {
+					loader: 'babel-loader?cacheDirectory',
+					options: {
+						presets: [
```
Comment (Aljullu) [inline webpack.config.js]: I think this should work too and this way we don't have to define the `presets` again:
```JS
options: {
	...require( '@wordpress/babel-preset-default' ),
	plugins: [
		'@babel/plugin-transform-react-jsx',
		'@babel/plugin-transform-runtime',
		'transform-object-rest-spread',
		'transform-async-generator-functions',
	],
},
```

File: assets/js/blocks/product-categories/block.js [hunk 4]
```diff
@@ -115,43 +104,26 @@ class ProductCategoriesBlock extends Component {
 										{ this.renderOptions( categories ) }
 									</select>
 								</div>
-								<IconButton
+								<button
+									type="button"
+									className="components-button components-icon-button"
```
Comment (Aljullu) [inline assets/js/blocks/product-categories/block.js]: I'm ok doing that in a follow-up, but it looks like these classes use styles from wp-admin stylesheets (`css/dist/components/style.css`) could we avoid importing that file and instead creating the new styles required for this button in `product-categories/style.scss`?

**Comment by Aljullu** [comment]
There seems to be an issue with the native `forEach()` and IE11:
image

File: assets/js/blocks/product-categories/block.js [hunk 5]
```diff
@@ -36,6 +22,10 @@ class ProductCategoriesBlock extends Component {
 		this.renderOptions = this.renderOptions.bind( this );
 	}
 
+	componentWillMount() {
+		this.id = uniqueID( '', 'wc-block-product-categories' );
```
Comment (Aljullu) [inline assets/js/blocks/product-categories/block.js]: Can we move this to the constructor? Using `componentWillMount` is discouraged:
https://reactjs.org/docs/react-component.html#unsafe_componentwillmount

File: assets/js/blocks/product-categories/frontend.js [hunk 6]
```diff
@@ -1,29 +1,31 @@
...
 import Block from './block.js';
+import getCategories from './get-categories';
 
 const containers = document.querySelectorAll(
 	'.wp-block-woocommerce-product-categories'
 );
 
 if ( containers.length ) {
-	forEach( containers, ( el ) => {
+	containers.forEach( function( el ) {
```
Comment (Aljullu) [inline assets/js/blocks/product-categories/frontend.js]: There seems to be an issue with the native NodeList `forEach()` and IE11:
image
Using Array's `forEach` should do the trick:
```suggestion
	Array.prototype.forEach.call( containers, ( el ) => {
```

For reference, I took the [work-around from MDN](https://developer.mozilla.org/en-US/docs/Web/API/NodeList#Example).

File: webpack.config.js (hunk 2 above)
Comment (mikejolley) [reply webpack.config.js]: This is what is documented on the package here https://www.npmjs.com/package/@wordpress/babel-preset-default

File: assets/js/blocks/product-categories/block.js (hunk 4 above)
Comment (mikejolley) [reply assets/js/blocks/product-categories/block.js]: 👍

**Comment by mikejolley** [comment]
Ready for another look @Aljullu. I handled the CSS change too (wasn't difficult) and cleaned up the ID generation using a HOC. Let me know your thoughts and if you think it's good for 2.3.

File: assets/js/blocks/product-categories/block.js [hunk 7]
```diff
@@ -115,43 +100,26 @@ class ProductCategoriesBlock extends Component {
...
-	 */
-	instanceId: PropTypes.number,
-	/**
-	 * Whether this is the block preview or frontend display.
-	 */
-	isPreview: PropTypes.bool,
-};
-
-export default withInstanceId( ProductCategoriesBlock );
+export default withComponentID( ProductCategoriesBlock );
```
Comment (Aljullu) [inline assets/js/blocks/product-categories/block.js]: I know that's very nitpicky, but what do you think about renaming `withComponentID` and `componentID` to `withComponentId` and `componentId` (notice the camel case)? This way it's consistent with `withInstanceId`and `instanceId`.

This also seems to be the consensus they arrived in Gutenberg: https://github.com/WordPress/gutenberg/issues/6741.
