### PR TITLE
Invalidate script data cache when site URL, scheme, or plugin name changes

### LINKED ISSUE #10221: Impossible to update cached script when transient already contains an incorrect value
## Describe the bug

I encountered this issue during the staging of a redesign:
The site was developed locally under Lando, in HTTPS, on a [Bedrock](https://roots.io/bedrock/) architecture: redesign from a classic WC to a FSE WC, preserving the database.
So far, so good.

The site was then installed in staging, the database was imported and then adapted using `wp db import` and `wp search replace`.
The result: the blocks no longer worked.

The console indicated a mixed-content issue with the WC Blocks scripts related to the blocks on the page that were loaded in **HTTP** instead of HTTPS:
Specifically, on the home page with a customer account block, and a mini-cart block in the menu header: wc-settings.js, mini-cart-frontend.js, price-format.js (I'm not completely certain about the last one, but I am about the first two).
No other scripts from other plugins had this problem.

My staging, also using a Bedrock architecture, had in its `.env` its `WP_ENV `set to `staging` which defined `SCRIPT_DEBUG` to `false`. When I switched its `WP_ENV` to `development` which defined `SCRIPT_DEBUG` to `true`, the problem disappeared.

I have no idea why this transient has a URL in HTTP instead of HTTPS. A recording during an SSL certificate crash maybe? I don't know.
In any case, once recorded it cannot be updated.

After looking at the code, my first attempt was to delete all the transients via the WooCommerce tools. Negative.

My second attempt was to install the Transient Manager plugin to delete the transient `woocommerce_blocks_asset_api_script_data`. Negative.

The only thing that worked was to fix the values using a `wp search-replace 'http:\/\/mystaging' 'https:\/\/mystaging'`

I believe the problem comes from [this commit](https://github.com/woocommerce/woocommerce-blocks/commit/6b9955d2a51bc56b0b029edc521ff98e3403dffc)
more specifically from [this code](https://github.com/woocommerce/woocommerce-blocks/blob/6b9955d2a51bc56b0b029edc521ff98e3403dffc/src/Assets/Api.php#L117C1-L131C3)

```PHP
	public function update_script_data_cache() {
		if ( is_null( $this->script_data ) || $this->disable_cache ) {
			return;
		}
		set_transient(
			'woocommerce_blocks_asset_api_script_data',
			wp_json_encode(
				array(
					'script_data' => $this->script_data,
					'version'     => $this->package->get_version(),
				)
			),
			DAY_IN_SECONDS * 30
		);
	}
```

I am in the case where `disable_cache` is `false`:
If `script_data` is `null`, we don't update it
If `script_data` contains something (and in my case something wrong), we put its value back in the transient

I might be making a mistake in my analysis, or perhaps the problem is more complex, but in any case, the problem was definitely there :)

## To reproduce

1. Modify the transient `woocommerce_blocks_asset_api_script_data` via PHPMyAdmin by replacing the `HTTPS` in the script `wc-settings.js` URL with `HTTP` 
2. See the mixed-content problem on a page using WC Blocks
3. Attempt to delete the transient to fix the problem.

## Environment
MacOS Ventura, Chrome...

### WordPress (please complete the following information):

-   WordPress version: 6.2.2
-   WooCommerce version: 7.8.2
-   WooCommerce Blocks version: 10.6.0

### PR DESCRIPTION
**Pull request by opr**
This PR adds a hash to the value of the `woocommerce_blocks_asset_api_script_data` transient. The hash is constructed based on the site URL, plugin version, and plugin path.

The plugin path is used to check whether we're loading from WC Core or the WC Blocks feature plugin.

This PR also introduces a new transient, `woocommerce_blocks_asset_api_script_data_ssl`. If the site is loaded using HTTPS the script data will be loaded from this transient, if it is loaded using HTTP it will get it from the original value.

This is required because, if a site is accessible by both HTTP and HTTPS, the URLs to the scripts would be cached with whatever scheme was used when the value was cached. While uncommon it has the potential to break sites so I would prefer to be safe at the expense of additional database storage.

Fixes #10221

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Load up your site, ensuring WooCommerce Blocks is active. Visit a page with the Cart or Checkout block on it.
2. Disable and delete the WooCommerce Blocks plugin from your site.
3. Load up the page from Step 1 and ensure it loads correctly.

##### Internal testing - Do not include in the Testing Notes

0. Ensure caching is disabled, go to [this line](https://github.com/woocommerce/woocommerce-blocks/blob/4a19873db1ed2b77c80ef5005616452757639d36/src/Assets/Api.php#L63) and set `$this->disable_cache` to `false`;
1. Set your site up to use both HTTPS and HTTP, it shouldn't redirect to one or the other, but should use whatever you access it by.
2. Open the network tab of dev tools
3. Load the HTTP version first. Load a page with Cart/Checkout blocks.
4. Load the HTTPS version next, load the same page and ensure the blocks render correctly, open the console.
5. Change the URL you use to access your site in your dev environment.
6. Change your site url (WordPress -> Settings -> General) to use the new site name.
7. Load the Cart/Checkout blocks and ensure they're working
8. Open your `wp_options` table search for
```sql
select *
FROM `wp_options`
where `option_name` LIKE '%woocommerce_blocks_asset_api_script_data%'
```
9. Ensure you see two transients, one for HTTPs and one for HTTP and they contain the correct URL for each.
10. Edit the transient values, make them invalid JSON.
11. Reload the page and ensure the scripts load correctly.
12. Re-query the database and ensure the invalid JSON you changed is gone and replaced with correctly formatted script data.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

Small increase in database storage due to new transient. This is an acceptable tradeoff because it prevents sites allowing access via HTTP and HTTPs from breaking based on who accesses the site first after the cache becomes invalid.

### Changelog

> Ensure cached script data is refreshed following a site URL change, version change, or when switching between the WooCommerce Blocks feature plugin and WooCommerce Core.

### CODE REVIEW

File: src/Assets/Api.php [hunk 1]
```diff
@@ -102,9 +136,9 @@ private function get_cached_script_data() {
 			return [];
 		}
 
-		$transient_value = json_decode( (string) get_transient( 'woocommerce_blocks_asset_api_script_data' ), true );
+		$transient_value = json_decode( (string) get_transient( $this->script_data_transient_key ), true );
```
Comment (wavvves) [inline src/Assets/Api.php:139]: Should we add an extra check with `json_last_error_msg()` or use the `JSON_THROW_ON_ERROR` flag to be extra safe here? [Documentation](https://www.php.net/manual/en/function.json-decode.php)

**Review by wavvves — CHANGES_REQUESTED** [review]

**Review by wavvves — APPROVED** [review]
