### PR TITLE
Fix inconsistent button styling with TT3

### LINKED ISSUE #7388: TT3: Inconsistent WooCommerce button styling
## Describe the bug

The WooCommerce buttons are styled differently to the current themes buttons on TT3, **this does not happen on TT2**.

## To reproduce

1. Activated TT3
2. Go To Appearance > Site Editor > Product Catalog and add a button to this template (or filter blocks) > Save.
3. Go to the Shop page
4. View the difference in button styles.
5. Go to the product page and now add to basket a related product at the bottom of the page
6. View another set of different buttons in the Mini Cart.

## Expected behavior

Button styling should be consistent.

## Screenshots

**Shop page**
Screenshot 2022-10-13 at 10 09 24

**Mini Cart**
Screenshot 2022-10-13 at 10 13 15

### PR DESCRIPTION
**Pull request by gigitux**
The WooCommerce buttons are styled differently from the current theme buttons on TT3. The issue is reproducible only if the link has never been visited. An easy way to test it is to visit that page from a private browsing window.

Fixes #7388

### Screenshots

| Before | After |
| ------ | ----- |
|image|image|

#### User Facing Testing

1. Enable TT3.
2. Create a new post/page and add the `All Product` block and the `Product Categories` block.
3. Save.
4. Visit the post/page via incognito mode and be sure that all the buttons have the same style. 

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix inconsistent button styling with TT3

### CODE REVIEW

File: src/BlockTypes/AbstractProductGrid.php [hunk 1]
```diff
@@ -647,7 +647,7 @@ protected function get_add_to_cart( $product ) {
 			'data-product_id'  => $product->get_id(),
 			'data-product_sku' => $product->get_sku(),
 			'rel'              => 'nofollow',
-			'class'            => 'wp-block-button__link add_to_cart_button',
+			'class'            => 'wp-block-button__link wp-element-button add_to_cart_button',
```
Comment (Aljullu) [inline src/BlockTypes/AbstractProductGrid.php]: Ideally, we should use `wp_theme_get_element_class_name( 'button' )` to get the correct class name, instead of directly using `wp-element-button`. Similar to what WC core does here: https://github.com/woocommerce/woocommerce/pull/35306/files#diff-3582a823c079f0c8354f3171ce608961ae6b224dd0182f7e4bb14e82278b05abR527-R543.

I don't know if there is an equivalent one for the JS side, but might be good investigating as well.

**Review by Aljullu — COMMENTED** [review]
Confirming it fixes the issue, thanks for picking this up, @gigitux! I just left one comment about using a function to retrieve the class name.

Also, I'm not sure about adding the `skip-changelog` label, I think it's worth mentioning it in the changelog.

File: src/BlockTypes/AbstractProductGrid.php (hunk 1 above)
Comment (gigitux) [reply src/BlockTypes/AbstractProductGrid.php]: Cool! Thanks for sharing this! I used `wc_wp_theme_get_element_class_name` to be more consistent with WC core [a00e4e6](https://github.com/woocommerce/woocommerce-blocks/pull/7516/commits/a00e4e60311b4fa407787a9451c55aab820f4537)

I searched, but I didn't find any JS equivalent. `wp_theme_get_element_class_name` reads data from theme.json that isn't accessible on the JS side.
https://github.com/WordPress/WordPress/blob/44881d209b2f37cccdbd1f9a8713ba782bbdb65f/wp-includes/theme.php/#L4231-L4233

**Comment by gigitux** [comment]
> Confirming it fixes the issue, thanks for picking this up, @gigitux! I just left one comment about using a function to retrieve the class name.
> 
> Also, I'm not sure about adding the `skip-changelog` label, I think it's worth mentioning it in the changelog.

Thanks for your review! I addressed your feedback, and I added a changelog entry too.

File: src/BlockTypes/AbstractProductGrid.php [hunk 2]
```diff
@@ -647,7 +647,7 @@ protected function get_add_to_cart( $product ) {
 			'data-product_id'  => $product->get_id(),
 			'data-product_sku' => $product->get_sku(),
 			'rel'              => 'nofollow',
-			'class'            => 'wp-block-button__link add_to_cart_button',
+			'class'            => 'wp-block-button__link ' . wc_wp_theme_get_element_class_name( 'button' ) . ' add_to_cart_button',
```
Comment (Aljullu) [inline src/BlockTypes/AbstractProductGrid.php]: If we use this function directly, we should update [the `WC requires at least` version to 7.0](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/woocommerce-gutenberg-products-block.php#L12), which is when `wc_wp_theme_get_element_class_name()` will be introduced. Another option would be to add a check around it to make sure it exists before calling it.

**Review by Aljullu — APPROVED** [review]
Pre-approving, but left a comment about adding a check around the PHP function or raising the required WC version (which we should do anyway in the next release).

File: src/BlockTypes/AbstractProductGrid.php (hunk 2 above)
Comment (gigitux) [reply src/BlockTypes/AbstractProductGrid.php]: > Pre-approving, but left a comment about adding a check around the PHP function or raising the required WC version (which we should do anyway in the next release).

Thanks for the review and thanks for the great catch! I added a check around the PHP function. I'm going to merge it!
