### PR TITLE
Fix bug with cart not updating

### LINKED ISSUE #1247: Add to Cart in new All Products Block does not update the page shopping cart on the same page
Reported  in a comment here: p90Yrv-1mS-p2

When adding a product to a cart using the add to cart button in the product grid, it's not updating the page shopping cart elsewhere on the page.  The item _is_ added to the cart, it's just not updating the view (Example using Storefront theme).

Screen Recording 2019-11-22 at 06 11 PM

### PR DESCRIPTION
**Pull request by senadir**
This PR adds a hack to trigger `wc_fragment_refresh` that updates the cart content when you click `Add to Cart` button, we should migrate to a store based approach when we build a cart block.

Fixes #1247

### CODE REVIEW

File: assets/js/atomic/components/product/button/index.js [hunk 1]
```diff
@@ -106,6 +106,15 @@ const ProductButton = ( { product, className } ) => {
 		}
 		return productCartDetails.text;
 	};
+
+	// This is a hack to trigger cart updates till we migrate to block based card
+	// that relies on the store, see
+	// https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1247
+	useEffect( () => {
+		const event = document.createEvent( 'Event' );
+		event.initEvent( 'wc_fragment_refresh', true, true );
```
Comment (Aljullu) [inline assets/js/atomic/components/product/button/index.js]: [`initEvent`](https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent) seems to be deprecated. I didn't test it, but do you think we could use `dispatchEvent` instead as shown here:

https://developer.mozilla.org/en-US/docs/Web/API/Event/Event#Example

Comment (senadir) [reply assets/js/atomic/components/product/button/index.js]: You're right, this is much better

File: assets/js/atomic/components/product/button/index.js [hunk 2]
```diff
@@ -106,6 +106,18 @@ const ProductButton = ( { product, className } ) => {
...
+	// that relies on the store, see
+	// https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1247
+	useEffect( () => {
+		// eslint-disable-next-line no-undef
+		const event = new Event( 'wc_fragment_refresh', {
+			bubbles: true,
+			cancelable: true,
+		} );
+		document.body.dispatchEvent( event );
+	}, [ addedToCart ] );
```
Comment (Aljullu) [inline assets/js/atomic/components/product/button/index.js]: I think replacing this line should fix the issue described above:
```suggestion
	}, [ cartQuantity ] );
```

Comment (senadir) [reply assets/js/atomic/components/product/button/index.js]: This seems to fix it

File: assets/js/atomic/components/product/button/index.js [hunk 3]
```diff
@@ -106,6 +106,18 @@ const ProductButton = ( { product, className } ) => {
 		}
 		return productCartDetails.text;
 	};
+
+	// This is a hack to trigger cart updates till we migrate to block based card
+	// that relies on the store, see
+	// https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1247
+	useEffect( () => {
+		// eslint-disable-next-line no-undef
+		const event = new Event( 'wc_fragment_refresh', {
```
Comment (nerrad) [inline assets/js/atomic/components/product/button/index.js]: Two concerns I have:

- `Event` constructor is not supported by IE 11 (but that might be handled by babel transpile)
- We've introduced a tight dependency here to the browser environment (which can be iterated on if needed separately - and documentation helps for explaining the purpose).

I would suggest though that there be some default assignments outside of the component (which would also remove the necessity for the lint rule exclusion), eg:

```js
const Event = window.Event || {};
```

Comment (senadir) [reply assets/js/atomic/components/product/button/index.js]: >Event constructor is not supported by IE 11 (but that might be handled by babel transpile)

we can test for `Event` existence and work accordingly.

>We've introduced a tight dependency here to the browser environment

I thought of the same thing, we can iterate on this in the future.

> `const Event = window.Event || {};`
Any examples of this? (defining things outisde component context)

**Comment by nerrad** [comment]
> Any examples of this? (defining things outisde component context)

By that I just mean before the `ProductButton` is defined (so in the module scope).

```js
const Event = window.Event || {};
const ProductButton = ( { product, className } ) => { /** **/ }
```

**Comment by senadir** [comment]
Before merging this we need to see how to fix the fact that `useEffect` is firing 6 times on initial load, creating 6 calls to the very expensive `wp-ajax`

image

**Comment by nerrad** [comment]
It's happening once for each product button mount.  So if there are 6 products you have 6 events firing :).  What you'll have to do is make sure it doesn't fire on mount.  This can be done either via using `useRef` or you might want to try `useLayoutEffect` here because that only runs when the component is updated (not mounted) I think.

**Comment by nerrad** [comment]
Nope `useLayoutEffect` didn't do anything for me.

**Comment by senadir** [comment]
@nerrad I applied some checks and notes that you provided, so if you can review this one last time?
