### PR TITLE
Fix Product Price styles leaking into the Mini Cart, Cart and Checkout blocks

### LINKED ISSUE #9044: Product Price global styles leak into the Mini Cart
Styles added to the Product Price block are also applied to the Mini Cart product prices, which might be confusing and cause broken layouts.

## To reproduce

1. Go to Appearance > Editor > Template Parts and edit the Mini Cart template part.
2. Now, open Styles > Blocks and search for the Product Price block.
3. Change its styles, for example, setting a margin.
4. Notice how the Mini Cart template part updates with those styles, making the layout look broken.
5. Notice also the product price shown in the Mini Cart is not a block, so there is no way to select it and remove the applied global styles.

## Expected behavior

Given that product prices shown in the Mini Cart are not blocks, global styles from the Product Price block should not be applied to them.

## Screenshots

[Enregistrament de pantalla des de 2023-04-14 12-09-09.webm](https://user-images.githubusercontent.com/3616980/232017333-5d69dd55-c48b-4605-b3e0-e2f46934b710.webm)

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #9044.

##### Product Price styles don't leak into the Mini Cart block

1. Go to Appearance > Editor > Template Parts > Mini Cart.
2. Open the Styles sidebar > Blocks > Product Price.
3. Set some margin and color to the Product Price.
4. Verify that the new styles aren't applied to the product prices shown in the Mini Cart.
5. Go to the frontend and open the Mini Cart drawer.
6. Verify again that the styles you set in step 3 don't affect the product prices shown in the Mini Cart drawer.

##### Product Price styles are still applied to the Single Product template

1. Go to Appearance > Editor > Templates > Single Product. Add the Product Price block somewhere in the template.
2. Open the Styles sidebar > Blocks > Product Price.
3. Set some margin and color to the Product Price.
4. Verify that the Product Price block has the margin and color you set.
7. Open the single product page in the frontend.
8. Verify that the Product Price block has the margin and color you set.

##### Product Price styles are still applied to the Products and All Products blocks

1. Go to Appearance > Editor > Templates > Product Catalog. Add the Products and All Products blocks somewhere in the template.
2. Open the Styles sidebar > Blocks > Product Price.
3. Set some margin and color to the Product Price.
4. Verify that the Product Price inner blocks have the margin and color you set.
7. Open the Shop page in the frontend.
8. Verify that the Product Price inner blocks have the margin and color you set.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Prevent Product Price global styles leaking into the Mini Cart, Cart and Checkout blocks.

### CODE REVIEW

File: src/BlockTypes/ProductPrice.php [hunk 1]
```diff
@@ -86,9 +86,9 @@ protected function render( $attributes, $content, $block ) {
 			$text_align_styles_and_classes = StyleAttributesUtils::get_text_align_class_and_style( $attributes );
 
 			return sprintf(
-				'<div class="wc-block-components-product-price wc-block-grid__product-price %1$s %2$s" style="%3$s">
+				'<div class="wp-block-woocommerce-product-price"><div class="wc-block-components-product-price wc-block-grid__product-price %1$s %2$s" style="%3$s">
```
Comment (imanish003) [inline src/BlockTypes/ProductPrice.php:89]: Is it necessary to add one more div? Can we not add the `wp-block-woocommerce-product-price` class to the existing div instead? 🤔

**Review by imanish003 — APPROVED** [review]
Hi @Aljullu, I have tested the changes, and it's working as expected. 🚀

I did come across one query during my review, but it's not a blocker and doesn't affect the overall functionality. Therefore pre-approving the PR. 🙌🏻

File: src/BlockTypes/ProductPrice.php (hunk 1 above)
Comment (Aljullu) [reply src/BlockTypes/ProductPrice.php:89]: I don't have a strong opinion, I just followed the structure we have in the `edit.tsx` document:

https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/atomic/blocks/product-elements/price/edit.tsx#L92-L94

I guess both options would work, but removing the wrapping `<div>` would make the React code a bit more complex as we need to pass down the props we get from `useBlockProps()` two levels down.

Do you think the extra div is problematic? If so, I'm happy to change it.

Comment (imanish003) [reply src/BlockTypes/ProductPrice.php:89]: @Aljullu Thanks for explaining the rationale behind the extra `<div>` . I understand that removing it would make the React code more complex. Since it's not a blocker and doesn't affect the overall functionality, I agree with your decision to keep the extra `<div>` 🤝
