### PR TITLE
Use 'enqueue_block_assets' action when is available

### LINKED ISSUE #9331: With Gutenberg trunk, the images aren't loaded on the Site Editor
## Describe the bug

The images aren't loaded on the Site Editor with the Gutenberg trunk. It seems that there is a new way to enqueue the assets on the Site Editor https://github.com/WordPress/gutenberg/pull/49655

## To reproduce

1. Be sure that you have the Gutenberg trunk installed.
2. Open the Site Editor, and open the Single Product Template.
3. See that the placeholder image isn't loaded.

## Expected behavior

The images should be visible. 

## Screenshots

| Image |
|--------|
|image|
|image
|

### PR DESCRIPTION
**Pull request by gigitux**
~~In the newer version of Gutenberg (and WordPress), there is a dedicated action to enqueue the assets of blocks on the Site Editor (https://github.com/WordPress/gutenberg/pull/49655). This PR uses the new action.~~

https://github.com/WordPress/gutenberg/pull/49655 changed how assets should be enqueued on the Site Editor. This PR is just a dirty patch to fix #9331, but we will revisit the entire process in the next cooldown. #9354 

### Summary
🆕🚀🐛

Hook `register_data_script` to `enqueue_block_assets` if available, or `init` otherwise, for compatibility and performance reasons. This is part of a pull request to improve asset data loading.

> _`enqueue_block_assets`_
> _A later hook for data scripts_
> _Fall leaves compatibility_

### Walkthrough
* Hook `register_data_script` to `enqueue_block_assets` if available, or `init` otherwise, to improve data loading performance and compatibility ([link](https://github.com/woocommerce/woocommerce-blocks/pull/9332/files?diff=unified&w=0#diff-03bb93b5d0012430b20f6488a8d662349b0f80d493e46efc0e7a830f5e649297L69-R70))

Fixes #9331

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Be sure that you have the Gutenberg trunk installed.
2. Open the Site Editor, and open the Single Product Template.
3. See that the placeholder image is loaded.
4. Disable the Gutenberg plugin.
5. Open the Site Editor, and open the Single Product Template.
6. See that the placeholder image is loaded.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by tjcafferkey — APPROVED** [review]
This works and LGTM!

File: src/Assets/AssetDataRegistry.php [hunk 1]
```diff
@@ -66,11 +66,25 @@ public function __construct( Api $asset_api ) {
 	 * Hook into WP asset registration for enqueueing asset data.
 	 */
 	protected function init() {
-		add_action( 'init', array( $this, 'register_data_script' ) );
+		if ( $this->is_site_editor() ) {
+			add_action( 'enqueue_block_editor_assets', array( $this, 'register_data_script' ) );
```
Comment (nerrad) [inline src/Assets/AssetDataRegistry.php:70]: This is dangerous because there may be other Woo Extensions using the AssetDataRegistry which aren't explicitly using it for blocks. Have you double-checked this?

Comment (nerrad) [reply src/Assets/AssetDataRegistry.php:70]: I guess it _should_ be okay when restricted to the site editor 🤔

Comment (nerrad) [reply src/Assets/AssetDataRegistry.php:70]: Still, I wonder if in a followup iteration we should expose a separate API on AssetDataRegistry that is _explicitly_ for blocks to register their asset data rather (and thus enqueued differently) than accounting for multiple locations here. That would help with future maintenance as well if things change.

Comment (tjcafferkey) [reply src/Assets/AssetDataRegistry.php:70]: >there may be other Woo Extensions using the AssetDataRegistry which aren't explicitly using it for blocks. Have you double-checked this?

>I guess it should be okay when restricted to the site editor

Yeah, this has only really changed within the context of the site editor. And are we aware of any plugins (of our own or third party) that pass data to the site editor in a non-blocks context? It seems like a bit of an edge case but definitely worth thinking about/a look into.

Comment (gigitux) [reply src/Assets/AssetDataRegistry.php:70]: > Still, I wonder if in a followup iteration we should expose a separate API on AssetDataRegistry that is explicitly for blocks to register their asset data rather (and thus enqueued differently) than accounting for multiple locations here

Agree on this! This is just a patch. We will revisit the entire process during the next cooldown!

Comment (nefeline) [reply src/Assets/AssetDataRegistry.php:70]: > This is dangerous because there may be other Woo Extensions using the AssetDataRegistry which aren't explicitly using it for blocks. Have you double-checked this?
> I guess it should be okay when restricted to the site editor 🤔

That's a good point: I _think_ so, but IMO it's hard to be 100% sure at this point without any further investigation. We have https://github.com/woocommerce/woocommerce-blocks/issues/9354 as a FU task for a permanent fix.

Comment (nefeline) [reply src/Assets/AssetDataRegistry.php:70]: @tjcafferkey @gigitux @nerrad do you think we should prioritize revising this before releasing the patch, just to make sure we won't end up breaking things elsewhere, or are we a-ok with keeping the patch as-is and revisiting later?

Comment (gigitux) [reply src/Assets/AssetDataRegistry.php:70]: I would release as-is, but instead of waiting for the cooldown, work on a proper fix now. In this way, we can:
- Apply the new changes if we break something.
- Work on a proper solution without the rush.

Comment (nefeline) [reply src/Assets/AssetDataRegistry.php:70]: I tend to be more conservative in such cases so my vote would be for spending some extra time investigating alternatives & possible consequences before releasing, but if most of us are comfortable with releasing as-is I agree with your proposed approach @gigitux

Comment (tjcafferkey) [reply src/Assets/AssetDataRegistry.php:70]: @gigitux @nefeline I am happy to pick this refactor up instead of waiting for cooldown.
