### PR TITLE
Fix handpicked product selections when a store has over 100 products.

### LINKED ISSUE #4505: Hand-Picked Products block limited to 11 products
## Describe the bug
For some reason the hand-picked products block only allows selecting 11 products.

Furthermore it counts up to 11 products in the block editor however overrides the last selected product without any warning or error.

## To reproduce

1. Add more than 11 products to the block

## Expected behavior
Allow me to add as many products as I want

## Screenshots
image

### WordPress (please complete the following information):
* Core version: 5.7.2
* Gutenberg version (if installed): na
* WooCommerce version: 5.5.2
* WooCommerce Blocks version: [e.g. 1.3.1]
* Site language: en
* Any other plugins installed: of course (none relevant to issue)

### Desktop (please complete the following information):
* OS: not relevant
* Browser not relevant
* Version not relevant

### Smartphone (please complete the following information):
* Device: not relevant
* OS: not relevant
* Browser not relevant
* Version not relevant

### PR DESCRIPTION
**Pull request by mikejolley**
There was a bug in `getProductsRequests` for stores with large catalogs. Our search functionality gets around page limits by including all selected products in a separate request. However, because this request had a limit or 10 products, some selected products would be left out of the list. Setting per_page to 0 (unlimited) resolves this.

When trying to make sense of the bug, I refactored the `withSearchedProducts` HOC to TypeScript.

Fixes #4505

### How to test the changes in this Pull Request:

To test this you need a catalog with > 100 products (or you can edit the code to make it require less).

1. Add a hand picked product block to a page.
2. Make 20 selections. You may need to search for products to have more results appear.
3. Save and reload the page.
4. Confirm 20 selections remain.

### Changelog

> Fix handpicked product selections when a store has over 100 products.

### CODE REVIEW

File: assets/js/editor-components/utils/index.js [hunk 1]
```diff
@@ -39,6 +39,7 @@ const getProductsRequests = ( {
 			addQueryArgs( '/wc/store/products', {
 				catalog_visibility: 'any',
 				include: selected,
+				per_page: 0,
```
Comment (ralucaStan) [inline assets/js/editor-components/utils/index.js:42]: I guess we won't need the comment above anymore:
```
// If we have a large catalog, we might not get all selected products in the first page
```

**Review by ralucaStan — APPROVED** [review]

File: assets/js/editor-components/utils/index.js (hunk 1 above)
Comment (mikejolley) [reply assets/js/editor-components/utils/index.js:42]: It's still relevant I think. With smaller catalogs the selections are guaranteed to be returned with the other results. In this use case, our first query might be missing selected things.

**Comment by mikejolley** [comment]
Thanks for the review 🥳
