### PR TITLE
Fix missing translations in inspector

### LINKED ISSUE #6244: Editor: Cart and Checkout inner blocks have missing translations in the inspector
## Describe the bug

Cart and Checkout inner blocks have missing translations in the inspector in the editor.

## To reproduce

1. Go to your website and install a different language (I used Romanian)
2. Go to the editor to the Cart block page
3. Select the Subtotal inner block
4. Notice that the Inner block is translated, but the inspector title is not
5. Try the same with the Shipping block
6. Test the Checkout block as well.

## Expected behavior

The texts for innerblocks should be translated in the inspector as well.

## Screenshots

Screenshot 2022-04-13 at 12 09 08
Notice how not all the content is translated. The Shipping calculator is translated, but the title is not.
Screenshot 2022-04-13 at 12 07 09

### PR DESCRIPTION
**Pull request by tarhi-saad**
This PR fixes the missing translations in the inspector (in the Editor mode) of the C&C Blocks & Inner Blocks!

Unlike standard blocks, the translations for the `Inner Blocks` (e.g., `title`, `description` & `keywords`) doesn't work when the [blocks are registered on the client-side only](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-registration.md). We are still unsure what is causing this unexpected behavior. Even though Gutenberg is [handling i18n for client-side only registered blocks](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-metadata.md#javascript), we didn't find a way to make it work in our case.

The expected behavior was for Gutenberg to wrap all localized properties in `_x` (from `@wordpress/i18n package`) function calls, similar to how it works in PHP. And then for [GlotPress](https://glotpress.blog/) to generate `.json` files in the `wp-content/languages/` folder containing the corresponding translations.

On the other hand, our missing translations can be found inside the `.po` files in the `wp-content/languages/` folder. These files are generated by [GlotPress](https://glotpress.blog/) when translating server-side (PHP). After this realization, the solution became clear: register our `Inner Blocks` server-side instead! This was also an early suggestion made by @senadir! Besides, the [recommended method to register new block types](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-metadata.md) is to use the `block.json` metadata file (i.e., register the block server-side). So, it was time for the implementation 💪:

And indeed, after adopting this approach for the `Inner Blocks`, the missing translations bug was fixed. The [translation was handled by WordPress](https://github.com/WordPress/WordPress/blob/35ab93306779cf1b04eba1b614f382365bea0b43/wp-includes/blocks.php#L308) on the back-end. [WordPress string discovery system can automatically translate](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-metadata.md#internationalization) fields marked in the `block.json` file as translatable.

Some changes that needed to be done to properly register our `Inner Blocks` server-side:

- [Generate block.json files for Inner Blocks](https://github.com/woocommerce/woocommerce-blocks/blob/b220e4937665119c139a01f43f0149111c95444b/bin/webpack-configs.js#L264-L277)
- [Register only the client-side settings on the client](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-metadata.md#javascript-client-side).
- Prevent WordPress from [injecting script tags](https://github.com/WordPress/WordPress/blob/master/wp-includes/blocks.php#L314-L316) for each Inner Block registered server-side by omitting the [editor_script](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-metadata.md#editor-script) field from our [register_block_type](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypes/AbstractBlock.php#L201) function and creating the new [AbstractInnerBlock](https://github.com/woocommerce/woocommerce-blocks/blob/b220e4937665119c139a01f43f0149111c95444b/src/BlockTypes/AbstractInnerBlock.php) for this purpose.

**Things that need improvement:**

- [x] Currently, the `/build` folder is [polluted with so many top-level folders](https://github.com/woocommerce/woocommerce-blocks/pull/6737#discussion_r933517699). To fix this, we can choose to generate the `Inner Blocks` `blocks.json` files inside a parent folder (e.g., `/checkout-blocks` and `/cart-blocks`).

 
### TODO

- [x] Fix the translation for the Checkout's Inner Blocks

Fixes #6244

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) .
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md)
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Change your site language (I tested using French & NL)
2. Go to the C&C Blocks (Editor mode)
3. Select each inner block and make sure the `title` & `description` are translated in the inspector. See image below:

image

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix missing translations in the inspector (editor mode)

### CODE REVIEW

File: assets/js/blocks/cart/inner-blocks/cart-order-summary-taxes/index.tsx [hunk 1]
```diff
@@ -21,7 +24,20 @@ registerFeaturePluginBlockType( metadata, {
...
+	title: __( 'Taxes', 'woo-gutenberg-products-block' ),
+	description: __(
+		'Shows the cart taxes row.',
+		'woo-gutenberg-products-block'
+	),
+	// description: _x(
+	// 	'Shows the cart taxes row.',
+	// 	'block description',
+	// 	'woo-gutenberg-products-block'
+	// ),
```
Comment (senadir) [inline assets/js/blocks/cart/inner-blocks/cart-order-summary-taxes/index.tsx]: All of those information should be present in the metadata file, why are you rewriting them?

File: src/BlockTypesController.php [hunk 2]
```diff
@@ -201,6 +201,7 @@ protected function get_block_types() {
 		if ( Package::feature()->is_feature_plugin_build() ) {
 			$block_types[] = 'Checkout';
 			$block_types[] = 'Cart';
+			$block_types[] = 'CartOrderSummaryTaxesBlock';
```
Comment (senadir) [inline src/BlockTypesController.php]: We might want to have this logic inside Cart.php class?

**Review by senadir — COMMENTED** [review]
I left a couple of questions while I dig more into this.

File: assets/js/blocks/cart/inner-blocks/cart-order-summary-taxes/index.tsx (hunk 1 above)
Comment (tarhi-saad) [reply assets/js/blocks/cart/inner-blocks/cart-order-summary-taxes/index.tsx]: I'm overwriting the `title` & `description` to test wrapping them with the `@wordpress/i18n` functions and see if it would make any change. This worked for the `title` (it was translated correctly), but it didn't work for the `description` since the corresponding translation script/file wasn't loaded.

Comment (tarhi-saad) [reply assets/js/blocks/cart/inner-blocks/cart-order-summary-taxes/index.tsx]: Seeing other blocks using the `block.json` file (e.g. `products-by-attribute`), I think we shouldn't need the `@wordpress/i18n` functions for our translation to work! 🙌

File: bin/webpack-entries.js [hunk 3]
```diff
@@ -45,6 +45,9 @@ const blocks = {
 	'stock-filter': {},
 	'active-filters': {},
 	cart: {},
+	'cart-order-summary-taxes-block': {
+		customDir: 'cart/inner-blocks/cart-order-summary-taxes',
+	},
```
Comment (senadir) [inline bin/webpack-entries.js]: I question the need for this one and maybe we can just rely on cart.js file :/

Comment (tarhi-saad) [reply bin/webpack-entries.js]: When I load the page (the cart edit mode), I get this error:

image

And after adding the code above, it stopped showing this console error. I think now that the `taxes'` inner block is registered server side, it's expecting to have its own `JS` file. But I'll look into that and see If we can choose not to include a JS file in this case.

Comment (tarhi-saad) [reply bin/webpack-entries.js]: ✅ Fixed here: [c5670f6](https://github.com/woocommerce/woocommerce-blocks/pull/6737/commits/c5670f6be17c2de2552028dc959bbcb8f4e57055)

File: src/BlockTypesController.php (hunk 2 above)
Comment (tarhi-saad) [reply src/BlockTypesController.php]: ✅ Fixed in: [83a8b43](https://github.com/woocommerce/woocommerce-blocks/pull/6737/commits/83a8b433fe749017f330920db89ab70501426037)

File: bin/webpack-configs.js [hunk 4]
```diff
@@ -262,14 +263,19 @@ const getMainConfig = ( options = {} ) => {
...
+							const JSONFile = fs.readFileSync(
+								path.resolve( __dirname, absoluteFilename )
+							);
+							const metadata = JSON.parse( JSONFile.toString() );
+							const blockName = metadata.name
 								.split( '/' )
-								.at( -2 );
+								.at( 1 );
 							return `./${ blockName }/block.json`;
 						},
```
Comment (senadir) [inline bin/webpack-configs.js:278]: I assume we have little control into where this goes? currently, it pollutes our `build` folder with so many top level folders.
image


We actually have two folders there `checkout-blocks` and `cart-blocks`. Do you think we can output those block.json files there, and how much effort would it require? For block.json, we can change that in the future so this is not a blocker.

**Review by senadir — APPROVED** [review]
I tested this and it's working fine! Thank you Saad for spending time with this.

File: assets/js/blocks/cart/inner-blocks/cart-accepted-payment-methods-block/block.json [hunk 5]
```diff
@@ -13,5 +13,6 @@
 	},
 	"parent": [ "woocommerce/cart-totals-block" ],
 	"textdomain": "woo-gutenberg-products-block",
+	"$schema": "https://schemas.wp.org/trunk/block.json",
```
Comment (senadir) [inline assets/js/blocks/cart/inner-blocks/cart-accepted-payment-methods-block/block.json:16]: I forget to ask why was this needed?

File: src/BlockTypes/Checkout.php [hunk 6]
```diff
@@ -411,4 +413,39 @@ protected function register_block_type_assets() {
...
+	 * Get list of Checkout block & its inner-block types.
+	 *
+	 * @return array;
+	 */
+	public static function get_checkout_block_types() {
+		$block_types = [];
+
+		if ( Package::feature()->is_feature_plugin_build() ) {
+			$block_types[] = 'Checkout';
+			$block_types[] = 'Checkout';
```
Comment (senadir) [inline src/BlockTypes/Checkout.php]: Checkout is twice here
```suggestion
			$block_types[] = 'Checkout';
```

**Review by senadir — APPROVED** [review]
This is looking good, I left a single comment but it's ready to merge.

File: src/BlockTypes/Checkout.php (hunk 6 above)
Comment (senadir) [reply src/BlockTypes/Checkout.php]: This is throwing an error for me.

File: assets/js/blocks/cart/inner-blocks/cart-accepted-payment-methods-block/block.json (hunk 5 above)
Comment (tarhi-saad) [reply assets/js/blocks/cart/inner-blocks/cart-accepted-payment-methods-block/block.json:16]: Loading the [schema definition ](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-metadata.md#benefits-using-the-metadata-file) file allows supported editors to provide help like tooltips, autocomplete, and schema validation. For example, you can hover over a field in `block.json` to see a tooltip description for it. So, it's always good to add this line for development purposes.

File: src/BlockTypes/Checkout.php (hunk 6 above)
Comment (tarhi-saad) [reply src/BlockTypes/Checkout.php]: Thank you, @senadir! 💯

**Review by senadir — CHANGES_REQUESTED** [review]
I was actually too quick to approve this without testing, I'm still seeing issues on frontend with scripts like `/proceed-to-checkout-block-frontend.js` missing.

**Review by senadir — APPROVED** [review]
This is now working fine without issues.
