### PR TITLE
Product Price: Fix alignment setting on the frontend

### LINKED ISSUE #7778: Product Price: Alignment setting not working on the frontend
The Product Price product element currently is not working correctly on the frontend.

**Editor**
Edit_Page_“All_Products”_‹_ratings_—_WordPress

**Frontend**
All_Products_–_ratings

This is necessary for building Product Query patterns like the following:
🔎_Product_Query_Block_–_Figma

### PR DESCRIPTION
**Pull request by danieldudzic**
This PR fixes the alignment setting on the frontend for the **Product Price** product element.

Fixes #7778 

#### Other Checks

- [x] This PR removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

Alignment set to `center`

| Before | After |
| ------ | ----- |
|All_Products_–_ratings-2|All_Products_–_ratings|

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Add the **Product Query** block to a page.
2. Add the **Product Price** block.
3. Make sure that you can set the alignment to left, center and right.
4. Make sure all options work both in the editor and on the page.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Product Price: Fix the alignment setting.

### CODE REVIEW

File: src/Utils/StyleAttributesUtils.php [hunk 1]
```diff
@@ -327,6 +327,44 @@ public static function get_align_class_and_style( $attributes ) {
...
+	/**
+	 * Get class and style for text align from attributes.
+	 *
+	 * @param array $attributes Block attributes.
+	 *
+	 * @return (array | null)
+	 */
+	public static function get_text_align_class_and_style( $attributes ) {
+
+		$text_align_attribute = isset( $attributes['textAlign'] ) ? $attributes['textAlign'] : null;
```
Comment (nefeline) [inline src/Utils/StyleAttributesUtils.php]: What do you think about using null coalescing here?

```
$text_align_attribute = $attributes['textAlign'] ?? null;
```

File: src/Utils/StyleAttributesUtils.php [hunk 2]
```diff
@@ -327,6 +327,44 @@ public static function get_align_class_and_style( $attributes ) {
...
+
+		if ( ! $text_align_attribute ) {
+			return null;
+		};
```
Comment (nefeline) [inline src/Utils/StyleAttributesUtils.php]: the `;` can be removed

File: src/BlockTypes/ProductPrice.php [hunk 3]
```diff
@@ -80,10 +82,13 @@ protected function render( $attributes, $content, $block ) {
 		$product = wc_get_product( $post_id );
 
 		if ( $product ) {
+			$classes_and_styles = StyleAttributesUtils::get_text_align_class_and_style( $attributes );
+
 			return sprintf(
-				'<div class="wc-block-components-product-price wc-block-grid__product-price">
+				'<div class="wc-block-components-product-price wc-block-grid__product-price %s">
```
Comment (nefeline) [inline src/BlockTypes/ProductPrice.php]: Nit: how about numbering the two placeholders here to quickly tell which string will be placed where? e.g. Instead of `%s`, adopting `%1$s` and `%2$s`.

**Review by nefeline — COMMENTED** [review]
Works like a charm ✨!

✅  Confirmed the price alignments are working as expected both in the editor and on the published post.
✅  Confirmed the alignments can be set to left, center and right.

Left a few suggestions in the code.

File: src/Utils/StyleAttributesUtils.php (hunk 1 above)
Comment (danieldudzic) [reply src/Utils/StyleAttributesUtils.php]: This is a good suggestion. I have double-checked and it seems that it's safe to use since WordPress now requires PHP 7.0.

That said, I have just followed the function above, and tried to keep the code consistent. I don't have a strong preference, to be honest :)

https://github.com/woocommerce/woocommerce-blocks/blob/e79766ab116827f4744d4b940a09e1e9892ebacf/src/Utils/StyleAttributesUtils.php#L286

File: src/Utils/StyleAttributesUtils.php (hunk 2 above)
Comment (danieldudzic) [reply src/Utils/StyleAttributesUtils.php]: Good catch!

File: src/Utils/StyleAttributesUtils.php (hunk 1 above)
Comment (nefeline) [reply src/Utils/StyleAttributesUtils.php]: > I have double-checked and it seems that it's safe to use since WordPress now requires PHP 7.0.

Yes it is ;)

**Review by nefeline — APPROVED** [review]
Thanks for addressing the feedback: I left a follow-up question, but LGTM :shipit: !

File: assets/js/atomic/blocks/product-elements/price/attributes.js [hunk 4]
```diff
@@ -12,14 +11,9 @@ let blockAttributes = {
 		type: 'boolean',
 		default: false,
 	},
+	textAlign: {
+		type: 'string',
+	},
 };
 
-if ( isFeaturePluginBuild() ) {
```
Comment (nefeline) [inline assets/js/atomic/blocks/product-elements/price/attributes.js:17]: Out of curiosity: why are we removing the feature flag here? Was this part of a decision documented elsewhere?

Comment (danieldudzic) [reply assets/js/atomic/blocks/product-elements/price/attributes.js:17]: No idea why it was there in the first place. I have asked @Aljullu, but he didn't know either. It doesn't really make sense for it to be there as `Text Alignment` is not an experimental feature. We have decided it's safe to just remove it.

Also that setting was broken on the frontend anyway 🤷‍♂️

Comment (nefeline) [reply assets/js/atomic/blocks/product-elements/price/attributes.js:17]: That makes sense: thanks for clarifying!
