### PR TITLE
Fix: Convert Filter Products by Stock to TypeScript

### LINKED ISSUE #6497: Convert Filter Products by Stock to TypeScript

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #6497 
This PR converts the codebase of the Filter Products by Stock status block to TypeScript. 

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) .
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md)
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

N/A

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

Ensure no regression for Filter Products by Price block after the conversion.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

N/A

### Changelog

N/A

### CODE REVIEW

File: assets/js/blocks/stock-filter/block.tsx [hunk 1]
```diff
@@ -50,14 +54,11 @@ const StockStatusFilterBlock = ( {
...
 
-	const [ hideOutOfStockItems ] = useState(
-		getSetting( 'hideOutOfStockItems', false )
-	);
-	const [ { outofstock, ...otherStockStatusOptions } ] = useState(
-		getSetting( 'stockStatusOptions', {} )
-	);
+	const [ { outofstock, ...otherStockStatusOptions } ] = useState<
+		Record< string, string >
+	>( getSetting( 'stockStatusOptions', {} ) );
```
Comment (Aljullu) [inline assets/js/blocks/stock-filter/block.tsx]: Not introduced in this PR, but I'm a bit confused by why we store this in the state. Couldn't this simply be?
```suggestion
	const { outofstock, ...otherStockStatusOptions } = getSetting(
		'stockStatusOptions',
		{}
	);
```

File: assets/js/blocks/stock-filter/block.tsx [hunk 2]
```diff
@@ -50,14 +54,11 @@ const StockStatusFilterBlock = ( {
...
 	const [ STOCK_STATUS_OPTIONS ] = useState(
```
Comment (Aljullu) [inline assets/js/blocks/stock-filter/block.tsx]: Same here, why is `STOCK_STATUS_OPTIONS` stored in the state if it's never changed? :confused:

**Review by Aljullu — COMMENTED** [review]
I left a couple of comments which are not directly related to this PR, but wanted to bring up, so we can either fix them or create a follow-up issue.

While this PR is testing well and code changes look good, I would like to re-review once #6505 has been merged into `trunk` because I skipped several files in this first review. :sweat_smile:

File: assets/js/blocks/stock-filter/block.tsx (hunk 1 above)
Comment (dinhtungdu) [reply assets/js/blocks/stock-filter/block.tsx]: Agreed!

File: assets/js/blocks/stock-filter/block.tsx (hunk 2 above)
Comment (dinhtungdu) [reply assets/js/blocks/stock-filter/block.tsx]: Went through the history and found the reason for this in https://github.com/woocommerce/woocommerce-blocks/pull/4682

> After discussing with @tjcafferkey we decided that these usages of useMemo were "over-optimisations". The length of STOCK_STATUS_OPTIONS will usually be 3, so iterating over it is cheap, and not worth memoizing given the complexity this adds to the component.
> Because the value of initialOptions is used as a dependency to the useEffect further down this file, setting these values as internal component state seemed the best way forward to stop this effect running every render.

Comment (Aljullu) [reply assets/js/blocks/stock-filter/block.tsx]: Oh, thanks for digging on it and finding the source. For cases like this, isn't the recommended solution to use [`useRef`](https://reactjs.org/docs/hooks-reference.html#useref)?

Comment (dinhtungdu) [reply assets/js/blocks/stock-filter/block.tsx]: @Aljullu Brilliant! Look like `useRef` is perfect for this case. I updated the code per your suggestion 🚀

**Review by Aljullu — APPROVED** [review]
LGTM! Nice work converting this block to TypeScript! :rocket:

**Comment by dinhtungdu** [comment]
@Aljullu In [d5163cf](https://github.com/woocommerce/woocommerce-blocks/pull/6533/commits/d5163cf152c374c999b524dbed6d5f4631fff9c6), I updated the Attributes type to make `className` and `isPreview` optional. I did that because we don't need them on the front end:
- `isPreview` is only used in the block inserter.
- We include the `className` attribute in the save component, so custom classes are rendered server-side.

Does this make sense to you?

**Review by Aljullu — APPROVED** [review]
Oh right, I agree. LGTM
