### PR TITLE
Cart and Checkout Page Migration: Inherit Page template and fix rendering

### LINKED ISSUE #10181: Cart and Checkout templates cause previous edits made by the user to be lost
## Describe the bug

Cart and Checkout templates don't inherit the changes made in the Page template. That's problematic as Cart and Checkout were using the Page template before 10.6.0, so updating WC might cause layout breakages.

## To reproduce

1. Create a fresh site and install WooCommerce (I used 7.8.2) but don't install WC Blocks yet.
1. Go to Appearance > Editor > Template Parts > Add New and create a new Header (we can name it My Header).
1. Add some content to it that it's easily identificable: ie "This is My Header".
1. Now go to Templates > Page, remove the default header and add the new one you created: My Header.
1. Feel free to make some more edits, like centering the Post Title.
1. Save the edits.
1. Now, in the frontend, visit the Cart and Checkout pages. You will notice they show the modifications you did in steps 4 and 5.
1. Now, install WC Blocks 10.6.0.
1. Reload the tabs from step 7 and notice all customizations you did are lost in the Cart and Checkout pages: they show the default header and the Post Title block is not centered.

## Expected behavior

Updating WC Blocks to 10.6.0 shouldn't cause any visible change on the frontend of the Cart and Checkout pages on existing stores.

## Screenshots

Cart page modified by the user | Same page after installing WC Blocks 10.6.0
--- | ---
imatge | imatge

## Additional context

I think that Cart and Checkout templates should default to whatever the existing Page template is at the time of updating. Ie, if the user made some edits to the Page template, Cart and Checkout templates should have those edits as well. Otherwise this seems like a breaking change that might affect existing stores.

Note: I only tested Cart and Checkout templates, but I guess the Order Confirmation template is affected as well.

Note 2: In the testing steps I mentioned creating a custom Header and modifying the Post Title alignment, but the issue affects all page customizations: ie custom Footers, page width, colors, etc.

cc @wavvves @mikejolley as I think you two worked on that? But feel free to ping somebody else.

### LINKED ISSUE #10357: [WC 8.0 Beta]: UI looks disorganised in the cart and checkout pages
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In WooCommerce 8.0 beta the style of the items in the cart page looks worse than in previous versions, just like if the layout properties were not consistent in the UI. Examples:

- In WooCommerce 7.9 (correct):
image

- In WooCommerce 8.0 beta (wrong)
image

As you can see, the `Proceed to checkout` button has significant padding on the upper side and the elements seem closer together. In any case, this change wasn't expected so we can consider it a bug that should be fixed before releasing the official WooCommerce 8.0 version.

### Expected behavior

The UI in the cart and checkout pages should look like in WooCommerce 7.9:
image

**NOTE:** After understanding the root of the issue, it would be good to investigate if it affects other pages apart than cart and checkout.

### Actual behavior

The UI in the cart and checkout pages are different and look worse than in previous versions:
image

### Steps to reproduce

1. Make sure you are using WooCommerce 8.0 beta.
2. As an admin, add some products to the store.
3. As a shopper, add any of these products to the cart.
4. Open the cart and analyze the UI.
5. Proceed to the checkout page and analyze the UI.

### WordPress Environment

```
WordPress address (URL): https://testsite.com
Site address (URL): https://testsite.com
WC Version: 8.0.0
REST API Version: ✔ 8.0.0
WC Blocks Version: ✔ 10.6.1
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Unix) OpenSSL/1.0.2g
PHP Version: 8.0.29
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.0
WC Database Prefix: wp_
Total Database Size: 5.31MB
Database Data Size: 3.61MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 11
page: 7
post: 2
product: 9
shop_order: 4
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Companion Plugin: by Osk – 1.29
Jetpack: by Automattic – 12.3
WooCommerce: by Automattic – 8.1.0-dev

### Inactive Plugins (2) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.1
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: woocommerce/woocommerce#7 - /shop/
Cart: woocommerce/woocommerce#8 - /cart/
Checkout: woocommerce/woocommerce#9 - /checkout/
My account: woocommerce/woocommerce#10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-26 06:18:36 +00:00
Options: ✔
Notes: 64
Onboarding: skipped

### Action Scheduler ###

Complete: 16
Oldest: 2023-07-25 06:20:37 +0000
Newest: 2023-07-25 08:14:42 +0000

Failed: 1
Oldest: 2023-07-25 06:21:42 +0000
Newest: 2023-07-25 06:21:42 +0000

Pending: 1
Oldest: 2023-07-26 06:20:37 +0000
Newest: 2023-07-26 06:20:37 +0000


### Status report information ###

Generated at: 2023-07-25 08:59:26 +00:00
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by mikejolley**
This PR resolves the styling issues reporting in #10357, and the template migration issue reported in #10181. Both are related to how content is migrated, and how content renders after migration.

@wavvves @ralucaStan 

## Issue causes

- #10357 Shortcode blocks work differently in templates than they do in pages. The rendered shortcode is ran though `wpautop` which introduces unwanted `<br>` and `<p>` tags around and within the rendered shortcode content. This is a know WP 6.2 issue (see trac links below).
- #10181 When the page content was migrated from a page to a new template, the new template had custom headers, footers, and content wrappers. This ignored any changes made by the merchant, or theme, to the original Page template.

Refs:

- https://core.trac.wordpress.org/ticket/58366 Trac issue for the shortcode `wpautop` issue, with some workarounds. The fix I employed is similar but more specific so as not to affect other shortcodes.
- https://core.trac.wordpress.org/ticket/58333 Original trac issue about shortcodes being broken after a security fix. This had media coverage, and was supposed to be fixed in 6.2.2, however some issues remain.
- https://wordpress.org/support/topic/wordpress-v6-2-1-breaks-the-shortcode-block-in-templates/page/5/
- https://wptavern.com/wordpress-6-2-1-update-breaks-shortcode-support-in-block-templates

Fixes #10357
Fixes #10181

#### User Facing Testing

To setup your environment for testing:

1. Switch to a non-block theme, such as Twenty Nineteen
2. Edit the Cart Page. Ensure there is some content inside, as well as a **shortcode block** containing `[woocommerce_cart]`
3. Delete WP options which may have been added already due to a past migration called `has_migrated_cart` and `has_migrated_checkout`. If you're using Local WP, you can use the Adminer tool it provides to access your DB.

Testing steps:

1. Switch from your non-block theme to Twenty Twenty Three theme
2. Visit the cart page on the frontend
3. Ensure the layout of your cart page matches other pages, and that the styles look correct, for example, the "proceed to checkout" button should have no extra padding caused by an erroneous `<br>` tag.
4. Repeat for the Checkout page.
5. Edit the cart page. You'll be redirected to the template editor.
6. Replace the shortcode block with a real Cart Block and save.
7. Go back to the frontend cart page and see the block working.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

Not needed as this feature has not landed yet.

### CODE REVIEW

**Comment by wavvves** [comment]
Nice find @mikejolley, I tested it and I works ok, I'm approving this if you make it ready 👍🏼 

There is another styling issue regarding the content's container width that happens on migration, and makes the cart/checkout narrower on templates than on pages:

Page:
image

Template:
image

For TT3 for example, the width is a calculation, but the template defaults at 650px. This can be edited and fixed by the merchant here:
image

Do you think this should be tackled along this fix, or should it be tackled along the [other migration issue](https://github.com/woocommerce/woocommerce-blocks/issues/10181) later? Both can be fixed manually by the merchant so urgency is lower than this one.

**Comment by alexflorisca** [comment]
I tried to reproduce this but I couldn't, even after following your steps in https://github.com/woocommerce/woocommerce-blocks/issues/10357#issuecomment-1651967849. Since Paulo has verified it, I'll assume I'm missing something but I won't spend more time on trying to figure it out.

File: src/BlockTemplatesController.php [hunk 1]
```diff
@@ -101,6 +101,34 @@ function( $settings, $metadata ) {
...
+				'block_type_metadata_settings',
+				function( $settings, $metadata ) {
+					if (
+						isset( $metadata['name'], $settings['render_callback'] ) &&
+						'core/shortcode' === $metadata['name']
+					) {
+						$settings['original_render_callback'] = $settings['render_callback'];
+						$settings['render_callback']          = function( $attributes, $content ) use ( $settings ) {
+							// The shortcode has already been rendered, so look for the cart/checkout HTML.
+							if ( strstr( $content, 'woocommerce-cart-form' ) || strstr( $content, 'woocommerce-checkout-form' ) ) {
```
Comment (mikejolley) [inline src/BlockTemplatesController.php:117]: It's checking for the classnames used by the cart/checkout forms so as only to target those shortcodes.

File: src/BlockTemplatesController.php [hunk 2]
```diff
@@ -101,6 +101,34 @@ function( $settings, $metadata ) {
...
+								// Return early before wpautop runs again.
+								return $content;
+							}
+
+							$render_callback = $settings['original_render_callback'];
```
Comment (mikejolley) [inline src/BlockTemplatesController.php:122]: Falls back to original renderer for other shortcodes.

File: src/BlockTemplatesController.php [hunk 3]
```diff
@@ -762,20 +813,27 @@ protected function migrate_page( $page_id, $page ) {
 			return;
 		}
 
+		// Use the page template if it exists, which we'll use over our default template if found.
+		$existing_page_template = BlockTemplateUtils::get_block_template( get_stylesheet() . '//page', 'wp_template' );
+
+		if ( $existing_page_template && ! empty( $existing_page_template->content ) ) {
+			// Massage the original content into something we can use. Replace post content with a group block.
+			$pattern          = '/(<!--\s*)wp:post-content(.*?)(\/-->)/';
```
Comment (mikejolley) [inline src/BlockTemplatesController.php:821]: Replaces the original `wp:post-content` block with the actual page content, wrapped in a group. Layout props are inherited.

**Review by wavvves — APPROVED** [review]

**Review by ralucaStan — APPROVED** [review]
Checkout and Cart shortcodes are migrated as expected.

I noticed some issues with other shortcodes tho, but we should not be the ones fixing those. The issue should be fixed upstream. I'm just sharing my findings in this comments.

Approving the PR.

Great work @mikejolley . Awesome that you also fixed the template parts bug

Products sale shortcode 
Screenshot 2023-07-27 at 15 05 02

products sale shortcode migrated
Screenshot 2023-07-27 at 15 04 54
