### PR TITLE
Reference Mini Cart drawer preview dynamically

### LINKED ISSUE #9910: Fix Mini Cart drawer preview image
## Describe the bug

In #9420, we introduced the Mini Cart drawer preview. In #9756, we added RTL support for the preview. While testing the 10.5.0 release, I noticed that the preview only works locally when the plugin slug is `woocommerce-blocks`. When using the plugin online, the plugin uses the old slug `woocommerce-gutenberg-products-block`. This leads to the fact that the preview is no longer visible.

This issue aims to reference the preview independent of the plugin slug.

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #9910

In https://github.com/woocommerce/woocommerce-blocks/pull/9420, we introduced the Mini Cart drawer preview. In https://github.com/woocommerce/woocommerce-blocks/pull/9756, we added RTL support for the preview. While testing the 10.5.0 release, I noticed that the preview only works locally when the plugin slug is `woocommerce-blocks`. When using the plugin online, the plugin uses the old slug `woocommerce-gutenberg-products-block`. This leads to the fact that the preview is no longer visible.

In this PR, I replaced the hardcoded preview address with a dynamic one. This ensures that the preview can be loaded independent of the plugin slug.

### Screenshots

<table>
<tr>
<td valign="top">Before:
<br><br>

Screenshot 2023-06-20 at 10 29 37
</td>
<td valign="top">After:
<br><br>

Screenshot 2023-06-20 at 10 30 21
</td>
</tr>
</table>

#### User Facing Testing

1. Create an online site, e.g. using Jurassic Ninja.
2. [Download the testing ZIP file](https://wcblocks.wpcomstaging.com/wp-content/uploads/woocommerce-gutenberg-products-block-9912.zip) of this PR and install it on the test site.
3. Create a test page and add the Mini Cart block to it.
4. Select the Mini Cart block and verify that the Mini Cart drawer preview is visible in the sidebar.
5. Inspect the URL of the Mini Cart drawer preview  and verify that the plugin slug does not contain `woocommerce-blocks`.

* [x] Do not include in the Testing Notes

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by gigitux — APPROVED** [review]
LGTM! 🚢

File: assets/js/blocks/mini-cart/edit.tsx [hunk 1]
```diff
@@ -237,8 +238,8 @@ const Edit = ( {
 								className="wc-block-editor-mini-cart__drawer-image"
 								src={
 									isRTL()
-										? '/wp-content/plugins/woocommerce-blocks/images/blocks/mini-cart/cart-drawer-rtl.svg'
-										: '/wp-content/plugins/woocommerce-blocks/images/blocks/mini-cart/cart-drawer.svg'
+										? `${ WC_BLOCKS_IMAGE_URL }/blocks/mini-cart/cart-drawer-rtl.svg`
+										: `${ WC_BLOCKS_IMAGE_URL }/blocks/mini-cart/cart-drawer.svg`
```
Comment (Aljullu) [inline assets/js/blocks/mini-cart/edit.tsx]: We should be able to remove the initial `/`, as [it's already included](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/settings/blocks/constants.ts#L33) in `WC_BLOCKS_IMAGE_URL`.

```suggestion
										? `${ WC_BLOCKS_IMAGE_URL }blocks/mini-cart/cart-drawer-rtl.svg`
										: `${ WC_BLOCKS_IMAGE_URL }blocks/mini-cart/cart-drawer.svg`
```

**Review by Aljullu — APPROVED** [review]
Thanks for catching this issue and fixing it, @nielslange. I left one comment about removing an unnecessary slash, but besides that, LGTM. :shipit:

**Comment by nielslange** [comment]
Thanks for your reviews, @gigitux and @Aljullu! 🙌
