### PR TITLE
Display decimals if intended by the merchant

### LINKED ISSUE #5019: `formatPrice` strips decimals
## To reproduce

1. Go to WooCommerce > Settings.
2. Set the number of decimals separator to `2`.
4. Save changes.
5. Add a block using `formatPrice` such as Mini Cart block to the page.
6. Remove all products from the cart if any.
7. See the error

## Expected behavior
The formatted price should always contain decimals as set in the WooCommerce settings.

## Screenshots

**Storefront mini cart with formatted by `wc_price` (above) vs Mini Cart block using `formatPrice` (below):**

image

### WordPress (please complete the following information):
* Core version: 5.8.1
* Gutenberg version (if installed): [2d6a363](https://github.com/WordPress/gutenberg/commit/2d6a363d55adeb50f382acd1a44af5ea85603b56J)
* WooCommerce version: 5.7.1 
* WooCommerce Blocks version: 6.2.0-dev
* Site language: English
* Any other plugins installed: WooCommerce Stripe Gateway 5.5.0

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #5019 

#### Automated Tests
* [x] Changes in this PR are covered by Automated Tests.
  * [x] Unit tests
  * [ ] E2E tests
  
Run the following command in the terminal:
```
npm run test -i packages/prices/utils/test/price.js
```
  
#### Test $0 price

1. Create a test page, add the mini cart block and save it.
2. Open the mini cart page in the frontend.
3. See that the price shows $0.00.
4. Hover over the price and verify that it remains $0.00.

#### Test $50 price

1. Add product(s) to the cart with a value of $50.
2. Open the mini cart page in the frontend.
3. See that the price shows $50.00.
4. Hover over the price and verify that it remains $50.00.

### User Facing Testing

These are steps for user testing (where "user" is someone interacting with this change that is not editing any code).
* [x] Same as above
* [ ] See steps below

### Changelog

> Ensure that expected numbers of decimals are visible, if wanted my the merchant, even if the price is $0 or has no decimals, such as $50.

### CODE REVIEW

File: packages/prices/utils/test/price.js [hunk 1]
```diff
@@ -3,48 +3,45 @@
  */
 import { formatPrice, getCurrency } from '../price';
 
-describe( 'formatPrice', () => {
+describe( 'The function formatPrice()', () => {
```
Comment (mikejolley) [inline packages/prices/utils/test/price.js:6]: 👍🏻

File: packages/prices/utils/price.ts [hunk 2]
```diff
@@ -177,7 +193,9 @@ export const formatPrice = (
 		beforeDecimal,
 		thousandSeparator
 	) }${
-		afterDecimal ? `${ decimalSeparator }${ afterDecimal }` : ''
+		afterDecimal || minorUnit > 0
```
Comment (mikejolley) [inline packages/prices/utils/price.ts]: Since we have a value for `afterDecimal`, and we are passing `minorUnit`, how about we remove the conditional here and just format it in the other util you wrote? We don't need to check twice.

File: packages/prices/utils/price.ts [hunk 3]
```diff
@@ -137,6 +137,22 @@ const splitDecimal = (
 	};
 };
 
+const applyDecimal = (
+	afterDecimal: string,
+	decimalSeparator: string,
+	minorUnit: number
+): string => {
+	if ( afterDecimal ) {
```
Comment (mikejolley) [inline packages/prices/utils/price.ts:145]: Do we need to pad decimals here regardless?

Create a test case or 2dp currency, with a given value of `10.2`. It should result in `10.20`

File: packages/prices/utils/price.ts [hunk 4]
```diff
@@ -137,6 +137,22 @@ const splitDecimal = (
...
+		return `${ decimalSeparator }${ afterDecimal }`;
+	}
+
+	if ( minorUnit > 0 ) {
+		return `${ decimalSeparator }${ '0'.repeat( minorUnit ) }`;
```
Comment (mikejolley) [inline packages/prices/utils/price.ts:153]: Concerning my above note, we could use `minorUnit` minus `afterDecimal` strlen.

**Review by mikejolley — CHANGES_REQUESTED** [review]

File: packages/prices/utils/price.ts (hunk 2 above)
Comment (nielslange) [reply packages/prices/utils/price.ts]: Great suggestion! I've updated the code accordingly.

File: packages/prices/utils/test/price.js (hunk 1 above)
Comment (nielslange) [reply packages/prices/utils/test/price.js:6]: 😊

File: packages/prices/utils/price.ts (hunk 3 above)
Comment (nielslange) [reply packages/prices/utils/price.ts:145]: After adding the additional test case, I realized that padding the decimals was needed. I add this accordingly.

File: packages/prices/utils/price.ts (hunk 4 above)
Comment (nielslange) [reply packages/prices/utils/price.ts:153]: I'm not sure if that's applicable here, as this part can only be reached if `afterDecimal` is empty. Therefore, `afterDecimal.strlen` should always result in `0` in this part. That's why I'm repeating the zeros based on the `Number of decimals` selected by the merchant. 

Was I missing something in this implementation?

Comment (mikejolley) [reply packages/prices/utils/price.ts:153]: Ok should be good. The minor units we're converting from mitigate this.

**Review by mikejolley — APPROVED** [review]

**Comment by nielslange** [comment]
Thanks for your review, @mikejolley! 🙌
