### PR TITLE
Remove order note

### LINKED ISSUE #2308: Checkout: Order notes component not usable
**Describe the bug**
The order notes component shows on the checkout page, it is unusable currently and you cannot remove it via the block settings:

Screenshot 2020-04-27 at 12 46 04

It should be removed if we are not going to enable it for the initial release.

### PR DESCRIPTION
**Pull request by senadir**
The checkbox for order note was there in we did the skeleton for the checkout, we never implemented but it’s still visible.
We will tackle this later, for now, I'm deleting it so people don't experience a broken feature.

Fixes #2308

image

### CODE REVIEW

File: assets/js/blocks/cart-checkout/checkout/block.js [hunk 1]
```diff
@@ -347,13 +347,6 @@ const Checkout = ( { attributes, scrollToTop } ) => {
 										}
 									/>
 								) }
-								{ /*@todo This is not implemented*/ }
-								<CheckboxControl
-									className="wc-block-checkout__add-note"
```
Comment (Aljullu) [inline assets/js/blocks/cart-checkout/checkout/block.js:352]: Should we remove the [CSS selector](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/blocks/cart-checkout/checkout/style.scss#L5) targeting this checkbox?

Comment (mikejolley) [reply assets/js/blocks/cart-checkout/checkout/block.js:352]: We can keep it; I think I'll give adding this back a shot during cooldown once all other issues are resolved :) Ref #1483
