### PR TITLE
Fix: Replace DropdownSelector with FormTokenField from Gutenberg

### LINKED ISSUE #3762: Replace DropdownSelector with FormTokenField from Gutenberg
Gutenberg has a component which is very similar to our `DropdownSelector`:

https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/form-token-field

This issue is about trying to completely remove `DropdownSelector` and instead use `FormTokenField` from Gutenberg.

In https://github.com/WordPress/gutenberg/pull/29110 some new props were added to that component so it's easier to match the behavior of the `DropdownSelector`.

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #3762

This PR replaces our `DropdownSelector` component with the `FormTokenField` from Gutenberg. The migration has some limitations:

- We need to remove border-radius support due to how `FormTokenField` works (see [the screenshot](https://user-images.githubusercontent.com/5423135/176823414-6d82631e-c0b7-4f48-8af5-34573e26899a.png)).
- `FormTokenField` doesn't fully support using components for display list items, which leads to [this issue](https://user-images.githubusercontent.com/5423135/176824807-cbf9d4db-c90e-4549-8d2d-3a3c5d220e68.png) when the component is printed as the string.

Thanks so much @ralucaStan for the suggestion to style `FormTokenField` block.

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) .
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md)
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
|    image    |   image    |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Add or edit Filter Products by Attribute block.
2. Change the display type to `Dropdown`.
3. Ensure the block functions normally.
4. Enable the Filter button, and ensure the block functions normally.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact
N/a

### Changelog

N/a

### CODE REVIEW

**Comment by dinhtungdu** [comment]
> * `FormTokenField` doesn't fully support using components for display list items, which leads to [this issue](https://user-images.githubusercontent.com/5423135/176824807-cbf9d4db-c90e-4549-8d2d-3a3c5d220e68.png) when the component is printed as the string.

I created https://github.com/WordPress/gutenberg/issues/42150 to track this issue.

File: assets/js/blocks/attribute-filter/block.tsx [hunk 1]
```diff
@@ -582,20 +582,47 @@ const AttributeFilterBlock = ( {
 				className={ `wc-block-attribute-filter style-${ blockAttributes.displayStyle }` }
 			>
 				{ blockAttributes.displayStyle === 'dropdown' ? (
-					<DropdownSelector
-						attributeLabel={ attributeObject.label }
-						checked={ checked }
+					<div
 						className={ classNames(
-							'wc-block-attribute-filter-dropdown',
+							'wc-blocks-components-form-token-field-wrapper',
```
Comment (ralucaStan) [inline assets/js/blocks/attribute-filter/block.tsx]: How do you feel about having a separate component what handles all the styling and default props needed for the FormTokenField before we can use it?

This was the customizations below would only have to be applied once, and it can be then included in other places in the repo.

With a new component we can also add a story so that we can showcase it in Storybook

**Review by ralucaStan — CHANGES_REQUESTED** [review]
I've added a comment. I recommend asking for another review from the Kirigami Team as well, as they are more familiar with the Block than I am.

**Comment by ralucaStan** [comment]
I've tested the branch with Storefront and I've notices some styling issues. Other than that the keyboard functionality is great.

Minor. This is how an empty suggestions list appears,notice the double border on the bottom.
Screenshot 2022-07-06 at 18 10 38
 maybe there are ways to improve it, from what I saw on [Gutenberg this is not happening there](https://wordpress.github.io/gutenberg/?path=/story/components-formtokenfield--async)
Screenshot 2022-07-06 at 18 19 04

**Hovering on the close icon**
Screenshot 2022-07-06 at 18 08 53

Hovering on a suggestion item
Screenshot 2022-07-06 at 18 07 56

**Comment by dinhtungdu** [comment]
@ralucaStan Thank you so much for the review! I address your comments and suggestions. Can you please take another look?

> Minor. This is how an empty suggestions list appears,notice the double border on the bottom.
> from what I saw on [Gutenberg this is not happening there](https://wordpress.github.io/gutenberg/?path=/story/components-formtokenfield--async)

The reason for the double border issue is that we use `__experimentalExpandOnFocus`. I fixed this in 0f09af2ef7bfc967306c15efe303cffa05b74ec3.

**Comment by ralucaStan** [comment]
> @ralucaStan Thank you so much for the review! I address your comments and suggestions. Can you please take another look?

I've tested again and all is looking well. 👏  Really happy to see this progress.


I would also add the new component to the Storybook, so it would be great to take care of that in this PR as well.


I want to hightlight that PR will introduce this warning from upstream when running `npm run start`.

Screenshot 2022-07-07 at 13 58 31

**Review by ralucaStan — CHANGES_REQUESTED** [review]
Looks good, I've added a comment requesting a storybook entry for the new component

**Comment by dinhtungdu** [comment]
> I would also add the new component to the Storybook, so it would be great to take care of that in this PR as well.

@ralucaStan I'm sorry, I missed this. I added stories in 5b60eed.

> I want to hightlight that PR will introduce this warning from upstream when running `npm run start`.

What do you think we should do here? That issue comes from `wordpress-components`.

**Comment by ralucaStan** [comment]
> What do you think we should do here? That issue comes from `wordpress-components`.

I think the best next step is to open a ticket on that ticket to replace the "/" operator with div and calc. 

✋

**Comment by dinhtungdu** [comment]
> I think the best next step is to open a ticket on that ticket to replace the "/" operator with div and calc.

@ralucaStan that issue was fixed this https://github.com/WordPress/gutenberg/pull/33433. But as https://github.com/woocommerce/woocommerce-blocks/pull/5223, it seems that we need to stick with the `14.2.0` version. I'm not so familiar with the build so pinging @senadir and @mikejolley for more insights.

**Review by Aljullu — COMMENTED** [review]
Very happy to see this being worked on! It's exciting to think that we might be able to get rid of the `DropdownSelector` component!

> - We need to remove border-radius support due to how `FormTokenField` works (see [the screenshot](https://user-images.githubusercontent.com/5423135/176823414-6d82631e-c0b7-4f48-8af5-34573e26899a.png)).

I think that's fine, considering we didn't enable it in WC core.

> - `FormTokenField` doesn't fully support using components for display list items, which leads to [this issue](https://user-images.githubusercontent.com/5423135/176824807-cbf9d4db-c90e-4549-8d2d-3a3c5d220e68.png) when the component is printed as the string.

That seems to be a blocking one, though. I tested with a screen reader and it's reading `[object Object] (1 of 1)`. :worried: 

---

Besides that, a couple of bugs I found:

I was able to crash the Filter Products by Attribute block:

https://user-images.githubusercontent.com/3616980/178476428-e1153dad-8693-40b2-beff-7c55d6224a7a.mp4

Steps to reproduce:

1. Add the Filter Products by Attribute block with _Allow selecting multiple options?_ to _Multiple_, _Query Type_  to _AND_ and _Display Style_ to _Dropdown_.
2. In the frontend, select a couple of attributes, select the white space after the labels and press left arrow.
3. Start typing the name of another attribute to add it.
4. Notice the block crashes.

The other issue is that popovers in the editor are no working anymore for me:

https://user-images.githubusercontent.com/3616980/178478664-c682163f-dfbb-4332-a58a-e3d4be5ed268.mp4

Can you reproduce as well? In `trunk` they seem to be working fine. (I have the latest version of GB installed)

**Comment by dinhtungdu** [comment]
> I was able to crash the Filter Products by Attribute block:

@Aljullu I can reproduce this issue too. We have this issue because we're using React components to display the suggestion list which is required to display product count. If we use string instead, we won't have this and the following issue. But losing the ability to display the product count is a blocker to me.

> > * `FormTokenField` doesn't fully support using components for display list items, which leads to [this issue](https://user-images.githubusercontent.com/5423135/176824807-cbf9d4db-c90e-4549-8d2d-3a3c5d220e68.png) when the component is printed as the string.
> 
> That seems to be a blocking one, though. I tested with a screen reader and it's reading `[object Object] (1 of 1)`. 😟

--

> The other issue is that popovers in the editor are no working anymore for me:

I can't get produce this issue, the popover is still working as expected checking out this PR. I tested for both Block and Site Editors.

**Comment by dinhtungdu** [comment]
@Aljullu @ralucaStan In 2a83fac0c564161fd32ea145000fc9dcaaf7ee53, I changed the label of the display option from component to string to fix current issues:
- Component is printed as a string (`[object Object] (1 of 1)`).
- The block crashes on search as @Aljullu pointed out above.

But this also introduces an issue: We can't style the product count. Compared to the above issues, this has a pretty smaller impact. IMO, we can accept this issue and update it when Gutenberg adds component support for suggestions. What do you think?

**Review by Aljullu — COMMENTED** [review]
This is looking great, thanks for all the updates, @dinhtungdu!

> But this also introduces an issue: We can't style the product count. Compared to the above issues, this has a pretty smaller impact. IMO, we can accept this issue and update it when Gutenberg adds component support for suggestions. What do you think?

Agree. While it's unfortunate, I think the benefits we get from this PR overcome that.

---

However, I found one last thing which I think is a blocker. I noticed that `FormTokenField` behaves differently than the `DropdownSelector` in one thing: the dropdown pushes the contents below instead of covering them.

| Before | After |
| --- | --- |
| imatge | imatge |
| _(notice the dropdown covers the title of the filter block below)_ | _(notice the dropdown pushes the next contents down)_ |

While I think that's ok when they are rendered one on top of the other (ie, in a sidebar); I see this being a problem when trying to add filters side-by-side and then the product grid blow. In those cases, opening the dropdown would push the entire product grid below.

Do you think that would be easy to fix? I'm a bit on the fence on whether we should try to get that enhancement made upstream (ie, the component has another attribute to control whether it pushes or covers the contents below), or just work-around it downstream. The rational is that I'm not sure how common is our use-case, so maybe it doesn't make sense trying to get the changes upstream. What do you think?

**Comment by dinhtungdu** [comment]
> While I think that's ok when they are rendered one on top of the other (ie, in a sidebar); I see this being a problem when trying to add filters side-by-side and then the product grid blow. In those cases, opening the dropdown would push the entire product grid below.

@Aljullu IMO, this is quite a significant issue because it causes content shift for below content, which may affect performance on low-end devices.

> I'm a bit on the fence on whether we should try to get that enhancement made upstream (ie, the component has another attribute to control whether it pushes or covers the contents below), or just work-around it downstream. The rational is that I'm not sure how common is our use-case, so maybe it doesn't make sense trying to get the changes upstream.

I think the better place for the fix is our plugin, because:
- Fixing the issue in Gutenberg takes a lot of time to release.
- We're using an older version of `@wordpress/components` due to an issue with React version.
- Gutenberg core might refuse that fix because it changes the current behavior.

In dbaae97, I fixed the styling issue to prevent the content shift issue. Note that I had to remove the focus style of the input because it feels broken with the next behavior when the suggestion list is expanded. To me, the flashing text cursor and the suggestion expanded on focus are enough to catch users' attention and make it distinguish from the normal state. We may still have an issue when the suggestions list is empty, but I think we can address it in the future with some help from the design team.

<table>
<tr>
	<td> With focus style (box-shadow)
	<td> Without focus style (box-shadow)
<tr>
	<td>image
	<td>image
</table>

File: assets/js/base/components/form-token-field/style.scss [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+		top: 100%;
+
+		> li {
+			border: 1px solid $gray-600;
+			border-width: 0 1px;
+		}
+
+		> li:last-child {
+			border-width: 0 1px 1px;
+		}
```
Comment (Aljullu) [inline assets/js/base/components/form-token-field/style.scss]: Small suggestion: I would move the border from the list items into the wrapper, so it's always visible even if the list overflows. I also needed to add a `z-index` value to avoid other elements overlapping it:

Before | After
--- | ---
imatge | imatge

```suggestion
		border: 1px solid $gray-600;
		border-width: 0 1px 1px;
		z-index: 1;

		&:empty {
			display: none;
		}
```

Adding `display: none` when the element is empty makes it so the border is not visible if there are no suggestions.

**Review by Aljullu — COMMENTED** [review]
This looks vey promissing. Thanks for the latest update, @dinhtungdu. I did another round of testing and found some other things:


I noticed it's possible to introduce any value into the input field:

https://user-images.githubusercontent.com/3616980/179493345-c899e06c-c249-46be-9a77-35af975e1ed7.mp4

I think we will need to use [`__experimentalValidateInput`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/form-token-field#properties) to verify that any input matches one of the suggestions. I also wonder if it would be possible to pre-select the first option, so if the user introduces `bl` and presses <kbd>Enter</kbd>, it selects `Blue`.

Another thing I noticed is that if the button is enabled, it appears cut-off at the bottom:

`trunk` | This branch
--- | ---
imatge | imatge

I also noticed that in `assets/js/blocks/attribute-filter/block.tsx`, we have a lot of code to announce the filter that was changed to screen readers, I wonder if we could use the `added`, `removed`, etc. [props](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/form-token-field#properties) from `FormTokenField` and further simplify our code.

File: assets/js/base/components/form-token-field/style.scss (hunk 2 above)
Comment (dinhtungdu) [reply assets/js/base/components/form-token-field/style.scss]: > Adding `display: none` when the element is empty makes it so the border is not visible if there are no suggestions.

TIL! Thanks for the lesson on the `:empty` selector!

**Comment by dinhtungdu** [comment]
> I also noticed that in `assets/js/blocks/attribute-filter/block.tsx`, we have a lot of code to announce the filter that was changed to screen readers, I wonder if we could use the `added`, `removed`, etc. [props](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/form-token-field?rgh-link-date=2022-07-18T10%3A47%3A00Z#properties) from `FormTokenField` and further simplify our code.

@Aljullu We can. But we will lose the ability to announce filter replacement. We also lose the dynamic announcement. Besides, `announceFilterChange()` doesn't announce messages at the moment. The function is executed, but the screen reader won't announce the messages. It seems that the `speak()` calls with `assertive` in `<FormTokenField>` override the messages from `<AttributeFilterBlock>`.

IMO, we have to use the `messages` prop and accept the trade-off. I updated it in [d02c911](https://github.com/woocommerce/woocommerce-blocks/pull/6647/commits/d02c9114ad414b0413199a3b7ad6f23321f0bbcc), I'd love to hear your opinion on this!

https://github.com/woocommerce/woocommerce-blocks/blob/9bf450cc9c69106089c70b7db88b3a10995e0084/assets/js/blocks/attribute-filter/block.tsx#L403-L413

> I also wonder if it would be possible to pre-select the first option, so if the user introduces bl and presses Enter, it selects Blue.

We need to add a new prop to `<FormTokenField/>` to support this behavior. Currently, we can't manipulate behaviors of the `addCurrentToken()` function to select the first matched suggestion (see the [function definition](https://github.com/dinhtungdu/gutenberg/blob/6105ee5bdddbcfaa410d71daf294a08361001a55/packages/components/src/form-token-field/index.tsx#L394-L407)). Edit: I can submit a PR to Gutenberg repo to add this.

File: assets/js/base/components/form-token-field/style.scss (hunk 2 above)
Comment (dinhtungdu) [reply assets/js/base/components/form-token-field/style.scss]: FYI, I use `50` for `z-index` because the nobs of the price filter use `21`. We can use `25` but I think `50` is more future proof.

Comment (Aljullu) [reply assets/js/base/components/form-token-field/style.scss]: Sounds good!

**Review by Aljullu — COMMENTED** [review]
> IMO, we have to use the messages prop and accept the trade-off. I updated it in [d02c911](https://github.com/woocommerce/woocommerce-blocks/pull/6647/commits/d02c9114ad414b0413199a3b7ad6f23321f0bbcc), I'd love to hear your opinion on this!

I think it makes sense.

> We need to add a new prop to <FormTokenField/> to support this behavior. Currently, we can't manipulate behaviors of the addCurrentToken() function to select the first matched suggestion (see the [function definition](https://github.com/dinhtungdu/gutenberg/blob/6105ee5bdddbcfaa410d71daf294a08361001a55/packages/components/src/form-token-field/index.tsx#L394-L407)). Edit: I can submit a PR to Gutenberg repo to add this.

Thanks for taking care of this!

---

I did a round of testing and everything seems to be working great. I have one last comment, though. When selecting "Single" in "Allow selecting multiple options?", this is how it looked before and now:

Before | This PR
--- | ---
imatge | imatge

From the previous UI, I liked that it made it easier to notice that only one option could be selected. I wonder if we should either:

1) Tweak the CSS so the token occupies the entire width.
2) Maybe use a [ComboboxControl](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/combobox-control) in cases when only one option is allowed.

What do you think?

**Comment by dinhtungdu** [comment]
> 1. Tweak the CSS so the token occupies the entire width.

@Aljullu Thanks for another great review! I updated the PR following your first suggestion. Please take another look a this!

**Review by Aljullu — COMMENTED** [review]
Looks great, I left one small comment about styling, but it's quite minor.

I also found there is a weird behavior when I select several options without closing the dropdown in between:

https://user-images.githubusercontent.com/3616980/179955380-36b49f3d-bc26-45e9-b27a-be27c05b0c53.mp4

I'm not 100% sure about how to reproduce it, but it seems to be:

1. Open the dropdown when there is an option already selected.
2. Select another option and then, without closing the dropdown, another one.
3. Then, click outside of the dropdown and it won't close anymore.

Can you reproduce it as well?

**Comment by dinhtungdu** [comment]
@Aljullu I can reproduce the issue. In [9d4b339](https://github.com/woocommerce/woocommerce-blocks/pull/6647/commits/9d4b339a68cc48306f71e41306f9bd4a7ebb5d4d), I hide the input field when a token is selected for single selection. Hiding the input field causes the focus issue. I fixed it in [ddf879c](https://github.com/woocommerce/woocommerce-blocks/pull/6647/commits/ddf879cd6ac57baada53ad801107bf6fdf0adf8d) 😄

File: assets/js/base/components/form-token-field/style.scss [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+
+		input[type="text"].components-form-token-field__input {
+			min-height: 30px;
+		}
+	}
+
+	.components-form-token-field__remove-token.components-button,
+	.components-form-token-field__token-text {
+		background: $gray-200;
+	}
```
Comment (Aljullu) [inline assets/js/base/components/form-token-field/style.scss:31]: I would set the background color to transparent if it's `.single-selection`.

File: assets/js/base/components/form-token-field/style.scss [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+		}
+
+		.components-form-token-field__token-text {
+			width: 100%;
+		}
+
+		.components-form-token-field__token + input[type="text"].components-form-token-field__input {
+			opacity: 0;
+			position: absolute;
+		}
```
Comment (Aljullu) [inline assets/js/base/components/form-token-field/style.scss]: Here, I wonder if we can make the input visible (and have a border) when the dropdown is open.

**Review by Aljullu — COMMENTED** [review]
Thanks for your patience with me, @dinhtungdu. I know I'm being very nit-picking! :smile: 

I just have a couple of additional comments (I left them inline below :point_down: ). They are based on how different the single selection component looks before and after:

Before | After
--- | ---
imatge | imatge

**Comment by dinhtungdu** [comment]
> Thanks for your patience with me, @dinhtungdu. 

I want to say the same. Thanks for your patience with me! Your suggestions and reviews are all great and make a lot of sense to me.

> I would set the background color to transparent if it's `.single-selection`.

I address this in [5cfd449](https://github.com/woocommerce/woocommerce-blocks/pull/6647/commits/5cfd4492a65ee853ce3bc5cffb6fcaa5ac0ef313).

> Here, I wonder if we can make the input visible (and have a border) when the dropdown is open.

Yes, we can do that. `<FormTokenField>` disable input when the number of selected tokens exceeds the `maxLength` value. But we can 'hack' it to fit our needs. I did it in [395fda8](https://github.com/woocommerce/woocommerce-blocks/pull/6647/commits/395fda856184610ef248eca21f9e40c3b58072aa).

I also found an interesting issue: we're breaking the editor. Including `popover` style in the build causes that issue. I fixed it in [3f5903d](https://github.com/woocommerce/woocommerce-blocks/pull/6647/commits/3f5903d9169111a110c32ba2515fa3226f87f16e).

Can you take another look when you have time?

**Review by Aljullu — COMMENTED** [review]
> I also found an interesting issue: we're breaking the editor. Including `popover` style in the build causes that issue. I fixed it in [3f5903d](https://github.com/woocommerce/woocommerce-blocks/pull/6647/commits/3f5903d9169111a110c32ba2515fa3226f87f16e).

Thanks for catching the issue!

---

New changes look good! I have just one more comment. The input field seems to be always visible, but in the old component, it was only visible when the select was focused. Is it possible to do that?

This is the old one:

https://user-images.githubusercontent.com/3616980/180178012-4632d089-a99e-4692-a013-e6499a600769.mp4

**Comment by dinhtungdu** [comment]
> New changes look good! I have just one more comment. The input field seems to be always visible, but in the old component, it was only visible when the select was focused. Is it possible to do that?

@Aljullu yes, I did it in 9ee302c. I'm sorry for missing this issue, I was too focused on resolving style conflict.

**Review by Aljullu — COMMENTED** [review]
Thanks for the improvements, @dinhtungdu! I just found one last issue (sorry for finding them one-by-one :sob: ):

https://user-images.githubusercontent.com/3616980/180207895-372a234c-9bfc-45a6-98c2-cdaef1a81456.mp4





When only a single option can be selected, the dropdown should close when one option is selected.

**Comment by dinhtungdu** [comment]
> When only a single option can be selected, the dropdown should close when one option is selected.

I'm afraid we can't do that with the current implementation of `<FormTokenField>`. We need to change the active state inside of `<FormTokenField>`.

I can create a PR to fix this upstream. But we're using `@wordpress/components` v14.2 (because of an issue with React version AFAIK).

**Review by Aljullu — APPROVED** [review]
Ok, let's get this merged in and we can iterate on it afterwards.

> I can create a PR to fix this upstream.

While I don't consider this a blocker, I think it would be good to get it fixed sooner than later, so if you could include that as part of the project, that would be great.

> But we're using `@wordpress/components` v14.2 (because of an issue with React version AFAIK).

Thanks for raising this. So even if we get this fixed upstream, we will need to fix this issue with the React version in order to get the benefits in our builds, is that correct?

**Review by Aljullu — CHANGES_REQUESTED** [review]
I just found one more issue. The filter doesn't seem to allow introducing multi-word filters. I created a `dark blue` color and if I write it in the input field, it doesn't appear in the dropdown:

https://user-images.githubusercontent.com/3616980/180479175-4da54c83-0547-490d-ad0a-f5fa3257def3.mp4

**Comment by dinhtungdu** [comment]
> I just found one more issue. The filter doesn't seem to allow introducing multi-word filters. I created a `dark blue` color and if I write it in the input field, it doesn't appear in the dropdown:

Ahh, I missed this. Thanks for the catch! I fixed it in [609b60a](https://github.com/woocommerce/woocommerce-blocks/pull/6647/commits/609b60ad34dc6de10abb8b40e4d8041f809432ef). Can you take another look?

https://user-images.githubusercontent.com/5423135/180717002-3ab00c78-4e4c-4972-973e-e0b1992dc276.mov

**Comment by dinhtungdu** [comment]
[609b60a](https://github.com/woocommerce/woocommerce-blocks/pull/6647/commits/609b60ad34dc6de10abb8b40e4d8041f809432ef) misses the actual fix. [49301b9](https://github.com/woocommerce/woocommerce-blocks/pull/6647/commits/49301b9c39c784525d221cf4fe8bbce790cb5fdd) adds a new utility to format attribute term value before processing, supporting slugs contain `-` and/or `_`

**Review by Aljullu — APPROVED** [review]
Awesome job with this PR @dinhtungdu! Everything is looking good on my end. :ship: 

> When only a single option can be selected, the dropdown should close when one option is selected.

Just to confirm: is this under your radar? I think at least we would need an issue to be created.

**Comment by dinhtungdu** [comment]
> Just to confirm: is this under your radar? I think at least we would need an issue to be created.

Yes, I will create a PR to add it upstream. What do you think about a new option to enable that behavior: `__experimentalCollapseOnMaxReached`? Or should we auto collapse and close the dropdown when the max length is reached? 🤔

**Comment by dinhtungdu** [comment]
@Aljullu can you do another review 😅? In d9baa88 and 57d0146 I address issues when attributes have `_` in their slug. I admit that the code is more complex, but as we allow `_` in the slug, we need to support it. Those issues are:
- The term is selected in the `<FormTokenField>` but the query doesn't change.
- The token label is the slug, not the name.
- The selected token still appears in the suggestion list.

**Comment by dinhtungdu** [comment]
I'm also thinking about using the fuzzy search here, for example, [fuse.js](https://fusejs.io/). But it looks like an overkill for this block.

**Review by Aljullu — APPROVED** [review]
> Yes, I will create a PR to add it upstream. What do you think about a new option to enable that behavior: `__experimentalCollapseOnMaxReached`? Or should we auto collapse and close the dropdown when the max length is reached? 🤔 

I don't have a strong opinion. Ideally we would get some feedback from GB devs. I see you mentioned it on [the issue you created](https://github.com/WordPress/gutenberg/issues/42773), so that's good. Thanks! :+1: 

> I address issues when attributes have _ in their slug.

Oh, good catch. Changes look good to me and it's testing as described. :shipit: 

> I'm also thinking about using the fuzzy search here, for example, [fuse.js](https://fusejs.io/). But it looks like an overkill for this block.

Yeah, I think for now we can keep it as-is. If in the future we get some reports that would like to improve/change this, we can then consider it.
