### PR TITLE
Checkout - Available Payment Method Filtering

### LINKED ISSUE #8322: You cant remove payment method using filter woocommerce_available_payment_gateways
## Describe the bug

woocommerce_available_payment_gateways filter do not remove the available payment gateway on the checkout page when you use woocommerce checkout block

## To reproduce
Enable Cod backment option in woocommerce 

after that add this code in your theme functions.php file this will remove the cod payment option
for normal checkout page
`
add_filter('woocommerce_available_payment_gateways', function( $payments){ 
unset($payments['cod']);
return $payments;
});
`

but when you make the checkout page using Block the payment option is shown on the checkout page 

## Expected behavior

Payment option should get removed with this filter

### PR DESCRIPTION
**Pull request by mikejolley**
This is a solution for compatibility with the `woocommerce_available_payment_gateways` filter. This filter hook can be used to remove payment methods from the core checkout, and in our case, can prevent certain gateways from being used to checkout. It doesn't however filter visible methods in the Checkout Block because we're not using it.

You can test this filter with some custom code:

```
add_filter(
	'woocommerce_available_payment_gateways',
	function( $payments ) {
		unset( $payments['cod'] );
		return $payments;
	}
);
```

The above example would disable the cash on delivery payment method.

The problem we have is that the settings API grabs all registered/enabled payment gateways early on and statically, so cart data and other globals cannot reliable be consumed by `woocommerce_available_payment_gateways`, which would also become stale if cart data changed.

The solution I've come up with in this PR is to return available payment methods with the cart response, so the list of payment methods can be filtered on the fly as the cart changes. I've also updated the checkout response to correctly filter available methods, since for some reason it was returning all of them in the `enum`.

Fixes #8322

This PR could use feedback on approach and testing. I had to update tests so that the cart listed available methods that were registered/mocked in the test suite. cc @senadir 

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Add the code above to your site. 
2. Ensure COD, BACs are enabled.
3. Go to the checkout page. COD should not be shown on checkout.
4. Place an order successfully with an available method. 

You can also test an OPTIONS request to `/wp-json/wc/store/checkout` to check the enum is valid for `payment_methods`. It should only include available methods.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Dev note

Payment methods on the Block checkout will now respect the `woocommerce_available_payment_gateways` filter. For example, on the PHP side you could prevent a payment method being shown to a customer using:

```php
add_filter(
	'woocommerce_available_payment_gateways',
	function( $payments ) {
		unset( $payments['cod'] );
		return $payments;
	}
);
```

As part of this work, the Store APIs `wc/store/v1/cart` route will now return a list of available payment methods for that cart, e.g.:

```json
"payment_methods": [ "cod", "bacs", "cheque" ],
```

This is in turn stored on the JavaScript side in the `wc/store/cart` data store. This change does not affect payment extensions or payment method registration, it only affects use of filters on the server side.

### Changelog

> Added support for `woocommerce_available_payment_gateways` to the Store API

### CODE REVIEW

**Review by tarhi-saad — COMMENTED** [review]
@mikejolley, I followed the testing instruction, and every time the `cod` payment method is also filtered out in the Checkout Block. I used the same code snippet in the PR description and added it using the `Code Snippet` plugin! I also tried debugging the issue locally, and I was indeed getting a `cartData` with the filtered-out `cod` payment method from the store API `/wc/store/v1/cart`. Do you have any idea what I may be doing wrong?

**Comment by mikejolley** [comment]
@tarhi-saad sorry I am not following you. COD should be filtered out - thats what the snippet does. 

If you test the snippet against trunk you'll see COD on checkout and when you place the order you'll see `The cod payment gateway is not available.`.

**Comment by tarhi-saad** [comment]
@mikejolley, I think I misunderstood the following explanation from the PR description:

> This filter hook can be used to remove payment methods from the core checkout... It doesn't however filter visible methods in the Checkout Block because we're not using it

Does this mean the code snippet should filter out the `cod` payment method from the Woo core's checkout and keep it visible in the Checkout Block? In my tests, the `cod` payment was filtered out from both checkouts. (i.e., core and Blocks)

**Comment by mikejolley** [comment]
@tarhi-saad That statement was describing the current behaviour. The hook works for core but not for blocks. With this PR, it should disable COD for both.

File: assets/js/base/context/hooks/cart/use-store-cart.ts [hunk 1]
```diff
@@ -15,6 +15,7 @@ import {
 	EMPTY_CART_ERRORS,
 	EMPTY_SHIPPING_RATES,
 	EMPTY_TAX_LINES,
+	EMPTY_PAYMENT_METHODS,
 	EMPTY_PAYMENT_REQUIREMENTS,
 	EMPTY_EXTENSIONS,
 } from '@woocommerce/block-data';
```
Comment (tarhi-saad) [inline assets/js/base/context/hooks/cart/use-store-cart.ts:21]: This is unrelated to the changes in this PR, but could we fix the TS error in this line? The TS error is `Projects must list all files or use an 'include' pattern.`, and the possible solution is to update the file `assets/js/base/context/hooks/tsconfig.json` by adding the path `"../../../data/index.ts"` to the `"include"` list!

File: src/StoreApi/Schemas/V1/CartSchema.php [hunk 2]
```diff
@@ -309,6 +309,12 @@ public function get_properties() {
 					'properties' => $this->force_schema_readonly( $this->error_schema->get_properties() ),
 				],
 			],
+			'payment_methods'         => [
+				'description' => __( 'List of available payment method IDs that can used to process the order.', 'woo-gutenberg-products-block' ),
```
Comment (tarhi-saad) [inline src/StoreApi/Schemas/V1/CartSchema.php]:
```suggestion
				'description' => __( 'List of available payment method IDs that can be used to process the order.', 'woo-gutenberg-products-block' ),
```

File: assets/js/data/payment/utils/check-payment-methods.ts [hunk 3]
```diff
@@ -139,22 +159,20 @@ export const checkPaymentMethodsCanPay = async ( express = false ) => {
...
-	}
+	// Order payment methods.
+	const paymentMethodsOrder = express
+		? Object.keys( paymentMethods )
+		: Array.from(
+				new Set( [
+					...( getSetting( 'paymentGatewaySortOrder', [] ) as [] ),
+					...Object.keys( paymentMethods ),
+				] )
+		  ).filter( ( key ) => canPayArgument.paymentMethods.includes( key ) );
```
Comment (tarhi-saad) [inline assets/js/data/payment/utils/check-payment-methods.ts]: @mikejolley, this filter is causing a regression in the `editor`. We will always get the static list of available payment gateways from the `previewCart` (i.e., `[ 'cod', 'bacs', 'cheque' ]`). This will cause showing any other payment gateway in the notice of incompatible gateways:

image

We can get payment methods from the cart instead of the preview, even when we are in the editor. But when I tested it, `cod` showed as an incompatible gateway! So, maybe we should take another approach.

So, the following line filters out `cod` payment method from the list of available payment gateway:

```TS
filter( ( key ) => canPayArgument.paymentMethods.includes( key ) );
```

And the notice of incompatible gateways using the `globalPaymentMethods` to get the list of enabled gateways. See https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/payment/selectors.ts#L16-L24 and https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/payment/selectors.ts#L113-L125. And see https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/BlockTypes/Checkout.php#L315-L332 for the `globalPaymentMethods` definition.

Does this hook `woocommerce_available_payment_gateways` hide a payment method and doesn't disable it?

File: assets/js/data/payment/test/check-payment-methods.tsx [hunk 4]
```diff
@@ -133,6 +134,9 @@ const registerMockPaymentMethods = ( savedCards = true ) => {
 	wpDataFunctions
 		.dispatch( PAYMENT_STORE_KEY )
 		.__internalUpdateAvailablePaymentMethods();
+	wpDataFunctions.dispatch( CART_STORE_KEY ).receiveCart( {
+		payment_methods: [ 'cheque', 'bacs', 'credit-card' ],
+	} );
```
Comment (tarhi-saad) [inline assets/js/data/payment/test/check-payment-methods.tsx:141]: We have a TS error in this line. We need a `CartResponse` object. We can use the `previewCart` object which include already these 3 payment methods:

```js
import { previewCart } from '@woocommerce/resource-previews';

wpDataFunctions.dispatch( CART_STORE_KEY ).receiveCart( previewCart );
```

File: assets/js/blocks/cart-checkout-shared/payment-methods/test/payment-methods.js [hunk 5]
```diff
@@ -102,9 +102,10 @@ describe( 'PaymentMethods', () => {
 		wpDataFunctions
 			.dispatch( CART_STORE_KEY )
 			.invalidateResolutionForStore();
-		wpDataFunctions
-			.dispatch( CART_STORE_KEY )
-			.receiveCart( defaultCartState.cartData );
+		wpDataFunctions.dispatch( CART_STORE_KEY ).receiveCart( {
+			...defaultCartState.cartData,
+			payment_methods: [ 'cod', 'credit-card' ],
+		} );
```
Comment (tarhi-saad) [inline assets/js/blocks/cart-checkout-shared/payment-methods/test/payment-methods.js:107]: `defaultCartState` isn't a `CartResponse` object. We can use the `previewCart` object:

```js
wpDataFunctions.dispatch( CART_STORE_KEY ).receiveCart( {
		...previewCart,
		payment_methods: [ 'cod', 'credit-card' ],
} );
```

**Review by tarhi-saad — CHANGES_REQUESTED** [review]
Thank you, @mikejolley, for the explanation! 🙌 I've reviewed the PR and left some suggestions below!

File: assets/js/data/payment/utils/check-payment-methods.ts (hunk 3 above)
Comment (mikejolley) [reply assets/js/data/payment/utils/check-payment-methods.ts]: I've modified it to only filter on the frontend.

**Review by tarhi-saad — APPROVED** [review]
Thank you, @mikejolley, for the changes! Everything looks good! Let's 🚢 it!

**Comment by PanosSynetos** [comment]
Thank you @mikejolley !

**Comment by senadir** [comment]
This broke checking out with COD if COD is condtional.

**Comment by mikejolley** [comment]
@senadir is there an issue logged? Assuming the conditional is on the server, it should allow us to return the updated list of payment methods in the cart response...

**Comment by senadir** [comment]
Sorry I didn’t expand much in this, I will create and issue later. It happens on the schema generation level, cod is not in the payment method enum so it’s rejected by Store API
