### PR TITLE
Display shipping calculator link for guests shopper

### LINKED ISSUE #11435: Shipping calculator link not present for guest/non logged in customers
## Describe the bug

For guests and not logged in customers, there's no visible link in the cart so they can change the shipping location and calculate the price.

## To reproduce

1. Make sure you have some shipping zone and method for United States - California
2. Make sure you have set Shop country/region as the default customer location in WooCommerce settings
3. Go to WooCommerce Settings and set the store's address to California
4. As a guest/not logged in user, visit the cart page with some product added already
5. Observe the issue, there's no link to change or add a new address to calculate shipping

## Expected behavior

The link to change an address and/or add a new address to calculate shipping should be present

## Screenshots

This is how [the link for calculating shipping](https://d.pr/i/Ooffsn) is visible when logged in
This is how [the link for calculating shipping](https://d.pr/i/s1Qp1G) is not visible when not logged in or a guest

### WordPress (please complete the following information):

-   WordPress version: 6.3.2
-   WooCommerce version: 8.2.1
-   WooCommerce Blocks version: 11.3.1
-   Site language: English
-   Any other plugins installed: Deactivated all such as MailPoet, WooCommerce Blocks..

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: latest Chrome and Firefox

## Additional context

There's an open thread on Slack # checkout-blocks-support where we confirmed a bug.

### PR DESCRIPTION
**Pull request by tarunvijwani**
## What

Fixes woocommerce/woocommerce-blocks#11435

## Why

- The shipping calculator link was displayed based on the `isAddressComplete` value.
- The shipping calculator was not displayed for the scenarios where the address was incomplete, but the formatted address was present.
- This made the shipping calculator not getting displayed for guest shoppers.
- With this, conditions are changed from `isAddressCompletea` to `formatShippingAddress` to display the shipping calculator if the formatted address is present.
- Added the unit test case for the condition for formatted address.

### Case 1
1. Go to the WooCommerce settings page: `wp-admin/admin.php?page=wc-settings`.
2. Change 'Default customer location' to `No location by default`. 
3. Remove any default(fallback) shipping rates. 
4. Open your site in a private session(incognito mode).
5. Add some products to the cart. 
6. Go to the cart page, and confirm the "Add an address for shipping rates" link is present in the shipping calculator.
7. Click on the link, and confirm it is working as expected.
8. Open your site in a regular session where you're already logged in and have placed an order before. 
9. Add some products to the cart. 
10. Go to the cart page, confirm the shipping address, and "change address" link present in the shipping calculator.
11. Click on the link, and confirm it is working as expected.

### Case 2
1. Go to the WooCommerce settings page: `wp-admin/admin.php?page=wc-settings`.
2. Change 'Default customer location' to `No location by default`. 
3. Add any default(fallback) shipping rates. 
4. Open your site in a private session(incognito mode).
5. Add some products to the cart. 
6. Go to the cart page, and confirm the shipping calculator is hidden and default shipping rates are visible
7. Open your site in a regular session where you're already logged in and have placed an order before. 
8. Add some products to the cart. 
9. Go to the cart page, confirm the shipping address, and "change address" link present in the shipping calculator.
10. Click on the link, and confirm it is working as expected.

### Case 3
1. Go to the WooCommerce settings page: `wp-admin/admin.php?page=wc-settings`.
2. Change 'Default customer location' to `Shop country/region`. 
3. Add the store's address.
4. Add the rates that cover the store's address
5. As a guest/not logged-in user, visit the cart page with some products added already.
7. Confirm the shipping address calculator link to change or add a new address is displayed.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|image|image|

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Display shipping calculator link for guests shoppers.

### CODE REVIEW

**Comment by ralucaStan** [comment]
@tarunvijwani to be super safe add also testing steps where the shipping address has all fields empty and the Add and address link to see shipping options link appears. That would imply not defaulting shipping to the store address

File: assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx [hunk 1]
```diff
@@ -31,15 +28,17 @@ export const ShippingAddress = ( {
...
 	const { isEditor } = useEditorContext();
 	const prefersCollection = useSelect( ( select ) =>
 		select( CHECKOUT_STORE_KEY ).prefersCollection()
 	);
-	// If the address is incomplete, and we're not in the editor, don't show anything.
-	if ( ! addressComplete && ! isEditor ) {
+	const hasFormattedAddress = !! formatShippingAddress( shippingAddress );
+
+	// If we don't have formatted address, and we're not in the editor, don't show anything.
+	if ( ! hasFormattedAddress && ! isEditor ) {
```
Comment (ralucaStan) [inline assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx:40]: This comments is redundant as it explains the code, but does not provide context. What case are we actually covering with this and why are we returning nothing?

Comment (opr) [reply assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx:40]: Yup, maybe the comment can explain _why_ `hasFormattedAddress` would be false? (i.e. the shopper hasn't entered one)

**Review by opr — APPROVED** [review]
Changes look fine besides the comment Raluca mentioned, a couple of the testing steps seem slightly redundant, why make the tester add rates for California, then update their store's address? We could just specify that there should be rates that cover the store's address couldn't we?

I tested with:
- above steps
- no shipping rates for the default location
- only local pickup for the default location

Since this works OK and the updates are only comments/testing steps I will approve.

File: assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx (hunk 1 above)
Comment (tarunvijwani) [reply assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx:40]: @ralucaStan Thank you for the suggestion, I will update the comment and add more testing steps.

>What case are we actually covering with this and why are we returning nothing?

If there is no default customer location in the store and the customer has not entered their address, but there is a default shipping method available for all locations, then we will hide the shipping calculator. This is because the store already has a default shipping address. This change was made in response to this request: https://github.com/woocommerce/woocommerce-blocks/pull/8141#issuecomment-1397239622

Here are the steps to reproduce this behavior:

1. Go to the WooCommerce settings page: `wp-admin/admin.php?page=wc-settings`.
3. Change 'Default customer location' to `No location by default`. 
4. Add any default(fallback) shipping rates. 
5. Open your site in a private session(incognito mode).
6. Add some products to the cart. 
7. Go to the cart page, and confirm the shipping calculator is hidden and default shipping rates are visible
image

image
image

Comment (senadir) [reply assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx:40]: I understand that we have this rather complex sutation because we choose to have two buttons, one named "change address" and one named "enter an address to view shipping rates"? Otherwise I don't understand why we need to check if a formatted address is present to begin with to see the calculator.

**Comment by tarunvijwani** [comment]
@opr I have updated the testing steps and comments. I'd appreciate it if you could review them before I merge the PR. Thank you so much!

File: assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx (hunk 1 above)
Comment (tarunvijwani) [reply assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx:40]: @senadir Yes, it wouldn't make sense to show the 'Add address for shipping rates' link when default rates are already displayed. Similarly, we should not display the 'Change address' link without an address. Hence we decided to hide it in this condition.

**Review by opr — CHANGES_REQUESTED** [review]
Thanks I re-tested this with this configuration:

- no default location,
- location-specific methods _and_ fallback methods enabled

I feel that the calculator should be shown here. Why don't we show it in this case?

**Comment by tarunvijwani** [comment]
> Thanks I re-tested this with this configuration:
> 
> * no default location,
> * location-specific methods _and_ fallback methods enabled
> 
> I feel that the calculator should be shown here. Why don't we show it in this case?

@opr There is a discussion ongoing about which text to show for the calculator link. Click here https://github.com/woocommerce/woocommerce-blocks/pull/11442#discussion_r1371500652 for more information.

I feel we should tackle that in a different PR. Happy to hear your thoughts about it.

**Comment by opr** [comment]
@tarunvijwani - ok if you create a follow-up issue to tackle this then that should be OK!

**Review by opr — APPROVED** [review]
Approving on the basis that a follow-up ticket will be created to tackle the issue of the calculator not showing if:

- No location set by default,
- Location-specific methods _and_ fallback methods available

File: assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx (hunk 1 above)
Comment (senadir) [reply assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx:40]: What happens when you have rates but not an address? Do we show nothing at that step?

Comment (tarunvijwani) [reply assets/js/base/components/cart-checkout/totals/shipping/shipping-address.tsx:40]: @senadir No, we don't show a calculator in that scenario. It will be addressed in the https://github.com/woocommerce/woocommerce-blocks/issues/10327 ticket.

**Comment by tarunvijwani** [comment]
> @opr I have updated the testing steps and comments. I'd appreciate it if you could review them before I merge the PR. Thank you so much!

We already have a separate ticket for it.  It will be addressed in the woocommerce/woocommerce#42280 ticket.
