### PR TITLE
Return null or object for ImageAttachmentSchema response

### LINKED ISSUE #9908: Expected null or Object but is Array on StoreAPI Product Categories
## Describe the bug
The return image of product categories should be null or object, but on some categories, it is an empty array.
The same issues happened on the image of `/wp-json/wc/store/products/categories` request.

## To reproduce

1. Access the [product category](https://www.boslla.com/wp-json/wc/store/products/categories/233) with wp-json.
2. Get the JSON content.

```
{
  "id": 233,
  "name": "Product Name",
  "slug": "product-name",
  "description": "Product description",
  "parent": 28,
  "count": 2,
  "image": [],   // not null or object, but array
  "review_count": 44,
  "permalink": ""
}
```

## Expected behavior

Expected the image to be null or object.

### WordPress

Core version: 6.2.2
WooCommerce version: 7.8.0

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #9908

In #9908, @whywilson reported:
> _"The return image of product categories should be null or object, but on some categories, it is an empty array. The same issues happened on the image of /wp-json/wc/store/products/categories request."_

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [x] Unit tests
  * [ ] E2E tests

The affected unit test can be executed using the following commands:
```sh
npm run wp-env start
npm run test:php -- tests/php/StoreApi/Routes/Products.php
```

#### User Facing Testing

1. Make sure to have two test product categories. One test product category should have an image, the other one should not have an image.
2. Open `[YOUR-URL]/wp-json/wc/store/products/categories` and replace `[YOUR-URL]` with the URL of your test site.
3. Alternatively, open `[YOUR-URL]/wp-json/wc/store/products/categories/[ID]` and replace `[ID]` with the ID of the test product category.
4. Verify that the response for the test product category without image is
```json
{
	...
	"image": null,
	...
}
```
5. Verify that the response for the test product category with image is
```json
{
   ...
   "images": { ... },
   ...
}
```

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix: Return null or object for ImageAttachmentSchema response.

### CODE REVIEW

File: src/StoreApi/Schemas/V1/ImageAttachmentSchema.php [hunk 1]
```diff
@@ -80,12 +80,12 @@ public function get_item_response( $attachment_id ) {
...
 
 		if ( ! is_array( $attachment ) ) {
-			return [];
+			return null;
 		}
 
 		$thumbnail = wp_get_attachment_image_src( $attachment_id, 'woocommerce_thumbnail' );
 
-		return [
+		return (object) [
```
Comment (mikejolley) [inline src/StoreApi/Schemas/V1/ImageAttachmentSchema.php:88]: Make sure to update the function return type to match—it still states array.

**Review by mikejolley — CHANGES_REQUESTED** [review]
The docblock needs changing but yes, this is what was needed.

Can we ensure that all consumers of these endpoints continue to function before merging. I don't think it will break any backwards compatibility because it would I think be treated as an object anyway, but let's be certain.

Test wise, you could test the response for the cart endpoint and ensure that images are either null or received as an object with said properties. This would be added to the PHP test suite.

**Comment by nielslange** [comment]
> The docblock needs changing but yes, this is what was needed.

Thanks for your review, @mikejolley. I just added the `docblock` that you mentioned in your review. Somehow, my reply was added as a review. When deleting it, to reply to your review comment, it accidentally also deleted your review comment. 🙈 Nevertheless, your feedback has been adjusted.

> Can we ensure that all consumers of these endpoints continue to function before merging. I don't think it will break any backwards compatibility because it would I think be treated as an object anyway, but let's be certain.
> 
> Test wise, you could test the response for the cart endpoint and ensure that images are either null or received as an object with said properties. This would be added to the PHP test suite.

Thanks for pointing this out. I'll create additional test cases to guarantee that this change will remain backwards compatible.

**Review by mikejolley — APPROVED** [review]
Thanks for adding the tests 🥇

**Review by opr — APPROVED** [review]
Looks good to me!

**Comment by nielslange** [comment]
Thanks for your reviews, @mikejolley and @opr! 🙌
