### PR TITLE
only show checkout login prompt if store allows it

### LINKED ISSUE #2325: Checkout block: displays login message when the store has that option turned off
**Describe the bug**
The checkout page displays a message inviting the user to login during checkout, when that option is turned off in settings.

**To Reproduce**
1. WooCommerce - Settings - Accounts & Privacy
2. Make sure that "Allow customers to place orders without an account" is turned on
3. Make sure that "Allow customers to log into an existing account during checkout" is turned off
4. See the message "Already have an account? Log in." in the checkout frontend. 

**Expected behavior**
Not seeing a message suggesting to login when a store doesn't have that option turned on.
**Screenshots**
https://d.pr/i/5aC7oS

### PR DESCRIPTION
**Pull request by haszari**
Fixes #2325

At the top of checkout a login prompt is displayed. In Woo settings there's an option to disable this under `Guest checkout` section. This PR exposes this setting to the block, and only shows the prompt if the merchant has configured site to do so.

### Screenshots

Screen Shot 2020-04-30 at 4 11 34 PM

### How to test the changes in this Pull Request:

1. Publish a page with checkout block, add some stuff to your cart, view checkout block on front end.
2. Toggle `Allow customers to log into an existing account during checkout` option in `WooCommerce > Settings > Accounts & Privacy`.
3. Refresh checkout page - the log in prompt should only show if you have the option ticked. 
2. Toggle it back, refresh, and repeat :)

### CODE REVIEW

File: assets/js/blocks/cart-checkout/checkout/block.js [hunk 1]
```diff
@@ -158,6 +159,19 @@ const Checkout = ( { attributes, scrollToTop } ) => {
 		return <CheckoutOrderError />;
 	}
 
+	const loginPrompt = () =>
+		! CHECKOUT_SHOW_LOGIN_REMINDER ? null : (
```
Comment (Aljullu) [inline assets/js/blocks/cart-checkout/checkout/block.js:163]: Nitpicking but what do you think about replacing the ternary with an AND operator? It should work as well and I think it simplifies the code a bit.
```suggestion
		CHECKOUT_SHOW_LOGIN_REMINDER && (
```

Comment (mikejolley) [reply assets/js/blocks/cart-checkout/checkout/block.js:163]: +1
