### PR TITLE
Fix: Attribute Filters: allow choosing between single/multiple selection

### LINKED ISSUE #1311: Attribute Filters: allow chosing between single/multiple selection
Coming from the discussion in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1309#issuecomment-561170477.

Currently, in order to add feature-parity with widgets in the _Widgets to Blocks_ project, we made it so the Attribute Filters block when set to `Display Style: Dropdown` and `Query Type: AND`, it only allows the users to select one single attribute term.

This issue is about investigating if it could allow selecting multiple terms and updating the UI so users can select between single and multiple selection.

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #1311

This PR:
- Adds a new attribute and block setting allowing users to control the select behavior of the Attribute filter block between multiple and single selections.
- Allows multi-select for dropdown when query type is set to `AND`.
- Hides the query setting when the select type is set to `single`.
- Optionally renders that new select type data in the `Save` component to avoid block mismatch issues for existing Attribute Filter blocks.

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) .
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md)
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ------ |
|    image    |   Screen Shot 2022-06-23 at 12 11 52Screen Shot 2022-06-23 at 12 11 41    |
|    image    |   image   |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Edit a page containing an attribute filter block.
2. See no `Attempt block recovery` button for that block.
3. Select that attribute filter block, and see the new setting `Allow selecting multiple options?` set to Multiple by default.
4. Switch that setting to `Single`. See the `Query Type` setting disappear.
5. Switch back to `Multiple`. Set display style to `Dropdown` and query type to `AND`.
6. Save the page.
7. Visit the page on the front end, and see that we can select multiple attributes.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact
N/A

### Changelog

> Add: Allow choosing between single and multiple sections.

### CODE REVIEW

**Comment by dinhtungdu** [comment]
Requesting one more review from @Aljullu because this PR is based on his suggestion.

File: assets/js/blocks/attribute-filter/frontend.ts [hunk 1]
```diff
@@ -26,8 +26,8 @@ const getProps = ( el: HTMLElement ) => {
 				el.dataset.displayStyle ||
 				metadata.attributes.displayStyle.default,
 			showFilterButton: el.dataset.showFilterButton === 'true',
-			isPreview: false,
-			className: el.dataset.className || '',
```
Comment (Aljullu) [inline assets/js/blocks/attribute-filter/frontend.ts:30]: Is the removal of `isPreview` and `className` intentional?

**Review by Aljullu — APPROVED** [review]
Looks great! I tested it with the All Products block and PHP templates and everything seems to be working fine.

Not introduced in this PR, but one suggestion: when the selection mode is `Single` and display style `List`, could we replace the checkboxes with radio inputs? I think it's better for accessibility and also a better UI. (No need to do it as part of this PR, it can be done as a follow-up)

File: assets/js/blocks/attribute-filter/frontend.ts (hunk 1 above)
Comment (dinhtungdu) [reply assets/js/blocks/attribute-filter/frontend.ts:30]: > Is the removal of `isPreview` and `className` intentional?

@Aljullu Yes, I removed them because we don't need them on the front end.
- `isPreview` is only used in the block inserter.
- `className` is handled by the `<Save>` component, we don't use the `className` attribute in the `<Block>` as well.

**Comment by dinhtungdu** [comment]
> Not introduced in this PR, but one suggestion: when the selection mode is `Single` and display style `List`, could we replace the checkboxes with radio inputs? I think it's better for accessibility and also a better UI.

@Aljullu I thought about this too and experimented with the `<RadioControl>`. I decided to not use the radio for the single-choice list because users can't uncheck the selected attribute within the attribute filter block. Even we can uncheck the radio button using JS, it doesn't feel 'natural' to me to uncheck a radio input (I may be biased). What do you think?

**Comment by Aljullu** [comment]
> @Aljullu I thought about this too and experimented with the `<RadioControl>`. I decided to not use the radio for the single-choice list because users can't uncheck the selected attribute within the attribute filter block. Even we can uncheck the radio button using JS, it doesn't feel 'natural' to me to uncheck a radio input (I may be biased). What do you think?

Ah, good point. I didn't think about this. LGTM
