### PR TITLE
Fix select rates when multiple packages exists

### LINKED ISSUE #1901: It's not possible to select shipping rates for second packages when there are more than one
**To Reproduce**
1. Install [WooCommerce Advanced Shipping Packages](https://woocommerce.com/products/woocommerce-advanced-shipping-packages/) and set up some package rules ([see how](https://docs.woocommerce.com/document/woocommerce-advanced-shipping-packages/)).
2. Add products that will be in different packages to your cart.
3. Create a page with a _Cart_ block and view it in the frontend.
4. Try selecting shipping rates for the second package and notice changes are applied to the first package.

**Screenshots**
Peek 2020-03-09 11-40

### PR DESCRIPTION
**Pull request by senadir**
This PR changes the shape of selected shipping rates to an object so that we can maintain keys, it also changes to using package_id instead of the index for better stability, and it fixes an issue with updating state (I didn’t use the previous values + new 🤦‍♀️)

Fixes #1901

### How to test the changes in this Pull Request:

1. Following instructions in #1901 to create packages.
2. try selecting rates in both packages.
3. it should persist and prices should update and reloading should maintain the same value.

### CODE REVIEW

File: assets/js/base/hooks/shipping/use-select-shipping-rate.js [hunk 1]
```diff
@@ -13,21 +13,30 @@ See also: https://github.com/woocommerce/woocommerce-gutenberg-products-block/tr
...
- * - selectedShippingRates An array of selected shipping rates, maintained
+ * - selectedShippingRates An object of selected shipping rates and package id as key, maintained
  * locally by a state and updated optimistically.
  */
 export const useSelectShippingRate = ( shippingRates ) => {
-	const initiallySelectedRates = shippingRates.map(
-		// the API responds with those keys.
-		// eslint-disable-next-line camelcase
-		( p ) => p.shipping_rates.find( ( rate ) => rate.selected )?.rate_id
+	const initiallySelectedRates = Object.fromEntries(
```
Comment (Aljullu) [inline assets/js/base/hooks/shipping/use-select-shipping-rate.js]: In #1941 I noticed `Object.fromEntries()` doesn't seem to work with IE11. We should either refactor this so it doesn't use `Object.fromEntries()` or find a way for Bable to transpile this.

**Comment by senadir** [comment]
fixed the fromEntries in this file, I also fixed and reverted the other fromEntries when I discovered your PR also solves it
