### PR TITLE
Fix Product Query block hijacking all Query blocks queries

### LINKED ISSUE #6950: Product Query block hijacks all further queries
## Describe the bug

When you add a Product Query block and select a custom query attribute (i.e. set the toggle to display “On sale products”), adding further Product Query blocks or even normal Query Loop blocks will result in the query always being the filtered one. This is due to the fact that we register the filter every time before we render a Query Loop block.

## To reproduce

1. Add a Product Query block
2. Set the toggle to display “On sale products”
3. Add another Product Query block on the same page
4. Do not set the toggle
5. Add a Query Loop block
6. Set it to display your posts
7. Go to the front-end
8. Notice that all three blocks will display only on sale products

## Expected behavior

Each Query Loop block should retain its own query.

### PR DESCRIPTION
**Pull request by sunyatasattva**
The Product Query block was adding a filter to Gutenberg's core Query Loop block. When this filter was added once, it would from then on apply to all other Query Loop blocks (or variations thereof) on a page.

This change makes sure that:

1. No filters are added in the first place if our custom `__woocommerceVariationProps`
are not set.
2. The filter only gets run once.

Fixes #6950

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Add a Product Query block
2. Set the toggle to display “On sale products”
3. Add another Product Query block on the same page
4. Do not set the toggle
5. Add a Query Loop block
6. Set it to display your posts
7. Go to the front-end
8. Make sure the three loop blocks show the expected items

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental

### Performance Impact

Filters are still created, hooked and ran. They are not removed even when they have ran their course. Tradeoff explained above.

### Changelog

> Product Query: Fix an issue where multiple query loop blocks on the same page would be hijacked by a custom variation settings.

### CODE REVIEW

**Review by gigitux — APPROVED** [review]
LGTM! Good catch! For now, I think that we can adopt this approach 👍  What do you think if we add a comment? Maybe add a link to this PR, it is a good idea too!

File: src/BlockTypes/ProductQuery.php [hunk 1]
```diff
@@ -37,13 +37,27 @@ protected function initialize() {
 	 * @param array       $parsed_block The block being rendered.
 	 */
 	public function update_query( $pre_render, $parsed_block ) {
-		if ( 'core/query' !== $parsed_block['blockName'] ) {
+		if ( 'core/query' !== $parsed_block['blockName'] || ! isset( $parsed_block['attrs']['__woocommerceVariationProps'] ) ) {
 			return;
 		}
 
 		add_filter(
```
Comment (Aljullu) [inline src/BlockTypes/ProductQuery.php:75]: I know it's not introduced in this PR, but the `$accepted_args` param of this [`add_filter()`](https://developer.wordpress.org/reference/functions/add_filter/) call could be 1 instead of 3. We are only using `$query`, right?

**Review by Aljullu — APPROVED** [review]
Tested on my end too, and confirming it fixes the issue. :ok_hand: 

I agree with Luigi that we can go ahead with this solution for now. We can always improve it in the future if we have any other ideas.

One thing we could try is to store `$parsed_block` into a class property, this way we don't need to pass it to the filter function every time. Something along these lines:

```PHP
public function update_query( $pre_render, $parsed_block ) {
	if ( 'core/query' !== $parsed_block['blockName'] || ! isset( $parsed_block['attrs']['__woocommerceVariationProps'] ) ) {
		return;
	}
	$this->parsed_block = $parsed_block;

	add_filter(
		'gutenberg_build_query_vars_from_query_block',
		array( $this, 'get_query_vars' ),
		10,
		1
	);
}

public function get_query_vars( $query ) {
	remove_filter(
		'gutenberg_build_query_vars_from_query_block',
		array( $this, 'get_query_vars' )
	);
	return $this->get_query_by_attributes( $query, $this->parsed_block );
}
```

It has the benefit that we can remove the filter, with the expense that we need to add a property to the class. So leaving the final decision to you.

**Comment by sunyatasattva** [comment]
Thank you @Aljullu!! I've tested your implementation and it's great. You solved my conundrum! This is a much cleaner solution and I don't have the reservations I had before for this fix now! This made me a happy dev :D
