### PR TITLE
StyleAttributesUtils: Fix PHP notices and invalid CSS output

### LINKED ISSUE #7899: Methods in StyleAttributesUtils are generating PHP notices and return invalid css
**The following methods are causing issues:**
- `get_border_radius_class_and_style()`
- `get_padding_class_and_style()`
- `get_margin_class_and_style()`

**Example notices:**
- Notice: Array to string conversion in /wp-content/plugins/woocommerce-blocks/src/Utils/StyleAttributesUtils.php on line 252
- Notice: Undefined index: left in /wp-content/plugins/woocommerce-blocks/src/Utils/StyleAttributesUtils.php on line 406

The invalid CSS causes multiple block settings to not work correctly in the frontend:

| Editor | Page |
| ------ | ----- |
|Edit_Page_“All_Products”_‹_ratings_—_WordPress-9|All_Products_–_ratings-5|

**To replicate:**

1. Create a page and add the **Products (Beta)** block.
2. Add Product Price, Product Button, and Product Rating blocks and customize settings (colors, margins, font sizes).
3. Compare the results and notice the discrepancy between the editor and the page.

### PR DESCRIPTION
**Pull request by danieldudzic**
This PR fixes PHP notices, fixes CSS output for `margin`, `padding`, `border-width`, and `border-radius`, and adds a missing function handling `font-style`.

Fixes #7899

### Screenshots

| Before | After |
| ------ | ----- |
|All_Products_–_ratings-10|All_Products_–_ratings-9|

| PHP Notice | 
| ------ |
|All_Products_–_ratings_and_danieldudzic_Dannys-MacBook____Local_Sites_ratings_app_public_wp-content_plugins_woocommerce-blocks|

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Create a page and add the **Products (Beta)** block.
2. Add the **Product Image** and **On-Sale Badge** blocks.
3. Try setting different combinations of the following block settings:
- Border Radius
- Border Width (test also in conjunction with different Border Radius settings )
- Margin
- Padding

Make sure to test in both 'Linked' and 'Unlinked' modes ( one value for all 4 sides, custom values for each side, some sides not set etc. ).

Make sure for any of the scenarios no PHP errors and notices are being generated and the options display correct visual results on the page (frontend).

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix Padding, Margin, Border Width, and Radius settings for all relevant blocks.

### CODE REVIEW

File: src/Utils/StyleAttributesUtils.php [hunk 1]
```diff
@@ -247,9 +266,30 @@ public static function get_border_radius_class_and_style( $attributes ) {
 			return null;
 		}
 
+		$border_radius_css = '';
+
+		if ( is_string( $custom_border_radius ) ) {
+			// Linked sides.
+			$custom_border_radius = 'border-radius:' . $custom_border_radius . ';';
```
Comment (Aljullu) [inline src/Utils/StyleAttributesUtils.php]: `border-radius` wasn't working on my end. I think it's because of this line. Should it be like this?
```suggestion
			$border_radius_css = 'border-radius:' . $custom_border_radius . ';';
```

**Review by Aljullu — COMMENTED** [review]
Thanks for fixing this, @danieldudzic! I noticed it also fixes #7828. :tada: 

I just found a couple of issues. One is mentioned below, the other one inline in the code.

---
When I unlink the border to add a different width to each side, the border color is lost:

Editor settings | Frontend
--- | ---
imatge | imatge

File: src/Utils/StyleAttributesUtils.php (hunk 1 above)
Comment (danieldudzic) [reply src/Utils/StyleAttributesUtils.php]: Thank you so much for the review and for pointing out the bugs.

That border color was super tough to nail down as the format of passed data varies greatly.

File: src/Utils/StyleAttributesUtils.php [hunk 2]
```diff
@@ -204,32 +223,50 @@ public static function get_background_color_class_and_style( $attributes ) {
...
-			return null;
+		if ( $border_color_linked_preset ) {
+			// Linked preset color.
+			$border_color_class = sprintf( 'has-border-color has-%s-border-color', $border_color_linked_preset );
+		} elseif ( $border_color_linked_custom ) {
+			// Linked custom color.
+			$border_color_css .= 'border-color:' . $border_color_linked_custom . ';';
+		} else {
+			// Unlinked.
+			if ( '' !== $custom_border ) {
```
Comment (Aljullu) [inline src/Utils/StyleAttributesUtils.php]: Instead of checking that is not an empty string, I wonder if it would be safer to check that `$custom_border` is an array. What do you think?

**Review by Aljullu — APPROVED** [review]
Great investigation with all the possible border values, @danieldudzic! I like how this PR fixes global styles in many blocks. :clap: 

I left one last question, but pre-approving.

File: src/Utils/StyleAttributesUtils.php (hunk 2 above)
Comment (danieldudzic) [reply src/Utils/StyleAttributesUtils.php]: That does make more sense. Thank you for this feedback :)
