### PR TITLE
Load WC Blocks CSS after editor CSS

### LINKED ISSUE #3068: Checkout Country input is not wysiwyg styling in editor
## Describe the bug
The `Country` input control looks a bit different in the editor. 

Screen Shot 2020-08-28 at 9 11 03 AM

- Square corners.
- Semi-transparent background.
- Height bug (too short). 

Compare with front end:

Screen Shot 2020-08-28 at 9 31 26 AM

I'm assuming this is a regression that snuck in.

## To reproduce

1. Edit a page with checkout block. 
2. Scroll down to country input.

## Expected behavior
Consistent appearance in editor and front end.

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #3068.

The issue was caused because editor CSS was leaking into the block. It could be fixed ensuring our CSS is loaded after `wp-edit-post-css`. Notice this fix might no longer be needed if https://github.com/WordPress/gutenberg/issues/20797 gets merged into Gutenberg.

### Screenshots

_Before:_
imatge

_After:_
imatge

### How to test the changes in this Pull Request:

1. Edit a page with checkout block.
2. Scroll down to country input.
3. Verify it has rounded corners and the correct height.

Notice the semi-transparent background is not fixed since it's a different issue (#2487).

### Changelog

> Fix wrong styling of Checkout's country input in the editor.

### CODE REVIEW

File: src/Assets.php [hunk 1]
```diff
@@ -35,7 +35,17 @@ public static function init() {
 	 */
 	public static function register_assets() {
 		$asset_api = Package::container()->get( AssetApi::class );
-		self::register_style( 'wc-block-vendors-style', plugins_url( $asset_api->get_block_asset_build_path( 'vendors-style', 'css' ), __DIR__ ), [] );
+
+		// In the editor, we want our stylesheets to load after editor CSS (see #3068).
+		// This might be no longer necessary when https://github.com/WordPress/gutenberg/issues/20797
+		// is merged.
```
Comment (nerrad) [inline src/Assets.php:41]: Should we create an issue for the backlog for removing this extra code when the fix in Gutenberg lands and we can safely remove because the minimum version of WordPress we support has the fix (if so, you could convert this comment to a todo)?

**Review by nerrad — APPROVED** [review]
Nice solution here Albert 👍 (and great sleuthing).

I confirmed the select is fixed as described. I also reviewed our other blocks and ensured interfaces weren't affected by this change.

Let's 🚢 🎉

**Comment by chvillanuevap** [comment]
Could this also be causing the Full Site Editing page in Gutenberg to be completely blank as reported in WordPress/gutenberg#27938? I'm using WooCommerce 4.8.0. I don't have the WooCommerce Blocks plugin installed.

**Comment by Aljullu** [comment]
Hi @chvillanuevap, thanks for raising this! I created a new issue so we can investigate it: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3626.
