### PR TITLE
Featured Item: Fix default color being overridden by themes

### LINKED ISSUE #6489: Featured Product and Featured Category blocks default colors don't have enough contrast
## To reproduce

1. Add a Featured Product or Featured Category block into a post or page.
2. Notice text doesn't have enough contrast with the background.

imatge

## Expected behavior

By default, we should make sure text and background have enough contrast.

### PR DESCRIPTION
**Pull request by sunyatasattva**
This PR fixes a problem in which certain themes would override the default color of the Featured Item blocks, possibly leading to contrast and unexpected issues. While fixing this, I also noticed that custom colors wouldn't be applied to the text, only palette colors would, so that's fixed too.

Fixes #6489

### Screenshots

| Before | After |
| ------ | ----- |
|    before    |  after |

#### User Facing Testing

1. Activate the Storefront theme.
2. Add the Featured Product block to the page.
3. Select a product.
4. Notice that the default color of the text inside should be white.
5. Change the color using the picker to a custom one (not included in the default palette).
6. The color of the text should change.
7. Repeat steps 2–6 with the Featured Category block.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Featured Item Blocks: fix an issue where the default color could be overridden by a theme, and where custom colors where not applied correctly.

### CODE REVIEW

File: assets/js/blocks/featured-items/with-featured-item.tsx [hunk 1]
```diff
@@ -70,9 +70,12 @@ interface FeaturedItemRequiredProps< T > {
 		| FeaturedProductRequiredAttributes
 	 ) &
 		EditorBlock< T >[ 'attributes' ] & {
-			// This is hardcoded because border is not yet included in Gutenberg's
-			// official types.
-			style: { border?: { radius?: number } };
+			// This is hardcoded because  and color ar not yet included
```
Comment (Aljullu) [inline assets/js/blocks/featured-items/with-featured-item.tsx]: It looks like there are some typos in this comment.

**Review by Aljullu — APPROVED** [review]
Works perfectly! I left one minor comment about some typos in a comment, but besides that LGTM.
