### PR TITLE
Fixes for jest transpilation issues.

### LINKED ISSUE #10523: Jest error: is-plain-obj:  SyntaxError: Unexpected token 'export'
## Describe the bug

There is an issue with the current dependencies tree. If the `package-lock.json` and `node_modules` are deleted, and the dependencies are reinstalled, Jest will not be able to run tests anymore. This is the error:

```
woocommerce-gutenberg-products-block/node_modules/is-plain-obj/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export default function isPlainObject(value) {
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'
```

image

This is the output of the `npm ls is-plain-obj`. On the right, the dependencies tree with the current package-lock, on the left the dependencies tree with a new installation without package-lock.json.

As you can see, the `@wordpress/data` package uses `is-plain-obj@4.1.0` that contains the ES Module on a new installation.

Searching online, I found [this PR](https://github.com/WordPress/gutenberg/pull/43511) on Gutenberg repo. I think the best solution is to upgrade all the `@wordpress/*` dependencies. We should do this after the webpack 5 migration.

## To reproduce

1. Remove `package-lock.json` and `node-modules`.
2. Run `npm install`.
3. Run `npm run test`.
4. See error.

## Expected behavior

Unit tests should run.

### PR DESCRIPTION
**Pull request by samueljseay**
## What

There are a number of transpilation issues when we try update some dependencies. This fixes them all and resolves #10523 

## Why

This is so we can keep updating our dependencies without fear that the test framework will stop working.

## Testing Instructions

TBD

* [x] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

n/a
## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [x] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

### CODE REVIEW

**Review by gigitux — CHANGES_REQUESTED** [review]
Thanks for working on this, but I can still replicate https://github.com/woocommerce/woocommerce-blocks/issues/10523:
- remove package-lock.json.
- remove node_modules folder.
- run `npm install`.
- run `npm run test`.
- See the error.

File: assets/js/base/components/read-more/trim-html.js [hunk 1]
```diff
@@ -0,0 +1,155 @@
+export function trimHtml( html, options ) {
```
Comment (samueljseay) [inline assets/js/base/components/read-more/trim-html.js:3]: This change is a bit crazy. I'm not sure how we never ran into this, maybe because technically its ok not to declare a variable before access but I thought browsers having use strict would make this throw.

So the issue is that in the published version of trim-html there is no declaration of the variable `rowCut` which causes tests to throw an exception. You can verify the declaration is missing by downloading the npm module and checking the source.

This uses the repository source which has the problem fixed. I did consider implementing something myself with Domparser but decided against it because there is nuanced behaviour of the truncation. Thankfully we have tests covering regressions here.

We could also use a tool like patch package if its preferred. https://www.npmjs.com/package/patch-package

File: assets/js/blocks/cart/test/block.js [hunk 2]
```diff
@@ -32,6 +32,11 @@ import OrderSummarySubtotalBlock from '../inner-blocks/cart-order-summary-subtot
 import OrderSummaryShippingBlock from '../inner-blocks/cart-order-summary-shipping/frontend';
 import OrderSummaryTaxesBlock from '../inner-blocks/cart-order-summary-taxes/frontend';
 
+jest.mock( '@wordpress/compose', () => ( {
+	...jest.requireActual( '@wordpress/compose' ),
+	useResizeObserver: jest.fn().mockReturnValue( [ null, { width: 0 } ] ),
```
Comment (samueljseay) [inline assets/js/blocks/cart/test/block.js:37]: As mentioned in my commit this is something I have actually run into before, if you're including useResizeObserver as a dependency outside of WP (such as in a jest test) then you get an error because the underlying library (react-resize-aware) cannot access the jsx runtime due to how it's built. See https://github.com/FezVrasta/react-resize-aware/issues/58

If we had pnpm we could force resolution to a newer version, but in npm the solutions to this are hackier so we just stub it out here instead.

File: assets/js/blocks/checkout/inner-blocks/checkout-terms-block/test/edit.js [hunk 3]
```diff
@@ -7,7 +7,31 @@ import { render, queryByText } from '@testing-library/react';
  * Internal dependencies
  */
 import { Edit } from '../edit';
-const blockSettingsMock = jest.requireMock( '@woocommerce/block-settings' );
+
+jest.mock( '@wordpress/data', () => ( {
+	...jest.requireActual( '@wordpress/data' ),
+	useSelect: jest.fn().mockImplementation( ( fn ) => {
```
Comment (samueljseay) [inline assets/js/blocks/checkout/inner-blocks/checkout-terms-block/test/edit.js:13]: This was a bit tricky, I had to mock a few useSelect cases to avoid exceptions in underlying RichText component.

File: tests/js/jest.config.json [hunk 4]
```diff
@@ -30,7 +30,9 @@
 		"@woocommerce/blocks-test-utils": "tests/utils",
 		"@woocommerce/types": "assets/js/types",
 		"@woocommerce/utils": "assets/js/utils",
-		"@woocommerce/interactivity": "assets/js/interactivity"
+		"@woocommerce/interactivity": "assets/js/interactivity",
+		"^react$": "<rootDir>/node_modules/react",
```
Comment (samueljseay) [inline tests/js/jest.config.json:34]: These 2 lines are to ensure we only resolve one version of React. In prod this is never an issue because we load React via the window, but here we end up with multiple React instances sometimes in test and this causes "invalid hook" errors that fail tests.

File: tests/js/jest.config.json [hunk 5]
```diff
@@ -45,7 +47,7 @@
 		"<rootDir>/node_modules/",
 		"<rootDir>/vendor/"
 	],
-	"transformIgnorePatterns": [ "node_modules/(?!(simple-html-tokenizer)/)" ],
+	"transformIgnorePatterns": [ "node_modules/?!(simple-html-tokenizer|is-plain-obj|is-plain-object|memize)" ],
```
Comment (samueljseay) [inline tests/js/jest.config.json:50]: This amended regex seems to cover the broken modules correctly.

**Comment by samueljseay** [comment]
@gigitux Hmm looks like the transform ignore is interfering with e2e. I'll investigate this tomorrow 😓

File: tests/e2e-jest/config/jest.config.js [hunk 6]
```diff
@@ -35,6 +35,9 @@ module.exports = {
 		// Ignore all the files that have utils in the name
 		'utils',
 	],
-	transformIgnorePatterns: [ 'node_modules/(?!(woocommerce)/)' ],
+	transformIgnorePatterns: [
+		'node_modules/?!(simple-html-tokenizer|is-plain-obj|is-plain-object|memize)',
+		'node_modules/@woocommerce/e2e-utils/node_modules/config',
```
Comment (samueljseay) [inline tests/e2e-jest/config/jest.config.js:40]: This is for an exception I ran into running e2e: https://github.com/node-config/node-config/issues/628

File: assets/js/base/components/read-more/trim-html.js (hunk 1 above)
Comment (gigitux) [reply assets/js/base/components/read-more/trim-html.js:3]: I would add a comment that explains that this code is copy-pasted.

**Review by gigitux — APPROVED** [review]
Nice work! I added a small comment, but I'm pre-approving this PR! Thanks! 🚀
