### PR TITLE
Fix migration process

### LINKED ISSUE #10196: Migration doesn't run on `installing plugin from uploaded file` screen
## Describe the bug

[The migration process](https://github.com/woocommerce/woocommerce-blocks/blob/797ffe5d8077d6d5ecb6a94ae141eb5d2cab3b1d/src/Domain/Bootstrap.php/#L103-L108) doesn't run on the `installing plugin form uploaded file` screen:

image

This code only gets triggered in this scenario when the user visits another page in the admin. 

Since that we use this code to run the migration of the blockified template, this means that if the merchant updates WooCommerce via zip and when it lands on the `installing plugin from uploaded file` screen, closes the browser the migration will not run, and the blockified templates will be displayed.

## To reproduce

1. Ensure that you have WooCommerce 7.8.
2. Ensure that you have the legacy template enabled.
3. Visit a product page on the front end. Keep this tap open.
4. Ensure that the legacy template is loaded.
5. Upgrade WooCommerce via zip and keep the tab on the `installing plugin from uploaded file` screen.
6. Refresh the product page opened earlier and see that the blockified template is displayed.
7. Visit another admin page.
8. Refresh the product page opened earlier and you can see that the legacy template is displayed.

## Expected behavior

The migration should always run after the update.

### LINKED ISSUE #42300: Migration doesn't run on `installing plugin from uploaded file` screen
## Describe the bug

[The migration process](https://github.com/woocommerce/woocommerce-blocks/blob/797ffe5d8077d6d5ecb6a94ae141eb5d2cab3b1d/src/Domain/Bootstrap.php/#L103-L108) doesn't run on the `installing plugin form uploaded file` screen:

image

This code only gets triggered in this scenario when the user visits another page in the admin. 

Since that we use this code to run the migration of the blockified template, this means that if the merchant updates WooCommerce via zip and when it lands on the `installing plugin from uploaded file` screen, closes the browser the migration will not run, and the blockified templates will be displayed.

## To reproduce

1. Ensure that you have WooCommerce 7.8 and Woo Blocks disabled
2. Add the below snippet to your themes `functions.php` and reload the frontend. Then comment it out.
3. Ensure that you have the legacy template enabled.
4. Visit a product page on the front end. *Keep this tap open*.
5. Ensure that the legacy template is loaded.
6. Upgrade WooCommerce via zip and keep the tab on the `installing plugin from uploaded file` screen.
7. Refresh the product page opened earlier and see that the blockified template is displayed.
8. Visit another admin page.
9. Refresh the product page opened earlier and you can see that the legacy template is displayed.

```php
// snippet used in step 2.
<?php
delete_option( 'wc_blocks_use_blockified_product_grid_block_as_template' );
update_option( 'wc_blocks_version', '10.2.3' );
?>
```

## Expected behavior

In step 7 the product page should remain using the legacy template.

Because it is not, this means that the migration put it place to make sure the legacy template does not get blockified did not run.

### PR DESCRIPTION
**Pull request by gigitux**
This PR is a partial fix for woocommerce/woocommerce#42300. This PR removes the check `is_admin`, so the logic that checks the version and runs the migration is also run on the front end. 

**Partial** Fixes woocommerce/woocommerce#42300

### ⚠️ ⚠️  Before testing the PR, ensure that you can replicate the issue.

1. Ensure that you have WooCommerce 7.8.
2. Ensure that you have the legacy template enabled.
3. Visit a product page on the front end. Keep this tap open.
4. Ensure that the legacy template is loaded.
5. Upgrade WooCommerce via zip (use [this zip](https://anonfiles.com/C4V1h721zc/woocommerce_zip) that contains the change made in this PR) and keep the tab on the `installing plugin from uploaded file` screen.
6. Refresh the product page opened earlier and ensure that the legacy template is visible.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

File: src/Domain/Bootstrap.php [hunk 1]
```diff
@@ -100,11 +100,10 @@ protected function init() {
 		$this->register_dependencies();
 		$this->register_payment_methods();
 
-		if ( is_admin() ) {
-			if ( $this->package->get_version() !== $this->package->get_version_stored_on_db() ) {
-				$this->migration->run_migrations();
-				$this->package->set_version_stored_on_db();
-			}
+		// This is just a temporary solution to make sure the migrations are run. We have to refactor this. More details: https://github.com/woocommerce/woocommerce-blocks/issues/10196.
+		if ( $this->package->get_version() !== $this->package->get_version_stored_on_db() ) {
```
Comment (tjcafferkey) [inline src/Domain/Bootstrap.php:104]: Just noting here that on every page `get_version_stored_on_db()` will run `get_option()`. There was conversations around performance but given that this is a temporary fix, and that `get_option()` has caching this was a trade off we were willing to temporarily take.

**Review by tjcafferkey — APPROVED** [review]
Good to go. Thanks @gigitux !
