### PR TITLE
Fix: Make Active Filters work with PHP templates

### LINKED ISSUE #6138: Make Active Filters work with PHP templates
Blocked by #6135, #6136 or #6137.

Currently, it's not possible to use the Active Filters block with PHP templates. That's because that block is designed to only work with the All Products block.

This issue is about updating it, so it can work with the Shop catalog template.

Take into account currently there isn’t a widget equivalent, so it might require some changes in WC core in order to get this block working with PHP templates. (That's why the estimate of this issue is higher than the one from similar issues)

## To reproduce

1. With a block theme, go to Appearance > Editor > Template > Product Catalog.
2. Add the Active Filters block above the product grid.
3. Remove some of the selected values in the filter block
4. Notice the products in the product grid don't update.

## Expected behavior

The products in the product grid should update based on the removed filters.

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #6138

This PR makes the Active Filters work with PHP templates. The idea is to update the current URL to remove the corresponding argument when users remove it from the Active Filters Block.

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
### Manual Testing

How to test the changes in this Pull Request:

1. With a block theme, go to Edit Site > Product Catalog.
2. Add `Active Product Filters`, `Filter Products by Stock`, `Filter Products by Attribute`, `Filter Products by Price` blocks to the template.
3. Go to the shop page on the front end.
4. Select some filters, see the page reload and the selected filters appear in the Active Products Filters block.
5. Remove an arbitrary filter, see the page reload and the removed filter doesn't appear in the Active Product Filters block. See the filtered product results updates accordingly.

### User Facing Testing
These are steps for user testing (where "user" is someone interacting with this change that is not editing any code).
* [x] Same as above, or
* [ ] See steps below.

### Changelog

> Add PHP templates support to the Active Product Filters block.

### CODE REVIEW

File: assets/js/blocks/active-filters/active-attribute-filters.js [hunk 1]
```diff
@@ -46,6 +47,11 @@ const ActiveAttributeFilters = ( {
 
 	const attributeLabel = attributeObject.label;
 
+	const filteringForPhpTemplate = getSetting(
```
Comment (tjcafferkey) [inline assets/js/blocks/active-filters/active-attribute-filters.js]: Shall we update this to use `getSettingWithCoercion` so its consistent with [other filters](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/blocks/attribute-filter/block.js#L66-L70)?

File: assets/js/blocks/active-filters/block.js [hunk 2]
```diff
@@ -28,6 +32,10 @@ const ActiveFiltersBlock = ( {
 	attributes: blockAttributes,
 	isEditor = false,
 } ) => {
+	const filteringForPhpTemplate = getSetting(
```
Comment (tjcafferkey) [inline assets/js/blocks/active-filters/block.js]: Shall we update this to use `getSettingWithCoercion` so its consistent with [other filters](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/blocks/attribute-filter/block.js#L66-L70)?

File: assets/js/blocks/stock-filter/block.js [hunk 3]
```diff
@@ -243,12 +243,8 @@ const StockStatusFilterBlock = ( {
 	useEffect( () => {
 		if ( filteringForPhpTemplate ) {
 			setChecked( checked );
-			// Only automatically redirect if the filter button is not active.
-			if ( ! blockAttributes.showFilterButton ) {
-				redirectPageForPhpTemplate( checked );
-			}
```
Comment (dinhtungdu) [inline assets/js/blocks/stock-filter/block.js:249]: @tjcafferkey in my test, we only need the call of `redirectPageForPhpTemplate` inside the `onSubmit`. When the filter button is disabled, `onSubmit` is called every time the checked value changes.

Comment (tjcafferkey) [reply assets/js/blocks/stock-filter/block.js:249]: I get the same results in my tests too thanks for correcting this.

**Review by tjcafferkey — APPROVED** [review]
This works great with all the filters and the code LGTM. Thanks for working on this @dinhtungdu !

**Comment by dincas** [comment]
> 1. Edit Site > Product Catalog

Where can I find "Edit Site> Product Catalog"?
I searched for my WordPress but didn't find it.

Thank you

**Comment by dinhtungdu** [comment]
> Where can I find "Edit Site> Product Catalog"?

@dincas Are you using a block theme? If not, you can install and activate Twenty Twenty-Two, then you can find Edit Site under the Appearance menu in the admin dashboard.

**Comment by tjcafferkey** [comment]
@dincas you must have a block theme active such as Twenty Twenty-Two and then you will see a sub-menu item titled "Editor" under the Appearance menu item.

See my video below.

https://user-images.githubusercontent.com/8639742/166432176-b0871561-01c5-458c-8940-0327108fcaf5.mp4

**Comment by dincas** [comment]
> @dincas you must have a block theme active such as Twenty Twenty-Two and then you will see a sub-menu item titled "Editor" under the Appearance menu item.
> 
> See my video below.
> 
>  product-catalog.mp4

Thank for fast reply.
I use WoodMart theme and i don't see Editor!
No Editor

**Comment by dincas** [comment]
> > Where can I find "Edit Site> Product Catalog"?
> 
> @dincas Are you using a block theme? If not, you can install and activate Twenty Twenty-Two, then you can find Edit Site under the Appearance menu in the admin dashboard.

I'm using WoodMart theme

**Comment by tjcafferkey** [comment]
>I use WoodMart theme and i don't see Editor!

@dincas it looks like this theme is _not_ a block theme so you will not have access to the new Site Editor feature that is available only with block themes.

**Comment by dincas** [comment]
> > I use WoodMart theme and i don't see Editor!
> 
> @dincas it looks like this theme is _not_ a block theme so you will not have access to the new Site Editor feature that is available only with block themes.

Thank you...I will find another way
