### PR TITLE
Fix positioning of default locked blocks in the editor and frontend

### LINKED ISSUE #4757: When forcing all blocks at once, they will append based o...
When forcing all blocks at once, they will append based on the order they are registered. Introduce formal sorting param.

---
https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/2c9f0473a0dbdf466eafb309144058d0cee53b4f/assets/js/blocks/cart-checkout/checkout/inner-blocks/register-components.ts#L29-L40
---
###### :rocket: This issue was generated by the [automations bot](https://github.com/woocommerce/automations) based on a `todo` comment in 2c9f0473a0dbdf466eafb309144058d0cee53b4f when #4745 was merged. cc @mikejolley

### PR DESCRIPTION
**Pull request by mikejolley**
Requesting @senadir to look at this given his familiarity with block locking.

This PR updates the frontend handling of locked blocks to include all core/default blocks in the template. This removes the risk that forced blocks could be appended in a random order, because they will instead be inserted in template order. Fixes #4757 (Test Case 1)

On the editor side, this PR fixes the positioning of forced blocks if they are removed (Test Case 2) by comparing the default template to the inner blocks.

Fixes #4757

### Testing

How to test the changes in this Pull Request:

#### Test Case 1

For the frontend blocks, we need to have no HTML saved.  For the purpose of testing, you can cheat by adding some code on this line:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/BlockTypes/Checkout.php#L87

Add:

```php
$content = '<div class="wp-block-woocommerce-checkout"></div>';
```

Then view the checkout block on the frontend. Confirm all default blocks are visible/inserted in the correct positions.

#### Test Case 2

1. In the editor, go to a page with the Checkout block
2. Switch to code view
3. Delete the "contact information" block by removing the HTML for that block
4. Switch back to the visual editor. 
5. The contact information block should be back, in the correct position

Before this fix, it would be appended at the end of the layout in the incorrect position.

### CODE REVIEW

File: assets/js/blocks/cart-checkout/checkout/edit.tsx [hunk 1]
```diff
@@ -130,46 +130,9 @@ export const Edit = ( {
...
-				[
-					'woocommerce/checkout-order-summary-block',
-					{
-						showRateAfterTaxName,
-					},
-					[],
-				],
-			],
-		],
+	const defaultTemplate = [
```
Comment (mikejolley) [inline assets/js/blocks/cart-checkout/checkout/edit.tsx:134]: Moved this template into the inner blocks rather than all defined top level.

File: assets/js/blocks/cart-checkout/checkout/form-step/additional-fields.tsx [hunk 2]
```diff
@@ -21,7 +21,7 @@ export const AdditionalFields = ( {
 
 	useForcedLayout( {
 		clientId,
-		template: allowedBlocks,
+		registeredBlocks: allowedBlocks,
```
Comment (mikejolley) [inline assets/js/blocks/cart-checkout/checkout/form-step/additional-fields.tsx:24]: Rename for clarity.

File: assets/js/blocks/cart-checkout/checkout/inner-blocks/checkout-fields-block/edit.tsx [hunk 3]
```diff
@@ -8,23 +8,57 @@ import { innerBlockAreas } from '@woocommerce/blocks-checkout';
...
+		showReturnToCart,
+		cartPageId,
+	} = useCheckoutBlockContext();
 	const allowedBlocks = getAllowedBlocks( innerBlockAreas.CHECKOUT_FIELDS );
 
 	const {
 		addressFieldControls: Controls,
 	} = useCheckoutBlockControlsContext();
 
+	const defaultTemplate = [
```
Comment (mikejolley) [inline assets/js/blocks/cart-checkout/checkout/inner-blocks/checkout-fields-block/edit.tsx]: This was at the top level. Moved here so we can easily pass it down to useForcedLayout

File: src/BlockTypes/Checkout.php [hunk 4]
```diff
@@ -88,7 +88,24 @@ protected function render( $attributes, $content ) {
...
+					<div data-block-name="woocommerce/checkout-contact-information-block" class="wp-block-woocommerce-checkout-contact-information-block"></div>
+					<div data-block-name="woocommerce/checkout-shipping-address-block" class="wp-block-woocommerce-checkout-shipping-address-block"></div>
+					<div data-block-name="woocommerce/checkout-billing-address-block" class="wp-block-woocommerce-checkout-billing-address-block"></div>
+					<div data-block-name="woocommerce/checkout-shipping-methods-block" class="wp-block-woocommerce-checkout-shipping-methods-block"></div>
+					<div data-block-name="woocommerce/checkout-payment-block" class="wp-block-woocommerce-checkout-payment-block"></div>
+					<div data-block-name="woocommerce/checkout-order-note-block" class="wp-block-woocommerce-checkout-order-note-block"></div>
+					<div data-block-name="woocommerce/checkout-terms-block" class="wp-block-woocommerce-checkout-terms-block"></div>
+					<div data-block-name="woocommerce/checkout-actions-block" class="wp-block-woocommerce-checkout-actions-block"></div>
+					<p>Hi</p>
```
Comment (senadir) [inline src/BlockTypes/Checkout.php]: Hi

File: assets/js/blocks/cart-checkout/checkout/use-forced-layout.ts [hunk 5]
```diff
@@ -1,63 +1,154 @@
...
+			const previousBlockPosition = innerBlocks.findIndex(
+				( { name }: { name: string } ) => name === previousBlock[ 0 ]
+			);
+
+			appendBlock(
+				block,
+				previousBlockPosition > -1
+					? previousBlockPosition + 1
+					: defaultTemplatePosition
+			);
```
Comment (senadir) [inline assets/js/blocks/cart-checkout/checkout/use-forced-layout.ts]: I was following very well, but you lost in me in this section. Can you expand a bit what's happening here?

**Review by senadir — APPROVED** [review]
This is looking good and working well. You missed a `<p>Hi</p>` in the PHP template, and I left a comment.

File: src/BlockTypes/Checkout.php (hunk 4 above)
Comment (mikejolley) [reply src/BlockTypes/Checkout.php]: Hello

asl?

**Comment by senadir** [comment]
Also, should this also be applied to Cart i2.

**Review by senadir — APPROVED** [review]
This is testing and looking fine with Cart i2 as well. :shipit:
