### PR TITLE
Reorganise Columns controls and fix undefined problem in Product Collection settings

### LINKED ISSUE #11561: Product Collection: `undefined` is showing in Settings menu
## Describe the bug

As you can see in screenshot, It's showing undefined:
image

## To reproduce

https://github.com/woocommerce/woocommerce-blocks/assets/16707866/94ad3af3-9a74-46ef-a638-f90fe32df8aa

## Expected behavior

Instead of undefined, the name of filter should appear in menu.

### LINKED ISSUE #11925: Product Collection: Rename and reorder "Shrink columns to fit"
### Actions
- [x] Rename it to "Responsive"
- [x] Move it below "Columns" controls
- [x] Change description to "Automatically adjust the number of columns to better fit smaller screens."
- [x] Remove "Max Columns" heading from heading control and always stick to "Columns"

### Screenshot
image

### PR DESCRIPTION
**Pull request by kmanijak**
## What

Improvements to Column controls in Product Collection:

1. Rename "Shrink columns to fit" to "Responsive"
2. Move the setting below "Columns" controls
3. Change description to "Automatically adjust the number of columns to better fit smaller screens."
4. Remove "Max Columns" heading from heading control and always stick to "Columns"
5. Fix `undefined` option that occurred in Product Collection's Inspector Controls settings

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/11561
Fixes https://github.com/woocommerce/woocommerce-blocks/issues/11925

## Why

- points 1. - 4. are UX Improvements raised after product review
- point 5. is a bug fix

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Go to Editor
2. Add Product Collection block
3. Check Inspector Controls
4. "Columns" and "Responsive" look like in the AFTER image:

| Before | After |
| ------ | ----- |
|   image     |   image    |

6. Click three dots next to "Settings"
7. There's no `undefined` entry, but "Columns" and "Responsive" like in the AFTER image:

| Before | After |
| ------ | ----- |
|   image     |   
image
    |

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:

* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:

* [ ] This PR has a UI change and has been cross-browser tested at different viewport sizes on both the frontend and in the editor.
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Product Collection: Rename "Shrink columns to fit" option to "Responsive" and improve the setting arrangement

### CODE REVIEW

File: assets/js/blocks/product-collection/inspector-controls/columns-control.tsx [hunk 1]
```diff
@@ -63,33 +55,35 @@ const ColumnsControl = ( props: DisplayLayoutToolbarProps ) => {
 	return showColumnsControl ? (
 		<>
 			<ToolsPanelItem
+				label={ columnsLabel }
 				hasValue={ () =>
-					defaultLayout?.shrinkColumns !== shrinkColumns
+					defaultLayout?.columns !== columns ||
+					defaultLayout?.type !== type
```
Comment (imanish003) [inline assets/js/blocks/product-collection/inspector-controls/columns-control.tsx]: I don't think the "defaultLayout?.type !== type" condition is necessary. In my view, "defaultLayout?.columns !== columns" should suffice. no?

**Review by imanish003 — APPROVED** [review]
Thanks for quickly making these changes & also fixing the undefined issue I reported. I tested the changes & everything is working as expected. 

I just left a minor suggestion, but pre-approving the PR 🚀 🚢 

**Sidenote:** Playwright tests are failing.

File: assets/js/blocks/product-collection/inspector-controls/columns-control.tsx (hunk 1 above)
Comment (kmanijak) [reply assets/js/blocks/product-collection/inspector-controls/columns-control.tsx]: Good catch, I applied your suggestion!
