### PR TITLE
Blockified Templates: Improve migration logic

### LINKED ISSUE #10413: Migration Blockified Template: The installation of WooCommerce Blocks plugin restore the no-blockified templates
## Describe the bug

The installation of WooCommerce Blocks plugin restore the no-blockified templates

## To reproduce

1. Install WC Core 7.9.
2. Ensure that you have the blockified templates.
3. Install WooCommerce Blocks.
4. The templates aren’t blockified anymore.

## Expected behavior

The templates have to be blockified after the WooCommerce Blocks installation.

### PR DESCRIPTION
**Pull request by gigitux**
@kmanijak and I worked on this PR.

This PR refactors the migration logic to fix woocommerce/woocommerce-blocks#10413. We improved to check to ensure that the migration is executed **ONLY** during the update from a WooCommerce version < 7.9.

image

Fixes woocommerce/woocommerce-blocks#10413

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

Zip files:
- WooCommerce 7.8: https://downloads.wordpress.org/plugin/woocommerce.7.8.2.zip
- WooCommerce 7.9: https://downloads.wordpress.org/plugin/woocommerce.7.9.0.zip
- WooCommerce 8.0 (with a version of WC Blocks that includes this fix:): https://anonfiles.com/16O1D75bzd/woocommerce_zip

##### Upgrade from WooCommerce Core 7.8 to WooCommerce 7.9 to WooCommerce 8.0
1. Install WooCommerce Core 7.8.
2. Ensure that the templates aren't blockified.
3. Upgrade to WooCommerce Core 7.9.
4. Ensure that the templates aren't blockified.
5. Upgrade to WooCommerce Core 8.0
6. Ensure that the templates aren't blockified.

##### Upgrade from WooCommerce Core 7.8  to WooCommerce 8.0
1. Install WooCommerce Core 7.8.
2. Ensure that the templates aren't blockified.
3. Upgrade to WooCommerce Core 8.0
4. Ensure that the templates aren't blockified.

##### Upgrade from WooCommerce Core 7.9 to WooCommerce 8.0
1. Install WooCommerce Core 7.9.
2. Ensure that the templates are blockified.
3. Upgrade to WooCommerce Core 8.0
4. Ensure that the templates are blockified.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Blockified templates: Improve migration logic.

### CODE REVIEW

File: src/Migration.php [hunk 1]
```diff
@@ -28,10 +28,14 @@ class Migration {
 	 */
 	public function run_migrations() {
 		$current_db_version = get_option( Options::WC_BLOCK_VERSION, '' );
+		$schema_version     = get_option( 'wc_blocks_db_schema_version', '' );
 
 		// This check is necessary because the version was not being set in the database until 10.3.0.
+		// Checking wc_blocks_db_schema_version determines if it's a fresh install (value will be empty)
```
Comment (nefeline) [inline src/Migration.php:34]: I would suggest exploring an alternative route here, as the assumption that `wc_blocks_db_schema_version` is empty on fresh installs is a bit fragile. This option is updated whenever [`maybe_create_tables`](https://github.com/woocommerce/woocommerce-blocks/blob/e59611bbccda1cf5133d64f787fc8d92d9161b06/src/Installer.php#L73) is triggered and this method is hooked to `'admin_init'`, which is fired whenever an admin screen or script is being initialized, so fresh installs will have the default 0 value updated to 260 whenever the table creation is complete.

Comment (gigitux) [reply src/Migration.php:34]: I agree that checking `wc_blocks_db_schema_version` isn't the best approach, but unfortunately, it seems that it is the only way to check if it is a new installation.

This code will be executed before that `admin_init`  is triggered. Empty returns true if you pass 0 or "".

Comment (nefeline) [reply src/Migration.php:34]: > This code will be executed before that admin_init  is triggered. Empty returns true if you pass 0 or "".

This option is not deleted from the DB when the plugin is removed, so if someone at some point in the past had Woo and/or Woo blocks up and running, removed them, and now enabled them again, `$this->wc_blocks_update_1030_blockified_product_grid_block();` will be triggered and cause the same problem.

> I agree that checking wc_blocks_db_schema_version isn't the best approach, but unfortunately, it seems that it is the only way to check if it is a new installation.

Just to clarify, is the goal here to run the migration to all users that already had Woo installed (keeping the classic template) while at the same time displaying the blockified template for brand-new users?

Comment (gigitux) [reply src/Migration.php:34]: > > This code will be executed before that admin_init  is triggered. Empty returns true if you pass 0 or "".
> 
> This option is not deleted from the DB when the plugin is removed, so if someone at some point in the past had Woo and/or Woo blocks up and running, removed them, and now enabled them again, `$this->wc_blocks_update_1030_blockified_product_grid_block();` will be triggered and cause the same problem.
> 

I think that it is fine since it is an uncommon use case. The user has an old version of WC Core. Remove it. Install the new one. The user will have the classic templates. 

> > I agree that checking wc_blocks_db_schema_version isn't the best approach, but unfortunately, it seems that it is the only way to check if it is a new installation.
> 
> Just to clarify, is the goal here to run the migration to all users that already had Woo installed while at the same time displaying the blockified template for brand-new users?

Yes.

Comment (nefeline) [reply src/Migration.php:34]: > Yes.

Thanks for confirming. I think that one way to reliably ensure a store is new when WooCommerce Blocks is enabled, is by looking for the existence of products or orders: a store that is brand new won't have at least one of those. Here's a loose example:

```php
$show_default_blockified_template = get_option( 'example_should_display_blockified_template', false );
if ( $show_default_blockified_template ) {
	return;
} else {
	$store_has_products = wc_get_products( array( 'limit' => 1 ) );
	$store_has_orders = wc_get_orders( array( 'limit' => 1 ) );

	if ( ! $store_has_products || ! $store_has_orders ) {
		update_option( 'example_should_display_blockified_template', true );
	} else {
		return;
	}
}
```

This way we have something more robust to rely on instead of the value of a DB migration to determine if the blockified template should be displayed or not. Also, notice that there's no condition to change the option back to false at any point in execution: this ensures that if someone enabled the plugin on a brand new store and after that created products/received orders, they won't have the legacy template accidentally displayed again.

Comment (gigitux) [reply src/Migration.php:34]: This is a good idea, but at the same time, if the user updates from WooCommerce Core 7.8 to WooCommerce Core 7.9 and doesn't have any products, we want to keep it using the classic template. This is the migration strategy that we have communicated and for this reason, I would not change the logic.

> This way we have something more robust to rely on instead of the value of a DB migration to determine if the blockified template should be displayed or not.

Not sure why you are saying this. We have full control of when the value is inserted in the DB, so I don't see any particular issue.

Comment (nefeline) [reply src/Migration.php:34]: regarding: 

> I think that it is fine since it is an uncommon use case. The user has an old version of WC Core. Remove it. Install the new one. The user will have the classic templates.

and:

> Not sure why you are saying this. We have full control of when the value is inserted in the DB, so I don't see any particular issue.

This migration is triggered on `'plugins_loaded'` (which is fired once activated plugins have loaded), so if someone installed the plugin on a new store, did some changes, deactivated the plugin and activated again, the value of `wc_blocks_db_schema_version` might not be 0 anymore (as all it takes to update this is accessing the WP admin page, firing the `'admin_init'` hook). One more example of how fragile this affirmation is:

> Checking wc_blocks_db_schema_version determines if it's a fresh install (value will be empty)

I don't agree with relying on this option for this and the aforementioned reasons.

> if the user updates from WooCommerce Core 7.8 to WooCommerce Core 7.9 and doesn't have any products, we want to keep it using the classic template

why?

Comment (gigitux) [reply src/Migration.php:34]: > This migration is triggered on `'plugins_loaded'` (which is fired once activated plugins have loaded), so if someone installed the plugin on a new store, did some changes, deactivated the plugin and activated again, the value of `wc_blocks_db_schema_version` might not be 0 anymore (as all it takes to update this is accessing the WP admin page, firing the `'admin_init'` hook). One more example of how fragile this affirmation is:

True, but this is the entire condition: 

```
if ( ! empty( $schema_version ) && ( empty( $current_db_version ) ) ) {
```

So, there is an additional check.

> why?

We worked on the migration strategy one year ago when the "blockified templates" were very far from ready. I think that we didn't think about :( 

I'm open to refactoring this, but since the migration logic has already been deployed and no issue has been reported, I would avoid this change and fix the current logic. Furthermore, in the following months, we will remove [it](https://github.com/woocommerce/woocommerce-blocks/pull/10415/files#diff-7a149914e4cec2dfd6fd142ebb3653fb186d871e694aea733ed1a14d1ec0b7f9R37-R40).

cc @kmanijak thoughts?

Comment (nefeline) [reply src/Migration.php:34]: > We worked on the migration strategy one year ago when the "blockified templates" were very far from ready. I think that we didn't think about :(

Thanks for the explanation. Regarding:

> if the user updates from WooCommerce Core 7.8 to WooCommerce Core 7.9 and doesn't have any products, we want to keep it using the classic template

This PR is planned to be released as part of version 10.6.3, right? Any changes made here shouldn't impact the update from version 7.8 to 7.9, correct?

Comment (gigitux) [reply src/Migration.php:34]: > This PR is planned to be released as part of version 10.6.3, right? Any changes made here shouldn't impact the update from version 7.8 to 7.9, correct?

Right, but it will impact the update from version 7.8 to 8.0.

Comment (nefeline) [reply src/Migration.php:34]: > Right, but it will impact the update from version 7.8 to 8.0.

Do you mind sharing an example of a real problem a user would have by updating from version 7.8 to 8.0 and allowing them to see the blockified template right away if they are a new store? I saw your explanation over here:

> We worked on the migration strategy one year ago when the "blockified templates" were very far from ready. I think that we didn't think about :(

but to be honest it is still not clear why we still want to display the classic template for such cases?

Comment (kmanijak) [reply src/Migration.php:34]: >  it is still not clear why we still want to display the classic template for such cases?

The rule that was followed since the blockified templates were implemented (couple of months and versions ago) was:
- use blockified template in new stores
- respect the current setup of the existing stores that update the version

Considering there's time pressure to include that change in WC Core, I wouldn't start changing that logic at this very moment and include the fix.

---

Regarding the discussion above I would consider adding another criterion, except for the number of products or orders in store. If we were to go that way, I think we would have to also check if the Product Archive templates were edited. There may be other cases too. I'm not against refactoring or changing the rules, but for now, I think sticking with the rules above (and then the solution in this PR) keeps it simple and covers the case that we found broken.

Comment (nefeline) [reply src/Migration.php:34]: > The rule that was followed since the blockified templates were implemented (couple of months and versions ago) was:

> use blockified template in new stores
> respect the current setup of the existing stores that update the version

yep! But @gigitux is saying that there's an exception to this rule and that we should display the classic template even for new stores when updating from version 7.8 to 7.9 and from 7.8 to 8.0, that's the part that no explanation was provided at all.

There are many technical limitations with the solution provided here, and I don't feel comfortable with approving it for this reason, so I'm withdrawing my review.

**Review by nefeline — CHANGES_REQUESTED** [review]
I don't feel comfortable with approving this PR in its current shape and form, given all the technical limitations this solution has. See more details about the problems and the proposed alternative solution at https://github.com/woocommerce/woocommerce-blocks/pull/10415#discussion_r1280372021. 

I'm glad to circle back for another pass if changes are made. Otherwise, I withdraw my review.

File: src/Migration.php (hunk 1 above)
Comment (gigitux) [reply src/Migration.php:34]: > yep! But @gigitux is saying that there's an exception to this rule and that we should display the classic template even for new stores when updating from version 7.8 to 7.9 and from 7.8 to 8.0, that's the part that no explanation was provided at all.

If you upgrade the version even if you don't have products, it means that the store isn't new:

image

**Comment by gigitux** [comment]
> I don't feel comfortable with approving this PR in its current shape and form, given all the technical limitations this solution has. See more details about the problems and the proposed alternative solution at [#10415 (comment)](https://github.com/woocommerce/woocommerce-blocks/pull/10415#discussion_r1280372021).
> 
> I'm glad to circle back for another pass if changes are made. Otherwise, I withdraw my review.

Thanks for the review! I'm ready to update the logic, but before proceeding, it would be great to have feedback from @tjcafferkey, who checked the migration strategy code for another issue (#10196).


I don't agree that we should change the migration strategy logic for several reasons:
- We know the current logic works fine (except for this bug). An update could be a risk.
- We already communicated the logic of the migration strategy to users and 3rd party developers. Changing it could create confusion.
- This logic is necessary because, for the old version of WooCommerce Blocks (<10.4.0), the version of the plugin isn't saved in the database. In the following months, we will remove this logic.

**Comment by nefeline** [comment]
> We know the current logic works fine (except for this bug). An update could be a risk.

Just to make it super clear, what is being questioned on https://github.com/woocommerce/woocommerce-blocks/pull/10415#discussion_r1280372021 is the changes made on this PR, not the current implementation.

> We already communicated the logic of the migration strategy to users and 3rd party developers. Changing it could create confusion.

The proposal is not to change the pre-existing migration logic: the proposal is to preserve it exactly the same, but with a more robust implementation that isn't sensible to plugin activation/deactivation and/or removal.

> This logic is necessary because, for the old version of WooCommerce Blocks (<10.4.0), the version of the plugin isn't saved in the database. In the following months, we will remove this logic.

This part is still very obscure to me as the version of the plugin shouldn't be part of the equation to determine if a store is new or not.

**Comment by gigitux** [comment]
There is a misunderstanding about the definition of "new store".

For the current logic, "new store" means a "fresh installation of WooCommerce", so for this reason, the version of the plugin is essential.

For your logic, "new stores" means a "store without any products/orders".

> The proposal is not to change the pre-existing migration logic: the proposal is to preserve it exactly the same, but with a more robust implementation that isn't sensible to plugin activation/deactivation and/or removal.

Not really. With the current logic, if a user upgrades a store (without any products/orders) from WC 7.8 to WC 8.0 will have the classic templates. Instead, with your logic, the templates will be blockified. 

It is something that I would not do since the migration strategy has already been communicated.

cc @kmanijak Please, correct me if I'm wrong!

File: src/Migration.php (hunk 1 above)
Comment (nefeline) [reply src/Migration.php:34]: > If you upgrade the version even if you don't have products, it means that the store isn't new:

This graphic is just a representation of the current logic & unfortunately, doesn't answer my question: nothing in it explains why the plugin version is being used to determine if a store is new or not. And to reinforce my comment over here: https://github.com/woocommerce/woocommerce-blocks/pull/10415#issuecomment-1661825951 there's no proposal to change what is represented in this image.

Comment (gigitux) [reply src/Migration.php:34]: We started saving the version of WC Blocks in the database only with WooCommerce Blocks 10.3.0 release.

So, if this condition below is true, it means that it isn't a new installation because:
- $schema_version is already set
- $current_db_version is empty, so it means that the user is upgrading from a version of WC Blocks < 10.3.0
```
! empty( $schema_version ) && ( empty( $current_db_version )
```

Comment (kmanijak) [reply src/Migration.php:34]: > nothing in it explains why the plugin version is being used to determine if a store is new or not.

I think "fresh WooCommerce installation" tries to answer it. It may be the insufficient choice of words, but this diagram was supposed to represent this table from [this PR](https://github.com/woocommerce/woocommerce-blocks/pull/6538):

image

which clearly differentiates "New installation" from "Upgrade" and that's what the first condition in the diagram was supposed to represent ("Fresh installation" meaning "New installation" and not "Upgrade"). And we'd like to preserve that logic. Does that help answer the concern?

**Comment by nefeline** [comment]
> Not really. With the current logic, if a user upgrades a store (without any products/orders) from WC 7.8 to WC 8.0 will have the classic templates. Instead, with your logic, the templates will be blockified.

@gigitux can you clear out the following, please?

First, you mentioned there was an exception for updating from version 7.8 to 7.9, but this PR doesn't touch any of those versions (this is planned for WC 8.0); after that you affirmed that this limitation also applies to upgrading from 7.8 to 8.0. 

This question I did earlier is still pending:

> Do you mind sharing an example of a real problem a user would have by updating from version 7.8 to 8.0 and allowing them to see the blockified template right away if they are a new store?

I would appreciate a concrete and technical explanation here. Where are these decisions being made? Is there any convo I missed where it was clearly discussed that we should port over this decision to WooCommerce version 8 that I'm unaware of? 

I would also appreciate any link of discussion when this decision of preserving the classic template for new stores when upgrading from version 7.8 to version 7.9 was made.

**Comment by gigitux** [comment]
> First, you mentioned there was an exception for updating from version 7.8 to 7.9, but this PR doesn't touch any of those versions (this is planned for WC 8.0); after that you affirmed that this limitation also applies to upgrading from 7.8 to 8.0.

This PR keeps the logic as it is, but if it fixes a bug when the user updates from 7.9 -> 8.0 or the WC Blocks is enabled, the user disables it and enables it again.

> Do you mind sharing an example of a real problem a user would have by updating from version 7.8 to 8.0 and allowing them to see the blockified template right away if they are a new store?

As I said above, I don't see any real problem issue. Also, I agreed with your idea, but we didn't think about it when we worked on this migration strategy. You are proposing the update the logic. The downsides that I see are explained in [this comment](https://github.com/woocommerce/woocommerce-blocks/pull/10415#issuecomment-1661801440).

> The proposal is not to change the pre-existing migration logic: the proposal is to preserve it exactly the same, but with a more robust implementation that isn't sensible to plugin activation/deactivation and/or removal.

This is not true, it doesn't preserve the same behavior as I wrote [here](https://github.com/woocommerce/woocommerce-blocks/pull/10415#issuecomment-1661849323).

> I would appreciate a concrete and technical explanation here. Where are these decisions being made? Is there any convo I missed where it was clearly discussed that we should port over this decision to WooCommerce version 8 that I'm unaware of?

I don't see a huge benefit of changing the current logic. It could create confusion, especially for 3rd party developers.

> I would also appreciate any link of discussion when this decision of preserving the classic template for new stores when upgrading from version 7.8 to version 7.9 was made.

Sure:

https://github.com/woocommerce/woocommerce-blocks/pull/6538
pdnLyh-1ne-p2

**Review by tjcafferkey — APPROVED** [review]
I appreciate the passion around this proposed change and its impact, and I also acknowledge that there are some circumstances that may require further thought and consideration. There appears to be a misalignment between how some of us distinguish between a fresh install vs upgrade vs unused (no orders, no products) store.

Given that this migration has run for all stores upgrading from 7.8 > 7.9 already and that this check will be removed in the near future, furthermore the time sensitive nature of this since its currently blocking two releases I am going to approve the PR and we can discuss this further in a more appropriate setting away from the pressures of a release.

Again, I appreciate and value of all the differing opinions and I’m glad we work in a team where we can express them between each other.

File: src/Migration.php (hunk 1 above)
Comment (nefeline) [reply src/Migration.php:34]: > And we'd like to preserve that logic. Does that help answer the concern?

Thanks @kmanijak , it does represent what the current implementation is, but unfortunately, I couldn't find any explanation why this decision was made on that PR =/. 

Either way, we still have all the aforementioned problems to clear out, as the solution provided here does not apply to all use-case scenarios, with very important limitations as flagged on https://github.com/woocommerce/woocommerce-blocks/pull/10415#discussion_r1280372021 , https://github.com/woocommerce/woocommerce-blocks/pull/10415#discussion_r1280425734 and  https://github.com/woocommerce/woocommerce-blocks/pull/10415#discussion_r1280656357 .

Since the decision was to proceed with this work for the patch release, I'll propose circling back to solve these problems in our next cycle.

Comment (kmanijak) [reply src/Migration.php:34]: > but unfortunately, I couldn't find any explanation why this decision was made on that PR =/.

Unfortunately, I cannot provide more context, as this PR was made way before I joined the project. It's possible the PR only represents the outcome of other discussions but I can't justify that as I wasn't there 😅. What I was trying to say is that the table represents the logic present in the project for months now and this PR aims to fix a specific scenario preserving those rules.

> Since the decision was to proceed with this work for the patch release, I'll propose circling back to solve these problems in our next cycle.

Agree! 👍

**Comment by nefeline** [comment]
> As I said above, I don't see any real problem issue. Also, I agreed with your idea, but we didn't think about it when we worked on this migration strategy. You are proposing the update the logic. The downsides that I see are explained in https://github.com/woocommerce/woocommerce-blocks/pull/10415#issuecomment-1661801440.

Thanks: I already shared my response to these concerns over here https://github.com/woocommerce/woocommerce-blocks/pull/10415#issuecomment-1661825951 . Also, since the decision was to merge this PR as-is for the patch release, we now have a few more limitations to circumvent. As flagged over here https://github.com/woocommerce/woocommerce-blocks/pull/10415#discussion_r1281705853 , I'll propose working on solving these problems in our next cycle.

> This is not true, it doesn't preserve the same behavior as I wrote https://github.com/woocommerce/woocommerce-blocks/pull/10415#issuecomment-1661849323.

It does for the vast majority of cases, but this PR is not solving the problem for all users either.

> I don't see a huge benefit of changing the current logic. It could create confusion, especially for 3rd party developers.

I see many limitations and flaws with the current implementation on this PR, not the logic for the migrations. IMO we can maintain the current logic unchanged, the critical part is getting rid of all problems introduced here, as flagged earlier on https://github.com/woocommerce/woocommerce-blocks/pull/10415#discussion_r1281705853 . 

> Sure:

Thanks!

**Review by kmanijak — COMMENTED** [review]
Re-tested scenarios:

_(When mentioning WC Core 8.0 that means build including changes from this PR)._

Scenario| Outcome
-- | --
Updating WC Core 7.8 -> 7.9 -> 8.0  | Classic templates ✅ 
Updating WC Core 7.8 -> 8.0  | Classic templates ✅ 
Updating WC Core 7.9 -> 8.0 | Blockified templates ✅
Updating WC Core 7.8 -> 7.9 (blockifying template manually) -> 8.0 | Blockified templates ✅
WC Core 7.9 and activate WC Blocks including changes from this PR | Blockified templates ✅
Deactivate WC Blocks from the previous scenario | Revert to Classic templates. We understand why that happens, the explanation below.

In the last scenario when we deactivate the newer version of WC Blocks, [this condition](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/Domain/Bootstrap.php#L105) is true - versions of WC Blocks are different:

```
if ( $this->package->get_version() !== $this->package->get_version_stored_on_db() ) {
```

and the migration is run with THE OLD logic (the one in `trunk`) which causes the classic templates to be loaded.

Along with WC Core 8.0, we may consider a patch update to WC Core 7.9 as well to fix that problem.

**Comment by gigitux** [comment]
I re-tested the PR and I can confirm the @kmanijak results. Also, I tested another two scenarios:

Scenario| Outcome
-- | --
WC Core 8.0 and activate WC Blocks including changes from this PR | Blockified templates ✅
Deactivate WC Blocks from the previous scenario | Blockified templates ✅

**Comment by gigitux** [comment]
Since that @tjcafferkey and @kmanijak tested and approved the PR, I will merge this PR. Thanks for the discussion and feedback!

**Comment by nefeline** [comment]
Issue created to address the aforementioned technical limitations: https://github.com/woocommerce/woocommerce/issues/42268
