### PR TITLE
Mini-cart: add setting to not render the block on the cart & checkout pages

### LINKED ISSUE #7760: Show mini cart also on checkout page
## Describe the bug
Showing a mini cart on the checkout page isn't necessarily a bad idea, often it is used as a go-back button, for users to make amends to their shopping carts.
Currently the behavior cannot be changed by an option or filter, on the checkout page the mini cart will be hidden.

Luckily it is only [hidden using inline CSS](https://github.com/woocommerce/woocommerce-blocks/blob/3f7ffceba3a5a8137f04b5860983382df8c441b7/src/BlockTypes/MiniCart.php#L388-L390), so it can be still displayed by using checkout-page-specific CSS.

## To reproduce
1. Place a mini cart onto a site so it also appears on the checkout page.
2. Visit the check out page, note that the min cart is missing there.
If you want to make changes to the cart, you can't do this by using the mini cart as a go-back link, 
rather you have to use the browser back button (which should be avoided and would be avoidable here).

## Expected behavior
Mini cart either is also shown on the check out page, or an option and/or filter is also provided by it, that allows toggling this behavior for specific pages.

### WordPress (please complete the following information):

-   WordPress version: `6.1.1`
-   Gutenberg version (if installed): `14.6.1`
-   WooCommerce version: `7.1.0`
-   WooCommerce Blocks version: `9.0.0`
-   Site language: `de_DE_formal`/`de_DE` (but not applicable to this issue)
-   Any other plugins installed: (yes, but not applicable to this issue)

### PR DESCRIPTION
**Pull request by albarin**
Currently, the `Mini Cart` is hidden with CSS on the Cart & Checkout pages. As discussed on https://github.com/woocommerce/woocommerce-blocks/issues/7760 we want to give the users the option to not render it at all (not only hide it).
This PR add this setting to the `Mini Cart` block and does not render the block when enabled. The default setting is to render it invisible (same behavior as until now) to not affect existing stores.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/7760
#### User-Facing Testing

**Site Editor**
1. Go to the Site Editor > Template parts and edit the header template to add the `Mini Cart` block. Save.
2. Edit the block and make sure you see the new setting:

Screenshot 2023-03-13 at 16 27 26

3. Make sure the default option is `Hide`.
4. In the store, go to the Cart page and make sure the `Mini Cart` is rendered but invisible. Repeat but for the Checkout page.
5. Go back to the Site Editor, change the `Mini Cart` setting to `Remove`, and save.
6. In the store, go to the Cart page and make sure the `Mini Cart` markup is not rendered at all. Repeat but for the Checkout page.

**Post/page**
1. Create a new post or page.
2. Insert the `Mini Cart`.
3. Make sure the new `Mini Cart in cart and checkout pages` setting does not appear.

### WooCommerce Visibility
* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Comment by albarin** [comment]
@pmcpinto @Aljullu do you have any suggestions for the toggle options and description copy?

File: src/BlockTypes/MiniCart.php [hunk 1]
```diff
@@ -567,4 +571,15 @@ public function register_empty_cart_message_block_pattern() {
...
 	}
+
+	/**
+	 * Returns whether the mini cart should be rendered or not.
+	 *
+	 * @param array $attributes Block attributes.
+	 *
+	 * @return bool
+	 */
+	public function shouldNotRenderMiniCart( array $attributes ) {
```
Comment (Aljullu) [inline src/BlockTypes/MiniCart.php]: Should we use snake case for PHP methods?

File: assets/js/blocks/mini-cart/index.tsx [hunk 2]
```diff
@@ -61,6 +61,10 @@ const settings: BlockConfiguration = {
 			type: 'boolean',
 			default: false,
 		},
+		makeInvisibleInCartAndCheckout: {
+			type: 'boolean',
+			default: true,
+		},
```
Comment (Aljullu) [inline assets/js/blocks/mini-cart/index.tsx]: I'm not sure about this, but given the discussion in #7760, I wonder if we should make this a `string` so it can support more options in the future. (I know we don't have any plans right now to add more options, but in case some day we do, it would make our lives easier than if it's a boolean, what do you think?) :thinking:

**Review by Aljullu — COMMENTED** [review]
I left a couple of comments in the code, but overall LGTM. I also tested it and it works perfectly. :ok_hand: 

> @pmcpinto @Aljullu do you have any suggestions for the toggle options and description copy?

It's a tricky one. An alternative would be to name the two options as "invisible" and "hidden", but I don't know if it makes things any easier to understand. Or to replace `Don't render` with `Don't display`.

Another option would be to use the explanation text below the toggle to explain what each options does. We seem to do it in some blocks, but I'm not sure if it's a correct GB pattern. :confused: 

[Enregistrament de pantalla des de 2023-03-10 14-13-45.webm](https://user-images.githubusercontent.com/3616980/224325623-64df4926-8f46-4484-b099-288dde628a33.webm)

File: src/BlockTypes/MiniCart.php (hunk 1 above)
Comment (albarin) [reply src/BlockTypes/MiniCart.php]: True, fixed 🙏

File: assets/js/blocks/mini-cart/index.tsx (hunk 2 above)
Comment (albarin) [reply assets/js/blocks/mini-cart/index.tsx]: Yeah, I was in doubt about it as well, I think you are right, it makes sense to make it more future-proof, I'll change it.

**Comment by albarin** [comment]
> It's a tricky one. An alternative would be to name the two options as "invisible" and "hidden", but I don't know if it makes things any easier to understand. Or to replace `Don't render` with `Don't display`.

More thoughts: what about `Hide` and `Remove`? 🤔  

> Another option would be to use the explanation text below the toggle to explain what each options does. We seem to do it in some blocks, but I'm not sure if it's a correct GB pattern. 😕

Yeah, that'd be useful, but I remember I changed that behavior some time ago on another toggle, so maybe it's something we are trying to avoid, not sure;

**Comment by pmcpinto** [comment]
> More thoughts: what about Hide and Remove? 🤔

 I was going to suggest this as an alternative :)

**Review by Aljullu — APPROVED** [review]
> More thoughts: what about `Hide` and `Remove`? 🤔  

I like it! :ok_hand: 

PR looks good to me. :shipit:
