### PR TITLE
Product Gallery Pager: Remove the Pager markup if there's only one image

### LINKED ISSUE #10799: Product Gallery > Pager: Hide for products that have only 1 product image
## Describe the bug

Currently, the Pager displays on the frontend even for products that have only 1 product image.

## To reproduce

1. With a block theme, open `Appearance > Editor`.
2. Open `Templates > Single Product`.
3. Select `Convert to Blocks` if you are using the Classic Templates.
4. Add the `Product Gallery` block.
5. Open a product page on the frontend with just one product image.
7. Notice the Pager block is displaying.

## Expected behavior

For the Pager block to only be visible for products with multiple product images.

## Screenshots

Polo_–_newproductgallery

### PR DESCRIPTION
**Pull request by danieldudzic**
This PR prevents the **Pager** block from being outputted on the page if there's only **one** image in the Product Gallery.

## What

Fixes #10799 

## Why

The **Pager** block doesn't have a purpose if there's only one product image in the product gallery and there's nothing to cycle through. 

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. With a block theme, open `Appearance > Editor`.
2. Open `Templates > Single Product`.
3. Select `Convert to Blocks` if you are using the Classic Templates.
4. Add the `Product Gallery` block.
5. Ensure the `Pager` is enabled.
6. Open a product page on the frontend with multiple product images and verify the pager is displaying correctly.
7. Open a product page on the frontend with just one product image and using the `Inspector` verify the pager markup is not present.

* [ ] Do not include in the Testing Notes 
* [x] Should be tested by the development team exclusively 

## Screenshots or screencast

| Product with one image | Product with multiple images |
| ------ | ----- |
|Album_–_newproductgallery|V-Neck_T-Shirt_–_newproductgallery|

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Product Gallery: Remove the Pager markup if a product has only one product image.

### CODE REVIEW

File: src/BlockTypes/ProductGalleryPager.php [hunk 1]
```diff
@@ -52,23 +52,25 @@ protected function render( $attributes, $content, $block ) {
...
-				$html
-			);
+				return sprintf(
+					'<div %1$s>
+						%2$s
+					</div>',
+					$wrapper_attributes,
+					$html
+				);
+			}
```
Comment (gigitux) [inline src/BlockTypes/ProductGalleryPager.php:73]: I would return an empty string if the `$number_of_thumbnails > 1 ` isn't true.

```
return "";  
```

**Review by gigitux — APPROVED** [review]
Thanks for working on this! I'm pre-approving the PR, but I would return an empty string if the condition isn't true
