### PR TITLE
Use consistent and semantically correct HTML elements in the Cart and Checkout blocks

### LINKED ISSUE #8976: Use consistent and semantically correct HTML elements in the Cart and Checkout blocks
## Note

Currently, similar looking elements in the Cart and the Checkout block, are using different HTML markup. This issue aims to use consistent and semantically correct HTML elements. This issue is part of #8710 and the result of pdFofs-SY-p2.

## Steps to reproduce

1. Add a test product to the cart.
2. Go to the cart page.
3. See that the titles `PRODUCT` and `TOTAL` use a `<span>` element, while the title `CART TOTALS` uses an `<h2>` element.
4. Go to the checkout page.
5. See that the title `Order summary` uses an `<h2>` element, while the titles `Subtotal`, `Shipping`, `Tax` and `Total` use a `<span>` element.

## Expected outcome

- The title `CART TOTALS` uses a `<span>` element instead of an `<h2>` element.
- The title `Order summary` uses a `<span>` element instead of an `<h2>` element.

### PR DESCRIPTION
**Pull request by nielslange**
### Summary
🚚🧹🎨

This pull request refactors the order summary heading components in the cart and checkout blocks, to improve their accessibility, semantics, and reusability. It removes the `Title` component and the `titleTag` prop, and uses simple `span` elements instead of nested headings.

> _We're refactoring the order summary_
> _To make it more accessible and tidy_
> _We're dropping the `titleTag` prop_
> _And the `Title` component we'll chop_

### Walkthrough
*  Remove `titleTag` prop from `OrderSummary` component to simplify API and avoid nested headings ([link](https://github.com/woocommerce/woocommerce-blocks/pull/9065/files?diff=unified&w=0#diff-9d93e50bc53fe392974d7340d8d896c2e970e2af39b00eb719442b0a78bda531L38))
* Replace `Title` component with `span` element in `cart-order-summary-heading` block and edit components to align with `OrderSummary` change and reduce bundle size ([link](https://github.com/woocommerce/woocommerce-blocks/pull/9065/files?diff=unified&w=0#diff-4e5bbbf7774b175e23ac58bdcbbaa093b69373967e6bec45820cddbd2a81b6a3L4), [link](https://github.com/woocommerce/woocommerce-blocks/pull/9065/files?diff=unified&w=0#diff-4e5bbbf7774b175e23ac58bdcbbaa093b69373967e6bec45820cddbd2a81b6a3L15-R18), [link](https://github.com/woocommerce/woocommerce-blocks/pull/9065/files?diff=unified&w=0#diff-abe9e3934a8eaffe26b7364844f16caae2956038434520b0b20d87eeaa04d0a8L5), [link](https://github.com/woocommerce/woocommerce-blocks/pull/9065/files?diff=unified&w=0#diff-abe9e3934a8eaffe26b7364844f16caae2956038434520b0b20d87eeaa04d0a8L27-R26), [link](https://github.com/woocommerce/woocommerce-blocks/pull/9065/files?diff=unified&w=0#diff-abe9e3934a8eaffe26b7364844f16caae2956038434520b0b20d87eeaa04d0a8L42-R40))

---

### 👨‍💼 Enhanced by @nielslange 

Fixes #8976

#### User Facing Testing

1. Create a test page and add the Cart block.
2. Within the post editor, verify that the `CART TOTALS` element, with the CSS class `.wc-block-cart__totals-title`, is using a `<span>` instead of an `<h2>`.
3. Create another test page and add the Checkout block.
4. Within the post editor, verify that the `Order summary` element, with the CSS class `.wc-block-components-order-summary`, is using a `<div>` instead of an `<h2>`.
5. Go to the frontend and add a product to the cart.
6. On the page with the Cart block, verify that the `CART TOTALS` element, with the CSS class `.wc-block-cart__totals-title`, is using a `<span>` instead of an `<h2>`.
7. On the page with the Checkout block, verify that the `Order summary` element, with the CSS class `.wc-block-components-order-summary`, is using a `<div>` instead of an `<h2>`.

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

File: assets/js/base/components/cart-checkout/order-summary/index.tsx [hunk 1]
```diff
@@ -35,7 +35,6 @@ const OrderSummary = ( {
 					{ __( 'Order summary', 'woo-gutenberg-products-block' ) }
 				</span>
 			}
-			titleTag="h2"
```
Comment (nielslange) [inline assets/js/base/components/cart-checkout/order-summary/index.tsx:38]: The issue description on https://github.com/woocommerce/woocommerce-blocks/issues/8976 states the following:

> The title `Order summary` uses a `<span>` element instead of an `<h2>` element.

Given that this element will contain a few sub elements, I believe using a `<div>` is the better option here. Therefore, instead of changing `titleTag="h2"` to `titleTag="span"`, I removed that part, as `div` is [defined as the default titleTag](https://github.com/woocommerce/woocommerce-blocks/blob/28534b7c463b796f5f2a22562b87a5c2b562c6ad/packages/checkout/components/panel/index.tsx#L29).

**Review by tarunvijwani — APPROVED** [review]
Thank you for working on it, @nielslange! It works as expected. 🎉

**Comment by nielslange** [comment]
> Thank you for working on it, @nielslange! It works as expected. 🎉

Yeah! Thanks for your review, @tarunvijwani! 🙌
