### PR TITLE
Capture notices from hidden block into siblings block

### LINKED ISSUE #8387: Two "The provided postcode / ZIP is not valid" error message are displayed.
## Describe the bug

5927922-zd / 40342701-hc

If you add a wrong zip code, two "The provided postcode / ZIP is not valid" error messages are displayed. If you correct the zip code, the first one disappears; The second is stuck. This is happening with the new version 9.5.0.

## To reproduce

1. Add the latest version of [WooCommerce Blocks](https://woocommerce.com/products/woocommerce-gutenberg-products-block/) on your website 
2. Add the [check-out block](https://woocommerce.com/document/cart-checkout-blocks-support-status/) on your check-out page. 
1. Add a product to the cart and go to checkout
2. Change country to Poland for example with the zip code 40-837. 
3. Change country to United Kingdom.
4. You will see two "The provided postcode / ZIP is not valid" error messages.
5. Change the zip code to E14 9AJ
6. The first "The provided postcode / ZIP is not valid" error message is stuck. 

## Expected behavior

Only one "The provided postcode / ZIP is not valid" error message is displayed and disappears after correcting the zip code. 

## Screenshots

Please check this Gif: d.pr/i/IkNwW4

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   WooCommerce version: 7.1.0
-   WooCommerce Blocks version: 9.5.0
-   Site language: English

## Additional context

The user also reported that the order summary was not updated after that, but I can't reproduce that.

### PR DESCRIPTION
**Pull request by senadir**
Recently in https://github.com/woocommerce/woocommerce-blocks/pull/8182 we introduced more controlled notice handling, this included showing notices in the correct places when needed and surfacing notices up to the main block when it makes sense.

However, this introduced a problem in sibling blocks (Shipping address billing address, payment and express payment) in which an error might be returned for both, but is rendered on one of them only while the other bubbles).

This PR adds a `capturedContexts` param to the store notice provider to capture other notices.

This PR also adds filtering so duplicate errors are shown once, based on the error content only.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/8387

### Testing

1. In Checkout, have billing as shipping.
2. Cause a bug in the zip code for example (wrong zipcode)
3. See that Checkout block will only show an error once, not in 2 places.

### Changelog

> Fix bug in which errors would be shown twice in Checkout block.

### CODE REVIEW

File: assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/block.tsx [hunk 1]
```diff
@@ -91,7 +91,14 @@ const Block = ( {
...
 	return (
 		<AddressFormWrapperComponent>
-			<StoreNoticesContainer context={ noticeContexts.BILLING_ADDRESS } />
+			<StoreNoticesContainer
+				context={ noticeContexts.BILLING_ADDRESS }
+				capturedContexts={
+					useBillingAsShipping
+						? [ noticeContexts.SHIPPING_ADDRESS ]
+						: []
+				}
```
Comment (senadir) [inline assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/block.tsx]: I don't feel strongly about approach, another option would be to call `registerContainer` from this block but I didn't test that yet.

File: packages/checkout/components/store-notices-container/index.tsx [hunk 2]
```diff
@@ -46,23 +57,31 @@ const StoreNoticesContainer = ( {
 			subContext.includes( context + '/' ) &&
 			! registeredContainers.includes( subContext )
 	);
-
+	const contexts = useMemo(
+		() => [ context, ...capturedContexts ],
+		[ capturedContexts, context ]
+	);
```
Comment (senadir) [inline packages/checkout/components/store-notices-container/index.tsx]: This caused an infinite loop so that's why I added it.

File: assets/js/blocks/checkout/inner-blocks/checkout-shipping-address-block/block.tsx [hunk 3]
```diff
@@ -103,6 +103,11 @@ const Block = ( {
 			<AddressFormWrapperComponent>
 				<StoreNoticesContainer
 					context={ noticeContexts.SHIPPING_ADDRESS }
+					capturedContexts={
+						useShippingAsBilling
+							? [ noticeContexts.BILLING_ADDRESS ]
```
Comment (alexflorisca) [inline assets/js/blocks/checkout/inner-blocks/checkout-shipping-address-block/block.tsx]: Do we need to take into account the WC settings where a merchant can default to the shipping address or force shipping address to the customer billing address? This seems to work ok when I tested, but I'm not sure why. The logic you have here is that the error should be displayed in the billing address context, if `useShippingAsBilling` is ticked. If shipping address is default, the context should be SHIPPING_ADDRESS. The notice is displayed correctly though, so I'm wondering why this works?

File: packages/checkout/components/store-notices-container/store-notices.tsx [hunk 4]
```diff
@@ -17,11 +17,11 @@ import { getClassNameFromStatus } from './utils';
 import type { StoreNotice } from './types';
 
 const StoreNotices = ( {
-	context,
+	contexts,
```
Comment (alexflorisca) [inline packages/checkout/components/store-notices-container/store-notices.tsx]: You'll need to update the docs [here](https://github.com/woocommerce/woocommerce-blocks/blob/try/shipping-captures-billing-notices/docs/internal-developers/block-client-apis/notices.md?plain=1#L26) as well to reflect plural

**Review by alexflorisca — COMMENTED** [review]
Nice work, works as advertised but I had a couple of q - see inline comments

File: assets/js/blocks/checkout/inner-blocks/checkout-shipping-address-block/block.tsx (hunk 3 above)
Comment (senadir) [reply assets/js/blocks/checkout/inner-blocks/checkout-shipping-address-block/block.tsx]: `useShippingAsBilling` takes that into account.

The logic here is that if we have the billing form hidden and its value being synced to shipping, then we also want to capture those notices and present them in the shipping step.

> The logic you have here is that the error should be displayed in the billing address context, if useShippingAsBilling is ticked.

The logic I have here is that if `useShippingAsBilling` is true, we want to capture the billing address errors and show them in that block (shipping address)

Comment (alexflorisca) [reply assets/js/blocks/checkout/inner-blocks/checkout-shipping-address-block/block.tsx]: Gotcha that makes more sense

**Comment by alexflorisca** [comment]
Just noticed some TS errors

> ⚠️ ⚠️ This PR introduces new TS errors on 13 files:

File: assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/block.tsx [hunk 5]
```diff
@@ -91,7 +91,14 @@ const Block = ( {
 
 	return (
 		<AddressFormWrapperComponent>
-			<StoreNoticesContainer context={ noticeContexts.BILLING_ADDRESS } />
+			<StoreNoticesContainer
+				context={ noticeContexts.BILLING_ADDRESS }
```
Comment (mikejolley) [inline assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/block.tsx]: I would prefer if we could somehow define an array of context here rather than the separate prop.

File: packages/checkout/components/store-notices-container/index.tsx [hunk 6]
```diff
@@ -24,9 +25,19 @@ const formatNotices = ( notices: Notice[], context: string ): StoreNotice[] => {
...
 };
 
+const removeDuplicateNotices = (
+	notice: Notice,
+	noticeIndex: number,
+	noticesArray: Notice[]
+) =>
+	noticesArray.findIndex(
+		( _notice: Notice ) => _notice.content === notice.content
+	) === noticeIndex;
```
Comment (mikejolley) [inline packages/checkout/components/store-notices-container/index.tsx]: 👍🏻 This makes sense.

**Review by alexflorisca — APPROVED** [review]
Looks good now, thanks for working on this 👍
