### PR TITLE
Product Rating: Remove empty markup if no ratings are present

### LINKED ISSUE #9804: Product Rating: Empty markup present in the loop
## Describe the bug

Currently, if you use the **Products (Beta)** block and add the **Product Rating** block, the loop will output the Rating block markup regardless of whether the rating is actually present or not.

Empty markup:

```
<div data-block-name="woocommerce/product-rating" data-is-descendent-of-query-loop="true" data-text-align="center" class="wc-block-components-product-rating wc-block-grid__product-rating has-text-align-center has-text-align-center" style="">
					
</div>
```

This surfaced as I was testing: https://github.com/woocommerce/woocommerce-blocks/pull/9781 and the empty markup adds unnecessary margin.

## To reproduce

1. Ensure at least one of your products has a rating.
2. On a new page add the **Products (Beta)** block.
3. Add the Product Rating block.
4. You can now observe that on the page, each product in the loop contains the empty markup.

## Screenshots

ITz2PQSjvt

### PR DESCRIPTION
**Pull request by danieldudzic**
This PR removes unnecessary Product Rating markup in case there are no real or mocked ratings present.

Fixes #9804

#### User Facing Testing

1. Add **All Products** and **Products (Beta)** blocks - make sure both blocks are displaying product ratings.
2. Make sure you have at least one product with review(s).
3. Check if the ratings display correctly in the **editor**:
- Products (Beta)
	- No ratings present: "⭐ No Reviews"
	- Ratings present: Star Ratings
- All Products
	 - No ratings present: Nothing displaying
	 - Ratings present: Star Ratings
4. Check if the ratings display correctly in the **frontend**:
- Products (Beta)
	 - No ratings present: Nothing displaying
	 - Ratings present: Star Ratings
- All Products
	 - No ratings present: Nothing displaying
	 - Ratings present: Star Ratings
5. Check with the inspector that in case of "Nothing" displaying, there's **no** following markup present:
`<div data-block-name="woocommerce/product-rating"></div>`

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Product Rating: Removes unnecessary Product Rating markup in case there are no real or mocked ratings present

### CODE REVIEW

File: assets/js/atomic/blocks/product-elements/rating/block.tsx [hunk 1]
```diff
@@ -168,16 +168,18 @@ export const Block = ( props: ProductRatingProps ): JSX.Element | null => {
...
 	);
 
-	return (
-		<div className={ className } style={ styleProps.style }>
-			<div className="wc-block-components-product-rating__container">
-				{ content }
-				{ reviews && isDescendentOfSingleProductBlock ? (
-					<ReviewsCount reviews={ reviews } />
-				) : null }
+	if ( reviews || shouldDisplayMockedReviewsWhenProductHasNoReviews ) {
```
Comment (gigitux) [inline assets/js/atomic/blocks/product-elements/rating/block.tsx:171]: This change introduces a TS error. Please, update the return type at line 137 from:
```
JSX.Element | null
```
to

```
JSX.Element | undefined
```

Another solution could be add this line after the if:
```
return null
```

**Review by gigitux — APPROVED** [review]
LGTM! 🚀  I Pre-approved the PR, but please, before merging ensure that you fixed the TS error.
