### PR TITLE
Fix: Convert Filter Products by Attribute Block to TypeScript 

### LINKED ISSUE #6496: Convert Filter Products by Attribute Block to TypeScript

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes woocommerce/woocommerce-blocks#6496

This PR converts the codebase of the Filter Products by Attribute block to TypeScript.

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) .
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md)
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

N/A

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

Ensure no regression after the conversion.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

N/A

### Changelog

N/A

### CODE REVIEW

File: assets/js/blocks/attribute-filter/block.tsx [hunk 1]
```diff
@@ -88,13 +97,17 @@ const AttributeFilterBlock = ( {
 	const attributeObject =
 		blockAttributes.isPreview && ! blockAttributes.attributeId
 			? previewAttributeObject
-			: getAttributeFromID( blockAttributes.attributeId );
+			: ( getAttributeFromID(
+					blockAttributes.attributeId
+			  ) as AttributeObject );
```
Comment (gigitux) [inline assets/js/blocks/attribute-filter/block.tsx]: Instead, to use `as` to enforce the cast, a safe way to proceed could be adding a type guard or converting the file `attribute.js` to TypeScript. What do you think?

File: assets/js/blocks/attribute-filter/block.tsx [hunk 2]
```diff
@@ -319,7 +342,7 @@ const AttributeFilterBlock = ( {
 	);
 
 	const checkedQuery = useMemo( () => {
-		return productAttributesQuery
+		return ( productAttributesQuery as QueryStateAttribute[] )
```
Comment (gigitux) [inline assets/js/blocks/attribute-filter/block.tsx]: Same here. I suggest to re-write the file `use-query-state.js` in TypeScript to avoid the enforced cast

File: assets/js/editor-components/search-list-control/types.ts [hunk 3]
```diff
@@ -6,11 +6,11 @@ import type { ReactNode } from 'react';
 export type SearchListItemType = {
 	id: string | number;
 	name: string;
-	value: string;
-	parent: number;
-	count: number;
-	children: SearchListItemsType;
-	breadcrumbs: string[];
+	value?: string;
```
Comment (gigitux) [inline assets/js/editor-components/search-list-control/types.ts]: Are you sure that these changes are necessary?

File: assets/js/editor-components/search-list-control/types.ts [hunk 4]
```diff
@@ -77,9 +77,9 @@ export interface SearchListControlProps {
 	// Callback fired when the search field is used.
 	onSearch?: ( search: string ) => void;
 	// Callback to render each item in the selection list, allows any custom object-type rendering.
-	renderItem: ( args: renderItemArgs ) => JSX.Element;
+	renderItem?: ( args: renderItemArgs ) => JSX.Element;
```
Comment (gigitux) [inline assets/js/editor-components/search-list-control/types.ts:80]: Same here

**Review by gigitux — CHANGES_REQUESTED** [review]
Great job! It is not an easy task convert JS file to TS 💪 

I tested the block and I didn't find any regressions. I suggest to avoid `as` , but for this is necessary refactor other files. Maybe could it be a good idea add a TODO comment, so can we work during our cooldown?

Also, I added another comment on `assets/js/editor-components/search-list-control/types.ts` because I'm not sure why some changes are necessary.

File: assets/js/editor-components/search-list-control/types.ts (hunk 4 above)
Comment (dinhtungdu) [reply assets/js/editor-components/search-list-control/types.ts:80]: I changed that argument to optional because of this https://github.com/woocommerce/woocommerce-blocks/blob/fix/6496/assets/js/editor-components/search-list-control/search-list-control.tsx#L154.

File: assets/js/editor-components/search-list-control/types.ts (hunk 3 above)
Comment (dinhtungdu) [reply assets/js/editor-components/search-list-control/types.ts]: We don't always provide the list with all properties to the `<SearchListControl>` and we don't need to. For example: https://github.com/woocommerce/woocommerce-blocks/blob/fix/6496/assets/js/blocks/attribute-filter/edit.tsx#L140-L148.

But this is not the complete solution because I didn't review the usage of `<SearchListControl>` in other places. I will revert this back to the original state. We should review the data structure of `<SearchListControl>` in a separate PR.

File: assets/js/blocks/attribute-filter/block.tsx (hunk 1 above)
Comment (dinhtungdu) [reply assets/js/blocks/attribute-filter/block.tsx]: I agree. I converted attribute utils to TS.

File: assets/js/blocks/attribute-filter/block.tsx (hunk 2 above)
Comment (dinhtungdu) [reply assets/js/blocks/attribute-filter/block.tsx]: I agree. But I think we should convert hooks inside `use-query-state.js` in a separate PR. I created https://github.com/woocommerce/woocommerce-blocks/issues/6577 for it.

File: assets/js/editor-components/search-list-control/types.ts (hunk 3 above)
Comment (dinhtungdu) [reply assets/js/editor-components/search-list-control/types.ts]: Created https://github.com/woocommerce/woocommerce-blocks/issues/6578 for this.

**Comment by dinhtungdu** [comment]
@gigitux Thanks so much for your review, I update the PR. Can you please take another look?

**Review by gigitux — APPROVED** [review]
Thanks for addressing the feedback and opening new issues. Great work! LGTM!
