### PR TITLE
Register missing C&C inner blocks and update fallback template for older C& C versions

### LINKED ISSUE #6185: Not all Cart & Checkout inner blocks render when migrating to inner blocks for Order Summary
## Describe the bug

When migrating to the Cart & Checkout blocks that have Order summary with inner blocks not all content is loaded for the Order summary.

See internal conversation p1649074270986619/1649068099.800419-slack-C8X6Q7XQU
## To reproduce

Steps to reproduce the behaviour:

1. Go to version v7.2.0
2. Build and add C & C blocks to pages
3. Check to see the content
4. Go to `git checkout trunk`
5. Build and see that some inner blocks are missing as follows:
**Cart**
- Order summary heading, Coupons & Taxes(?) inner blocks
**Checkout**
- Cart summary, Coupons & Taxes(?) inner blocks

## Expected behavior

All inner blocks should be rendered in the Order summary.

### PR DESCRIPTION
**Pull request by ralucaStan**
This will fix the issues with missing Order summary inner blocks: Coupons (both in C & C blocks) and the Cart header. 

The issue was happening because, for example, for Cart the coupons were registered on the on frontend, but it just wasn't forced in the attributes. Because it also wasn't added to the PHP fallback layout, the render function didn't include it. For the Checkout block the coupons inner block wasn't registered at all.

Fixes #6185 

#### Other Checks

- [ ] I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) for any feature flags or experimental interfaces implemented in this pull request.
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before  | After |
| ------------- | ------------- |
|   Screenshot 2022-04-05 at 11 53 18 |   Screenshot 2022-04-05 at 16 55 41 |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
### Manual Testing

How to test the changes in this Pull Request:
**Test from tag v7.2.0**

1. Run `git checkout tags/v7.2.0` 
2. Insert fresh Cart/Checkout blocks in different pages, save them
3. Notice that there is no inner blocks for Order summary
4. Switch to the PR branch & build
5. Test that Cart/Checkout blocks load fine in the frontend and the editor without crashing and the missing inner blocks are there

### User Facing Testing
These are steps for user testing (where "user" is someone interacting with this change that is not editing any code).
* [ ] Same as above, or
* [ ] See steps below.
* [x] Not included in user facing testing instructions

### CODE REVIEW

File: src/BlockTypes/Checkout.php [hunk 1]
```diff
@@ -109,6 +111,30 @@ protected function render( $attributes, $content ) {
...
+		 */
+		$coupons_enabled                 = wc_coupons_enabled();
+		$order_summary_with_inner_blocks = '$0
+			<div data-block-name="woocommerce/checkout-order-summary-cart-items-block" class="wp-block-woocommerce-checkout-order-summary-cart-items-block"></div>
+			<div data-block-name="woocommerce/checkout-order-summary-subtotal-block" class="wp-block-woocommerce-checkout-order-summary-subtotal-block"></div>
+			<div data-block-name="woocommerce/checkout-order-summary-fee-block" class="wp-block-woocommerce-checkout-order-summary-fee-block"></div>
+			<div data-block-name="woocommerce/checkout-order-summary-discount-block" class="wp-block-woocommerce-checkout-order-summary-discount-block"></div>' .
+			( $coupons_enabled ? '<div data-block-name="woocommerce/checkout-order-summary-coupon-form-block" class="wp-block-woocommerce-checkout-order-summary-coupon-form-block"></div>' : '' ) .
+			'<div data-block-name="woocommerce/checkout-order-summary-shipping-block" class="wp-block-woocommerce-checkout-order-summary-shipping-block"></div>
+			<div data-block-name="woocommerce/checkout-order-summary-taxes-block" class="wp-block-woocommerce-checkout-order-summary-taxes-block"></div>
```
Comment (opr) [inline src/BlockTypes/Checkout.php:128]: Do we need to do a check for if taxes are enabled here?

**Review by opr — COMMENTED** [review]
Testing works well! 🙌🏼  Also the code changes look mostly fine, just added a question about the taxes block.

File: src/BlockTypes/Checkout.php (hunk 1 above)
Comment (ralucaStan) [reply src/BlockTypes/Checkout.php:128]: Most definitely, but I don't trust myself to do this change. There is no issue if the wrapper appears when it shouldn't because it's handled on the CSS side, but we can add a ticket for this separately.

File: src/BlockTypes/Cart.php [hunk 2]
```diff
@@ -105,6 +112,30 @@ protected function render( $attributes, $content ) {
...
+		 * Cart i3 added inner blocks for Order summary. We need to add them to Cart i2 templates.
+		 * The order needs to match the order in which these blocks were registered.
+		 */
+		$coupons_enabled                 = wc_coupons_enabled();
+		$order_summary_with_inner_blocks = '$0
+			<div data-block-name="woocommerce/cart-order-summary-heading-block" class="wp-block-woocommerce-cart-order-summary-heading-block"></div>
+			<div data-block-name="woocommerce/cart-order-summary-subtotal-block" class="wp-block-woocommerce-cart-order-summary-subtotal-block"></div>
+			<div data-block-name="woocommerce/cart-order-summary-fee-block" class="wp-block-woocommerce-cart-order-summary-fee-block"></div>
+			<div data-block-name="woocommerce/cart-order-summary-discount-block" class="wp-block-woocommerce-cart-order-summary-discount-block"></div>' .
+			( $coupons_enabled ? '<div data-block-name="woocommerce/cart-order-summary-coupon-form-block" class="wp-block-woocommerce-cart-order-summary-coupon-form-block"></div>' : '' ) .
```
Comment (senadir) [inline src/BlockTypes/Cart.php]: This shouldn't be here and shouldn't be needed at all, the logic inside `cart-order-summary-coupon-form/block.tsx` should be enough. The logic to render those divs should match the logic we have inside `defaultTemplate` of `cart-order-summary-block/edit.tsx`, so if we don't have conditions inside that array, we shouldn't have logic here.

Comment (senadir) [reply src/BlockTypes/Cart.php]: You can confirm that by inserting a V3 Cart and saving, the HTML from coupon form is always there, regardless of taxes being enabled or not.

File: src/BlockTypes/Checkout.php (hunk 1 above)
Comment (senadir) [reply src/BlockTypes/Checkout.php:128]: We shouldn't check for taxes being enabled, not coupons as well. That logic lives inside the actual block.

**Review by senadir — APPROVED** [review]
Tested and reviewed functionality, this is looking great! 🚢
