### PR TITLE
Respect core settings for showing the Checkout block

### LINKED ISSUE #7823: Regression: Checkout still visible, can place orders, even when core settings contradict
WooCommerce core has 2 options, one dictates if you can create an account or not at Checkout, the other if you need to have an account to Checkout.

Depending on the configuration, for guests, you can end up either having the option to create an account, being forced to create an account, or asked to log in before you see Checkout.

Currently Checkout Block and Store API don't respect that, I can see Checkout block and submit a guest order.

image

This is what shortcode shows when both are disabled

image

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #7823

In #7823, @senadir reported that the following two WooCommerce core settings are not respected by the Checkout block:

- Guest Checkout:  Allow customers to place orders without an account
- Account creation:  Allow customers to create an account during checkout

This PR aims to ensure that these WooCommerce core settings are respected by the Checkout block and that the Checkout block behaves identical to the shortcode-based checkout.

#### Show login prompt when guest checkout and account creation (in core) are disabled 

1. Create a test page and add the Checkout block to it.
2. Head over to `/wp-admin/admin.php?page=wc-settings&tab=account`.
3. Deactivate the option `Guest checkout` → `Allow customers to place orders without an account`.
4. Deactivate the option `Account creation` → `Allow customers to create an account during checkout`.
5. Open the frontend in an incognito window and ensure that you're not accidentally logged in (from a previous test).
6. Add a product to the cart and go to the test page with the Checkout block.
7. Verify that the checkout form is not visible.
8. Verify that the message `You must be logged in to checkout. Click here to log in.`.

#### Show checkout when guest checkout is enabled, but account creation is disabled

1. Create a test page and add the Checkout block to it.
2. Head over to `/wp-admin/admin.php?page=wc-settings&tab=account`.
3. Activate the option `Guest checkout` → `Allow customers to place orders without an account`.
4. Deactivate the option `Account creation` → `Allow customers to create an account during checkout`.
5. Open the frontend in an incognito window and ensure that you're not accidentally logged in (from a previous test).
6. Add a product to the cart and go to the test page with the Checkout block.
7. Verify that the checkout form is visible.
8. Place a test order and verify that no account had been created. The order details show `Guest` as a `Customer`:

Screenshot 2022-12-16 at 12 26 59

#### Show checkout when guest checkout is disabled, but account creation is enabled

1. Create a test page and add the Checkout block to it.
2. Head over to `/wp-admin/admin.php?page=wc-settings&tab=account`.
3. Deactivate the option `Guest checkout` → `Allow customers to place orders without an account`.
4. Activate the option `Account creation` → `Allow customers to create an account during checkout`.
5. Open the frontend in an incognito window and ensure that you're not accidentally logged in (from a previous test).
6. Add a product to the cart and go to the test page with the Checkout block.
7. Verify that the checkout form is visible.
8. Place a test order and verify that a new account had been created. The order details shows the new account as a `Customer`:

Screenshot 2022-12-16 at 12 37 07

#### Show checkout when guest checkout and account creation are enabled, but don't create account

1. Create a test page and add the Checkout block to it.
2. Head over to `/wp-admin/admin.php?page=wc-settings&tab=account`.
3. Activate the option `Guest checkout` → `Allow customers to place orders without an account`.
4. Activate the option `Account creation` → `Allow customers to create an account during checkout`.
5. Open the frontend in an incognito window and ensure that you're not accidentally logged in (from a previous test).
6. Add a product to the cart and go to the test page with the Checkout block.
7. Verify that the checkout form is visible.
8. Verify that the checkbox `Create an account?` is not checked.
10. Place a test order and verify that no account had been created. The order details show `Guest` as a `Customer`.

Screenshot 2022-12-16 at 12 26 59

#### Show checkout when guest checkout and account creation are enabled, and create account

1. Create a test page and add the Checkout block to it.
2. Head over to `/wp-admin/admin.php?page=wc-settings&tab=account`.
3. Activate the option `Guest checkout` → `Allow customers to place orders without an account`.
4. Activate the option `Account creation` → `Allow customers to create an account during checkout`.
5. Open the frontend in an incognito window and ensure that you're not accidentally logged in (from a previous test).
6. Add a product to the cart and go to the test page with the Checkout block.
7. Verify that the checkout form is visible.
8. Verify that the checkbox `Create an account?` is checked.
9. Place a test order and verify that a new account had been created. The order details shows the new account as a `Customer`:

Screenshot 2022-12-16 at 12 37 07

#### Verify that display logic is in sync

1. Execute the previous test cases again, both with the classic checkout and the Checkout block.
2. Do not place an order, but verify that the display logic of the login link respectively the checkout form is in sync.

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix: Ensure that the Checkout block respects the WooCommerce core settings for guest checkout and account creation.

### CODE REVIEW

File: assets/js/base/components/block-error-boundary/types.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ export interface BlockErrorBoundaryProps extends BlockErrorBase {
 	 * Override the default error with a function that takes the error message and returns a React component
 	 */
 	renderError?: ( props: RenderErrorProps ) => React.ReactNode;
-	showErrorMessage?: boolean;
+	showErrorMessage?: boolean | unknown;
```
Comment (mikejolley) [inline assets/js/base/components/block-error-boundary/types.ts]: Should this be `| undefined`?

File: assets/js/blocks/checkout/block.tsx [hunk 2]
```diff
@@ -84,22 +84,29 @@ const Checkout = ( {
...
 
+	/**
+	 * Show the login prompt if the user is not logged in
+	 * AND no guest checkout is allowed
+	 * AND no account creation is allowed..
+	 */
 	if (
 		isLoginRequired( customerId ) &&
-		getSetting( 'checkoutAllowsSignup', false )
+		! getSetting( 'checkoutAllowsSignup', false )
```
Comment (mikejolley) [inline assets/js/blocks/checkout/block.tsx:94]: I was slightly confused by this change but after deep thought, I think I get it.

`isLoginRequired` returns true if guest checkout is disabled. 

Therefore, the only way we can take an order for the logged-out user is if we allow them to create an account during checkout (1), or if they log in/create an account elsewhere and come back (2).

👍🏻

File: assets/js/blocks/checkout/block.tsx [hunk 3]
```diff
@@ -84,22 +84,29 @@ const Checkout = ( {
...
 	) {
-		<LoginPrompt />;
+		return <LoginPrompt />;
```
Comment (mikejolley) [inline assets/js/blocks/checkout/block.tsx]: I think while you are here you should rename `LoginPrompt`, because we have 2 components with this name and both have very different purposes.

One shows a link to login, while this one says checkout is not possible.

File: assets/js/blocks/checkout/block.tsx [hunk 4]
```diff
@@ -84,22 +84,29 @@ const Checkout = ( {
 		return <CheckoutOrderError />;
 	}
 
+	/**
+	 * Show the login prompt if the user is not logged in
```
Comment (alexflorisca) [inline assets/js/blocks/checkout/block.tsx]: I like the comment here, useful to see what's going on below

File: assets/js/blocks/checkout/block.tsx (hunk 3 above)
Comment (alexflorisca) [inline assets/js/blocks/checkout/block.tsx]: The <LoginPrompt> component returns `You must be logged in to checkout.
[Click here to log in.](https://woo.local/my-account/?redirect_to=https%3A%2F%2Fwoo.local%2Fcheckout-2%2F)`. There is no space between the two sentences, could you add a non breaking space there as part of this PR just to tidy it up a bit?

**Review by alexflorisca — APPROVED** [review]
Nice work Niels, minor comment but feel free to ship without it :)

File: assets/js/blocks/checkout/block.tsx [hunk 5]
```diff
@@ -84,22 +84,29 @@ const Checkout = ( {
...
+	 * AND no guest checkout is allowed
+	 * AND no account creation is allowed..
```
Comment (mikejolley) [inline assets/js/blocks/checkout/block.tsx]:
```suggestion
	 * If checkout requires an account (guest checkout is turned off), render
	 * a notice and prevent access to the checkout, unless we explicitly allow 
	 * account creation during the checkout flow.
```

**Review by mikejolley — APPROVED** [review]
I understand this now and tested the main case. Small comments/suggestions but nothing blocking. Pre-approving.

File: assets/js/blocks/checkout/block.tsx (hunk 2 above)
Comment (nielslange) [reply assets/js/blocks/checkout/block.tsx:94]: Correct, @mikejolley. It also took me a bit to understand the logic here.

File: assets/js/blocks/checkout/block.tsx (hunk 4 above)
Comment (nielslange) [reply assets/js/blocks/checkout/block.tsx]: Thanks, @alexflorisca. I've added the comment, which @mikejolley improved, as the check below is a bit confusing without context.

File: assets/js/base/components/block-error-boundary/types.ts (hunk 1 above)
Comment (nielslange) [reply assets/js/base/components/block-error-boundary/types.ts]: > Should this be | undefined?

https://github.com/woocommerce/woocommerce-blocks/blob/c9f4a0ea2a4fa47a2374ff19767532507dc1683c/assets/js/base/components/block-error-boundary/types.ts#L50 affects https://github.com/woocommerce/woocommerce-blocks/blob/c69f13d7e6ab1b1ef7ba528e7b7015d6aacea179/assets/js/blocks/checkout/block.tsx#L187 whereas `CURRENT_USER_IS_ADMIN` is coming from https://github.com/woocommerce/woocommerce-blocks/blob/c69f13d7e6ab1b1ef7ba528e7b7015d6aacea179/assets/js/settings/shared/default-constants.ts#L12

As `allSettings.currentUserIsAdmin` has the type `unknown`, I was using 

```tsx
showErrorMessage?: boolean | unknown;
```

instead of

```tsx
showErrorMessage?: boolean | undefined;
```

Would you say it's better to change 

```tsx
export const CURRENT_USER_IS_ADMIN = allSettings.currentUserIsAdmin;
```

to

```tsx
export const CURRENT_USER_IS_ADMIN = allSettings.currentUserIsAdmin as boolean;
```

in https://github.com/woocommerce/woocommerce-blocks/blob/c69f13d7e6ab1b1ef7ba528e7b7015d6aacea179/assets/js/settings/shared/default-constants.ts, @mikejolley ?

File: assets/js/blocks/checkout/block.tsx (hunk 3 above)
Comment (nielslange) [reply assets/js/blocks/checkout/block.tsx]: Good catch, @mikejolley. I renamed `<LoginPrompt>` to `<MustLoginPrompt>` in this PR. While I could have changed the other `<LoginPrompt>` to `<MayLoginPrompt>`, I decided against it, as this would slightly change the scope of this PR and would require additional testing.

Comment (nielslange) [reply assets/js/blocks/checkout/block.tsx]: Good catch, @alexflorisca. I noticed this initially, but then forgot to address this part. It took me a while to figure out what happened in this case. Initially, the text `You must be logged in to checkout. ` had a trailing space as part of the translation string:

```tsx
{ __(
    'You must be logged in to checkout. ',
    'woo-gutenberg-products-block'
) }
```

Technically, this space should have been visible. It turned out that we're wrapping the Checkout block with the CSS class `.wc-block-components-sidebar-layout` which is defined on https://github.com/woocommerce/woocommerce-blocks/blob/c69f13d7e6ab1b1ef7ba528e7b7015d6aacea179/assets/js/base/components/sidebar-layout/style.scss#L1-L5

As the out box is using `display: flex;`, the space behind the text gets trimmed. Removing the CSS class `.wc-block-components-sidebar-layout` would not be an option, as this would affect the styles of the Checkout block. 

I addressed this issue by wrapping the login text and login link with the CSS class `.wc-block-must-login-prompt`. In https://github.com/woocommerce/woocommerce-blocks/blob/0fc0177aa1393fbb7bf2491f978b06d7d2c56ae9/assets/js/base/components/sidebar-layout/style.scss#L7-L9, I then set the display setting to `display: block;`. This way, the trailing space became visible. I went a step further and removed the space from the translation changed

```tsx
{ __(
	'You must be logged in to checkout. ',
	'woo-gutenberg-products-block'
) }
<a href={ LOGIN_TO_CHECKOUT_URL }>
	{ __(
		'Click here to log in.',
		'woo-gutenberg-products-block'
	) }
</a>
```

to 

```tsx
{ __(
	'You must be logged in to checkout.',
	'woo-gutenberg-products-block'
) }{ ' ' }
<a href={ LOGIN_TO_CHECKOUT_URL }>
	{ __(
		'Click here to log in.',
		'woo-gutenberg-products-block'
	) }
</a>
```

The reason I'm doing this, is that a translator might not be aware of the purpose of the trailing space and might not add that to a translation. A translation would then end up without the space between the login text and the login link.

Comment (alexflorisca) [reply assets/js/blocks/checkout/block.tsx]: Thanks Niels, nice work. I don't think there's any need for the extra `wc-block-must-login-prompt` class. I've just removed it and the text still renders just fine with the space outside the translated text

File: assets/js/base/components/block-error-boundary/types.ts (hunk 1 above)
Comment (mikejolley) [reply assets/js/base/components/block-error-boundary/types.ts]: Yes, I think so. We know that it will be a boolean if provided. It technically could also be undefined I guess but under normal circumstances its a boolean.

Comment (nielslange) [reply assets/js/base/components/block-error-boundary/types.ts]: Thanks, @mikejolley.

I changed
```ts
export const CURRENT_USER_IS_ADMIN = allSettings.currentUserIsAdmin;
```
to
```ts
export const CURRENT_USER_IS_ADMIN = allSettings.currentUserIsAdmin as boolean;
```
and
```ts
showErrorMessage?: boolean | unknown;
```
to
```ts
showErrorMessage?: boolean | undefined;
```

**Review by mikejolley — APPROVED** [review]

File: assets/js/blocks/checkout/block.tsx (hunk 3 above)
Comment (nielslange) [reply assets/js/blocks/checkout/block.tsx]: As discussed in Slack, we'll leave this part, as we're seeing different results in this case.
