### PR TITLE
Load Interactivity API in `bootstrap.php`

### LINKED ISSUE #10661: [GlobalStep] "Publishing failed. The response is not a valid JSON response." error notice displayed after publishing a new Post with "Products (Beta)" block.
### Bug Description:
"Publishing failed. The response is not a valid JSON response." error notice displayed after publishing a new Post with "Products (Beta)" block.

### Environment:
Woocommerce Version: 8.1.0-dev
WordPress version: 6.3
PHP version: 8.0.30

PC:
Windows 10
Chrome(Version 116.0.5845.97)
Firefox (Version 116.0.3)

### Steps To Reproduce:
1. Create any test site.
2. Install and activate all the required plugins.
3. Install and activate the Woocommerce 8.1.0-dev plugin.
4. Go to Post > Add New Page.
5. Add the "Products (Beta)" block.
6. Click on "Publish" button
7. Observe that, "Publishing failed. The response is not a valid JSON response." error notice displayed.

### Actual Result:
"Publishing failed. The response is not a valid JSON response." error notice displayed after publishing a new Post with "Products (Beta)" block.

### Expected Result:
"Products (Beta)" block should be published without any error on the new post.

### ScreenShot:

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 8.1.0
REST API Version: ✔ 8.1.0
WC Blocks Version: ✔ 10.9.0
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: 6.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Unix) OpenSSL/1.0.2g
PHP Version: 8.0.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.1.0
WC Database Prefix: wp_
Total Database Size: 5.38MB
Database Data Size: 3.65MB
Database Index Size: 1.73MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.47MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 7
post: 4
product: 18
product_variation: 7
revision: 4
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Query Monitor: by John Blackbourn – 3.13.1
Companion Plugin: by Osk – 1.30
WooCommerce: by Automattic – 8.1.0-dev

### Inactive Plugins (3) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 12.4

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-19 08:22:03 +00:00
Options: ✔
Notes: 61
Onboarding: skipped

### Action Scheduler ###

Complete: 31
Oldest: 2023-08-18 08:23:30 +0000
Newest: 2023-08-18 08:49:10 +0000

Failed: 1
Oldest: 2023-08-18 08:23:30 +0000
Newest: 2023-08-18 08:23:30 +0000

Pending: 1
Oldest: 2023-08-19 08:23:30 +0000
Newest: 2023-08-19 08:23:30 +0000

### Status report information ###

Generated at: 2023-08-18 11:08:27 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by gigitux**
## What

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/10661 https://github.com/woocommerce/woocommerce-blocks/issues/10662

## Why

`woocommerce-gutenberg-products-block.php` is loaded only when WooCommerce Blocks is loaded as feature plugin.

This means when the WooCommerce Blocks is included into WooCommerce Core, the Interactivity API aren't loaded. This causes a runtime error:

image.

This PR refactors how the Interactivity API are loaded.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Install this custom build of WooCommerce that includes this patch: [woocommerce.zip](https://github.com/woocommerce/woocommerce-blocks/files/12378677/woocommerce.zip).
2. Open the Site Editor and ensure that you are using the blockified template on the Product Catalog template.
3. Visit the `/shop` page and ensure that the Product Button works as expected.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Improved how Interactivity API are loaded.

### CODE REVIEW

File: src/Domain/Bootstrap.php [hunk 1]
```diff
@@ -225,6 +231,33 @@ function() {
...
+	 */
+	protected function load_interactivity_api() {
+	// phpcs:ignore WooCommerce.Commenting.CommentHooks.MissingHookComment
+		$is_enabled = apply_filters(
+			'woocommerce_blocks_enable_interactivity_api',
+			true
+		);
+
+		if ( $is_enabled ) {
+			require_once '../Interactivity/load.php';
```
Comment (imanish003) [inline src/Domain/Bootstrap.php]: I was able to make it work after following change:
```suggestion
			require_once __DIR__ . '/../Interactivity/load.php';
```

File: src/Domain/Bootstrap.php [hunk 2]
```diff
@@ -100,6 +100,12 @@ public function __construct( Container $container ) {
 	protected function init() {
 		$this->register_dependencies();
 		$this->register_payment_methods();
+		$this->load_interactivity_api();
+		add_filter(
+			'woocommerce_blocks_enable_interactivity_api',
+			array( $this, 'has_wp_html_tag_processor' ),
+			999
+		);
```
Comment (imanish003) [inline src/Domain/Bootstrap.php]: I think this filter should be added before `$this->load_interactivity_api();`. What do you think?
```suggestion
		add_filter(
			'woocommerce_blocks_enable_interactivity_api',
			array( $this, 'has_wp_html_tag_processor' ),
			999
		);
		$this->load_interactivity_api();
```

File: src/Domain/Bootstrap.php [hunk 3]
```diff
@@ -225,6 +231,33 @@ function() {
 		);
 	}
 
+	/**
+	 * Load and set up the Interactivity API if enabled.
+	 */
+	protected function load_interactivity_api() {
+	// phpcs:ignore WooCommerce.Commenting.CommentHooks.MissingHookComment
```
Comment (imanish003) [inline src/Domain/Bootstrap.php]:
```suggestion
	 // phpcs:ignore WooCommerce.Commenting.CommentHooks.MissingHookComment
```

**Review by imanish003 — APPROVED** [review]
Hello @gigitux,
I've thoroughly tested the modifications and confirmed that they address both of the issues. Thank you immensely for your efforts on this. 🚀 🙌🏻

File: src/Domain/Bootstrap.php [hunk 4]
```diff
@@ -225,6 +231,33 @@ function() {
...
+	/**
+	 * Disable the Interactivity API if the required `WP_HTML_Tag_Processor` class
+	 * doesn't exist, regardless of whether it was enabled manually.
+	 *
+	 * @param bool $enabled Current filter value.
+	 * @return bool True if _also_ the `WP_HTML_Tag_Processor` class was found.
+	 */
+	public function has_wp_html_tag_processor( $enabled ) {
+		return $enabled && class_exists( 'WP_HTML_Tag_Processor' );
+
```
Comment (imanish003) [inline src/Domain/Bootstrap.php]: Looks like we can remove this blank line.

**Comment by imanish003** [comment]
Also, I believe it's important for us to carefully consider why we are loading the interactivity API conditionally. This is crucial because without the interactivity API, the user interface could potentially break.

File: woocommerce-gutenberg-products-block.php [hunk 5]
```diff
@@ -293,27 +293,3 @@ function woocommerce_blocks_plugin_outdated_notice() {
  * @param bool $enabled Current filter value.
  * @return bool True if _also_ the `WP_HTML_Tag_Processor` class was found.
  */
```
Comment (DAreRodz) [inline woocommerce-gutenberg-products-block.php]: This comment should be removed, shouldn't it? 👀

**Comment by gigitux** [comment]
> Also, I believe it's important for us to carefully consider why we are loading the interactivity API conditionally. This is crucial because without the interactivity API, the user interface could potentially break.

Great point!

File: woocommerce-gutenberg-products-block.php (hunk 5 above)
Comment (DAreRodz) [reply woocommerce-gutenberg-products-block.php]: I see it fixed in https://github.com/woocommerce/woocommerce-blocks/pull/10657/commits/606712785ef6968446b20ee32ee8aeb6f78aba22 👍

**Comment by gigitux** [comment]
> Also, I believe it's important for us to carefully consider why we are loading the interactivity API conditionally. This is crucial because without the interactivity API, the user interface could potentially break.

We decided to remove this logic given that WooCommerce Core has L1 support policy. `WP_HTML_Tag_Processor` is available on WordPress 6.2 and WordPress 6.3.
