### PR TITLE
Cart & Checkout: conditionally register country and state settings

### LINKED ISSUE #1751: PHP error when editing a post which contains both blocks: Cart and Checkout
**To Reproduce**
1. Create a post with a _Cart_ block.
2. Add a _Checkout_ block and try to save the post.
3. An error bar will appear saying update failed (`Updating failed.`).
4. Reload the page.
5. A PHP error appears (see screenshot).

**Expected behavior**
There should be no error.

**Screenshots**
imatge

**Additional context**
This happens because both blocks are trying to register the same settings (`shippingCountries` and `shippingCounties`):
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/src/BlockTypes/Checkout.php#L54
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/src/BlockTypes/Cart.php#L52

Currently, the asset data registry doesn't allow registering data with the same key:
* https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/src/Assets/AssetDataRegistry.php#L250

Some possible fixes:

* Prefix data registered as `cartShippingCountries` and `checkoutShippingCountries`. This way we would prevent conflicts between the data registered by both blocks. To me, that sounds more like a workaround than a real fix. But would avoid having to make any change to the Data Registry.
* Expose a method to retrieve data from the Data Registry. So we could do something like:
```PHP
$shipping_countries = $data_registry->get( 'shippingCountries' );
if ( ! $shipping_countries ) {
	$data_registry->add( 'shippingCountries', ... );
}
```
* Allow overriding data when registered with the same key. So calling `$data_registry->add( 'shippingCountries', ... );` the second time would overwrite whatever was in `shippingCountries`.
* Ignore new data when registered with the same key. So calling `$data_registry->add( 'shippingCountries', ... );` the second time would do nothing but would not throw an error.

cc @nerrad for feedback.

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #1751.

### How to test the changes in this Pull Request:

1. Create a post and add both the _Cart_ and _Checkout_ blocks.
2. Save it and verify it doesn't show an error.
3. Reload the editor and verify it doesn't show an error either.

### CODE REVIEW

File: src/BlockTypes/Cart.php [hunk 1]
```diff
@@ -49,8 +49,12 @@ public function render( $attributes = array(), $content = '' ) {
 		$data_registry = Package::container()->get(
 			\Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry::class
 		);
-		$data_registry->add( 'shippingCountries', WC()->countries->get_shipping_countries() );
-		$data_registry->add( 'shippingStates', WC()->countries->get_shipping_country_states() );
+		if ( ! $data_registry->exists( 'shippingCountries' ) ) {
+			$data_registry->add( 'shippingCountries', WC()->countries->get_shipping_countries() );
```
Comment (mikejolley) [inline src/BlockTypes/Cart.php]: I wonder if we could add a method combining both to reduce the code here? Not sure what it would be called though :D

Comment (Aljullu) [reply src/BlockTypes/Cart.php]: Yeah... I was wondering the same. I like the current implementation because each method does just one thing, but if we see this pattern used over and over again (checking if a setting exists, and then adding it) it might make sense creating a method (or a util function) to do both.

I still thing we can defer it in case we see this is used in several other blocks. For now it's only _Cart_ and _Checkout_ so I think it's ok as-is.

**Comment by Aljullu** [comment]
> Do we also need test coverage?

Yes! Added in 39888cf8f991cb149b9925b4da72df6119b73c5d.

File: src/BlockTypes/Cart.php (hunk 1 above)
Comment (senadir) [reply src/BlockTypes/Cart.php]: it does make sense to have the same function, I think `add` should do that (add if not exist)

Comment (Aljullu) [reply src/BlockTypes/Cart.php]: We more or less discussed that in #1751. I recognize I don't have a strong opinion about this. The issue with `add` is that the consumer would not know if it overrided the previous value or it was ignored, so we thought that an explicit method to check for a setting existence would avoid possible confusion.

I think we can work on that in a follow-up if we think that's something that needs to be fixed.
