### PR TITLE
fix translation quantities

### LINKED ISSUE #1413: Fix incorrect translation string usage for numbered values.
See comment posted here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1032#discussion_r359316102.

Along with fixing what was noted in that comment, we should also do a review of the code to see if there are any other instances where a numbered string exists that needs addressed.

### PR DESCRIPTION
**Pull request by senadir**
fixes #1413

### CODE REVIEW

File: assets/js/base/components/checkbox-list/index.js [hunk 1]
```diff
@@ -48,17 +48,21 @@ const CheckboxList = ( {
...
+								optionCount - limit,
 								'woo-gutenberg-products-block'
 							),
 							optionCount - limit
 						) }
 					>
 						{ // translators: %s number of options to reveal.
 						sprintf(
-							__(
+							_n(
```
Comment (nerrad) [inline assets/js/base/components/checkbox-list/index.js]: I know this wasn't added in this pull but the translators comment is in the wrong place here.  It should be in the line above the `_n`

File: assets/js/base/components/checkbox-list/index.js [hunk 2]
```diff
@@ -99,9 +103,9 @@ const CheckboxList = ( {
 				{ options.map( ( option, index ) => (
 					<Fragment key={ option.value }>
 						<li
-							{ ...shouldTruncateOptions &&
+							{ ...( shouldTruncateOptions &&
```
Comment (nerrad) [inline assets/js/base/components/checkbox-list/index.js]: good catch!

Comment (senadir) [reply assets/js/base/components/checkbox-list/index.js]: Actually the post-commit linter caught this and I didn’t notice it until you commented, good job robot 🤖
