### PR TITLE
Price filter: preserve previous constraints while loading

### LINKED ISSUE #1375: [WC 3.9 beta1]: Filter by Price Block - NaN is displayed instead of zero while waiting for the filter results
**Describe the bug**

Found this bug during WooCommerce 3.9 beta1 testing. 

In Filter by Price Block - NaN is displayed instead of zero while waiting for the filter results. 

**To Reproduce**

1. Create a page or a post where you can add blocks;
2. Add `Filter by Price` block and `All Products` block underneath it;
3. Set `Filter by Price` block with price range to be `Text` and enable the filter button:

f1

4. Publish the page/post;
5. Navigate to that page/post at the front end;
6. Adjust the crate of the bar and click on `Go` button to filter the results;
7. Note that while the results are loading, `NaN` is shown instead of zero `0` in the `Price` filed. See screencast below:

**Expected behavior**

I expected zero `0` to be shown while the result of the filtering are loaded. 

**Screenshots**

See screenshot and screencast above. 

**WordPress (please complete the following information):**

* Core version: 5.3.1
* Gutenberg version (if installed): not installed
* WooCommerce version: 3.9 beta1
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: No

**Desktop (please complete the following information):**

* OS: macOS Catalina
* Browser: Chrome
* Version: 78.0.3904.108 (Official Build) (64-bit)

**Additional context**

Thanks to @rantoncuadrado for spotting this issue during his testing.

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #1375.

This PR makes it so the previous constraints are preserved in the Price filter, so a `NaN` value is not displayed while loading. I also took the chance to add tests to `formatPrice`.

### Screenshots

_Before:_

_After:_

### How to test the changes in this Pull Request:

Follow the steps described in #1375 and verify the bug is no longer reproducible.

### Changelog

> Price Filter: fix NaN values shown in some occasions while loading .

### CODE REVIEW

File: assets/js/base/utils/test/price.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+ * Internal dependencies
+ */
+import { formatPrice } from '../price';
+
+describe( 'formatPrice', () => {
+	test.each`
+		value        | priceFormat   | currencySymbol | expected
+		${10}        | ${'%1$s%2$s'} | ${'€'}         | ${'€10'}
+		${10}        | ${'%2$s%1$s'} | ${'€'}         | ${'10€'}
+		${10}        | ${'%2$s%1$s'} | ${'$'}         | ${'10$'}
```
Comment (nerrad) [inline assets/js/base/utils/test/price.js]: Nice!  Thanks for adding this test - good practice to have all our utilities covered by tests so I appreciate this :)

File: assets/js/blocks/price-filter/block.js [hunk 2]
```diff
@@ -5,13 +5,38 @@ import {
...
+	const previousMaxConstraint = usePrevious( currentMaxConstraint, ( val ) =>
+		Number.isFinite( val )
+	);
+	const maxConstraint = Number.isFinite( currentMaxConstraint )
+		? currentMaxConstraint
+		: previousMaxConstraint;
+
+	return { minConstraint, maxConstraint };
+};
+
```
Comment (nerrad) [inline assets/js/blocks/price-filter/block.js]: Awesome idea to extract this to a hook.  As a side-effect, it also makes this behaviour more testable as it's isolated from the component.  Would you mind adding some tests for this hook that help verify it's behaviour?

**Comment by Aljullu** [comment]
Thanks for the review @nerrad! I added some tests (and refactored the code a bit) in 4d2c961ac08e9059c7138dba389456f13b4bf4e7.
