### PR TITLE
 Hide the shipping address form from Checkout Block in Editor and rename the Billing Address label when "Force shipping to the customer billing address" is enabled.

### LINKED ISSUE #7394: Hide shipping address form from the Editor when "Force shipping to the customer billing address" is enabled.
## Describe the bug

In PRs #7268 and #7393, we hide the shipping address form from the front end for the Checkout block when `Force shipping to the customer billing address` is enabled. We need to hide the shipping address inner block in the Checkout block Editor as well. We also need to change the label of the billing address inner block from `Billing Address` to `Billing and Shipping Address` and it should mention: `Enter the billing and shipping address that matches your payment method.` in the default block description. 

 
We need to find settings tied to the shipping address inner block and surface them in the billing address inner block. 

More details: p1665655511491119/1665654716.887749-slack-C8X6Q7XQU

## To reproduce

1. Go to `wp-admin/admin.php?page=wc-settings&tab=shipping&section=options` page.
2. Enable the `Force shipping to the customer billing address` option and save the changes.
3. Go to Checkout block Editor, and notice both billing and shipping inner blocks are visible

## Expected behavior

Only billing inner block should be visible.

### LINKED ISSUE #7513: Update Billing address block labels in frontend
## Describe the bug

In PRs #7268 and #7393, we hide the shipping address form from the front end for the Checkout block when `Force shipping to the customer billing address` is enabled. We also need to change the label of the billing address inner block from `Billing Address` to `Billing and Shipping Address`

## To reproduce

1. Go to `wp-admin/admin.php?page=wc-settings&tab=shipping&section=options` page.
2. Enable the `Force shipping to the customer billing address` option and save the changes.
3. Go to Checkout page on the frontend.
4. Go to the Checkout block front-end, and notice shipping address form is not visible and billing inner block label is "Billing Address"

## Expected behavior

Billing inner block label should be "Billing and Shipping Address" in frontend and editor.

## Screenshots
image

## Expected
It should also mention: `Enter the billing and shipping address that matches your payment method.`

image

## Additional context

More details: p1666792315010919-slack-C011ENB20Q1

### PR DESCRIPTION
**Pull request by tarunvijwani**
In PRs #7268 and #7393, we hide the shipping address form from the front end for the Checkout block when `Force shipping to the customer billing address` is enabled. 

In this PR, we hide the shipping address form from the Editor and rename the billing address label when `Force shipping to the customer billing address` is enabled.

Fixes #7513
Fixes #7394 

## Changes in the PR
- Moved default title and descriptions in constants.tsx. 
- Fixed TypeScript errors for attributes.  
- Hide the Shipping Address block from the editor. 
- Rename Billing Address labels. 

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Editor Before | Editor After |
| ------ | ----- |
|image|image|
| Frontend Before | Frontend After |
| image | image|

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Go to `wp-admin/admin.php?page=wc-settings&tab=shipping&section=options` page.
2. Enable the `Force shipping to the customer billing address` option and save the changes.
3. Go to Checkout block Editor, and confirm Shipping Address form is not visible.
4. Confirm Billing Address form label is `Billing and shipping address` and the description is `Enter the billing and shipping address that matches your payment method.`
5. Go to the Checkout block front-end, and confirm Shipping Address form is not visible.
6. Confirm Billing Address form label is `Billing and shipping address` and the description is `Enter the billing and shipping address that matches your payment method.`
7. Change the billing address, confirm the shipping address in the order summary gets changed, and shipping methods are updated. 
8. Disable the `Force shipping to the customer billing address` option and save the changes.
9. Confirm Shipping Address form is visible in both the frontend and Editor. 
10. Please test around this issue with multiple use cases. 

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Hide the shipping address form from Checkout Block in Editor and rename the Billing Address label when "Force shipping to the customer billing address" is enabled.

### CODE REVIEW

File: assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/attributes.tsx [hunk 1]
```diff
@@ -1,20 +1,13 @@
...
-import { __ } from '@wordpress/i18n';
-
 /**
  * Internal dependencies
  */
 import formStepAttributes from '../../form-step/attributes';
+import { DEFAULT_TITLE, DEFAULT_DESCRIPTION } from './constants';
 
-export default {
+export const attributes: Record< string, Record< string, unknown > > = {
```
Comment (opr) [inline assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/attributes.tsx]: Could we use the Gutenberg type `BlockAttributes` here?

You'd need to `import { BlockAttributes } from '@wordpress/blocks';`

File: assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/edit.tsx [hunk 2]
```diff
@@ -41,12 +46,30 @@ export const Edit = ( {
...
+	const { showBillingFields, forcedBillingAddress } = useCheckoutAddress();
 
-	if ( ! showBillingFields ) {
+	if ( ! showBillingFields && ! forcedBillingAddress ) {
 		return null;
 	}
-
+	if ( forcedBillingAddress ) {
+		attributes.title =
+			attributes.title === DEFAULT_TITLE
```
Comment (opr) [inline assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/edit.tsx]: This ternary operator is a little hard to reason with, maybe adding comments would be useful here.

Comment (opr) [reply assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/edit.tsx]: I would also consider if we need the `if/else` structure here, or if it would be better to move this logic into a separate function, remove the use of ternary operators and make this easier to read, what do you think?

File: assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/frontend.tsx [hunk 3]
```diff
@@ -43,7 +49,19 @@ const FrontendBlock = ( {
 	if ( ! showBillingFields && ! forcedBillingAddress ) {
 		return null;
 	}
-
+	if ( forcedBillingAddress ) {
```
Comment (opr) [inline assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/frontend.tsx]: Please see my comment about `if/else` and ternary operators in the `edit.tsx` file and consider if the same applies here.

File: assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/attributes.tsx [hunk 4]
```diff
@@ -1,20 +1,13 @@
...
- */
-import { __ } from '@wordpress/i18n';
-
 /**
  * Internal dependencies
  */
 import formStepAttributes from '../../form-step/attributes';
+import { DEFAULT_TITLE, DEFAULT_DESCRIPTION } from './constants';
 
-export default {
```
Comment (opr) [inline assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/attributes.tsx:11]: How come we removed this and now only export a named const?

Should we add `export default attributes` at the bottom of this file?

**Review by opr — CHANGES_REQUESTED** [review]
Hey @tarunvijwani thanks for working on this, it looks great! I have added a few comments, but nothing major.

File: assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/edit.tsx (hunk 2 above)
Comment (tarunvijwani) [reply assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/edit.tsx]: That's actually a good idea! I have moved the logic to a different function and added the comments for better understanding. Thank you! 🙂

File: assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/attributes.tsx (hunk 4 above)
Comment (tarunvijwani) [reply assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/attributes.tsx:11]: Ah, I missed that. This is fixed now. Thank you!

File: assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/utils.tsx [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+	DEFAULT_FORCED_BILLING_DESCRIPTION,
+	DEFAULT_FORCED_BILLING_TITLE,
+} from './constants';
+
+export const getBillingAddresssBlockTitle = (
+	title: string,
+	forcedBillingAddress: boolean
+): string => {
+	if ( forcedBillingAddress ) {
+		// returns default forced billing title when forced billing address is enabled and there is no title set
```
Comment (opr) [inline assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/utils.tsx]: Slight nit pick on these comments: please ensure we follow the WP Coding guidelines here: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/#comments

Besides this, these new functions look good!

Comment (tarunvijwani) [reply assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/utils.tsx]: Thank you for the guide! I have fixed the comments. 👍

File: assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/attributes.tsx (hunk 1 above)
Comment (tarunvijwani) [reply assets/js/blocks/checkout/inner-blocks/checkout-billing-address-block/attributes.tsx]: Yes, that's a better way to define types. Added the `BlockAttributes` type. 👍

**Review by opr — APPROVED** [review]
Great work Tarun, this looks good to merge now! 🥳
