### PR TITLE
[Product Collection] Fix: HTML Entity Decoding in Taxonomy Controls

### LINKED ISSUE #9242: Products block: taxonomy filter names are not decoded properly
## To reproduce

1. Go to Products > Categories and create a category with name `Clothing & Accessories`.
2. Create a new post and add the Product Collection block.
3. In the sidebar, add a Taxonomies filter and select the Product category you just created.
4. Notice the name is not decoded properly.

imatge

## Expected behavior

The name should be shown the same way it was introduced when created.

cc @kmanijak in case you think this should be included to the Products epic.

### PR DESCRIPTION
**Pull request by imanish003**
## What

Fix HTML entity decoding issue in Taxonomy filters. You can see the issue in screenshot below:
image

Fixes #9242 

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Create a new post & add Product Collection block to it.
2. From filters dropdown, Add “Taxonomies” filter. This will add “Product Categories” and “Product Tag” taxonomy filters to inspector control.
3. Inside “Product Categories” filter, search a category that contains an HTML Entity.
    1. If you don’t have any category with HTML entities, then you will need to either rename the existing category or create a new category with HTML entities. For example, “Electronics & Gadgets” or “Health & Wellness / Supplements”
    2. Verify that HTML entities show as expected. 
4. Perform step 3 for “Product Tags” too.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [X] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:

* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:

* [ ] This PR has a UI change and has been cross-browser tested at different viewport sizes on both the frontend and in the editor.
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Product Collection - Fix: HTML Entity Decoding in Taxonomy Controls

### CODE REVIEW

**Review by kmanijak — APPROVED** [review]
Nice work!

Works for categories **&** tags! ( 😜  )
image

File: assets/js/blocks/product-collection/inspector-controls/taxonomy-controls/taxonomy-item.tsx [hunk 1]
```diff
@@ -250,6 +251,10 @@ const TaxonomyItem = ( { taxonomy, termIds, onChange }: TaxonomyItemProps ) => {
 		onChange( newTermIds );
 	};
 
+	const decodeHTMLEntities = ( value: string ) => {
+		return decodeEntities( value ) || '';
```
Comment (kmanijak) [inline assets/js/blocks/product-collection/inspector-controls/taxonomy-controls/taxonomy-item.tsx:255]: What's the need for the wrapping function and `|| ''` part? Seems like [`decodeEntities`](https://www.npmjs.com/package/@wordpress/html-entities#decodeentities) always returns a string.

Comment (imanish003) [reply assets/js/blocks/product-collection/inspector-controls/taxonomy-controls/taxonomy-item.tsx:255]: As you can see in [this code](https://github.com/WordPress/gutenberg/blob/9905301c5f783141177f61e37851eb9e7e96b875/packages/html-entities/src/index.js#L18-L21), it may return non-string value. Therefore, Just to be extra careful, I added `|| ''` part.

Comment (imanish003) [reply assets/js/blocks/product-collection/inspector-controls/taxonomy-controls/taxonomy-item.tsx:255]: When I implemented same thing for hand-picked products [here](https://github.com/woocommerce/woocommerce-blocks/blob/fd56c6c94df2ea1f7d2434fca3215590af75cbde/assets/js/blocks/product-collection/inspector-controls/hand-picked-products-control.tsx#L100-L110), it resulted in an error. That’s why I added extra check here.
