### PR TITLE
Blocks: Restrict row/column values to only valid values

### LINKED ISSUE #359: Setting column and row settings to value greater than 6
**Describe the bug**
Adjusting the columns or row settings by typing a value in the input that is greater than the expected maximum (6) leads to surprising results. 

**To Reproduce**

1. Insert a block that displays products in a grid
2. Change the number of columns by typing 7 into the input (anything greater than 6 will cause this to happen)
3. Note the number of columns jumps to an arbitrarily large number in the editor, that doesn't necessarily match the number in the input. 
4. Note that the layout on the published page only has two columns

**Expected behavior**
We should validate the input number, and not allow for numbers greater than 6.  Update the labels to read :Columns (Maximum 6) to set expectations, or show a tool tip that indicates six is the maximum value after a failed validation. 

**Screenshots**

Setting the columns input to seven (editor)

screen shot 2019-01-22 at 2 07 16 pm

Setting the columns input to seven (front end)

screen shot 2019-01-22 at 2 05 10 pm

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #359 – It was possible to set the row/column values to numbers > 6, which in addition to not looking right, was not supported by the CSS. This PR adds a new control called `LayoutControl`, which wraps the two `RangeControl`s for row and column. It also adds a check to limit each value to the min/max set up by the site/theme settings.

### How to test the changes in this Pull Request:

There should be no visual changes.

1. Edit any block with row & col settings: Newest Products, Best Selling Products, Products by Category, etc
2. Attempt to change the rows or columns values to larger than 6 by entering text in the text box
3. Expect: you can't, it defaults to 6

### CODE REVIEW

File: assets/js/components/layout-control/index.js [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+import { __ } from '@wordpress/i18n';
+import { clamp, isNaN } from 'lodash';
+import { Fragment } from '@wordpress/element';
+import PropTypes from 'prop-types';
+import { RangeControl } from '@wordpress/components';
+
+/**
+ * A combination of range controls for product grid layout settings.
+ */
+const LayoutControl = ( { columns, rows, setAttributes } ) => {
```
Comment (coderkevin) [inline assets/js/components/layout-control/index.js]: Should this be called "GridLayoutControl" to be more specific?

**Review by coderkevin — APPROVED** [review]
Code looks good, I just have a couple comments not directly related to this PR that perhaps should be filed as an issue:

1. The preview CTA button appears to always be "Add to cart" regardless of what is displayed on the front end. Is this desirable?
2. The CTA button text wrap is pretty rough, even though I've got plenty of width left over in my browser frame.

test_post_ _two_wordpress_test

Pre-approving

**Comment by coderkevin** [comment]
@LevinMedia Can we get your input on the above formatting issues? Thanks.

**Comment by ryelle** [comment]
> The preview CTA button appears to always be "Add to cart" regardless of what is displayed on the front end. Is this desirable?

IMO this is OK for a preview, but I'll let @jameskoster weigh in.

> The CTA button text wrap is pretty rough, even though I've got plenty of width left over in my browser frame.

Themes control the content width, and twenty nineteen does have a slightly narrow, offset-of-center content area - does that match what you're seeing? It seems that the button text wrap issue comes from the core (Twenty Nineteen) button styles. We could override that, I suppose - I only see the issue on the front end of the site, so it would probably be fine.

File: assets/js/components/layout-control/index.js (hunk 1 above)
Comment (ryelle) [reply assets/js/components/layout-control/index.js]: I was thinking that after I'd written this up, so yeah - I've changed it.
