### PR TITLE
Use theme's body background color as the mini cart contents default background color

### LINKED ISSUE #7501: TT3 theme: Mini Cart block is not legible with some TT3 style variations
## To reproduce

1. Download and activate [TT3](https://github.com/WordPress/twentytwentythree) select the Pilgrimage style variation (see screenshot below).
2. Add the Mini Cart block to a post or page.
3. In the frontend, click on the Mini Cart button to open the drawer.
4. Notice most of the text can't be read.

## Screenshots

imatge

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #7501 

This PR introduces an alternative approach to https://github.com/woocommerce/woocommerce-blocks/pull/7503. Instead of fixing the mini cart contents background per theme basis, we get the background color of the body element and use it as the default background color:
- On the front end, we get the background color of the body element using `getComputedStyle`.
- In the Site Editor, we parse the editor style and get the original value of the background color of the `.editor-styles-wrapper` element. By doing so, the Mini Cart Contents background works when users change the preset style.

### Screenshots

https://user-images.githubusercontent.com/5423135/198499307-a8249428-98db-4d00-9fc4-23f77c9ee9e6.mov

| Before | After |
| ------ | ----- |
| imatge | imatge |
| imatge | imatge |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Download and activate [TT3](https://github.com/WordPress/twentytwentythree) select the Pilgrimage style variation (see screenshot below).
2. Add the Mini Cart block to a post or page.
3. In the frontend, click on the Mini Cart button to open the drawer.
4. Verify the background is dark and text can be read properly.
5. Back in the editor, select the Mini Cart block and press on `Edit Mini Cart template part` in the sidebar. That will open the template editor.
6. Verify text is legible there as well:
imatge
7. Try with all other TT3 theme variations and verify text can be properly read in all of them.
8. Repeat all steps above with TT2.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Update the Mini Cart block drawer to honor the theme's background.

### CODE REVIEW

File: assets/js/blocks/mini-cart/frontend.ts [hunk 1]
```diff
@@ -152,4 +152,18 @@ window.addEventListener( 'load', () => {
 			);
 		}
 	} );
+
+	const head = document.head || document.getElementsByTagName( 'head' )[ 0 ];
+	const style = document.createElement( 'style' );
+	const body = document.body || document.getElementsByTagName( 'body' )[ 0 ];
```
Comment (Aljullu) [inline assets/js/blocks/mini-cart/frontend.ts]: Just curious, do you think this check of `document.body` is needed? In several other places of this file we assume `document.body` exists.

File: assets/js/blocks/mini-cart/frontend.ts [hunk 2]
```diff
@@ -152,4 +152,18 @@ window.addEventListener( 'load', () => {
...
+	const backgroundColor = getComputedStyle( body ).backgroundColor;
```
Comment (Aljullu) [inline assets/js/blocks/mini-cart/frontend.ts]: What do you think if, instead of only copying `backgroundColor` we copy the entire `background` declaration? In some style variations it makes a difference (ie: Pilgrimage and the ones which have gradients). But I wonder if there are some risks from this approach. :thinking:

File: assets/js/blocks/mini-cart/frontend.ts [hunk 3]
```diff
@@ -152,4 +152,18 @@ window.addEventListener( 'load', () => {
...
+
+	head.appendChild( style );
+	style.appendChild(
+		document.createTextNode(
+			`:where(.wp-block-woocommerce-mini-cart-contents) {
+				background-color: ${ backgroundColor };
+			}`
+		)
+	);
```
Comment (Aljullu) [inline assets/js/blocks/mini-cart/frontend.ts]: Nit: Things might have changed in browsers since I read about it, but I think if you do it the other way around (append the CSS into `style` and then `style` into `head`), the browser only needs to update the DOM once instead of twice.

```suggestion
	style.appendChild(
		document.createTextNode(
			`:where(.wp-block-woocommerce-mini-cart-contents) {
				background-color: ${ backgroundColor };
			}`
		)
	);
	head.appendChild( style );
```

**Review by Aljullu — COMMENTED** [review]
Oooh, I love this approach. It feels a bit _hacky_, but it works wonderfully and it seems to be the only approach we have right now that works cross-theme.

I left several questions below, but none of them is really blocking.

File: assets/js/blocks/mini-cart/frontend.ts (hunk 3 above)
Comment (dinhtungdu) [reply assets/js/blocks/mini-cart/frontend.ts]: 100% agree!

File: assets/js/blocks/mini-cart/frontend.ts (hunk 2 above)
Comment (dinhtungdu) [reply assets/js/blocks/mini-cart/frontend.ts]: The risk here is the background can override the background color set by users. For example, gradient uses background-image, which will display regardless of the background color.

File: assets/js/blocks/mini-cart/frontend.ts (hunk 1 above)
Comment (dinhtungdu) [reply assets/js/blocks/mini-cart/frontend.ts]: My bad! I will fix it. I think we can also use `document.head` without a fallback.

File: assets/js/blocks/mini-cart/frontend.ts (hunk 2 above)
Comment (Aljullu) [reply assets/js/blocks/mini-cart/frontend.ts]: Oh, right. Good point!

**Review by Aljullu — APPROVED** [review]
Tested and it works great. Thanks for working on this, @dinhtungdu!

Btw, heads-up that I marked the `WooCommerce Core` option under _WooCommerce Visibility_.

**Review by Aljullu — APPROVED** [review]
New changes are testing well and LGTM. :ship:

**Comment by dinhtungdu** [comment]
Failed tests relate to checkout and Gutenberg. Merging...
