### PR TITLE
Switch to correct view if inner block is selected

### LINKED ISSUE #5351: Editor: On the sidebar - list view, when the user clicks on a block related to a different status, the editor doesn't render the block with the new status
## Describe the bug
For an improved UX the editor should render the block with the new status.

## To reproduce

1. Open template parts.
2. Edit the Mini Cart template.
3. Be sure that in the editor the block state is set to `Filled`
4. Open the list view and click on `Empty Mini Cart`.
5. Check that in the editor the block state doesn't change

https://user-images.githubusercontent.com/4463174/145421682-c77f754b-2d1f-4dac-b5d3-17b2642b3fb2.mp4

## Expected behavior
For an improved UX the editor should render the block with the new status after that the user clicks on `Empty Mini Cart`.

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #5351

This PR watches for the change of current selected block then switch the current view of the view switcher if an inner block is selected.

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
### Manual Testing

How to test the changes in this Pull Request:

1. Insert or edit the Cart block.
2. Open the block navigation list panel.
3. Given the current view is the Filled Cart.
4. Select an inner block of Empty Cart.
5. See the view changes to Empty.
6. Repeat all steps above to test Mini Cart Contents block.

### User Facing Testing
These are steps for user testing (where "user" is someone interacting with this change that is not editing any code).
* [x] Same as above, or
* [ ] See steps below.

### Changelog

> Cart block: switch to correct view if inner block is selected.

### CODE REVIEW

File: assets/js/blocks/cart-checkout/shared/use-view-switcher.tsx [hunk 1]
```diff
@@ -23,8 +23,47 @@ export const useViewSwitcher = (
 } => {
 	const initialView = views[ 0 ];
 	const [ currentView, setCurrentView ] = useState( initialView );
+	const viewNames = views.map( ( { view } ) => view );
```
Comment (Aljullu) [inline assets/js/blocks/cart-checkout/shared/use-view-switcher.tsx]: This line can be moved inside the `useEffect()`, `viewNames` doesn't seem to be used outside of the effect.

**Review by Aljullu — COMMENTED** [review]
Works like a charm! :clap: 

Code looks good but I have a performance improvement proposal: can we move the [`views` definition](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/blocks/cart-checkout/mini-cart-contents/edit.tsx#L39-L50) from Cart and Mini Cart blocks outside of the component? This way the array is persisted across renders and that would avoid that `useEffect()` running on every render.

**Comment by dinhtungdu** [comment]
@Aljullu thanks for the suggestion, I moved those definitions outside of components in bdf9748, can you please take another look at this PR?

**Review by Aljullu — APPROVED** [review]
Thanks for updating the PR @dinhtungdu, this is working like a charm. :clap:
