### PR TITLE
Store Customization > Fetch product images from the Pexels API

### LINKED ISSUE #11461: Store Customization > Update the images provider for the Customize your Store Experience
Given several restrictions and limitations we have found with the Verticals API, including low availability of images and incorrect classification of images, we need to explore alternatives to ensure the assignment of images to patterns and products by AI is consistent.

For Woo Express, the decision from the design team is to replace it with Pexels. For self-hosted, to avoid licensing restrictions, we should rely on other alternatives, such as Openverse.

### PR DESCRIPTION
**Pull request by nefeline**
## What

Update the image provider for the Customize Your Store experience, migrating from Verticals to Pexels. Additional changes made on this PR also include:

- Performance optimization for the creation of dummy products and assignment of images.
- Ensure the `'woocommerce_blocks_allow_ai_connection'` option is updated to true whenever the store owner updates their business description (either via the onboarding flow or the store admin area). The option that stores the business description is available within WooExpress exclusively. The `'woocommerce_blocks_allow_ai_connection'` option will be updated only if the site has an active connection with JetPack (therefore they accepted the terms and conditions).
- Updates the Prompts used for generating AI content for Products and Patterns. Note: there's an improvement to the AI-assigned images based on the changes made here, but additional fine-tuning is planned as part of a separate PR.

### Implementation details

Instead of making requests directly to the Pexels API, we are now relying on WP.com's endpoint (`'/wpcom/v2/external-media/list/pexels'`) as a middleman to ensure there won't be any restrictions regarding rate limiting. JetPack is a dependency for this connection as their built-in client for this endpoint is being used to power the requests. 

Fixes #11461

## Why

Given several restrictions and limitations we have found with the Verticals API, including low availability of images and incorrect classification of images, this update ensures the assignment of images to patterns and products by AI is consistent and more accurate.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

### Initial Setup

- Request access to https://woo-delightfully-luminous-kryptonite.wpcomstaging.com/ if you still don't have it.

Or alternatively, create a new WordPress install from scratch (make sure the install is a Jurassic Ninja install or equivalent. Otherwise you won't be able to connect with Jetpack to test this PR).

- Install and activate [this version](https://github.com/woocommerce/woocommerce/releases/tag/untagged-eb8de7515421456195de) of WooCommerce.
- Install and activate WooCommerce Blocks from the following zip file: [woocommerce-gutenberg-products-block.zip](https://github.com/woocommerce/woocommerce-blocks/files/13174321/woocommerce-gutenberg-products-block.zip) 
- Install and activate Jetpack.
- In your wp-admin, you should see the following section for Jetpack:

Screenshot 2023-10-22 at 09 29 08

- Click on "Set up Jetpack" and make sure the connection is successful:

Screenshot 2023-10-22 at 09 29 08

- Install and activate Woo AI (the plugin is available [within the monorepo](https://github.com/woocommerce/woocommerce/tree/trunk/plugins))
- Install and activate WooCommerce Beta Tester (the plugin is available [within the monorepo](https://github.com/woocommerce/woocommerce/tree/trunk/plugins))
- Head over to `/wp-admin/tools.php?page=woocommerce-admin-test-helper` and enable `customize-store` feature flag:

Screenshot 2023-10-22 at 10 32 24

### Test the AI-managed images

1. Head over to Home > Customize your Store:
 
Screenshot 2023-10-22 at 09 29 08

2. Click on design with AI.
3. Type a description for your business.
4. Make sure the AI content is properly generated and images are assigned to patterns and products based on the description provided.

### Known limitations: 

* In a few cases, you may notice that new images are not assigned to a product or pattern in particular. This is still under investigation, and a separate PR will be opened to address this limitation.
* Sometimes, depending on the store description, images are not tightly associated with the expected content: more fine-tuning is happening in upcoming PRs.

* [x] Do not include in the Testing Notes 
* [] Should be tested by the development team exclusively 

## Screenshots or screencast

https://github.com/woocommerce/woocommerce-blocks/assets/15730971/2ee290e8-d6e9-49b0-98ee-e5b59f44a427

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Update the image provider for the Customize Your Store experience, migrating from Verticals to Pexels.

### CODE REVIEW

File: src/BlockPatterns.php [hunk 1]
```diff
@@ -53,10 +53,37 @@ public function __construct( Package $package ) {
...
+	/**
+	 * Make sure the 'woocommerce_blocks_allow_ai_connection' option is set to true if the site is connected to AI.
+	 *
+	 * @param string $option The option name.
+	 * @param string $value The option value.
+	 *
+	 * @return bool
+	 */
+	public function update_ai_connection_allowed_option( $option, $value ): bool {
+		$ai_connection = new Connection();
```
Comment (gigitux) [inline src/BlockPatterns.php:70]: NIT: Should this class be a Singleton? Every time that we get the jwt_token, we do a fetch request.

File: src/BlockPatterns.php [hunk 2]
```diff
@@ -274,16 +301,40 @@ public function update_patterns_content( $value ) {
...
+
+		$populate_products = ( new ProductUpdater() )->generate_content( $ai_connection, $token, $images, $business_description );
+
+		if ( is_wp_error( $populate_products ) ) {
+			return $populate_products->get_error_message();
+		}
 
-		( new PatternUpdater() )->generate_content( $vertical_images, $business_description );
-		( new ProductUpdater() )->generate_content( $vertical_images, $business_description );
+		return true;
```
Comment (gigitux) [inline src/BlockPatterns.php:338]: NIT: I would remove this return value and update the PHPDoc to:

```
* @return void|\WP_Error
```

File: src/Images/Pexels.php [hunk 3]
```diff
@@ -0,0 +1,94 @@
+<?php
+
+namespace Automattic\WooCommerce\Blocks\Images;
+
+use Automattic\WooCommerce\Blocks\AI\Connection;
+
+/**
+ * Pexels API client.
+ */
+class Pexels {
```
Comment (gigitux) [inline src/Images/Pexels.php:12]: Should we mark this class as `@internal`?

File: src/Images/Pexels.php [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+			return new \WP_Error( 'pexels_api_error', __( 'Request to the Pexels API failed.', 'woo-gutenberg-products-block' ), $error_msg );
+		}
+
+		$response = $response_data['media'] ?? $response_data;
+
+		if ( is_array( $response ) ) {
+			shuffle( $response );
+		}
+
+		return $response;
```
Comment (gigitux) [inline src/Images/Pexels.php]: Not sure, but if `response` is a string, we could return a string. I would return an empty array to avoid any potential issues.

File: src/Patterns/PatternUpdater.php [hunk 5]
```diff
@@ -194,52 +175,53 @@ private function pattern_has_images( array $pattern ): bool {
...
 
 	/**
-	 * Returns the image format for the given vertical image.
+	 * Returns the selected image format. Defaults to landscape.
 	 *
-	 * @param array $vertical_image The vertical image.
+	 * @param array $selected_image The selected image to be assigned to the pattern.
 	 *
-	 * @return string The image format, or an empty string if the image format is invalid.
+	 * @return mixed
```
Comment (gigitux) [inline src/Patterns/PatternUpdater.php]: NIT: I think that we can keep the return value as `string`.

**Review by gigitux — APPROVED** [review]
Thanks for your great work! Overall, the code looks great. I added some comments, but I would suggest skipping the NIT ones. We can iterate and improve the code in successive iterations.

I tested this PR with the prompt:

> I want to sell football clothes and gadgets.

I noticed that some images are not related to my prompt and some content is missing:

File: src/BlockPatterns.php (hunk 1 above)
Comment (nefeline) [reply src/BlockPatterns.php:70]: Good call, I'm doing this change on a separate PR 👍 !

File: src/Images/Pexels.php (hunk 3 above)
Comment (nefeline) [reply src/Images/Pexels.php:12]: Good call, updated! 780df8ed51d0d9b2dc7ae1e85ec11dcf282fd230

File: src/Images/Pexels.php (hunk 4 above)
Comment (nefeline) [reply src/Images/Pexels.php]: Thanks for the suggestion, updated! 780df8ed51d0d9b2dc7ae1e85ec11dcf282fd230

File: src/Patterns/PatternUpdater.php (hunk 5 above)
Comment (nefeline) [reply src/Patterns/PatternUpdater.php]: Nice catch: done! 780df8ed51d0d9b2dc7ae1e85ec11dcf282fd230

**Comment by nefeline** [comment]
> Thanks for your great work! Overall, the code looks great. I added some comments, but I would suggest skipping the NIT ones. We can iterate and improve the code in successive iterations.
> I tested this PR with the prompt:
> I want to sell football clothes and gadgets.
> I noticed that some images are not related to my prompt and some content is missing:

Thanks for the testing here @gigitux ! This was a consequence of the limitations mentioned in the description of this PR. I did some additional fine-tuning to the prompts, between other changes, to ensure the store is updated with content/images that better fit the description. I still wanna do some additional changes to improve consistency, but we need to unblock the call for testing now, so I'm working on these changes as part of a separate PR.

Thanks again for your review and tests here; much appreciated! 🙏

**Comment by gigitux** [comment]
> I still wanna do some additional changes to improve consistency, but we need to unblock the call for testing now, so I'm working on these changes as part of a separate PR.

Completely agree! Let's 🚢 !
