### PR TITLE
Load core translations for PHP strings that don't have a translation

### LINKED ISSUE #1272: Sale! Label not translated in WooCommerce Blocks
**Describe the bug**
When adding products on a page using Gutenberg blocks, the Sale! label doesn't translate correctly, 

**To Reproduce**
1. Change WordPress language (I used Polish)
2. Create a product that is on sale
3. Install Loco Translate, and make sure the phrase `Sale!` is translated in both WooCommerce and WooCommerce Blocks:

Screenshot
Screenshot: https://cld.wthms.co/9N7u9D

4. Open a shop / category page and observe the `Sale!` label is translated there:

Screenshot
Screenshot: https://cld.wthms.co/8OA8YX

5. Create a new page and add there one of the Gutenblocks, i.e. Products by Category
6. Observe the word `Sale!` isn't translated there, even though it's translated in both core and Blocks plugin:

Screenshot
Screenshot: https://cld.wthms.co/WYBpDx

**Expected behavior**
The label is translated consistently between category pages and blocks.

**Screenshots**
(see above)

**WordPress (please complete the following information):**

* Core version: 5.3
* Gutenberg version (if installed): (using core version)
* WooCommerce version: 3.8.0
* WooCommerce Blocks version: 2.5.1
* Site language: Polish (same happens in French)
* Any other plugins installed: Loco Translate

**Desktop (please complete the following information):**

* OS: OS X 10.14.6
* Browser: Chrome 78

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #1272.

#1242 made it so we load WooCommerce Core translations when they are missing for WooCommerce Blocks. That worked for JS-rendered strings, but didn't include PHP strings.

This PR is an attempt to extend it to PHP strings.

Tagging @mikejolley and @nerrad for review since you worked on/reviewed #1242, which is kinda related. But anybody else is welcome to take a look.

### Screenshots
_Before:_
imatge

_After:_
imatge

### How to test the changes in this Pull Request:

1. Create a post:
	* With a _Product Categories List_ block with _Display Style_ set to _Dropdown_.
	* With a _Handpicked Products_ block (or any other PHP-rendered product grid block).
2. Change your site language to `Deustch (Sie)`.
3. Load these translations into (`/wp-content/languages/plugins/`):
	* https://downloads.wordpress.org/translation/plugin/woocommerce/3.9.1/de_DE_formal.zip
	* https://downloads.wordpress.org/translation/plugin/woo-gutenberg-products-block/1.3.1/de_DE_formal.zip
4. Verify `Sale!` and `Select a category` strings appear in German.

### Changelog

> Load WooCommerce Core translations for 'Sale!'  and some other strings if translations are unavailable for WooCommerce Blocks.

### CODE REVIEW

File: woocommerce-gutenberg-products-block.php [hunk 1]
```diff
@@ -180,3 +180,27 @@ function woocommerce_blocks_get_i18n_data_json( $translations, $file, $handle, $
...
+ */
+function woocommerce_blocks_get_php_translation_from_core( $translation, $text, $domain ) {
+	if ( 'woo-gutenberg-products-block' !== $domain ) {
+		return $translation;
+	}
+
+	// When translation is the same, that could mean the string is not translated.
+	// In that case, load it from core.
+	if ( $translation === $text ) {
+		return translate( $text, 'woocommerce' ); // phpcs:ignore
```
Comment (mikejolley) [inline woocommerce-gutenberg-products-block.php]: What rule is being ignored here? Can we add specificity to the ignore rule?

**Comment by mikejolley** [comment]
@nerrad I think if thats the case, `gettext_with_context` is used instead. https://github.com/WordPress/WordPress/blob/dd4d98a368ca1d617adfaaef9b2937c60464ac4a/wp-includes/l10n.php#L238

File: woocommerce-gutenberg-products-block.php [hunk 2]
```diff
@@ -180,3 +180,27 @@ function woocommerce_blocks_get_i18n_data_json( $translations, $file, $handle, $
...
+	}
+	return $translation;
+}
+
+add_filter( 'gettext', 'woocommerce_blocks_get_php_translation_from_core', 10, 4 );
```
[the remark this answers is not in the document]
Comment (Aljullu) [reply woocommerce-gutenberg-products-block.php]: Sure! Copy & paste mistake. Fixed in a44618f97da4cf598319dca7f2e4ffaedba87ba1.

File: woocommerce-gutenberg-products-block.php (hunk 1 above)
Comment (Aljullu) [reply woocommerce-gutenberg-products-block.php]: Actually it's three rules, I think it makes sense to ignore all of them in this context, but let me know if that doesn't sound good: 3c72d23c858d8dc00b8ea62ed7055df0fb035143.

**Comment by Aljullu** [comment]
> The changes seem to be okay. I'm guessing this is just intended to attempt to retrieve translations from WooCommerce core in the context of the feature plugin being active on a site but not when included as a package right?

@nerrad Right, `woocommerce-gutenberg-products-block.php` only runs in the feature plugin, but not when included as a package in core. So changes included in this PR shouldn't affect WC Core.

> I think if thats the case, gettext_with_context is used instead. https://github.com/WordPress/WordPress/blob/dd4d98a368ca1d617adfaaef9b2937c60464ac4a/wp-includes/l10n.php#L238

@mikejolley Interesting. I wonder if we should add a `gettext_with_context` filter too. I think we don't have any PHP string that uses this function right now, but that might change in the future.

File: woocommerce-gutenberg-products-block.php (hunk 1 above)
Comment (nerrad) [reply woocommerce-gutenberg-products-block.php]: Ha! good catch Mike! You're probably wondering why I didn't say anything here :)

Albert, I generally prefer the rules to be on the line above what's being affected because it's easier to pick up when browsing the code.

**Comment by mikejolley** [comment]
> Interesting. I wonder if we should add a gettext_with_context filter too. I think we don't have any PHP string that uses this function right now, but that might change in the future.

It's probably not worth adding extra overhead to that gettext filter unless we need it. These functions do run on all string translations.
