### PR TITLE
Fix calculation of number of reviews in Reviews by Category block

### LINKED ISSUE #4669: [GlobalStep] "Review" count fails to update on "Reviews by Category" block.
## Bug Description:
"Review" count fails to update on "Reviews by Category" block when reviews are added on 2 different product of same category. 

## Environment:
Woocommerce Version : WooCommerce 5.7.0 RC 1
WordPress version: v5.8

PC:
Windows 10, Mac 10.14.6
Chrome(Version 92.0.4515.131) 
Firefox(Version 90.0.2)
Safari: v14.1.2

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Install and activate WooCommerce 5.7.0 RC 1.
1. Complete the setup wizard.
1. Go to Products screen and add or import the product csv.
1. Go to Store page and add the reviews 2 different product of same category.
1. Approve the comments as admin user.
1. Go to Pages-> Add new and Insert "Reviews by Category" block.
1. Observe that "Review" count fails to update on "Reviews by Category" block.

## Actual Result:
"Review" count fails to update on "Reviews by Category" block

## Expected Result:
"Review" count should gets update on "Reviews by Category" block.

## Video:

https://user-images.githubusercontent.com/41110392/131705824-704e070b-5c1b-403a-9320-7077dc500a6d.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###


WC Version: 5.7.0
REST API Version: ✔ 5.7.0
WC Blocks Version: ✔ 5.7.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.6.0
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.48 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.22
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.7.0
WC Database Prefix: wp_
Total Database Size: 5.65MB
Database Data Size: 3.87MB
Database Index Size: 1.78MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.11MB + Engine InnoDB
wp_postmeta: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 27
page: 10
post: 2
product: 25
product_variation: 28
revision: 2
shop_order: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Query Monitor: by John Blackbourn – 3.7.1
Companion Plugin: by Osk – 1.18
Google Listings and Ads: by WooCommerce – 1.4.2
Jetpack: by Automattic – 10.0
Mailchimp for WooCommerce: by Mailchimp – 2.5.2
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce: by Automattic – 5.7.0-rc.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.10
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.8.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 66
Oldest: 2021-09-01 07:31:03 +0000
Newest: 2021-09-01 12:02:28 +0000


### Status report information ###

Generated at: 2021-09-01 15:46:14 +00:00
`
```
</details>

### PR DESCRIPTION
**Pull request by Aljullu**
This PR includes two commits:
* 20978544cad3bd295ebba16d0eec2d1afadcf9d2: removes an unused method from Reviews by Category block.
* 47ce7699012b98a0506cbb55271287ba4374d288: changes how the reviews count is calculated. Fixes #4669.

### Screenshots

| Before | After |
| --- | --- |
| Before screenshot | After screenshot |

### Manual Testing

1. Add some reviews to some of your products.
2. Create a page and add the Reviews by Category block.
3. Verify the counter shows the correct number of reviews. Take special attention to categories with more than one review and categories with subcategories

### Changelog

> Fix calculation of number of reviews in the Reviews by Category block

### CODE REVIEW

**Comment by Aljullu** [comment]
Given that this PR modifies some code that interacts directly with the database, I think it would be great to get a second pair of eyes. @mikejolley will you have some spare time to take a look at [this commit](https://github.com/woocommerce/woocommerce-gutenberg-products-block/commit/47ce7699012b98a0506cbb55271287ba4374d288) and verify if everything looks good?

File: src/StoreApi/Schemas/ProductCategorySchema.php [hunk 1]
```diff
@@ -102,13 +102,18 @@ public function get_item_response( $term ) {
 	protected function get_category_review_count( $term ) {
 		global $wpdb;
 
+		$term_children_ids = get_term_children( $term->term_id, 'product_cat' );
+		$term_ids          = array_map( 'intval', array_merge( array( $term->term_id ), $term_children_ids ) );
+		$term_ids_str      = implode( ',', $term_ids );
+
+		// phpcs:disable WordPress.DB.PreparedSQL.InterpolatedNotPrepared
 		$products_of_category_sql = $wpdb->prepare(
-			"SELECT SUM( DISTINCT comment_count) as review_count
```
Comment (mikejolley) [inline src/StoreApi/Schemas/ProductCategorySchema.php:106]: 👍🏻  Not sure why that DISTINCT was left around. Good catch.

File: src/StoreApi/Schemas/ProductCategorySchema.php [hunk 2]
```diff
@@ -102,13 +102,18 @@ public function get_item_response( $term ) {
 	protected function get_category_review_count( $term ) {
 		global $wpdb;
 
+		$term_children_ids = get_term_children( $term->term_id, 'product_cat' );
+		$term_ids          = array_map( 'intval', array_merge( array( $term->term_id ), $term_children_ids ) );
```
Comment (mikejolley) [inline src/StoreApi/Schemas/ProductCategorySchema.php]: Just confirming, does this mirror how we display reviews (from children, or just the parent)?

File: src/StoreApi/Schemas/ProductCategorySchema.php [hunk 3]
```diff
@@ -102,13 +102,18 @@ public function get_item_response( $term ) {
 	protected function get_category_review_count( $term ) {
 		global $wpdb;
 
+		$term_children_ids = get_term_children( $term->term_id, 'product_cat' );
```
Comment (mikejolley) [inline src/StoreApi/Schemas/ProductCategorySchema.php]: Might need error handling here. See https://github.com/woocommerce/woocommerce/blob/a5333ffd1f15c22d5298d759c6b5fb166d087306/includes/wc-term-functions.php#L475-L482

**Review by mikejolley — COMMENTED** [review]
Changes look good to me @Aljullu, but I have not tested.

File: src/StoreApi/Schemas/ProductCategorySchema.php (hunk 2 above)
Comment (Aljullu) [reply src/StoreApi/Schemas/ProductCategorySchema.php]: Yes, when selecting a category reviews from all children are displayed. In the case of the screenshots above, if I select `Clothing` the three reviews from `Accessories` are shown.

File: src/StoreApi/Schemas/ProductCategorySchema.php (hunk 3 above)
Comment (Aljullu) [reply src/StoreApi/Schemas/ProductCategorySchema.php]: Ah, thanks for catching! I adapted the code to look like the example you posted.

**Review by ralucaStan — APPROVED** [review]
I've tested this and it works as expected
