### PR TITLE
Link shipping form fields to shipping rates to load them.

### LINKED ISSUE #1883: Changing or submiting a shipping address in Checkout block won't update rates
**Describe the bug**
Due to a recent PR (https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1794) that changed how we handle shipping rates and selection and submission, a regression occurred in Checkout block in which writing your address won’t dynamically update shipping rates.

**To Reproduce**

1. Go to a page with Checkout block
2. type your address
3. shipping rates won’t change (assuming you have different shipping rates for different places).

**Expected behavior**

**Screenshots**
Shipping Rates changes directly (or a slightly debounced).

### PR DESCRIPTION
**Pull request by senadir**
This PR is a continuation from yesterday's mega PR, it fixes the problem with shipping rates not updating when you change a value, it now works fine, and is debounced, there are some updates to how `useShippingRates` work now, it is required that you pass the shape of your fields for them to be watched and updated accordingly. 

Fixes #1883

### How to test the changes in this Pull Request:

1. go to a page/post with Cart or Checkout block, and a sit with shipping rates.
2. enter your shipping informations.
3. watch that changing first name, last name and street address does not trigger a rate update.
4. changing country, state, city or postcode will trigger an update.
5. updates are debounced.

### CODE REVIEW

File: assets/js/base/hooks/use-shipping-rates.js [hunk 1]
```diff
@@ -1,40 +1,63 @@
...
-		const store = select( storeKey );
-		const shippingRatesLoading = store.areShippingRatesLoading();
-		const { updateShippingAddress } = dispatch( storeKey );
-
-		return {
-			shippingRatesLoading,
-			updateShippingAddress,
-		};
-	}, [] );
+	const derivedAddress = shippingRates[ 0 ]?.destination;
```
Comment (senadir) [inline assets/js/base/hooks/use-shipping-rates.js]: we prefill `derivedAddress` with the address we got from updated shipping rates.

File: assets/js/base/hooks/use-shipping-rates.js [hunk 2]
```diff
@@ -1,40 +1,63 @@
...
+	const initialAddress = { ...addressFields, ...derivedAddress };
```
Comment (senadir) [inline assets/js/base/hooks/use-shipping-rates.js]: we create a new initial state from fields shape + existing fields

File: assets/js/base/hooks/use-shipping-rates.js [hunk 3]
```diff
@@ -1,40 +1,63 @@
...
+	const shippingAddressReducer = ( state, address ) => ( {
```
Comment (senadir) [inline assets/js/base/hooks/use-shipping-rates.js]: a reducer takes new addresses and merge them with old ones

File: assets/js/base/hooks/use-shipping-rates.js [hunk 4]
```diff
@@ -1,40 +1,63 @@
...
+		...state,
+		...address,
+	} );
+	const [ shippingAddress, setShippingAddress ] = useReducer(
+		shippingAddressReducer,
+		initialAddress
+	);
+	const [ debouncedShippingAddress ] = useDebounce( shippingAddress, 400 );
```
Comment (senadir) [inline assets/js/base/hooks/use-shipping-rates.js]: we debounce the reducer value.

File: assets/js/base/hooks/use-shipping-rates.js [hunk 5]
```diff
@@ -1,40 +1,63 @@
...
+	useEffect( () => {
+		if (
+			! isShallowEqual(
+				pluckAddress( debouncedShippingAddress ),
+				pluckAddress( initialAddress )
+			) &&
+			debouncedShippingAddress.country
+		) {
+			updateShippingAddress( debouncedShippingAddress );
+		}
```
Comment (senadir) [inline assets/js/base/hooks/use-shipping-rates.js]: we only trigger a rate update if a relevant value has changed (country, state, city, postcode) and if a country is set.

File: assets/js/base/utils/address.js [hunk 6]
```diff
@@ -0,0 +1,14 @@
...
+ * @param {Object} address          An object containing all address information
+ *
+ * @return {Object} pluckedAddress  An object containing shipping address that are needed to fetch an address.
+ */
+export const pluckAddress = ( { country, state, city, postcode } ) => ( {
+	country,
+	state,
+	city,
+	postcode,
+} );
```
Comment (senadir) [inline assets/js/base/utils/address.js]: plunk takes an address object and return needed fields, this is required for comparison with shallow equal and to track needed fields, we might supply this to the hook if we want to (not blocking)

File: assets/js/blocks/cart-checkout/cart/full-cart/index.js [hunk 7]
```diff
@@ -103,8 +103,17 @@ const Cart = ( {
...
+		country: '',
+		state: '',
+		city: '',
+		postcode: '',
+	};
+	const {
+		shippingAddress,
+		setShippingAddress,
+		shippingRatesLoading,
+	} = useShippingRates( defaultAddress );
```
Comment (senadir) [inline assets/js/blocks/cart-checkout/cart/full-cart/index.js]: we refactor Cart block to use the new muse.

File: assets/js/blocks/cart-checkout/checkout/block.js [hunk 8]
```diff
@@ -72,6 +70,16 @@ const Block = ( { attributes, isEditor = false, shippingRates = [] } ) => {
...
 	};
 
+	const {
+		shippingRatesLoading,
+		shippingAddress: shippingFields,
+		setShippingAddress: setShippingFields,
+	} = useShippingRates(
+		Object.fromEntries(
+			Object.entries( addressFields ).map( ( [ key ] ) => [ key, '' ] )
+		)
```
Comment (senadir) [inline assets/js/blocks/cart-checkout/checkout/block.js]: the current shape of `addressFields` is key => object of meta things, we only something like
```js
{
	country: '',
	state: '',
	city: '',
	postcode: '',
	};
```
so we remap the object to this.

File: assets/js/base/hooks/use-shipping-rates.js [hunk 9]
```diff
@@ -1,40 +1,63 @@
...
-			updateShippingAddress,
-		};
-	}, [] );
+	const derivedAddress = shippingRates[ 0 ]?.destination;
+	const initialAddress = { ...addressFields, ...derivedAddress };
+	const shippingAddressReducer = ( state, address ) => ( {
+		...state,
+		...address,
+	} );
+	const [ shippingAddress, setShippingAddress ] = useReducer(
```
Comment (senadir) [inline assets/js/base/hooks/use-shipping-rates.js]: One issue that is not blocking but didn’t understand yet is that `useReducer` initial value doesn’t work like `useState`, it seems `shippingAddress` is returning empty values, even if `initialAddress` has values in it, this means on page load, no address will be in the checkout shipping fields, this is not blocking but we should fix it.

File: assets/js/base/hooks/use-shipping-rates.js [hunk 10]
```diff
@@ -1,40 +1,64 @@
...
+		shippingAddressReducer,
+		initialAddress
+	);
+	const [ debouncedShippingAddress ] = useDebounce( shippingAddress, 400 );
+	const shippingRatesLoading = useSelect(
+		( select ) => select( storeKey ).areShippingRatesLoading(),
+		[]
+	);
+	const { updateShippingAddress } = useDispatch( storeKey );
```
Comment (Aljullu) [inline assets/js/base/hooks/use-shipping-rates.js]: Before, this was inside the `useSelect()`. Is there any benefit on having it outside? Not saying I prefer one way or the other, just asking to help me understand. :slightly_smiling_face:

File: assets/js/base/hooks/test/use-shipping-rates.js [hunk 11]
```diff
@@ -19,11 +19,13 @@ describe( 'useShippingRates', () => {
 	let registry, mocks, renderer;
 	const getProps = ( testRenderer ) => {
 		const {
-			shippingRates,
```
Comment (Aljullu) [inline assets/js/base/hooks/test/use-shipping-rates.js]: Couldn't we just leave the `shippingRates` in the tests? Or you removed them for some reason?

File: assets/js/blocks/cart-checkout/checkout/block.js (hunk 8 above)
Comment (senadir) [reply assets/js/blocks/cart-checkout/checkout/block.js]: the goal is to always and watch and send the fields being used in the form, this ensures that if someone adds custom fields in the future, it should also work, in the cart, we don’t have any sort of dynamic fields yet (the fields are hardcoded in https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/4ddcf447be4f9bce7e973a7c91d9da148d1d2f3d/assets/js/base/components/shipping-calculator/address.js#L22

we might export them somewhere and use them here.

there is also the logic of turning an array to an object, this I will move to the hook.

Comment (senadir) [reply assets/js/blocks/cart-checkout/checkout/block.js]: fixed in a73d39d14

File: assets/js/base/hooks/use-shipping-rates.js (hunk 10 above)
Comment (senadir) [reply assets/js/base/hooks/use-shipping-rates.js]: no benefit from having it inside or outside, this simply avoids us returning it from useSelect `results` then taking it off again, according to Darren there should be no difference 000&cid=C8X6Q7XQU-slack-C8X6Q7XQU

File: assets/js/base/hooks/test/use-shipping-rates.js (hunk 11 above)
Comment (senadir) [reply assets/js/base/hooks/test/use-shipping-rates.js]: well at first I did because I also removed shippingRates from useShipping for some reason? and returned it. refactored

**Comment by senadir** [comment]
@Aljullu so I addressed all of your issues except the one in which shipping rates are not returning, this seems to be an issue from the REST API (no rates are being returned for countries that have states/cities defined in Woo) so I tested with Spain, it has cities, it won’t work until you define a city, I tested with US, it didn’t work, I tested with Algeria, Morocco and France, non of which have states in Woo core, and they all worked fine, for other countries, it simply doesn’t return, worth opening an issue and seeing why.
image

**Comment by Aljullu** [comment]
> @Aljullu so I addressed all of your issues except the one in which shipping rates are not returning, this seems to be an issue from the REST API (no rates are being returned for countries that have states/cities defined in Woo) so I tested with Spain, it has cities, it won’t work until you define a city, I tested with US, it didn’t work, I tested with Algeria, Morocco and France, non of which have states in Woo core, and they all worked fine, for other countries, it simply doesn’t return, worth opening an issue and seeing why.

Thanks for finding steps to reproduce and opening an issue @senadir.

**Comment by senadir** [comment]
I followed up on the initial issue and fixed it in our repo while it’s fixed in Woo Core.
