### PR TITLE
Fix: loading WC Blocks templates content

### LINKED ISSUE #5110: Template Editor: Empty template content if open plugin block template using edit link
## To reproduce

1. Install a FSE theme, i.e. TT1 Blocks, or Tove.
2. Make make sure you have [this change applied in your WooCommerce plugin](https://github.com/woocommerce/woocommerce/pull/30997/files).
The block theme needs to declare `add_theme_support( 'woocommerce' );` in the `functions.php` file.
3. Update to the latest Gutenberg `trunk`.
1. Make sure there isn't any WC block template overridden by the theme or customized using the Template Editor.
2. Edit the `single-product` template by this edit link: `/wp-admin/themes.php?page=gutenberg-edit-site&postId=woocommerce%2F%2Fsingle-product&postType=wp_template` (Prepend your test domain).
3. See the empty template.

## Expected behavior
WC Blocks templates should load in the editor.

## Screenshots
image
image

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #5110

This PR fixes the template loading of WC Blocks templates in the Template Editor by building the proper `WP_Block_Template` object for the `get_block_template` filter.

### Screenshots

<table>
<tr>
	<td>Before
	<td>After
<tr>
	<td>
	<td>

<tr>
	<td>
	<td>
</table>

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
### Manual Testing

How to test the changes in this Pull Request:

1. Install a FSE theme, i.e. TT1 Blocks, or Tove.
2. Make make sure you have [this change applied in your WooCommerce plugin](https://github.com/woocommerce/woocommerce/pull/30997/files).
The block theme needs to declare `add_theme_support( 'woocommerce' );` in the `functions.php` file.
3. Update to the latest Gutenberg `trunk`.
1. Make sure there isn't any WC block template overridden by the theme or customized using the Template Editor.
2. Edit the `single-product` template by this edit link: `/wp-admin/themes.php?page=gutenberg-edit-site&postId=woocommerce%2F%2Fsingle-product&postType=wp_template` (Prepend your test domain).
3. See the template loads properly.

### CODE REVIEW

File: src/BlockTemplatesController.php [hunk 1]
```diff
@@ -118,7 +118,9 @@ public function get_single_block_template( $template, $id, $template_type ) {
 		}
 
 		$available_templates = $this->get_block_templates( array( $slug ) );
-		return ( is_array( $available_templates ) && count( $available_templates ) > 0 ) ? (object) $available_templates[0] : $template;
+		return ( is_array( $available_templates ) && count( $available_templates ) > 0 )
```
Comment (tjcafferkey) [inline src/BlockTemplatesController.php:121]: We've removed the aspect of the code which casted the return value to `(object)`, do you think we should put this back in?

**Review by tjcafferkey — APPROVED** [review]
Just left an optional comment but this LGTM

File: src/BlockTemplatesController.php (hunk 1 above)
Comment (dinhtungdu) [reply src/BlockTemplatesController.php:121]: @tjcafferkey I remove it because `BlockTemplateUtils::gutenberg_build_template_result_from_file` always returns a `WP_Block_Template` object, so it's not necessary to cast the return value.
