### PR TITLE
Fix undefined variable in ProductSchema.php closure 

### LINKED ISSUE #2896: Fix undefined variable `$product` in ProductSchema.php
I saw these notices happening in my php logs:

```
 PHP Notice:  Undefined variable: product in /srv/www/wordpress-one/public_html/wp-content/plugins/woocommerce-gutenberg-products-block/src/StoreApi/Schemas/ProductSchema.php on line 561
```

It looks like the closure needs to pass through the `$product` variable via the `use` statement.

### PR DESCRIPTION
**Pull request by senadir**
Fixes the issue by defining `use ( $product )` in the closure, as far as my googling went, this syntax is supported from PHP 5.3, so we're safe (WC requires 7.0).

Fixes #2896
### How to test the changes in this Pull Request:

1. You shouldn't see the notice anymore

### How to test
0- Make sure you have WP_DEBUG set to true.
1- Load a page that already contains a product data, so single product or All Products, either in the editor or frontend.
2- Make sure no notices are printed to the page, you can check the source code or at the top of the page.

### Changelog

> Fix an undefined variable PHP notice related to Product REST API.

### CODE REVIEW

File: assets/js/blocks/products/utils.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ export const renderNoProductsPlaceholder = ( blockTitle, blockIcon ) => (
 			className="wc-block-products__add-product-button"
 			isDefault
 			isLarge
-			href={ adminUrl + 'post-new.php?post_type=product' }
+			href={ ADMIN_URL + 'post-new.php?post_type=product' }
```
Comment (nerrad) [inline assets/js/blocks/products/utils.js:38]: wowzer! good catch here!

Comment (senadir) [reply assets/js/blocks/products/utils.js]: this was from another PR, not sure how it got here 😅, props to Albert.

Comment (senadir) [reply assets/js/blocks/products/utils.js]: this was from another PR, not sure how it got here 😅, props to Albert.

**Comment by nerrad** [comment]
Tested okay, I also verified that there was no impact to variation meta data returned as a result of this change.
