### PR TITLE
`SearchListControl`: Fix preserving case of original item

### LINKED ISSUE #6524: `SearchListControl` shows product names in the same case the user entered.
## Describe the bug

When searching for a product, the product name is displayed in the same case you type it in the input.

## To reproduce

1. Add a Hand Picked Products Block.
2. Search for `hOoDiE`.
3. Observe the list of products returned contains the same case you entered.

## Expected behavior

I think it should show the product name as entered by the merchant, i.e. `Hoodie`

## Screenshots

image

## Additional context
Code responsible for highlighting the part of the product name is here: https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/editor-components/search-list-control/utils.tsx

### PR DESCRIPTION
**Pull request by sunyatasattva**
This PR fixes an issue where the `SearchListControl` component (for example, used in the Hand-picked Products block) would render the search results list with highlighted text borrowing the case from the user's input instead of the original item's name. So, if the original item's name was `Hoodie`, but the user's input was `hOoDiE`, search results would display the latter, rather than the former.

Search still is case insensitive, but preserves the original item's case.

Also, this PR adds a test for this bug and fixes a previous test case which wasn't actually testing for this at all.

Fixes #6524

### Screenshots

| Before | After |
| ------ | ----- |
| 172268138-7445fbf1-ad25-4716-8b5a-ee4b463af54b |  Screenshot 2022-06-11 at 21 16 42 |

#### Automated Tests
* [x] Changes in this PR are covered by Automated Tests.
  * [x] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Add a “Hand-picked Products” block to your page.
2. Type the name of one of your products with the incorrect case (e.g. if you have imported the sample data, type “hOoDiE”.
3. Make sure all matching products appear on the list.
4. Make sure all items on the list preserve their original case.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fixes an issue where search lists would not preserve the case of the original item.

### CODE REVIEW

File: assets/js/editor-components/search-list-control/utils.tsx [hunk 1]
```diff
@@ -2,8 +2,8 @@
  * External dependencies
  */
 import { groupBy, keyBy } from 'lodash';
+import { Fragment } from 'react';
```
Comment (Aljullu) [inline assets/js/editor-components/search-list-control/utils.tsx]: I'm a bit confused by this now, but I thought we always wanted to prioritize importing from [`@wordpress/element`](https://github.com/WordPress/gutenberg/tree/4719b98c8cd70908897237613a70af54081b652f/packages/element) instead of `react`.

**Review by Aljullu — APPROVED** [review]
This is testing well and code looks good, thanks for fixing this @sunyatasattva!

I'm pre-approving, but I left a comment about whether we should import from `react` or from `@wordpress/element`. It looks like the way this PR is done, it's currently [adding the `react` dependency to several scripts](https://github.com/woocommerce/woocommerce-blocks/pull/6551#issuecomment-1152985944).

File: assets/js/editor-components/search-list-control/utils.tsx (hunk 1 above)
Comment (sunyatasattva) [reply assets/js/editor-components/search-list-control/utils.tsx]: Oh thanks for pointing that out @Aljullu! I wasn't aware of that. Perhaps it's something we could write somewhere? Team Handbook? READMEs?

I'll fix it and merge it! Thanks for the review! 🙏

Comment (Aljullu) [reply assets/js/editor-components/search-list-control/utils.tsx]: > Oh thanks for pointing that out @Aljullu! I wasn't aware of that. Perhaps it's something we could write somewhere? Team Handbook? READMEs?

Sounds good, I agree. Is that something you can own or create an issue with the `documentation` label?
