### PR TITLE
#3906 screen reader fix for order summary block accessibility 

### LINKED ISSUE #3906: Order summary: with a screen reader it's not clear what's the difference between the cart item subtotal and the product price
In the Checkout Order Summary, we display all products with its unitary price and the cart item price. While the alignment helps explain their meaning (unitary price on the left, under the title / cart item price aligned to the right in bold), nothing of this is obvious to screen reader users, which will get two prices read without any clue of which one is which.

Order summary screenshot

### PR DESCRIPTION
**Pull request by ovidiul**
Fixes #3906 

#### Accessibility

- [x] I've tested using only a keyboard (no mouse)
- [x] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)
- [ ] I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) for any feature flags or experimental interfaces implemented in this pull request.

### Screenshots

Screen Recording 2021-09-22 at 13 58 25

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
### Manual Testing

How to test the changes in this Pull Request:

1. Add one or more items to your cart
2. Create a post/page add the `Checkout` block
3. Open the new page from previous step
4. Click on `Order Summary` to expand the tab, or navigate to it using TAB key
5. Navigate using the `TAB` key
6. Optionally you could enable the screen reader

### Changelog

> Improve the Checkout Order Summary block accessibility by making more info available to screen readers.

### CODE REVIEW

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js [hunk 1]
```diff
@@ -121,11 +124,27 @@ const OrderSummaryItem = ( { cartItem } ) => {
 				<ProductImage image={ images.length ? images[ 0 ] : {} } />
 			</div>
 			<div className="wc-block-components-order-summary-item__description">
+				<span className="screen-reader-text" tabIndex={ 0 }>
```
Comment (Aljullu) [inline assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: We don't need to make these elements focusable, screen readers already offer a way to navigate unfocusable elements.

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js [hunk 2]
```diff
@@ -151,6 +170,17 @@ const OrderSummaryItem = ( { cartItem } ) => {
 					variation={ variation }
 				/>
 			</div>
+			<span className="screen-reader-text" tabIndex={ 0 }>
+				{ sprintf(
+					/* translators: Total Price for %d quantity items: %s */
```
Comment (Aljullu) [inline assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: In the translators comment, you need to explain what each variable will be replaced with. For example, in this case it could be written as:
```suggestion
					/* translators: %1$d is the number of items and %2$s is the total prices including the currency symbol. */
```

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js [hunk 3]
```diff
@@ -151,6 +170,17 @@ const OrderSummaryItem = ( { cartItem } ) => {
...
+					__(
+						'Total Price for %1$d items: %2$s',
```
Comment (Aljullu) [inline assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: Ideally, we should use sentence case everywhere, even if it's a text for a screen reader:
```suggestion
						'Total price for %1$d items: %2$s',
```

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js [hunk 4]
```diff
@@ -121,11 +124,27 @@ const OrderSummaryItem = ( { cartItem } ) => {
...
 					permalink={ permalink }
 				/>
+
+				<span className="screen-reader-text" tabIndex={ 0 }>
+					{ sprintf(
+						/* translators: Unit Price %s */
+						__( 'Unit Price: %s', 'woo-gutenberg-products-block' ),
+						formatPrice( priceSingle, priceCurrency )
+					) }
+				</span>
```
Comment (Aljullu) [inline assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: This is a bit tricky because when a product has a discount, we want to announce it to screen readers too. `ProductPrice` already has some logic to handle these cases.

Considering you already added screen reader text to the 'Total price', I wonder if we need to specify this is the unitary price. I think this will be clear now. How does it sound getting rid of this span and just leaving the 'total price' one?

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js [hunk 5]
```diff
@@ -121,11 +124,27 @@ const OrderSummaryItem = ( { cartItem } ) => {
 				<ProductImage image={ images.length ? images[ 0 ] : {} } />
 			</div>
 			<div className="wc-block-components-order-summary-item__description">
+				<span className="screen-reader-text" tabIndex={ 0 }>
+					{ sprintf(
+						/* translators: %d items of product %s */
```
Comment (Aljullu) [inline assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: I think this translators comment could be made a bit more specific so translators have a better understanding of what these variables are. Something along these lines: `%1$d is the quantity of items and %2$s the name of the product`. How does it sound?

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js (hunk 3 above)
Comment (Aljullu) [reply assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: Another thing about this string, you will need to account for the case when there is only one item of a specific product. In that case `items` should be `item`. For this, we use `sprintf()` and `_n()`.

You can see an example of how this functions are being used here:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/19d29d11fea059650da48cbca4f35275e88324d6/assets/js/editor-components/product-category-control/index.js#L48-L58

**Review by Aljullu — COMMENTED** [review]
Thanks for working on this @ovidiul! I like that you also took the chance to improve the accessibility of the count badge. :clap: 

I left some comments below with some suggestions that I would apply. Let me know what you think!

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js (hunk 1 above)
Comment (ovidiul) [reply assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: Thanks for pointing that out, I've removed it.

Seems [VO key(CTRL+Option) + →] and [VO key + ←] would work for me as opposed to using the TAB key.

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js (hunk 2 above)
Comment (ovidiul) [reply assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: Thanks for the suggestion, I've adjusted the items with the appropriate description.

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js (hunk 3 above)
Comment (ovidiul) [reply assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: That's great, suggestion has been applied here as well. Thanks!

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js (hunk 4 above)
Comment (ovidiul) [reply assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: We can definitely remove this as it makes the screen reader easier to follow.

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js (hunk 5 above)
Comment (ovidiul) [reply assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: Fixed as well.

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js (hunk 3 above)
Comment (ovidiul) [reply assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: One mention is that I've added the product name in the mix as it makes the Screen Reader easier to understand on my part, so the user gets the full info of quantity, product name, and total price in one sentence.

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js [hunk 6]
```diff
@@ -151,6 +159,20 @@ const OrderSummaryItem = ( { cartItem } ) => {
...
+						'Total price for %1$d %3$s items: %2$s',
+						quantity,
+						'woo-gutenberg-products-block'
+					),
+					quantity,
+					formatPrice( subtotalPrice, totalsCurrency ),
+					name
+				) }
+			</span>
 			<div className="wc-block-components-order-summary-item__total-price">
```
Comment (Aljullu) [inline assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: I would add `aria-hidden="true"` here, otherwise the price is read twice by screen readers.
```suggestion
			<div className="wc-block-components-order-summary-item__total-price" aria-hidden="true">
```

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js [hunk 7]
```diff
@@ -151,6 +159,20 @@ const OrderSummaryItem = ( { cartItem } ) => {
 					variation={ variation }
 				/>
 			</div>
+			<span className="screen-reader-text">
+				{ sprintf(
+					/* translators: %1$d is the number of items, %2$s is the total price including the currency symbol and %3$s is the item name. */
+					_n(
+						'Total price for %1$d %3$s item: %2$s',
```
Comment (Aljullu) [inline assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: Not a big deal, but wondering if we should place variables in order, so `%2$s` is the name and `%3$s` the price?

**Review by Aljullu — COMMENTED** [review]
This is looking great, good job @ovidiul! :clap: 

I left a couple of minor comments. Once they are addressed, this should be ready to go.

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js (hunk 6 above)
Comment (ovidiul) [reply assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: Added now!

File: assets/js/base/components/cart-checkout/order-summary/order-summary-item.js (hunk 7 above)
Comment (ovidiul) [reply assets/js/base/components/cart-checkout/order-summary/order-summary-item.js]: Done as well!

**Review by Aljullu — APPROVED** [review]
This is working like a charm, now! Thanks for working on this @ovidiul and congrats on your first PR merged in WC Blocks! :clap:
