### PR TITLE
Make Filter Products by Stock block compatible with PHP rendered Classic Template block

### LINKED ISSUE #6137: Make Filter Products by Stock work with PHP templates
Currently, it's not possible to use the Filter Products by Stock block with PHP templates. That's because that block is designed to only work with the All Products block.

This issue is about updating it, so it can work with the Shop catalog template.

Take into account currently there isn’t a widget equivalent, so it might require some changes in WC core in order to get this block working with PHP templates. (That's why the estimate of this issue is higher than the one from similar issues)

## To reproduce

1. With a block theme, go to Appearance > Editor > Template > Product Catalog.
2. Add the Filter Products by Stock block above the product grid.
3. Change the selected values in the filter block
4. Notice the products in the product grid don't update.

## Expected behavior

The products in the product grid should update based on the selected filters.

### PR DESCRIPTION
**Pull request by gigitux**
This PR updates the Filter Products By Stock block to work with the Classic Template block which is PHP rendered, but also still maintains compatibility with the All Products block.

Filter Products by Stock block will only work with the PHP rendered Classic Template block if the filters are applied to the URL and the page is re-rendered. This behavior happens with the Classic Themes such as Storefront.

Fixes #6137 

## Technical details

I believe there is a lot of space to improve the code regarding all the blocks that filter the products.
Now, there are a lot of side effects, hard to debug, and these blocks are not performant (there are a lot of rerender :'( )

 Also, [As said by ](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/6138#issuecomment-1098868583) @dinhtungdu this approach is not really extendible when we will blockify this template.

My suggestion is to dedicate some time (in cooldown or in a dedicated project) to improve the quality of the codebase regarding the block that handles filters cc @Aljullu 

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
 
### Manual Testing

How to test the changes in this Pull Request:

1. With a block theme, go to Appearance > Editor > Template > Product Catalog.
2. Add the Filter Products by Stock block above the product grid.
3. Be sure that you have some out stock products. Check "out of stock" on the frontend.
4. Notice the page reloads and the list of products updates accordingly.
5. Add a test page to your site with the `All Products` block, and the `Filter Product by Stock` block and ensure no regressions have been introduced here.

### User Facing Testing
These are steps for user testing (where "user" is someone interacting with this change that is not editing any code).
* [x] Same as above

### Changelog

> Allow adding the Filter Products by Stock block to Product Catalog templates to filter products.

### CODE REVIEW

File: assets/js/blocks/attribute-filter/block.js [hunk 1]
```diff
@@ -392,9 +397,20 @@ const AttributeFilterBlock = ( {
 					getQueryArgs( window.location.href )
 				);
 
+				const parsedTaxonomy = parseTaxonomyToGenerateURL(
+					attributeObject?.taxonomy
+				);
+
 				const url = currentQueryArgKeys.reduce(
 					( currentUrl, queryArg ) =>
-						removeQueryArgs( currentUrl, queryArg ),
```
Comment (gigitux) [inline assets/js/blocks/attribute-filter/block.js:397]: I updated this logic because with the previous implementation, ALL query parameters were removed, instead only the query parameters related to the attribute filter have to be removed.

**Review by dinhtungdu — COMMENTED** [review]
@gigitux The filter isn't working for me. I tested on the shop page, and the filter worked with the Active Filter block but the product grid didn't take the stock status into account. The Stock filter is still working with the All Products block as expected.

image

**Comment by tjcafferkey** [comment]
@dinhtungdu I have just fixed that in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6261/commits/38e3642ffa4f4bbff89bf53e24ff101317c933d2 so should be working as expected. Please can you re-test this?

**Review by dinhtungdu — COMMENTED** [review]
@tjcafferkey thanks for the update, this is working for me, the selected stock filter also appears in the Active filters block.

But when I enabled the Filter button, I got some issues:
- The page reloads immediately after I selected a filter. It should wait until I click the filter button.
- The selected filter doesn't appear in the Active Filters block anymore.

https://user-images.githubusercontent.com/5423135/164141965-45766ac1-6f8e-46ab-b660-68fa5a728caf.mov

**Comment by tjcafferkey** [comment]
Good catch @dinhtungdu apologies that this was overlooked. I've addressed your feedback in this commit https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6261/commits/03c607f6f1ed9a3602fafb2c2afd43231fdc377b and its now ready for another round of testing.

File: assets/js/blocks/stock-filter/block.js [hunk 2]
```diff
@@ -183,6 +233,35 @@ const StockStatusFilterBlock = ( {
...
+		isRenderingPHPTemplate,
+		productStockStatusQuery,
+		checked,
+		blockAttributes.queryType,
+		blockAttributes.showFilterButton,
+	] );
+
+	useEffect( () => {
+
+	}, [] )
```
Comment (dinhtungdu) [inline assets/js/blocks/stock-filter/block.js]: Look like a left-over debug code.

File: assets/js/blocks/stock-filter/block.js [hunk 3]
```diff
@@ -156,8 +197,17 @@ const StockStatusFilterBlock = ( {
...
+			if ( isRenderingPHPTemplate ) {
+				redirectPageForPhpTemplate( checked );
+			}
 		},
-		[ isEditor, setProductStockStatusQuery, checked ]
+		[
+			isEditor,
+			setProductStockStatusQuery,
+			checked,
+			isRenderingPHPTemplate
```
Comment (dinhtungdu) [inline assets/js/blocks/stock-filter/block.js]: Please fix the ESLint warning here : ).

File: assets/js/blocks/stock-filter/block.js [hunk 4]
```diff
@@ -183,6 +233,35 @@ const StockStatusFilterBlock = ( {
...
+		if ( isRenderingPHPTemplate ) {
+			setChecked( checked );
+			// Only automatically redirect if the filter button is not active.
+			if ( ! blockAttributes.showFilterButton ) {
+				redirectPageForPhpTemplate( checked );
+			} else {
+				setProductStockStatusQuery(
+					getActiveFilters( STOCK_STATUS_OPTIONS, QUERY_PARAM_KEY )
+				);
+			}
```
Comment (dinhtungdu) [inline assets/js/blocks/stock-filter/block.js]: This code will not only set the active filter on load but also force the stock status filter to follow the value in the initial URL. With this, the stock filter can't be removed from the Active Filters block (while it's possible to remove it when the filter button is disabled):

https://user-images.githubusercontent.com/5423135/164211007-b4d55a57-9729-49b8-8ba7-b607ad539e9b.mov

File: assets/js/blocks/stock-filter/block.js [hunk 5]
```diff
@@ -183,6 +237,43 @@ const StockStatusFilterBlock = ( {
...
+			// Only automatically redirect if the filter button is not active.
+			if ( ! blockAttributes.showFilterButton ) {
+				redirectPageForPhpTemplate( checked );
+			}
+		}
+	}, [
+		filteringForPhpTemplate,
+		productStockStatusQuery,
+		checked,
+		blockAttributes.queryType,
```
Comment (dinhtungdu) [inline assets/js/blocks/stock-filter/block.js]: Are this and `productStockStatusQuery` intentional? Look like we don't use those values inside the `useEffect` callback.

**Review by dinhtungdu — APPROVED** [review]
I left a minor comment but this is LGTM so pre-approving it.

File: assets/js/blocks/stock-filter/block.js (hunk 5 above)
Comment (tjcafferkey) [reply assets/js/blocks/stock-filter/block.js]: I wasn't sure myself when I took over this PR. After your testing, I will remove them and check the behaviour is still the same and there are no regressions on this feature.

**Review by dinhtungdu — APPROVED** [review]
