### PR TITLE
 Check if WordPress version is higher than 6.2.2 to make Products block compatible with Gutenberg 16+

### LINKED ISSUE #10367: [GlobalStep] [WP 6.3+] "Products (Beta)" block grid layout is wrongly displayed on a new post/page with Gutenberg disabled.
### Bug Description:
"Products (Beta)" block grid layout is wrongly displayed on a new post/page with Gutenberg disabled.

### Environment:
Woocommerce Version: 8.0.0-beta.2
WordPress version: 6.3-RC2
PHP version: 8.0.29

PC:
Windows 10
Chrome(Version 115.0.5790.110)
Firefox (Version 115.0.2)

### Steps To Reproduce:
1. Create any test site.
2. Install and activate all required plugins.
3. Confirm that WordPress version is 6.3+ with Gutenberg DISABLED.
4. Create a new post/page.
5. Insert the Products (Beta) block.
6. Observe that, "Products (Beta)" block grid layout is wrongly displayed.

### Actual Result:
"Products (Beta)" block layout is wrongly displayed on a new post/page with Gutenberg disabled.

### Expected Result:
"Products (Beta)" block grid layout should be a row grid on a new post/page with Gutenberg disabled.

### Video:

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 8.0.0
REST API Version: ✔ 8.0.0
WC Blocks Version: ✔ 10.6.1
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3-RC2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Unix) OpenSSL/1.0.2g
PHP Version: 8.0.29
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.0
WC Database Prefix: wp_
Total Database Size: 5.39MB
Database Data Size: 3.66MB
Database Index Size: 1.73MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.47MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 9
post: 3
product: 18
product_variation: 7
revision: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.13.1
Companion Plugin: by Osk – 1.29
WooCommerce Beta Tester: by WooCommerce – 2.1.0
WooCommerce: by Automattic – 8.0.0-beta.2
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.2

### Inactive Plugins (3) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 12.3

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-27 07:02:37 +00:00
Options: ✔
Notes: 65
Onboarding: skipped

### Action Scheduler ###

Complete: 34
Oldest: 2023-07-26 07:04:05 +0000
Newest: 2023-07-26 07:50:41 +0000

Failed: 2
Oldest: 2023-07-26 07:05:43 +0000
Newest: 2023-07-26 07:12:09 +0000

Pending: 1
Oldest: 2023-07-27 07:04:05 +0000
Newest: 2023-07-27 07:04:05 +0000

### Status report information ###

Generated at: 2023-07-26 10:13:01 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by kmanijak**
In Gutenberg 16+ the layout attributes of Query block has been moved from `core/query` to `core/post-template`. Products (Beta) and Product Template blocks are variations of the mentioned blocks, hence we had to adjust to this logic (issue: https://github.com/woocommerce/woocommerce-blocks/issues/9884).

In https://github.com/woocommerce/woocommerce-blocks/pull/9916 we fixed this, but the change is applied based on the Gutenberg version. When Gutenberg was not installed or disabled we didn't apply the adjusting logic.
However, Gutenberg 16+ is included in WordPress 6.3, so we have to apply the fix also in the case of WordPress 6.3+.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/10367

### Screenshots

| Before - no layout option is chosen, which defaults to list | After  - grid option is chosen by default|
| ------ | ----- |
|   image     |   image    |

#### User Facing Testing

Check below steps in following configurations:
- WordPress 6.2:
    - [ ] Gutenberg 16 enabled
    - [ ] Gutenberg 16 disabled
- WordPress 6.3:
    - [ ] Gutenberg 16 enabled
    - [ ] Gutenberg 16 disabled

1. Create new post
2. Add Products (Beta) block
3. **Expected**: It has grid layout applied by default

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Products: fix the incorrect layout with WordPress 6.3+ without Gutenberg

### CODE REVIEW

File: src/BlockTypes/ProductQuery.php [hunk 1]
```diff
@@ -91,6 +91,14 @@ protected function initialize() {
 	protected function enqueue_data( array $attributes = [] ) {
 		parent::enqueue_data( $attributes );
 
+		if ( version_compare( $GLOBALS['wp_version'], '6.2.2', '>' ) ) {
```
Comment (gigitux) [inline src/BlockTypes/ProductQuery.php]: NIT: Should we put both logic in a dedicated function and add a comment? (it would be great just the link to this PR)

**Review by gigitux — APPROVED** [review]
LGTM! I added a comment, but feel free to merge as it is! Thanks for tacking care of this! 🚀

File: src/BlockTypes/ProductQuery.php (hunk 1 above)
Comment (kmanijak) [reply src/BlockTypes/ProductQuery.php]: > NIT: Should we put both logic in a dedicated function and add a comment? (it would be great just the link to this PR)

Good idea! I extracted the logic to separate function, do you mind taking a look one more time?

File: src/BlockTypes/ProductQuery.php [hunk 2]
```diff
@@ -82,18 +82,19 @@ protected function initialize() {
...
-		parent::enqueue_data( $attributes );
-
-		$gutenberg_version = '';
+	 * Post Template support for grid view was introduced in Gutenberg 16 / WordPress 6.3
+	 * Fixed in:
+	 * - https://github.com/woocommerce/woocommerce-blocks/pull/9916
+	 * - https://github.com/woocommerce/woocommerce-blocks/pull/10360
+	 */
+	private function check_if_post_template_has_support_for_grid_view() {
+		if ( version_compare( $GLOBALS['wp_version'], '6.2.2', '>' ) ) {
```
Comment (gigitux) [inline src/BlockTypes/ProductQuery.php]: Are you sure that this check is correct? Should be 
```suggestion
		if ( version_compare( $GLOBALS['wp_version'], '6.3.0', '>=' ) ) {
```

File: src/BlockTypes/ProductQuery.php (hunk 1 above)
Comment (gigitux) [reply src/BlockTypes/ProductQuery.php]: I noticed that we should fix the check for the WP version :D

File: src/BlockTypes/ProductQuery.php (hunk 2 above)
Comment (kmanijak) [reply src/BlockTypes/ProductQuery.php]: `version_compare` consider versions with suffix as lower, for example, 6.3.0 is higher than 6.3.0-RC2. That means the fix won't be applied to the RC version.

But you're right, I cannot compare to 6.2.2, because there may be another 6.2.x release and there will be incorrect behaviour.

I'll try to use this custom function [`wp_version_compare`](https://github.com/woocommerce/woocommerce-blocks/blob/b4ba06a6242cbb6a64d2ec554a263ebe60d8d3af/src/Utils/Utils.php#L16) which I belive was written for exactly this case or I'll think of something custom.

Comment (gigitux) [reply src/BlockTypes/ProductQuery.php]: > version_compare consider versions with suffix as lower, for example, 6.3.0 is higher than 6.3.0-RC2. That means the fix won't be applied to the RC version.

TIL

> version_compare consider versions with suffix as lower, for example, 6.3.0 is higher than 6.3.0-RC2. That means the fix won't be applied to the RC version.

Thanks!

Comment (kmanijak) [reply src/BlockTypes/ProductQuery.php]: OK, code updated! And I updated testing steps to cover cases with higher and lower than WP 6.3 + Gutenberg 16 enabled and disabled.

**Review by gigitux — APPROVED** [review]
LGTM! Thanks for your work!
