### PR TITLE
Fix Cart block making 404 requests in the editor

### LINKED ISSUE #1924: 404 requests to the API in the Cart block in the editor
Found it while rebasing #1907.

**To Reproduce**
1. Create a post and add a _Cart_ block.
2. In the _Network_ tab of your browser devtools, notice there are two calls that return 404: `/wc/store/cart/update-item`.

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #1924.

### How to test the changes in this Pull Request:

1. Create a post and add a _Cart_ block.
2. In the _Network_ tab of your browser devtools, verify there are no calls that return 404.
3. In the frontend, verify you can still update the cart item quantities.

### CODE REVIEW

File: assets/js/base/hooks/use-store-cart-item-quantity.js [hunk 1]
```diff
@@ -45,7 +47,10 @@ export const useStoreCartItemQuantity = ( cartItem ) => {
 	// Observe debounced quantity value, fire action to update server when it
 	// changes.
 	useEffect( () => {
-		changeCartItemQuantity( cartItem.key, debouncedQuantity );
+		// Don't run it if quantity didn't change but it was set for the first time.
+		if ( Number.isFinite( previousDebouncedQuantity ) ) {
```
Comment (nerrad) [inline assets/js/base/hooks/use-store-cart-item-quantity.js]: I do have some concern here about `previousDebouncedQuantity` not being included as a dependency (so there is risk of it going stale). But in this case, I think the staleness is _desirable_ because that's what is actually fixing the issue.

Comment (senadir) [reply assets/js/base/hooks/use-store-cart-item-quantity.js]: Shouldn’t we compare previous with current value? or am I miss understanding usePrevious

Comment (nerrad) [reply assets/js/base/hooks/use-store-cart-item-quantity.js]: I think we're taking advantage of the stale props issue here where at the time the effect is first called, `previousDebouncedQuantity` is `undefined`. Hence it's suitable as a method for preventing the initial quantity set from triggering a request.  Subsequent calls to useEffect won't be affected at all by the conditional because `previousDebouncedQuantity` will always be a number.

Comment (senadir) [reply assets/js/base/hooks/use-store-cart-item-quantity.js]: would it make sense to add an extra to check to not trigger debounced values that are the same, in shippingRates I simply compared debouncedValues with the previous values and bailed if they’re the same.

Comment (Aljullu) [reply assets/js/base/hooks/use-store-cart-item-quantity.js]: [React docs](https://reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect) seem to suggest all values used inside the effect should be declared in the dependencies, but I'm not sure that applies to our case because we don't want to run the effect when `previousDebouncedQuantity` changes, only when `debouncedQuantity` changes. Otherwise, the fix wouldn't work.

Comment (Aljullu) [reply assets/js/base/hooks/use-store-cart-item-quantity.js]: > would it make sense to add an extra to check to not trigger debounced values that are the same

I don't think that's needed. `QuantitySelector` doesn't trigger `onChange` if the introduced value is the same that it was, and using the `-` and `+` buttons will always change the value.
