### PR TITLE
Fix: When creating a template part for the Mini Cart area, it should be created already containing the Mini Cart Contents block

### LINKED ISSUE #5196: When creating a template part for the Mini Cart area, it should be created already containing the Mini Cart Contents block
As described in #5194, we are planning to create a Mini Cart template part area. Users will be able to use the WC core provided template part or create their own. When creating a new one, the template part area should start with a Mini Cart Contents block already included, that's the block responsible of handling the Empty cart / Full cart state so it should be there by default.

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #5196 
Depends on #5221

This PR adds the Mini Cart content to the template parts created for the Mini Cart area. Template content is taken dynamically from the template part file, and theme has a higher priority than plugin.

### Screenshots

Screen after adding a new Mini Cart template part:
image

### Manual Testing

How to test the changes in this Pull Request:

1. Check out the latest `trunk` of `woocommerce` or install the [nightly build](https://github.com/woocommerce/woocommerce/releases/tag/nightly).
2. Check out the latest `trunk` of Gutenberg.
3. Remove mini-cart template part file from the active theme if exists.
3. Go to Appearance > Editor (Beta).
4. Click on the W icon > Template Parts.
5. Click the Add new button on the top right corner.
6. Select the Mini Cart area, and give the template part a random name.
7. Click `Create`, after the editor has been loaded, the template content should contain the Mini Cart Contents block.
8. Update the content of the `woocommerce-gutenberg-products-block/templates/block-template-parts/mini-cart.html` with the one below.
9. Repeat steps 4-7. See the content of the newly created template part is the updated one in the step 9.
10. Add mini-cart template to the active theme with the content below.
11. Repeat steps 4-7. See the content of the newly created template part is the updated one in the step 11, the teampate content is taken from theme now, not the plugin.
12. Repeat steps 4-5 then Edit the default Mini Cart template part.
13. Repeat steps 4-7. See the content of the newly created template part is the updated one in the step 11, the template content is taken from template file in theme, not the customized one in the database.
---
**woocommerce-gutenberg-products-block/templates/block-template-parts/mini-cart.html:**
```
<!-- wp:paragraph --> <p>WC Mini Cart content template</p> <!-- /wp:paragraph -->
<!-- wp:woocommerce/mini-cart-contents /-->
```
---
**theme-slug/block-template-parts/mini-cart.html:**
```
<!-- wp:paragraph --> <p>Theme Mini Cart content template</p> <!-- /wp:paragraph -->
<!-- wp:woocommerce/mini-cart-contents /-->
```

### CODE REVIEW

File: src/BlockTemplatesController.php [hunk 1]
```diff
@@ -298,7 +299,7 @@ function( $saved_woo_template ) {
 	 *
 	 * @param string[] $slugs An array of slugs to filter templates by. Templates whose slug does not match will not be returned.
 	 * @param array    $already_found_templates Templates that have already been found, these are customised templates that are loaded from the database.
-	 * @param array    $template_type wp_template or wp_template_part.
+	 * @param string   $template_type wp_template or wp_template_part.
```
Comment (Aljullu) [inline src/BlockTemplatesController.php:302]: Good catch!

File: src/BlockTemplatesController.php [hunk 2]
```diff
@@ -472,4 +484,69 @@ public function add_template_part_areas( $area_definitions ) {
...
+
+		if ( is_wp_error( $type_terms ) || false === $type_terms ) {
+			return;
+		}
+
+		if ( 'mini-cart' !== $type_terms[0]->name ) {
+			return;
+		}
+
+		// Remove the filter temporaryly for wp_update_post below.
```
Comment (Aljullu) [inline src/BlockTemplatesController.php]: Small typo:
```suggestion
		// Remove the filter temporarily for wp_update_post below.
```

**Review by Aljullu — APPROVED** [review]
Works like a charm and code looks good. :ship: 

Heads-up that I rebased this branch with `trunk` to fix some conflicts and to include the changes from #5221, hope you don't mind!
