### PR TITLE
Fix cart preview when shipping calculator is false and core setting for require address is true	

### LINKED ISSUE #3566: Cart block does not show the correct preview when shipping calculator is false and core -> require address is true
## Describe the bug
When **WooCommerce > Settings > Shipping > Hide shipping costs until an address is entered** is true and the cart block's **Shipping calculator** is false, the preview of the cart block should reflect what will be displayed on the front-end.

## To reproduce
1. Tick **WooCommerce > Settings > Shipping > Hide shipping costs until an address is entered** 
2. Add a cart block to a page, and in the block options disable "Shipping Calculator"
3. See the preview of the block, the shipping options section shows some example shipping methods.

## Expected behavior
The Shipping options section should say:
> **Shipping**
  _Calculated during checkout_ 
like it does on the front-end.

### Block preview

Screenshot 2020-12-17 at 20 46 18

### Front-end
Screenshot 2020-12-17 at 20 46 55

### WordPress (please complete the following information):
* Core version: 5.6
* WooCommerce version: 4.8.0
* WooCommerce Blocks version: 3.9.0

### PR DESCRIPTION
**Pull request by ralucaStan**
When WooCommerce > Settings > Shipping > Hide shipping costs until an address is entered is true and the cart block's Shipping calculator is false, the preview of the cart block should reflect what will be displayed on the front-end.

First commit actual fix, 2nd TS change.

Fixes #3566

### Screenshots
BEFORE: 
Screenshot 2021-03-10 at 15 01 10

AFTER: 
Screenshot 2021-03-10 at 14 58 04

### How to test the changes in this Pull Request:

- Tick WooCommerce > Settings > Shipping > Hide shipping costs until an address is entered
- Add a cart block to a page, and in the block options disable "Shipping Calculator"
- See the preview of the block

### Changelog

> Fix cart preview when shipping rates are set to be hidden until an address is entered.

### CODE REVIEW

**Review by opr — APPROVED** [review]
Looks good and tests well, thanks Raluca! 👍🏼

File: assets/js/base/components/cart-checkout/totals/shipping/index.tsx [hunk 1]
```diff
@@ -58,6 +144,12 @@ const TotalsShipping = ( {
 		isShippingCalculatorOpen,
 		setIsShippingCalculatorOpen,
 	};
+	// used for the editor logic as an extra check
+	// because previewData.cartHasCalculatedShipping is always true and shipping is always showed
+	const shippingCostRequiresAddress = getSetting(
+		'shippingCostRequiresAddress',
+		false
+	);
```
Comment (senadir) [inline assets/js/base/components/cart-checkout/totals/shipping/index.tsx]: Why can't preview data use this directly instead?

File: src/Assets.php [hunk 2]
```diff
@@ -162,6 +162,7 @@ public static function get_wc_block_data( $settings ) {
 				'productCount'                  => array_sum( (array) $product_counts ),
 				'attributes'                    => array_values( wc_get_attribute_taxonomies() ),
 				'isShippingCalculatorEnabled'   => filter_var( get_option( 'woocommerce_enable_shipping_calc' ), FILTER_VALIDATE_BOOLEAN ),
+				'shippingCostRequiresAddress'   => filter_var( get_option( 'woocommerce_shipping_cost_requires_address' ), FILTER_VALIDATE_BOOLEAN ),
```
Comment (senadir) [inline src/Assets.php:165]: Why isn't this part of block-settings consts?
