### PR TITLE
Checkout block: don't show message of missing shipping options if they are already set

### LINKED ISSUE #1793: Checkout block in editor: shows no shipping options configured even when they are set
**To Reproduce**
1. Make sure you have shipping methods set up in your WooCommerce settings (_WooCommerce_ > _Settings_ > _Shipping_).
2. Create a post with a _Checkout_ block.
3. Notice it shows the `Your store does not have any Shipping Options configured` message even though they are configured.

**Expected behavior**
Placeholder shipping options should be rendered there when they are configured.

**Screenshots**
imatge

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #1793.

### Screenshots

_No shipping zones configured:_
imatge

_Shipping zones configured:_
imatge
(this screenshot shows an issue with radio boxes in the editor, filled here: #1803)

### How to test the changes in this Pull Request:

To test this PR, you will need to check out this branch of WooCommerce `fix/25752-wc_get_shipping_method_count-check-enabled` (see https://github.com/woocommerce/woocommerce/pull/25753).

1. In _WooCommerce_ > _Settings_ make sure you have at least one shipping zone configured.
2. Create a post with the _Checkout_ block.
3. Verify the _Checkout_ block shows placeholder shipping rates.*
4. In the settings, remove all shipping zones.
5. Reload the post with the _Checkout_ block and verify it shows a message to configure them.

`*` We can't use the store shipping zones because they depend on the customer location and we don't know it in the editor, so I used the placeholder shipping rates. In the future we could try to use real shipping rates from the store if they are set worldwide, or the store only sells to a specific location which always has shipping options, etc. But that's probably out of the scope of _Cart_/_Checkout_ v1.

### What if #25753 is not merged in core?

I would create a follow-up issue to investigate other ways to check whether shipping methods exist or not.

### If #25753 is merged, what happens with older versions of WooCommerce?

People using old versions of WooCommerce will not get the fix from #25753. So in some cases they will see shipping zone placeholders even when they don't have any shipping method set up. While not ideal, I don't think that's a critical issue that should make us implement work-arounds in our code that will make maintenance more difficult. But I'm happy to discuss if the team thinks otherwise. :slightly_smiling_face:

### CODE REVIEW

File: src/BlockTypes/Checkout.php [hunk 1]
```diff
@@ -62,6 +62,13 @@ public function render( $attributes = array(), $content = '' ) {
 		if ( ! $data_registry->exists( 'shippingStates' ) ) {
 			$data_registry->add( 'shippingStates', WC()->countries->get_shipping_country_states() );
 		}
+		if ( function_exists( 'get_current_screen' ) ) {
+			$screen = get_current_screen();
+			if ( $screen->is_block_editor() && ! $data_registry->exists( 'shippingMethodsExist' ) ) {
```
Comment (mikejolley) [inline src/BlockTypes/Checkout.php]: I'd add a conditional just for `$screen` here before calling methods - sometimes it's not there, depending on how early this is called.

Comment (Aljullu) [reply src/BlockTypes/Checkout.php]: Good call. Done in fbf4c438af4b126f1bfdd6c7141e45db73655b64.

**Comment by Aljullu** [comment]
@mikejolley thanks for the review. This should be ready for another look.

> The only issue I saw was the styling was off on my install - maybe theme?

That was happening in the last Gutenberg release. Should be fixed in 46b75e857ed8d7b97aea4105ab9e491a67540f70.
