### PR TITLE
Single Product Template: fix compatibility layer logic when the blocks aren't wrapped in a group block

### LINKED ISSUE #9922: Single Product Template - Compatibility Layer: in some cases only the first block is rendered
## Describe the bug

In some cases, the Compatibility Layer display only the first block on the frontend side.

## To reproduce

1. Edit the Single Product Template.
2. Remove all the blocks.
3. Add three paragraph blocks.
4. Save it.
5. Visit a product.
6. Only the first paragraph block is visible.

## Expected behavior

All the paragraph blocks should be visible on the frontend.

## Screenshots

| Editor | Frontend |
|--------|--------|
|image|image|

### PR DESCRIPTION
**Pull request by gigitux**
This PR fixes woocommerce/woocommerce-blocks#9922. In this PR, I revisit the logic of the Compatibility Layer: It isn't necessary to wrap the blocks inside a div with the class `woocommerce` if any block related to the Single Product Template is used. In this way, it has been easier to fix the issue.

Fixes woocommerce/woocommerce-blocks#9922

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [x] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Edit the Single Product Template.
2. Remove all the blocks.
3. Add three paragraph blocks.
4. Save it.
5. Visit a product.
6. Ensure that all three paragraph blocks are visible.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Single Product Template Compatibility Layer: fix some blocks that don't show on the frontend side in a specific case.

### CODE REVIEW

File: src/Templates/SingleProductTemplateCompatibility.php [hunk 1]
```diff
@@ -396,10 +392,11 @@ private static function create_wrap_block_group( $blocks ) {
 	 * woocommerce/product-gallery-image, woocommerce/product-details, woocommerce/add-to-cart-form]
 	 *
 	 * @param array $parsed_blocks Array of parsed block objects.
-	 * @param array $single_product_template_blocks Array of single product template blocks.
 	 * @return bool True if the template has a single product template block, false otherwise.
 	 */
-	private static function has_single_product_template_blocks( $parsed_blocks, $single_product_template_blocks ) {
+	private static function has_single_product_template_blocks( $parsed_blocks ) {
+		$single_product_template_blocks = array( 'woocommerce/product-image-gallery', 'woocommerce/product-details', 'woocommerce/add-to-cart-form', 'woocommerce/product-meta', 'woocommerce/product-price', 'woocommerce/breadcrumbs' );
```
Comment (nefeline) [inline src/Templates/SingleProductTemplateCompatibility.php:398]: What do you think about adding an attribute or context that indicates a given block is part of the single product template instead of hardcoding names here? 

The reason I'm suggesting this change is because this list can quickly become obsolete as more blocks are added and/or their usage is enabled within the single product template.

Comment (gigitux) [reply src/Templates/SingleProductTemplateCompatibility.php:398]: Good point. Since this is a refactor, I would prefer to do this in a dedicated PR. If you agree, I would say to open an issue and add the cooldown label (in this PR, I just moved the array to a dedicated function). What do you think?

Comment (nefeline) [reply src/Templates/SingleProductTemplateCompatibility.php:398]: > If you agree, I would say to open an issue and add the cooldown label (in this PR, I just moved the array to a dedicated function). What do you think?

Sounds good! Can you please create the issue, then? 🙏

Comment (gigitux) [reply src/Templates/SingleProductTemplateCompatibility.php:398]: Done! https://github.com/woocommerce/woocommerce-blocks/issues/10008

**Review by nefeline — COMMENTED** [review]
The code looks good 🎉 ! I just have a question as the test instructions state:

> Only the first paragraph block is visible.

But all three paragraphs are visible with the changes made here (which I suspect is the desired outcome of this PR). Can you please confirm?

**Comment by gigitux** [comment]
> The code looks good 🎉 ! I just have a question as the test instructions state:
> 
> > Only the first paragraph block is visible.
> 
> But all three paragraphs are visible with the changes made here (which I suspect is the desired outcome of this PR). Can you please confirm?

Yeah! I updated the testing instructions:
> Ensure that all three paragraph blocks are visible.

Thanks for catching it!

**Review by nefeline — APPROVED** [review]
> Yeah! I updated the testing instructions

Thanks for confirming and updating the description: LGTM! 🚀
