### PR TITLE
Decode billing address data from the server

### LINKED ISSUE #2263: Checkout: Address fields are not decoded
**To Reproduce**
1. Go to `my-account` > _Addresses_ and modify your billing address with a city name that has an apostrophe.
2. Save it and add a digital product to your _Cart_ (make sure there are no physical products, otherwise the shipping address will be used).
3. Go to the _Checkout_ page.
3. Notice the address is not correctly decoded.

**Screenshots**
imatge

### PR DESCRIPTION
**Pull request by mikejolley**
Decodes billing address data loaded from the server.

Fixes #2263

### How to test the changes in this Pull Request:

See instructions in https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2263

### CODE REVIEW

File: assets/js/type-defs/billing.js [hunk 1]
```diff
@@ -1,19 +1,19 @@
...
+ * @property {string} last_name          Last name of billing customer
+ * @property {string} company            Company name for the billing address
+ * @property {string} address_1          First line of the billing address
+ * @property {string} address_2          Second line of the billing address
+ * @property {string} city               The city of the billing address
+ * @property {string} state              The state of the billing address (ISO or name)
+ * @property {string} postcode           The postal or zip code for the billing address
+ * @property {string} country            The country for the billing address (ISO)
+ * @property {string} phone              The phone number for the billing address
+ * @property {boolean} shippingAsBilling Whether the shipping and billing
```
Comment (Aljullu) [inline assets/js/type-defs/billing.js:15]: Nice find. I think I introduced this one. :sweat_smile:
