### PR TITLE
Prevent wp.components loading on frontend

### LINKED ISSUE #1899: wp.components is fully loading on Cart frontend
**Describe the bug**
as per @nerrad latest research in pb0Spc-nM-p2 it seems wp.components is loading in the frontend but we're supposed to be tree shaking it.

**To Reproduce**
in a page with Cart block, open network tab and watch the resources, you will see wp.components (I didn’t confirm this yet but I'm opening this trusting Darren analytics, I will fully check later.

### PR DESCRIPTION
**Pull request by mikejolley**
There were some frontend/base components using the `@wordpress/components` package. This PR fixes that to reduce the number of assets required on frontend.

Fixes #1899

### How to test the changes in this Pull Request:

1. Checkout this branch
2. Do a production build `npm run build`
3. Check network tools on the cart page to confirm `components` scripts are not loaded
4. Check /build/cart-frontend.asset.php for wp-components. It should not be there.

### CODE REVIEW

File: assets/js/base/components/tabs/index.js [hunk 1]
```diff
@@ -2,7 +2,7 @@
  * External dependencies
  */
 import { useState } from '@wordpress/element';
-import { withInstanceId } from '@wordpress/compose';
+import withComponentId from '@woocommerce/base-hocs/with-component-id';
```
Comment (nerrad) [inline assets/js/base/components/tabs/index.js]: We don't have to change this back, but now that WP packages can be tree-shaken, another approach here would be do direct imports for `@wordpress/compose` similar to how we do for `@wordpress/components` (via `wordpress-components`). `withComponentId` filled a gap for us when we had no way to either directly import WP packages or tree-shake them, but it's becoming unnecessary and we _could_ retire it.

Comment (mikejolley) [reply assets/js/base/components/tabs/index.js]: Ill sunset it in a followup
