### PR TITLE
Fix: WooCommerce Blocks causing malfunction of the navigation block on WordPress 6.3

### LINKED ISSUE #10220: "Doing it wrong" error triggers after navigating to "Appearance > Widgets" page
## Describe the bug
GlobalStep discovered this issue as part of critical flow testing.

A WordPress `Doing it wrong` message appears when the user clicks `Appearance > Widgets`.

```SHELL
Function wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). (This message was added in version 5.8.0.)
```

This check was first introduced in this WordPress commit: https://github.com/WordPress/WordPress/commit/846529de97790b9b866d4dd77a2940167374a52b. It has the following description:

> … in widgets editor

> It is common that plugins erroneously have `wp-editor` or `wp-edit-post` as a
dependency in a script that is loaded in the new widgets editor. This is a smell
since both `@wordpress/editor` and `@wordpress/edit-post` assume the existence
of a global "post" object which the widgets editor does not have.

And here is the original WordPress ticket: https://core.trac.wordpress.org/ticket/53569

The generated Woo Blocks build files `build/cart.asset.php` and `build/checkout.asset.php` does indeed include `wp-editor` as a dependency. Maybe the solution would be to dequeue the `wp-editor` script on the Widgets page.

## To reproduce

1. Use a non Block theme (I tested using the `storefront` and the `Twenty Twenty-one` themes)
2. Install and activate the [Query Monitor](https://wordpress.org/plugins/query-monitor/) plugin
3. Click on the new menu item in the admin toolbar menu to open the overview panel of the Query Monitor plugin

image

4. Go to `Appearance > Widgets`
5. Notice under the `Doing it Wrong` tab from Query Monitor's overview panel, the error message: `Function wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). (This message was added in version 5.8.0.)`

## Expected behavior

The page should be displayed without any error after navigating to "Woocommerce > Widgets".

## Screenshots

image

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   WooCommerce version: 8.0
-   WooCommerce Blocks version: 10.7
-   Site language: English (US)
-   Any other plugins installed: Query Monitor

### Desktop (please complete the following information):

-   OS: macOS
-   Browser Chrome
-   Version 114

## Additional context

- Global step ticket: https://github.com/woocommerce/woocommerce/issues/39169
- Slack thread: p1689010155432319-slack-C01DT6U03HC
- P2 comment: p6q8Tx-37X-p2#comment-7815

### LINKED ISSUE #10259: WooCommerce causing malfunction of the navigation block on WordPress 6.3
## Describe the bug

The core's Navigation Block doesn't work as expected while having the latest version of WooCommerce enabled on WordPress 6.3.

## To reproduce

1. Make sure you have a fresh WordPress install running on version 6.3. You can update the version via WP-CLI by running: `wp core download --version=nightly --force`
2. Update the DB via user interface or via WP-CLI as well by running: `wp core update-db`
3. Access your Dashboard and make sure you are indeed running the nightly version of WordPress, which currently is version `6.3-beta4-56253`.
4. Create a new post and insert the Navigation block. Make sure everything works as expected.
5. Now install and activate the latest version of WooCommerce (7.9.0)
6. Access the post you just created and notice the navigation block is not working anymore and there are errors in the console:

Screenshot 2023-07-18 at 16 47 47

## Expected behavior

The navigation block should work as expected while having WooCommerce enabled.

## Environment

-   WordPress version: [6.3-beta4-56253]
-   WooCommerce version: [7.9.0]

### PR DESCRIPTION
**Pull request by nefeline**
This PR solves the conflict preventing the core's navigation block from being correctly previewed in the editor while having WooCommerce 7.9.0 running alongside WordPress version 6.3. It also ensures the `Revert to Classic Product Template` button within the Product Catalog template works as expected.

Additional changes:

- The `getSiteEditorConfig` was added to WebPack, as we didn't have anything pre-existing that would perfectly fit this use-case. The benefit of this change is that we now have a dedicated entry to any scripts aimed for usage exclusively within the site editor (not on the front end). Open to discussion in case folks have different opinions/ideas.

Fixes woocommerce/woocommerce-blocks#10259 and woocommerce/woocommerce-blocks#10220

#### Navigation block:

| Before | After |
| ------ | ----- |
| Screenshot 2023-07-23 at 11 15 40 | Screenshot 2023-07-23 at 11 14 09 |

#### The revert button in the Product Catalog Template:

Screenshot 2023-07-27 at 18 47 46

#### User Facing Testing

1. Ensure you have a local install up and running with the release candidate version of WordPress 6.3. You can do so by downloading it via WP-CLI: `wp core update --version=6.3-RC1 --force` followed by `wp core update-db`. Alternatively, you can also download the zip for the release [over here](https://wordpress.org/wordpress-6.3-RC1.zip).
2. Ensure you have a block theme enabled such as Twenty-Twenty Three
3. Create a new post
4. Insert the navigation block
5. Make sure you can correctly preview it without any problems, as demonstrated in the screenshot in the description of this PR.
6. Now head over to Appearence > Editor > Templates > Product Catalog and edit it.
7. If you are seeing the "WooCommerce Product Grid Block", click on "Transform into blocks":

Screenshot 2023-07-27 at 18 56 37

8. Now, on the sidebar, click on Template and ensure the "Revert to classic template" button is visible (as demonstrated on the screenshot in the description of this PR).
9. Click on "Revert to classic template" button and make sure everything works as expected: the product blocks should be replaced with the "WooCommerce Product Grid Block".

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix: Resolve the conflict preventing the navigation block from being correctly previewed in the editor while having WooCommerce enabled.

### CODE REVIEW

File: src/AssetsController.php [hunk 1]
```diff
@@ -76,6 +75,20 @@ public function register_assets() {
 		);
 	}
 
+	/**
+	 * Register and enqueue assets for exclusive usage within the Site Editor.
+	 */
+	public function register_and_enqueue_site_editor_assets() {
+		$this->api->register_script( 'wc-blocks-classic-template-revert-button', 'build/wc-blocks-classic-template-revert-button.js', [ 'wp-edit-site', 'wp-data', 'wp-core-data', 'wp-element', 'wp-components', 'wp-i18n', 'wp-block-editor', 'wp-blocks' ] );
```
Comment (nerrad) [inline src/AssetsController.php]: You shouldn't need to include dependencies here. The `Automattic\WooCommerce\Blocks\Assets\API::register_script` method automatically handles detecting the relevant `*.asset.php` file for getting the dependencies and will utilize it. The dependencies argument on this method is only for explicitly adding dependencies when either there is no automatically generated `*.asset.php` file for the script handle, or to merge additional explicit dependencies with it.

**Review by nerrad — COMMENTED** [review]
Definitely in the right direction here. However, there's a an issue with the dependency registration and it looks like a build error (see the `.zip` build action log).

I didn't checkout the branch or test it, just took a quick look at the code.

File: src/AssetsController.php (hunk 1 above)
Comment (nefeline) [reply src/AssetsController.php]: Gotcha, thanks! I'm pushing a commit to streamline this soon.

**Comment by nefeline** [comment]
> Definitely in the right direction here. However, there's a an issue with the dependency registration and it looks like a build error (see the .zip build action log).

Out of curiosity, is this something you can reproduce locally? The build is working as expected locally over here: very odd =/

File: src/AssetsController.php (hunk 1 above)
Comment (nefeline) [reply src/AssetsController.php]: Confirmed that 100% of the dependencies added here are already provided via `Automattic\WooCommerce\Blocks\Assets\API::register_script` > `get_script_data`: updated https://github.com/woocommerce/woocommerce-blocks/pull/10388/commits/68b672d98f9d85f4052d7b6128b95e22427d5455

**Comment by nefeline** [comment]
> Definitely in the right direction here. However, there's a an issue with the dependency registration and it looks like a build error (see the .zip build action log).

Fixed on https://github.com/woocommerce/woocommerce-blocks/pull/10388/commits/d69082529d9fc975dc016fe0891ceeed1e0d487a : kudos to @roykho for the help! More details on p1690481974812849-slack-C02UBB1EPEF. As it turns out, even though this error was triggered locally, it didn't interrupt the build or cause any problems, that's the reason why it was missed during development.

**Comment by nefeline** [comment]
> As it turns out, even though this error was triggered locally, it didn't interrupt the build or cause any problems, that's the reason why it was missed during development.

Created https://github.com/woocommerce/woocommerce/issues/42273 to keep track of this issue.

**Review by roykho — APPROVED** [review]
Everything tested nicely per description. Thanks for creating the new `getSiteEditorConfig` in Webpack as that will definitely be useful in the future.

The only thing that stood out is do we need [`ProgressBarPlugin`](https://github.com/woocommerce/woocommerce-blocks/pull/10388/files#diff-fe2a96dd06027bb736a2f6e1cbaae6d5174d6aefd9fc1058a2527f810648504aR719) in the config? But it is not a blocker so approving.

Good job!

File: bin/webpack-entries.js [hunk 2]
```diff
@@ -130,6 +130,8 @@ const entries = {
 		'add-to-cart-form':
 			'./assets/js/atomic/blocks/product-elements/add-to-cart-form/index.tsx',
 		...getBlockEntries( '{index,block,frontend}.{t,j}s{,x}' ),
+		'wc-blocks-classic-template-revert-button-style':
+			'./assets/js/templates/revert-button/style.scss',
```
Comment (thealexandrelara) [inline bin/webpack-entries.js]: I think it would be better to move the usage of the spread operator to be the last item in the object:

```suggestion
		'wc-blocks-classic-template-revert-button-style':
			'./assets/js/templates/revert-button/style.scss',
		...getBlockEntries( '{index,block,frontend}.{t,j}s{,x}' ),
```

Comment (thealexandrelara) [inline bin/webpack-entries.js]: I noticed that all the values in other keys are referencing `.tsx`, `.ts`, `.js` or `.jsx` files, shouldn't we reference the `index.tsx` file in this case too?

```suggestion
		'wc-blocks-classic-template-revert-button-style':
			'./assets/js/templates/revert-button/index.tsx',
```

**Review by thealexandrelara — APPROVED** [review]
Great! I just tested and everything is working as expected. I just left some comments regarding the code but I'm pre-approving the PR

Here are the tests results:
✅ The Navigation blocks works without any errors
✅ The Revert to Classic Template button is visible and works as expected when clicked

File: bin/webpack-entries.js (hunk 2 above)
Comment (nefeline) [reply bin/webpack-entries.js]: Good call, updated for consistency with the other entries in this constant: [68e5415](https://github.com/woocommerce/woocommerce-blocks/pull/10388/commits/68e54150f47a7c2f82529102b6e9e3d17546f3f6)

Comment (nefeline) [reply bin/webpack-entries.js]: Thanks: I went ahead and added a comment to separate this new entry from the rest as the revert button is not really in the same category as the other blocks: it is meant specifically for usage within the template editor. [68e5415](https://github.com/woocommerce/woocommerce-blocks/pull/10388/commits/68e54150f47a7c2f82529102b6e9e3d17546f3f6)

**Comment by nefeline** [comment]
Thanks both for the reviews, much appreciated!

> The only thing that stood out is do we need [ProgressBarPlugin](https://github.com/woocommerce/woocommerce-blocks/pull/10388/files#diff-fe2a96dd06027bb736a2f6e1cbaae6d5174d6aefd9fc1058a2527f810648504aR719) in the config? But it is not a blocker so approving.

This was added to show the progress during the build, similar to what we do for other assets:

Screenshot 2023-07-31 at 08 42 42
