### PR TITLE
Ensure aria-label is showing correct value based on setting

### LINKED ISSUE #9645: Mini-Cart: aria-label value contains price even if "Display total price" attribute is set to false
## To reproduce

1. Add the Mini-Cart block to a post or page and set the _Display total price_ attribute to false.
2. Go to the frontend and with your browser devtools (<kbd>F12</kbd>) instead the `aria-label` value.
3. Notice it says "X items in cart, total price of Y".

## Expected behavior

If _Display total price_ attribute is set to false, I would expect `aria-label` to not contain the price, so it should be something like "X items in cart".

### PR DESCRIPTION
**Pull request by roykho**
Fixes https://github.com/woocommerce/woocommerce-blocks/issues/9645

This PR fixes the issue where the attribute `aria-label` is always displaying the `total price` information even when `Display total price` setting is false.

### Screenshots

| Display total price: false | Display total price: true |
| ------ | ----- |
|        |       |

#### User Facing Testing

1. Add the Mini-Cart block to a post or page and set the Display total price attribute to false.
2. Go to the frontend and with your browser devtools (F12). Inspect element and look for the`.wc-block-mini-cart__button` on the `mini cart block`. Find the `aria-label`.
3. Notice it says `X item(s) in cart`, with the price. Hover over the `mini cart` icon and click on. Inspect the element again to ensure it is still displaying `X item(s) in cart`.
4. Go back to the `mini cart` settings and switch it to show `Display total price`.
5. The `aria-label` should now show "X item(s) in cart, total price of Y".
6. BONUS: Add another instance of the `mini cart` in the header and perform the same tests and ensure each instance of the `mini cart` shows their own `aria-label` value depending on the `Display total price` settings.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix aria-label displaying wrong information on mini-cart

### CODE REVIEW

File: assets/js/blocks/mini-cart/utils/data.ts [hunk 1]
```diff
@@ -13,8 +13,8 @@ export const updateTotals = ( totals: [ string, number ] | undefined ) => {
 		return;
 	}
 	const [ amount, quantity ] = totals;
-	const miniCartButtons = document.querySelectorAll(
-		'.wc-block-mini-cart__button'
+	const miniCarts = document.querySelectorAll(
+		'.wc-block-mini-cart.wp-block-woocommerce-mini-cart'
```
Comment (danieldudzic) [inline assets/js/blocks/mini-cart/utils/data.ts]: I'd suggest keeping this in line with the code located in `frontend.ts`. Maybe it's also worth aborting if no mini cart blocks are found?

```suggestion
	const miniCartBlocks = document.querySelectorAll( '.wc-block-mini-cart' );
	if ( miniCartBlocks.length === 0 ) {
		return;
	}
```

File: assets/js/blocks/mini-cart/utils/data.ts [hunk 2]
```diff
@@ -23,21 +23,40 @@ export const updateTotals = ( totals: [ string, number ] | undefined ) => {
...
 
-	miniCartButtons.forEach( ( miniCartButton ) => {
-		miniCartButton.setAttribute(
-			'aria-label',
-			sprintf(
-				/* translators: %s number of products in cart. */
-				_n(
-					'%1$d item in cart, total price of %2$s',
-					'%1$d items in cart, total price of %2$s',
+	miniCarts.forEach( ( miniCart ) => {
```
Comment (danieldudzic) [inline assets/js/blocks/mini-cart/utils/data.ts]: Same here, following `frontend.ts`:

```suggestion
	miniCartBlocks.forEach( ( miniCartBlock ) => {
	if ( ! ( miniCartBlock instanceof HTMLElement ) ) {
		return;
	}
```

File: assets/js/blocks/mini-cart/utils/data.ts [hunk 3]
```diff
@@ -23,21 +23,40 @@ export const updateTotals = ( totals: [ string, number ] | undefined ) => {
...
+		const hasHiddenPrice = miniCart.getAttribute( 'data-has-hidden-price' );
```
Comment (danieldudzic) [inline assets/js/blocks/mini-cart/utils/data.ts]:
```suggestion

```

File: assets/js/blocks/mini-cart/utils/data.ts [hunk 4]
```diff
@@ -23,21 +23,40 @@ export const updateTotals = ( totals: [ string, number ] | undefined ) => {
...
+		const button = miniCart.querySelector( '.wc-block-mini-cart__button' );
```
Comment (danieldudzic) [inline assets/js/blocks/mini-cart/utils/data.ts]:
```suggestion
		const miniCartButton = miniCartBlock.querySelector(
			'.wc-block-mini-cart__button'
		);
		if ( ! miniCartButton ) {
			return;
		}
```

File: assets/js/blocks/mini-cart/utils/data.ts [hunk 5]
```diff
@@ -23,21 +23,40 @@ export const updateTotals = ( totals: [ string, number ] | undefined ) => {
...
+			button?.setAttribute(
+				'aria-label',
+				sprintf(
+					/* translators: %1$d is the number of products in the cart. %2$s is the cart total */
+					_n(
+						'%1$d item in cart, total price of %2$s',
+						'%1$d items in cart, total price of %2$s',
+						quantity,
+						'woo-gutenberg-products-block'
+					),
```
Comment (danieldudzic) [inline assets/js/blocks/mini-cart/utils/data.ts]:
```suggestion
	miniCartButton.setAttribute(
			'aria-label',
			miniCartBlock.dataset.hasHiddenPrice
				? sprintf(
						/* translators: %s number of products in cart. */
						_n(
							'%1$d item in cart',
							'%1$d items in cart',
							quantity,
							'woo-gutenberg-products-block'
						),
						quantity
				  )
				: sprintf(
						/* translators: %1$s number of products in cart, %2$s total price of products in cart. */
						_n(
							'%1$d item in cart, total price of %2$s',
							'%1$d items in cart, total price of %2$s',
							quantity,
							'woo-gutenberg-products-block'
						),
						quantity,
```

File: assets/js/blocks/mini-cart/utils/data.ts [hunk 6]
```diff
@@ -23,21 +23,40 @@ export const updateTotals = ( totals: [ string, number ] | undefined ) => {
...
-					'woo-gutenberg-products-block'
-				),
-				quantity,
-				amount
-			)
-		);
+					amount
+				)
+			);
+		}
```
Comment (danieldudzic) [inline assets/js/blocks/mini-cart/utils/data.ts]:
```suggestion
					amount
				  )
		);
```

**Review by danieldudzic — APPROVED** [review]
Was actually working on this also, but forgot to assign myself 😅.

I have tested this PR and it works great!

I am adding some stylistic suggestions based on the code present in `frontend.ts` but feel free to ignore them.

I'm pre-approving :)

**Comment by roykho** [comment]
@danieldudzic - great suggestions, I didn't know there were already existing code in `frontend.ts` that did just about the same.
