### PR TITLE
Product Search Results template: fix the preview when the Inherit Query option is enabled  

### LINKED ISSUE #7921: Product Query: Inherit Query template enabled and preview on the editor side
## Describe the bug
This issue is a follow-up of [this comment](https://github.com/woocommerce/woocommerce-blocks/pull/7641#issuecomment-1346472867).

On the Product Search Results template, if the user applies some filters on the Product Query and after that enables "Inherit Query from template", the preview doesn't update and shows only the products that match the filters.

The preview for other templates is updated correctly because [Gutenberg logic takes care of it](https://github.com/WordPress/gutenberg/blob/7dda7859adfa06adbe0da026f8f1253c2b001847/packages/block-library/src/post-template/edit.js/#L168-L177).

## To reproduce

1. Edit the _Product Search Results_ template.
2. Add the _Products_ block.
3. Add the _Sale Status_ filter and select _Show only products on sale_.
4. Now, enable _Inherit query from template_.
5. Notice only products on sale are displayed in the editor.
6. Instead, all products are shown in the front end.

## Expected behavior

When the "Inherit Query from template" option is enabled, the preview should be updated and show all the products.

### PR DESCRIPTION
**Pull request by gigitux**
With this PR, when the user disabled the "Inherit Query option", the previous options are restored.

Fixes #7921

#### Automated Tests
* [x] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [x] E2E tests

#### User Facing Testing

1. Edit the _Product Search Results_ template.
2. Add the _Products_ block.
3. Add the _Sale Status_ filter and select _Show only products on sale_.
4. Now, enable _Inherit query from template_.
5. Be sure that all products are displayed.
6. Disable  _Inherit query from template_.
7. Be sure that only on-sale products are visible.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [x] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Comment by nefeline** [comment]
Hey @gigitux ! I see this PR is flagged as blocked by #7956 : All good to review it right away or are more changes expected here after the blocker is removed & the other PR merged?

**Comment by gigitux** [comment]
> Hey @gigitux ! I see this PR is flagged as blocked by #7956 : All good to review it right away or are more changes expected here after the blocker is removed & the other PR merged?

You can already review it. This PR includes changes from #7956. I suggest reviewing #7956 and, after that, reviewing this PR.

**Comment by nefeline** [comment]
Great work! 👏 

> This PR includes changes from https://github.com/woocommerce/woocommerce-blocks/pull/7956. I suggest reviewing https://github.com/woocommerce/woocommerce-blocks/pull/7956 and, after that, reviewing this PR.

I see @danieldudzic is already assigned to review that one, so I'll focus here, but heads up, some tests here are failing (both on the CI and locally). 

### User facing test results:

> Edit the Product Search Results template.
> Add the Products block.
> Add the Sale Status filter and select Show only products on sale.

✅ Confirmed that when the sale status filter is enabled, only products on sale are displayed

> Now, enable Inherit query from template.
> Be sure that all products are displayed.

✅ Confirmed all products are displayed when the Inherit query from template option is enabled.

> Disable Inherit query from template.
> Be sure that only on-sale products are visible.

✅ Confirmed only on-sale products are visible.

### e2e test results:

The tests on this branch are failing. When running the product-query test suite locally, it also failed, so probably worth investigating the causes.

**Comment by gigitux** [comment]
Thanks for the review!

> ### e2e test results:
> The tests on this branch are failing. When running the product-query test suite locally, it also failed, so probably worth investigating the causes.

The E2E tests fail in trunk too. I will take a look at them next week!

File: assets/js/blocks/product-query/inspector-controls.tsx [hunk 1]
```diff
@@ -203,7 +232,16 @@ const ProductQueryControls = ( props: ProductQueryBlock ) => {
...
+								<Control
+									{ ...props }
+									queryObjectBeforeInheritEnabled={
+										queryObjectBeforeInheritEnabled
+									}
+									defaultWooQueryParams={
+										defaultWooQueryParams
+									}
+									key={ key }
+								/>
```
Comment (imanish003) [inline assets/js/blocks/product-query/inspector-controls.tsx]: AFAIU `queryObjectBeforeInheritEnabled` & `defaultWooQueryParams` will be used in only `wooInherit`.  If that's the case then I think instead of passing these as props, we should calculate it inside `wooInherit` function. 

As we are using hooks (ex. `usePrevious`), I believe we will need to extract the wooInherit function as a component, something like this.
```
wooInherit: WooInheritToggleControl
```

IMO this would make the code easier to understand, but please feel free to ignore my suggestion if you disagree.

**Review by imanish003 — APPROVED** [review]
I tested the PR & it's working as expected. I left one minor suggestion but pre-approving PR because that's not a blocker 🚀

File: assets/js/blocks/product-query/inspector-controls.tsx (hunk 1 above)
Comment (gigitux) [reply assets/js/blocks/product-query/inspector-controls.tsx]: Nice suggestion! I addressed it via 33fbac9cf1e874904c36164dc2f54104ba0f3a0b.
I tested it, and it works. Please, could you recheck it?

**Review by imanish003 — CHANGES_REQUESTED** [review]
Hi @gigitux,
There is one issue. If I set keyword in filters as shown in screenshot below:
image

And then enable `Inherit query from template` then, keyword effect is still there, i.e., I still see products that are filtered by the Keyword. 

Is it expected? AFAIK filters shouldn't have any effect when `Inherit query from template` is enabled. I might be wrong 🤷🏻‍♂️

**Comment by gigitux** [comment]
> Hi @gigitux, There is one issue. If I set keyword in filters as shown in screenshot below: image
> 
> And then enable `Inherit query from template` then, keyword effect is still there, i.e., I still see products that are filtered by the Keyword.
> 
> Is it expected? AFAIK filters shouldn't have any effect when `Inherit query from template` is enabled. I might be wrong 🤷🏻‍♂️

That is a good point, but I can replicate this issue on the trunk. I think that it is a bug in the Query Loop block. Should we open another issue or write the issue on https://github.com/WordPress/gutenberg/issues/29438?

**Review by imanish003 — APPROVED** [review]
@gigitux You are right. We can open a new issue on Gutenberg repo. Approving the PR 🚀

Although I think the issue you mentioned is a different one & not related to Inherit query from template toggle. You can also see [my comment](https://github.com/WordPress/gutenberg/issues/29438#issuecomment-1413572661) on the issue.

**Comment by gigitux** [comment]
Thanks for the review!

> We can open a new issue on Gutenberg repo.

Can you take care of this?

**Comment by imanish003** [comment]
> Can you take care of this?

Sure, I will take care of this 🤝
