### PR TITLE
Product Gallery: fix warning

### LINKED ISSUE #10836: Product Gallery: Warning: Cannot update a component (`Layout`) while rendering a different component (`Edit`).
## Describe the bug

When the Product Gallery is added on the Single Product Template, on the console, ```react-dom.js?ver=18.2.0:73 Warning: Cannot update a component (`Layout`) while rendering a different component (`Edit`).``` shows up.

## To reproduce

1. Open the Site Editor.
2. Edit the SIngle Product template
3. Add the Product Gallery.
4. Open the console.
5. See error.

## Expected behavior

No error should be visible in the console.

## Screenshots

image

### PR DESCRIPTION
**Pull request by gigitux**
## What

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/10836

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. Open the Site Editor.
2. Edit the SIngle Product template
3. Add the Product Gallery.
4. Open the console.
5. Ensure that the error is not visible.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|        |       |

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental
* [ ] N/A

## Checklist

Required:
* [ ] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

### CODE REVIEW

**Review by danieldudzic — COMMENTED** [review]
I have tested this, and it works correctly. But since I had trouble replicating the original issue, I'd be more comfortable with someone else also checking.

**Comment by imanish003** [comment]
> I have tested this, and it works correctly. But since I had trouble replicating the original issue, I'd be more comfortable with someone else also checking.

Hi @danieldudzic, I'll take a look today as well 🤝

File: assets/js/blocks/product-gallery/edit.tsx
Comment (imanish003) [inline assets/js/blocks/product-gallery/edit.tsx:1]: As you can see in the video below, the position of thumbnails is incorrect after adding the 'Product Gallery' block.

https://github.com/woocommerce/woocommerce-blocks/assets/16707866/7ee4c2bc-45cb-4365-b0ec-6663ede95a84


- Can you reproduce this issue? Here are the steps I followed:
  - Dev build using this command: `npm run package-plugin:dev`
  - Created a new JN instance: https://jurassic.ninja/create/?nojetpack&woocommerce
  - Uploaded the zip file generated by the dev build command
  - Followed the steps shown in the video.

I'm not sure if this issue is related to the code changes in this PR, but I wanted to share it here.

**Review by imanish003 — APPROVED** [review]
I've tested the changes and can confirm that there are no longer any errors in the console. During my testing, I did encounter one issue, but I believe it's unrelated to this PR. Hence, I'm pre-approving it. Thanks for fixing the error 🚀

File: assets/js/blocks/product-gallery/edit.tsx
Comment (gigitux) [reply assets/js/blocks/product-gallery/edit.tsx:1]: Nice catch, @imanish003!

I fixed it with [79d8eef](https://github.com/woocommerce/woocommerce-blocks/pull/10839/commits/79d8eef403af64243d9075bdb84914d7fc88e9af). Also, I added an E2E test to ensure that the position is always right.

https://github.com/woocommerce/woocommerce-blocks/assets/4463174/ed93d39e-59aa-4751-950d-f9c129f1bc44

This is not related to this PR, but I realized that in the utils file, in the function `moveInnerBlocksToPosition` ([source code](https://github.com/woocommerce/woocommerce-blocks/blob/79d8eef403af64243d9075bdb84914d7fc88e9af/assets/js/blocks/product-gallery/utils.tsx)), we are invoking the `select` function to retrieve some redux selectors. I think that we should pass the selectors from the block and avoid invoking the `select` function inside the function. 

cc @danieldudzic

Comment (imanish003) [reply assets/js/blocks/product-gallery/edit.tsx:1]: Hi Luigi, I tested the changes again. It fixed the initial loading issue, but now the thumbnails position isn't working correctly, as you can see in video 🤷🏻‍♂️


https://github.com/woocommerce/woocommerce-blocks/assets/16707866/291d4fde-875e-4047-b31b-765dfaa88d54



Are you able to reproduce this issue?

Comment (gigitux) [reply assets/js/blocks/product-gallery/edit.tsx:1]: Ops sorry! With [435efc6](https://github.com/woocommerce/woocommerce-blocks/pull/10839/commits/435efc6bc674317bc6add3ad102c34922f4825b6), I fixed the regression!

Luckily, we have E2E tests that catch these regressions!

Comment (imanish003) [reply assets/js/blocks/product-gallery/edit.tsx:1]: Hey Luigi, Thanks for fixing the issue. I tested the changes & looks like the issue is resolved now 🎉

I am just curious: Will we handle this overflow issue in other PR?
image

File: assets/js/blocks/product-gallery/utils.tsx [hunk 1]
```diff
@@ -121,6 +126,23 @@ const findBlock = ( {
 	return undefined;
 };
 
+export const updateGroupBlockType = (
```
Comment (imanish003) [inline assets/js/blocks/product-gallery/utils.tsx]: Is it necessary to export this function because AFAIU is used inside this file only?

Comment (imanish003) [inline assets/js/blocks/product-gallery/utils.tsx]: I'm not sure if the function's name accurately reflects its functionality. Since it's responsible for updating the layout, how about renaming it to something like **setGroupBlockLayout** or **adjustGroupBlockLayoutForThumbnails** etc.?

File: tests/e2e/tests/product-gallery/inner-blocks/product-gallery-thumbnails/product-gallery-thumbnails.block_theme.side_effects.spec.ts
Comment (imanish003) [inline tests/e2e/tests/product-gallery/inner-blocks/product-gallery-thumbnails/product-gallery-thumbnails.block_theme.side_effects.spec.ts:1]: Thanks for adding the E2E tests 💪🏻

**Review by imanish003 — APPROVED** [review]
Hello @gigitux, I wanted to express my appreciation for addressing the minor issues I pointed out. Great job 🚀! I've left some minor suggestions, but I'm pre-approving the PR since I don't believe these are blockers. :shipit:

File: assets/js/blocks/product-gallery/utils.tsx (hunk 1 above)
Comment (gigitux) [reply assets/js/blocks/product-gallery/utils.tsx]: Good point, I renamed it in `setGroupBlockLayoutByThumbnailsPosition`
