### PR TITLE
Make Mini-Cart block work well with caching plugins

### LINKED ISSUE #9353: Make the Mini Cart block cache-friendly
Currently, if a store wants to use page caching, the Mini Cart block can show outdated totals or even totals from other sessions. We would like to fix that so stores can enable page caching without problems even when having the Mini Cart block in their page.

See also https://github.com/woocommerce/woocommerce-blocks/issues/7530.

## To reproduce

1. Install _WP-Optimize - Clean, Compress, Cache_ or a similar caching plugin.
2. Go to WP-Optimize > Settings > Cache and enable page caching.
3. In the frontend without being logged in (ie: in a private/incognito window) visit any page.
4. Add some products to your cart.
5. Visit the same page from step 3.
6. Notice the Mini Cart totals don't include the products you added in step 4.

## Expected behavior

Mini Cart should always show the correct totals, even if caching is enabled.

## Approach

In order to solve that, we would like to:

1. Store cart data in the client local storage. Ideally we would store the minimum data needed for the Mini Cart to show the correct values.
2. On PHP render, we would render the Mini Cart block as we do right now, assuming there are 0 products in the cart.
3. On page load:
3.1. We would check if the user has some cart data in their local storage. If it does, we will use it to fill Mini Cart block details.
3.2. In addition to the previous step, we will make a query to the Store API to gather the cart values and will update them in the Mini Cart button. We will save these values into the user local storage.

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #9353.

#### Accessibility

- [x] I've tested using only a keyboard (no mouse)
- [x] I've tested using a screen reader
- (n/a) All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- (n/a) All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [x] Unit tests
  * [ ] E2E tests

#### User Facing Testing

**With your admin user:**

1. Install _[WP-Optimize - Clean, Compress, Cache](https://wordpress.org/plugins/wp-optimize/)_ or a similar caching plugin.
2. Go to WP-Optimize > Settings > Cache and enable page caching.

**In a private/incognito window without being logged in:**
3. In the frontend visit any page. This will cache the page without products in the cart.

**With your admin user:**
4. Add some products to your cart.
5. Visit the same page from step 3.
6. Notice the Mini Cart totals do include the products you added in step 4, even though it's serving the cached version of step 3.

* [ ] Do not include in the Testing Notes

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

This PR adds an extra request to all page views were the Mini-Cart block is present. It also increases a the weight of Mini-Cart block scripts on page load. However, I think the benefits of this outweight the performance impact.

### Changelog

> The Mini-Cart block is now compatible with caching plugins.

### CODE REVIEW

File: assets/js/blocks/rating-filter/test/block.tsx [hunk 1]
```diff
@@ -258,7 +257,9 @@ describe( 'Filter by Rating block', () => {
 			);
 
 			if ( removeRating4Button ) {
-				userEvent.click( removeRating4Button );
+				act( () => {
+					userEvent.click( removeRating4Button );
+				} );
```
Comment (Aljullu) [inline assets/js/blocks/rating-filter/test/block.tsx:262]: I have no idea why these tests suddenly stopped passing, so I needed to add `atc()` here.

File: assets/js/blocks/mini-cart/utils/set-styles.ts
Comment (Aljullu) [inline assets/js/blocks/mini-cart/utils/set-styles.ts:1]: Heads-up that I didn't change anything in the code of this file, I just moved it over from `assets/js/blocks/mini-cart/frontend.ts`.

File: assets/js/blocks/mini-cart/utils/data.ts [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+} from '@woocommerce/price-format';
+import { CartResponse } from '@woocommerce/types';
+
+export const updateTotals = ( totals: [ string, number ] | void ) => {
+	if ( ! totals ) {
+		return;
+	}
+	const [ amount, quantity ] = totals;
+	const miniCartButtons = document.querySelectorAll(
+		'.wc-block-mini-cart__button'
```
Comment (gigitux) [inline assets/js/blocks/mini-cart/utils/data.ts:17]: What do you think about using a more specific selector? Also, is it a particular reason for using `querySelectorAll`?

File: assets/js/blocks/mini-cart/utils/data.ts [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+ * External dependencies
+ */
+import { _n, sprintf } from '@wordpress/i18n';
+import {
+	getCurrencyFromPriceResponse,
+	formatPrice,
+} from '@woocommerce/price-format';
+import { CartResponse } from '@woocommerce/types';
+
+export const updateTotals = ( totals: [ string, number ] | void ) => {
```
Comment (gigitux) [inline assets/js/blocks/mini-cart/utils/data.ts]: I would use `undefined` instead `void`.

The intent of void is that a function's return value will not be observed. This is very different from will be undefined.  ([source](https://stackoverflow.com/a/58885486))

File: assets/js/blocks/mini-cart/utils/data.ts [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+	const currency = getCurrencyFromPriceResponse( miniCartTotals.totals );
+	const formattedPrice = formatPrice(
+		miniCartTotals.totals.total_price,
+		currency
+	);
+	return [ formattedPrice, miniCartTotals.itemsCount ] as [ string, number ];
+};
+
+export const getMiniCartTotalsFromServer = async (): Promise<
+	[ string, number ] | void
```
Comment (gigitux) [inline assets/js/blocks/mini-cart/utils/data.ts]: I would use undefined instead void.

The intent of void is that a function's return value will not be observed. This is very different from will be undefined. ([source](https://stackoverflow.com/a/58885486))

File: assets/js/blocks/mini-cart/utils/data.ts [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+				'wc-blocks_mini_cart_totals',
+				JSON.stringify( {
+					totals: data.totals,
+					itemsCount: data.items_count,
+				} )
+			);
+			return [ formattedPrice, data.items_count ] as [ string, number ];
+		} )
+		.catch( ( error ) => {
+			// eslint-disable-next-line no-console
```
Comment (gigitux) [inline assets/js/blocks/mini-cart/utils/data.ts:110]: I would return `undefined` or maybe a fallback value to have a graceful error handling.

File: assets/js/blocks/mini-cart/utils/set-styles.ts [hunk 6]
```diff
@@ -0,0 +1,53 @@
+function getClosestColor(
+	element: Element | null,
+	colorType: 'color' | 'backgroundColor'
+): string | null {
+	if ( ! element ) {
+		return null;
+	}
```
Comment (gigitux) [inline assets/js/blocks/mini-cart/utils/set-styles.ts:7]: I suggest removing this check. In this way `element` can be defined. The caller should do this check. (you already do for `badgeTextColor` and `badgeBackgroundColor`).

File: assets/js/blocks/mini-cart/frontend.ts
Comment (gigitux) [inline assets/js/blocks/mini-cart/frontend.ts:1]: Just a question: Any idea why:
```
updateTotals( getMiniCartTotalsFromLocalStorage() );
getMiniCartTotalsFromServer().then( updateTotals );
setStyles();
```

are invoked even if this file isn't in the `sideEffects` array in the `package.json`?

File: src/BlockTypes/MiniCart.php [hunk 7]
```diff
@@ -421,43 +414,23 @@ protected function get_markup( $attributes ) {
...
-			/* translators: %1$d is the number of products in the cart. %2$s is the cart total */
-			_n(
-				'%1$d item in cart, total price of %2$s',
-				'%1$d items in cart, total price of %2$s',
-				$cart_contents_count,
-				'woo-gutenberg-products-block'
-			),
-			$cart_contents_count,
-			wp_strip_all_tags( wc_price( $cart_contents_total ) )
-		);
```
Comment (gigitux) [inline src/BlockTypes/MiniCart.php:449]: Should we remove the `aria_label`?

**Review by gigitux — CHANGES_REQUESTED** [review]
Thanks for working on this! Overall it works great! 

I noticed when the PHP version is loaded the badge is visible, while when the JS version is loaded, the badge isn't visible:

Screen Capture on 2023-05-22 at 11-30-31

Also, I added some comments.

**Comment by Aljullu** [comment]
Thanks for the review, @gigitux!

> I noticed when the PHP version is loaded the badge is visible, while when the JS version is loaded, the badge isn't visible:

Oh, good catch. Should be fixed in c288ee2451caeebd9328665b7fa410940b58aedb.

File: assets/js/blocks/mini-cart/utils/data.ts (hunk 2 above)
Comment (Aljullu) [reply assets/js/blocks/mini-cart/utils/data.ts:17]: > What do you think about using a more specific selector?

What would be the benefit of using a more specific selector? We want to select all Mini-Cart buttons and `.wc-block-mini-cart__button` will give us all of them.

> Also, is it a particular reason for using `querySelectorAll`?

You mean why using `querySelectorAll` instead of `querySelector`? The reason is that even though we only allow inserting one Mini-Cart button, there is the chance that more than one might be displayed at the same time. Imagine somebody adding the Mini-Cart block to the header of their site and then creating a page with the Mini-Cart block. When viewing that page, there will be two Mini-Cart buttons on the same page. That's why I usually try to make everything work assuming there might be several Mini-Cart blocks on the same, even if we don't officially support that.

File: assets/js/blocks/mini-cart/utils/data.ts (hunk 3 above)
Comment (Aljullu) [reply assets/js/blocks/mini-cart/utils/data.ts]: Good point, all types should have been fixed in 01d162e50c4885d954be0f1ee77637b79e72f916.

File: assets/js/blocks/mini-cart/frontend.ts
Comment (Aljullu) [reply assets/js/blocks/mini-cart/frontend.ts:1]: Hmmm, I'm not sure, but I think it's the same with all block frontend scripts we have, no? We are enqueuing the built files directly from PHP instead of bundling them in a separate JS built.

File: src/BlockTypes/MiniCart.php (hunk 7 above)
Comment (Aljullu) [reply src/BlockTypes/MiniCart.php:449]: I'm not sure to understand your comment. This `aria-label` has been moved to the frontend script, as we no longer have the data in the PHP side:

https://github.com/woocommerce/woocommerce-blocks/blob/fix/9353-mini-cart-cache-friendly/assets/js/blocks/mini-cart/utils/data.ts#L27-L41

Comment (gigitux) [reply src/BlockTypes/MiniCart.php:449]: Sorry, I wanted to cancel this comment

File: assets/js/blocks/mini-cart/utils/data.ts (hunk 2 above)
Comment (gigitux) [reply assets/js/blocks/mini-cart/utils/data.ts:17]: > What would be the benefit of using a more specific selector? We want to select all Mini-Cart buttons and .wc-block-mini-cart__button will give us all of them.

Yeah! Good point! 👍

**Review by gigitux — APPROVED** [review]
Thanks for addressing the comments! LGTM!
