### PR TITLE
Show a warning to notify the user if the WC Blocks version is behind the one bundled in WC Core

### LINKED ISSUE #5587: Add a notice when WC Blocks plugin is active but the version being run is the one from WC core
When the version of WC Blocks bundled in core is bigger than the version of the WC Blocks feature plugin, the version bundled in core 'wins' and that's the one that is executed. That can cause unexpected results like the Cart and Checkout blocks not being available.

## To reproduce
1. Install WC core 6.1.0 and WC Blocks 6.5.0.
2. Create a post or page and try to add the Cart or Checkout blocks.
3. Notice they aren't available because the version of WC Blocks that is run is the one from WC core (which doesn't include those blocks). However, there is no easy way to know where the issue comes from.

Quoting @frontdevde:
> You can check to see which package is being loaded here: `/wp-admin/admin.php?page=wc-status`… if it’s loading the plugin version, it’ll look something like this:
> `…/wp-content/plugins/woocommerce-gutenberg-products-block/`
> If it’s loading the version packaged with WooCommerce, it’ll look like this:
> `…/wp-content/plugins/woocommerce/packages/woocommerce-blocks/`

## Expected behavior
If I have WC Blocks installed and active, but the version of WC Blocks that is run is the one from WC core, I should be notified about that. For example, with a notice bar in the plugins page telling me: "You have WC Blocks installed, but the version that is run is the one bundled in WC core because it's more modern (6.5.1 vs. 6.5.0). Please, update WC Blocks." (or something like that)

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #5587

This PR checks if the current version of WC Blocks plugin is behind the one bundled in WC Core and then shows a warning to notify the store admin about that.

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) .
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md)
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

image

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Edit `wp-content/plugins/woocommerce-blocks/vendor/composer/jetpack_autoload_psr4.php`, look for the `Automattic\\WooCommerce\\Blocks\\`, change the version from `dev-trunk` to `7.5.0`.
```php
	'Automattic\\WooCommerce\\Blocks\\' => array(
		'version' => '7.5.0',
		'path'    => array( $baseDir . '/src' )
	),
```
2. Go to the Admin > Plugins.
3. See the notice as the screenshot shows above.
4. Make sure to revert the file after the test.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [x] Feature plugin
* [ ] Experimental

### CODE REVIEW

File: woocommerce-gutenberg-products-block.php [hunk 1]
```diff
@@ -261,3 +261,54 @@ function woocommerce_blocks_get_php_translation_from_core( $translation, $text,
...
+
+if ( woocommerce_blocks_plugin_is_outdated() ) {
+	/**
+	 * Add notice to the admin dashboard if the plugin is outdated.
+	 */
+	function woocommerce_blocks_plugin_outdated_notice() {
+		if ( should_display_compatibility_notices() ) {
+			?>
+			<div class="notice notice-warning">
+				<p><?php esc_html_e( 'You have WooCommerce Blocks installed, but the version that is running is the one bundled in WooCommerce core because it is more up-to-date. Please, update the WooCommerce Blocks plugin.', 'woo-gutenberg-products-block' ); ?></p>
```
Comment (senadir) [inline woocommerce-gutenberg-products-block.php]: We might to mention that this will cause unexpected compatibility issues.

Comment (dinhtungdu) [reply woocommerce-gutenberg-products-block.php]: Agree! I updated the message in e479a49.

File: woocommerce-gutenberg-products-block.php [hunk 2]
```diff
@@ -261,3 +261,54 @@ function woocommerce_blocks_get_php_translation_from_core( $translation, $text,
...
+
+if ( woocommerce_blocks_plugin_is_outdated() ) {
+	/**
+	 * Add notice to the admin dashboard if the plugin is outdated.
+	 */
+	function woocommerce_blocks_plugin_outdated_notice() {
+		if ( should_display_compatibility_notices() ) {
+			?>
+			<div class="notice notice-warning">
+				<p><?php esc_html_e( 'You have WooCommerce Blocks installed, but the WocCommerce bundled version is running because it is more up-to-date. This may cause unexpected compatibility issues. Please update the WooCommerce Blocks plugin.', 'woo-gutenberg-products-block' ); ?></p>
```
Comment (Aljullu) [inline woocommerce-gutenberg-products-block.php]: Typo:
```suggestion
				<p><?php esc_html_e( 'You have WooCommerce Blocks installed, but the WooCommerce bundled version is running because it is more up-to-date. This may cause unexpected compatibility issues. Please update the WooCommerce Blocks plugin.', 'woo-gutenberg-products-block' ); ?></p>
```

File: woocommerce-gutenberg-products-block.php [hunk 3]
```diff
@@ -261,3 +261,54 @@ function woocommerce_blocks_get_php_translation_from_core( $translation, $text,
 }
 
 add_filter( 'gettext', 'woocommerce_blocks_get_php_translation_from_core', 10, 3 );
+
+/**
+ * Check the current WC Blocks path. If the WC Blocks plugin is active but the
+ * current path is from the WC Core, we can consider the plugin is outdated
+ * because JetPack autoloader always loads the newer package.
```
Comment (Aljullu) [inline woocommerce-gutenberg-products-block.php]: Not a big deal, but I think the correct branding is as follows:
```suggestion
 * because Jetpack Autoloader always loads the newer package.
```

File: woocommerce-gutenberg-products-block.php [hunk 4]
```diff
@@ -261,3 +261,54 @@ function woocommerce_blocks_get_php_translation_from_core( $translation, $text,
...
+	$active_plugins = get_option( 'active_plugins', array() );
+
+	// We check for the main plugin file only instead of the full path, because
+	// the plugin folder may not be 'woocommerce-blocks'.
+	foreach ( $active_plugins as $plugin ) {
+		if ( strpos( $plugin, 'woocommerce-gutenberg-products-block.php' ) ) {
+			$is_active = true;
+			break;
+		}
+	}
```
Comment (Aljullu) [inline woocommerce-gutenberg-products-block.php]: I don't have a strong opinion, but we could alternatively use [`is_plugin_active()`](https://developer.wordpress.org/reference/functions/is_plugin_active/) here, right? Did you discard it for some reason?
```PHP
$is_active =
	is_plugin_active( 'woocommerce-gutenberg-products-block/woocommerce-gutenberg-products-block.php' ) ||
	is_plugin_active( 'woocommerce-blocks/woocommerce-gutenberg-products-block.php' );
```

(I tested and that function is not available yet when this code is executed, but we could easily move the `woocommerce_blocks_plugin_is_outdated()` check inside the `woocommerce_blocks_plugin_outdated_notice()` function to solve that)

**Review by Aljullu — APPROVED** [review]
LGTM, thanks for fixing this one, @dinhtungdu! I left a couple of comments, but pre-approving.

File: woocommerce-gutenberg-products-block.php (hunk 4 above)
Comment (dinhtungdu) [reply woocommerce-gutenberg-products-block.php]: @Aljullu yes, we can use `is_plugin_active()`. I did it the current way so the code works with any plugin folder name. We already have three possible names:
- `woo-gutenberg-products-block` (which is used by the .org plugin).
- `woocommerce-blocks`.
- `woocommerce-gutenberg-products-block`.

Comment (dinhtungdu) [reply woocommerce-gutenberg-products-block.php]: After considering, I decided to use `is_plugin_active` and explicitly check for three possible cases.

File: woocommerce-gutenberg-products-block.php [hunk 5]
```diff
@@ -239,25 +239,38 @@ function woocommerce_blocks_get_i18n_data_json( $translations, $file, $handle, $
...
- * texts are the same (which happens when translations are missing).
+ * Add notice to the admin dashboard if the plugin is outdated.
  *
- * @param string $translation Translated text based on WC Blocks translations.
- * @param string $text        Text to translate.
- * @param string $domain      The text domain.
- * @return string WC Blocks translation. In case it's the same as $text, Core translation.
+ * @see https://github.com/woocommerce/woocommerce-blocks/issues/5587
  */
-function woocommerce_blocks_get_php_translation_from_core( $translation, $text, $domain ) {
```
Comment (Aljullu) [inline woocommerce-gutenberg-products-block.php]: Is removing this function a mistake, or I'm missing something?

**Review by Aljullu — APPROVED** [review]
Overall looking good, but I'm a bit confused by the removal of `woocommerce_blocks_get_php_translation_from_core()`, seems unrelated to this PR.

**Review by Aljullu — CHANGES_REQUESTED** [review]
Ups, sorry. I didn't want to approve it yet. :sweat_smile:

File: woocommerce-gutenberg-products-block.php (hunk 5 above)
Comment (senadir) [reply woocommerce-gutenberg-products-block.php]: PR probably needs to be rebased given this is change in another PR.

Comment (dinhtungdu) [reply woocommerce-gutenberg-products-block.php]: My bad! Have no idea why I removed this function in the latest commit.

**Comment by dinhtungdu** [comment]
@Aljullu I'm so sorry for the mistake! I updated my PR. Please take another look!

**Review by Aljullu — APPROVED** [review]
Thanks for updating the PR, @dinhtungdu! This is testing well and code looks good. :rocket:
