### PR TITLE
Fix use of sanitizeHTML

### LINKED ISSUE #7230: The store notices component doesn't render the text
## Describe the bug
The store notices component doesn't render the text

## To reproduce

1. Check out branch [1287-gh-Automattic/woopay ](1287-gh-Automattic/woopay)
1. Update the code:
    In src/Checkout/PaymentsHandler.php, comment or remove the if around the exception:
    ```
     // if ( empty( $customer_id ) ) {
              $session_data      = WooPaySession::UNSANITIZED_get_data();
              $blog_checkout_url = esc_url( add_query_arg( 'skip_platform_checkout', 'true', $session_data['store_data'] 
                                                     ['blog_checkout_url'] ) );
              /* translators: %1$s opening anchor tag with url, %2$s closing anchor tag */
              $error_message = __( 'we were unable to process your payment. Please %1$s go back to the merchant store %2$s and 
                                              log into WooPay again.', 'woopay' );
              $open_tag      = '<a href="' . $blog_checkout_url . '">';
              $close_tag     = '</a>';
              throw new InvalidSessionException(
		        sprintf( $error_message, $open_tag, $close_tag ),
              );
   // }
    ```
1. Get a valid checkout_session by checking out with a valid email and filling in the OTP code. 
1. Place an order and see the blank error message

## Expected behavior
To be able to see the error message

## Screenshots
// Before
Screen Shot 2022-09-26 at 12 17 39 PM

// After
Screen Shot 2022-09-26 at 12 34 36 PM

### WordPress (please complete the following information):

-   WooCommerce version: 6.9.3
-   WooCommerce Blocks version: 8.6.0-dev
-   WooCommerce payments version: 4.7.2

### PR DESCRIPTION
**Pull request by hsingyuc**
This PR fixes the `sanitizeHTML` return value data type and imports to the `store-notices-container` so we don't have two same methods in one repo.

Fixes #7230 

### Screenshots

| Before | After |
| ------ | ----- |
|Screen Shot 2022-09-26 at 12 17 39 PM|Screen Shot 2022-09-26 at 12 34 36 PM|

### Testing
1. Check out branch 1287-gh-Automattic/woopay
1. Update the code:
In src/Checkout/PaymentsHandler.php, comment or remove the if around the exception:
```
 // if ( empty( $customer_id ) ) {
          $session_data      = WooPaySession::UNSANITIZED_get_data();
          $blog_checkout_url = esc_url( add_query_arg( 'skip_platform_checkout', 'true', $session_data['store_data'] 
                                                 ['blog_checkout_url'] ) );
          /* translators: %1$s opening anchor tag with url, %2$s closing anchor tag */
          $error_message = __( 'we were unable to process your payment. Please %1$s go back to the merchant store %2$s and 
                                          log into WooPay again.', 'woopay' );
          $open_tag      = '<a href="' . $blog_checkout_url . '">';
          $close_tag     = '</a>';
          throw new InvalidSessionException(
	        sprintf( $error_message, $open_tag, $close_tag ),
          );
// }
```
1. Get a valid checkout_session by checking out with a valid email and filling in the OTP code.
1. Place an order and see the error message

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Review by brianyu28 — COMMENTED** [review]
Thanks @hsingyuc! This looks good to me, though two thoughts:

- Since I'm less familiar with the `woocommerce-blocks`, I'd like to get a second reviewer on this for another pair of eyes. Maybe @nielslange, since I see you worked on related code recently?
- There's a lot of changes to `package-lock.json` here for what seems like a fairly small dev dependency change. I wonder if maybe yours was generated with a different version of npm than this repo normally uses?

**Comment by hsingyuc** [comment]
Thank you for the feedbacks, @brianyu28!
>Since I'm less familiar with the woocommerce-blocks, I'd like to get a second reviewer on this for another pair of eyes. Maybe @nielslange, since I see you worked on related code recently?

Good idea.

>There's a lot of changes to package-lock.json here for what seems like a fairly small dev dependency change. I wonder if maybe yours was generated with a different version of npm than this repo normally uses?

I `nvm use` before `npm i` and I checked the npm version is the same as `.nvmrc.` I just tried again and no changes.

**Comment by hsingyuc** [comment]
@brianyu28  I tried to remove `package-lock` and `npm i` a few more times, and the third time got some more changes.  But still doesn't pass this test `JavaScript, CSS and Markdown Linting / Lint JavaScript (pull_request)`

File: assets/js/base/context/providers/store-notices/components/store-notices-container.js [hunk 1]
```diff
@@ -74,11 +66,7 @@ export const StoreNoticesContainer = ( {
 						}
 					} }
 				>
-					<span
-						dangerouslySetInnerHTML={ sanitizeHTML(
-							props.content
-						) }
-					/>
+					{ sanitizeHTML( props.content ) }
```
Comment (nielslange) [inline assets/js/base/context/providers/store-notices/components/store-notices-container.js:72]: Shouldn't `{ sanitizeHTML( props.content ) }` remain `<span dangerouslySetInnerHTML={ { __html: sanitizeHTML( props.content ) } } />` to ensure that HTML elements are rendered as expected? Wouldn't changing that part to `{ sanitizeHTML( props.content ) }` show the plain HTML code on the site?

I'm asking because when I replace
```js
{ ( showItems || collapsible ) && (
  <div
    className="wc-block-components-shipping-rates-control__package-title"
    dangerouslySetInnerHTML={ {
      __html: sanitizeHTML( packageData.name ),
    } }
  />
) }
```
with
```
{
  ( showItems || collapsible ) && sanitizeHTML( packageData.name )
}
```
in https://github.com/woocommerce/woocommerce-blocks/blob/2f8e4f79b01ef706723164cc1e72ddabad04f6d6/assets/js/base/components/cart-checkout/shipping-rates-control-package/index.tsx#L73-L80, I see the following result:

Screenshot 2022-09-28 at 11 43 00

File: assets/js/utils/sanitize-html.ts [hunk 2]
```diff
@@ -1,27 +1,20 @@
...
-	return {
-		__html: DOMPurify.sanitize( html, {
-			ALLOWED_TAGS: tagsValue,
-			ALLOWED_ATTR: attrValue,
-		} ),
-	};
+	return sanitize( html, {
+		ALLOWED_TAGS: tagsValue,
+		ALLOWED_ATTR: attrValue,
+	} );
```
Comment (nielslange) [inline assets/js/utils/sanitize-html.ts:19]: Based on your feedback in https://github.com/woocommerce/woocommerce-blocks/pull/7147#discussion_r980380183, I was wondering if we shouldn't remove the object keys. The final function could look something like this:

```ts
/**
 * External dependencies
 */
import { sanitize } from 'dompurify';

const DEFAULT_TAGS = [ 'a', 'b', 'em', 'i', 'strong', 'p', 'br' ];
const DEFAULT_ATTR = [ 'target', 'href', 'rel', 'name', 'download' ];

export const sanitizeHTML = (
	html: string,
	config?: { tags?: typeof DEFAULT_TAGS; attr?: typeof DEFAULT_ATTR }
) => {
	const ALLOWED_TAGS = config?.tags || DEFAULT_TAGS;
	const ALLOWED_ATTR = config?.attr || DEFAULT_ATTR;

	return sanitize( html, { ALLOWED_TAGS, ALLOWED_ATTR } );
};
```

**Review by nielslange — COMMENTED** [review]
Thanks for working on this, @hsingyuc. I left one question, regarding removing `dangerouslySetInnerHTML()`, and one suggestions, regarding removing the object keys, based on your comment in https://github.com/woocommerce/woocommerce-blocks/pull/7147#discussion_r980380183.

**Comment by nielslange** [comment]
@hsingyuc I just want to let you know that @alexflorisca is currently merging #6612. To avoid inconsistencies, please do not merge this PR until @alexflorisca is done with the other PR and is giving green light. Thanks in advance! 🙌

**Comment by alexflorisca** [comment]
You can merge now, but you may have some conflicts. If you need a hand fixing them just let me know.

File: assets/js/base/context/providers/store-notices/components/store-notices-container.js (hunk 1 above)
Comment (hsingyuc) [reply assets/js/base/context/providers/store-notices/components/store-notices-container.js:72]: @nielslange  That's a good question.  So we use `sanitizeHTML( props.content )` here because `Notice` has changed the behavior and magically deals with the `dangerouslySetInnerHTML` for us.  If we keep using the below code, we will actually get an empty div tag which causes the store notices component doesn't render the text.
```
<span
	dangerouslySetInnerHTML={ sanitizeHTML( props.content ) }
/>
```

Comment (hsingyuc) [reply assets/js/base/context/providers/store-notices/components/store-notices-container.js:72]: For your case, you are not using `Notice`, so you still need the `dangerouslySetInnerHTML` and pass an object with a `__html` key to translate your sanitized HTML.

File: assets/js/utils/sanitize-html.ts (hunk 2 above)
Comment (hsingyuc) [reply assets/js/utils/sanitize-html.ts:19]: Method A & B work the same way, so either is ok.  I prefer method B because it's cleaner.
```
// Method A:
return sanitize( html, {
	ALLOWED_TAGS: tagsValue,
	ALLOWED_ATTR: attrValue,
} );
```

```
// Method B:
return sanitize( html, { ALLOWED_TAGS, ALLOWED_ATTR } );
```

File: assets/js/base/context/providers/store-notices/components/store-notices-container.js (hunk 1 above)
Comment (nielslange) [reply assets/js/base/context/providers/store-notices/components/store-notices-container.js:72]: Thanks for clarifying this, @hsingyuc.

File: assets/js/utils/sanitize-html.ts (hunk 2 above)
Comment (nielslange) [reply assets/js/utils/sanitize-html.ts:19]: > I prefer method B because it's cleaner.

I agree. Method B indeed looks much cleaner.

**Review by opr — APPROVED** [review]
I ran the linting jobs locally and they are both fine. E2E failures seem unrelated so I will approve and merge. Thanks @hsingyuc for working on this! 🙌🏼

**Comment by hsingyuc** [comment]
@opr  Thank you!
