### PR TITLE
Restore block transform for filter blocks

### LINKED ISSUE #7390: Filter blocks: Legacy widgets transform function broken after conversion to InnerBlocks
## Describe the bug

@dinhtungdu first noticed the issue, here: https://github.com/woocommerce/woocommerce-blocks/pull/7362#discussion_r992929138

The transform function no longer works for filters blocks after the following commits:
- https://github.com/woocommerce/woocommerce-blocks/commit/4b2b6fb99f6a7aa84e11759b89affb935f3a923d (Filter by Price, Filter by Attributes etc.)
- https://github.com/woocommerce/woocommerce-blocks/commit/e2c1d59dffe817146258a8d9bcd21f7986d5aee3 (Filter by Ratings)

## To reproduce

1. Check out the pre-innerblocks commit: 1564de216dadf8dd7d7ef7eba70dd10ba1e0fc91
2. Verify that the transform works
3. Check out the innerblocks commit: 4b2b6fb99f6a7aa84e11759b89affb935f3a923d
4. Verify that the transform is no longer working

## Expected behavior

I'd expect the transform function to work correctly for InnerBlocks blocks.

## Screenshots

**Transform missing:**
Widgets_‹_ratings_—_WordPress

**Transform working correctly:**
Widgets_‹_ratings_—_WordPress

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #7390

This PR restores the block transform functionality for filter blocks that allow filter widgets can be transformed into new filter blocks. This has some limitations:

- Gutenberg only supports declaring transform at the block level, not variation, so in the transform menu, the base block `Filter Wrapper` is shown for all filter blocks.

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

image

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

0. Install WooCommerce 6.5.1 from https://wordpress.org/plugins/woocommerce/advanced/.
1. Deactivate WooCommerce Blocks, activate Storefront.
2. Go to Appearance > Widgets and add filter widgets to a widget area.
3. Update WooCommerce to latest version and activate WooCommerce Blocks.
4. Go to Appearance > Widgets, and open the transform menu for a filter widget. See Filter Block as an option.
5. Hover on the Filter Block, see the preview of corresponding filter blocks.
6. Click the Filter Block, see the widget converted to filter blocks.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix: restore transform functionality for filter widgets.

### CODE REVIEW

File: assets/js/blocks/filter-wrapper/index.tsx [hunk 1]
```diff
@@ -20,6 +21,97 @@ import { isFeaturePluginBuild } from '@woocommerce/block-settings';
...
+		default:
+			return {};
+	}
+};
+
+const isFilterWidget = ( widgetId: string ) =>
+	filterBlocksWidgets
+		.map( ( item ) => item.widgetId )
+		.filter( Boolean )
+		.includes( widgetId );
```
Comment (Aljullu) [inline assets/js/blocks/filter-wrapper/index.tsx]: I think this can be simplified to:
```suggestion
	filterBlocksWidgets
		.some( ( item ) => item.widgetId === widgetId );
```

**Review by Aljullu — APPROVED** [review]
This is working like a charm, thanks for investigating and fixing this, @dinhtungdu! :clap: 

Heads-up that I updated the testing instructions because I needed to install WC core 6.5.1 in order to be able to add filter widgets.

**Comment by dinhtungdu** [comment]
In 71664d9, we rename `Filter Wrapper` to `Filter Block` to avoid making users confused. The string only appears in the transform menu of the filter widgets.

image

**Review by Aljullu — APPROVED** [review]
I didn't test it again, but code changes look good to me, so re-approving. Thanks @dinhtungdu!

**Comment by dinhtungdu** [comment]
Merging with failed e2e tests that relate to the Checkout block.
