### PR TITLE
Fix total shipping display info when no shipping method is available

### LINKED ISSUE #8206: Local pickup: When there is no shipping method, local pickup won't remove the pickup cost.
## Describe the bug

When there is no shipping method, local pickup won't remove the pickup cost from the Cart totals.

## To reproduce

1. Enable local pickup with pickup price
2. Remove the shipping methods from the WC settings
3. Go to the Checkout block and select the local pickup option
4. Notice the local pickup price from the totals won't get removed when you select the shipping option

## Expected behavior

When selecting the shipping option, it should remove the pickup cost from the Cart totals.

## Screen Recording

https://user-images.githubusercontent.com/11503784/212719022-cb59a0cc-9343-4c91-9ae5-c57d8517a0a7.mov

## Additional context

p1673880972090869-slack-C02UBB1EPEF

### PR DESCRIPTION
**Pull request by tarhi-saad**
When there is no shipping method, local pickup won't remove the pickup cost from the Cart totals.

The shipping rates don't get updated when there are no shipping options available. So, it will always return the list of the available pickup locations when selecting the "Shipping" option. A solution for this issue will be to check if all available shipping methods are local pickup only. Then when selecting "Shipping", we can determine that there are no shipping options available!

A conflict did arise after merging #8141. With this PR, we display a link to add the shipping address in the shipping calculator on the cart page when the shipping address is incomplete. We had to change the logic implementation for this one to fix the conflict!

Fixes #8206

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
|    image    |     image  |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

The order of the test cases is important!

### Case 1 (Local pickup enabled and no shipping options available)

1. Enable local pickup with pickup price. For that, go to `WooCommerce -> Settings -> Shipping -> Local pickup`, under `General` Check `Enable local pickup` and `Add a price for customers who choose local pickup`, and save. Then add a price under the `Cost` input.
2. Remove the shipping methods from the WC settings (WooCommerce -> Settings -> Shipping -> Shipping zones)
3. Go to the store and add an item to the cart
4. Go to the Checkout block and select the `Local Pickup` option under the `Shipping Method` section. Ensure the correct shipping information is displayed in the `Order Summary` Block  (i.e., The correct price and correct local pickup option)
5. Select `Shipping` under the `Shipping Method` section. Ensure `No shipping options available` is displayed under `shipping` in the `Order Summary` Block

### Case 2 (Local pickup enabled and shipping option(s) available)

1. Add a shipping method in `WooCommerce -> Settings -> Shipping -> Shipping zones`. Ensure the shopper's address is within the shipping zone created.
2. Go to the Checkout block and select the `Local Pickup` option under the `Shipping Method` section. Ensure the correct shipping information is displayed in the `Order Summary` Block  (i.e., The correct price and correct local pickup option)
3. Select `Shipping` under the `Shipping Method` section. Ensure the correct shipping information is displayed in the `Order Summary` Block (i.e., The correct price and correct shipping option)

### Case 3 (Local pickup disabled and no default shipping rates)

1. Disable local pickup. For that, go to `WooCommerce -> Settings -> Shipping -> Local pickup`, under `General` uncheck `Enable local pickup` and save.
2. Go to `WooCommerce -> Settings -> General`. Select `No location by default` under `Default customer location`
3. Remove any default(fallback) shipping rates in `WooCommerce -> Settings -> Shipping -> Shipping zones -> Locations not covered by your other zones`
4. Open your site in a private session(incognito mode).
5. Add an item to the cart
6. Go to the cart page, and confirm the "Add an address for shipping rates" link is present in the shipping calculator.
7. Click on the link, and confirm it is working as expected.
8. Open your site in a regular session where you're already logged in and have placed an order before.
9. Add an item to the Cart
10. Go to the cart page, confirm the shipping address, and "change address" link present in the shipping calculator.
11. Click on the link, and confirm it is working as expected.

### Case 4 (With default shipping rates)

1. Add a default(fallback) shipping rate in `WooCommerce -> Settings -> Shipping -> Shipping zones -> Locations not covered by your other zones`
2. Follow steps 4 and 5 from the previous case (i.e., `Case 3`)
3. Go to the cart page, and confirm the shipping calculator is hidden and default shipping rates are visible
4. Follow steps 8 to 11 from the previous case (i.e., `Case 3`)

### Case 5 (Error Notice)

1. Follow steps 3 to 6 from `Case 3`
2. Click on the link, and change the address to a location where shipping rates are unavailable.
3. Confirm that `There are no shipping options available. Please check your shipping address.` error is visible in the text form.
4. Proceed to the Checkout block page, and confirm the `There are no shipping options available. Please check your shipping address` error is visible in the text form under the `Shipping options` section.

Note: Notice will appear for a few seconds until we receive the server's response, even with the valid shipping address, when we change the shipping method. 

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix total shipping display info when no shipping method is available

### CODE REVIEW

**Review by nielslange — APPROVED** [review]
Thanks for working on this, @tarhi-saad! I've successfully tested the change. While reviewing, I saw that the buyer's notice `No shipping options available` could be improved:

Screenshot 2023-03-28 at 12 54 42

I then recalled that @mikejolley is currently working on [Feature Branch: Updated Buyer Notices](https://github.com/woocommerce/woocommerce-blocks/pull/8659). Once that PR has been merged, I believe we should improve the  `No shipping options available` message in the sidebar. But that's another story. For now, let's ⛴ this PR.

**Comment by tarhi-saad** [comment]
Hello @tarunvijwani, @nielslange! We finally fixed a conflict me and @tarunvijwani between this PR and #8141. I added additional testing instructions to ensure we didn't introduce regression! Feel free to merge this PR if you think everything works well!

**Comment by nielslange** [comment]
Case 1 / Step 5 states:

> Select `Shipping` under the `Shipping Method` section. Ensure `No shipping options available` is displayed under `shipping` in the `Order Summary` Block

Despite not having any shipping zones defined, I still see `Local Pickup` under `Shipping` in the `Order Summary` Block. 

Screen Shot 2023-04-04 at 11 21 09

> The order of the test cases is important!

Given that the first test case failed, I've stopped the review, as other tests might also fail, given that _"The order of the test cases is important"_.

**Review by nielslange — COMMENTED** [review]
See https://github.com/woocommerce/woocommerce-blocks/pull/8819#issuecomment-1495327006

File: assets/js/base/components/cart-checkout/totals/shipping/utils.ts [hunk 1]
```diff
@@ -31,3 +31,31 @@ export const getTotalShippingValue = ( values: {
...
+		return true;
+	}
+
+	// We check for the availability of shipping options if the shopper selected "Shipping"
+	if ( ! prefersCollection ) {
+		return shippingRates.some(
+			( shippingRatePackage ) =>
+				! shippingRatePackage.shipping_rates.some(
+					( shippingRate ) =>
+						shippingRate.method_id !== 'pickup_location'
```
Comment (opr) [inline assets/js/base/components/cart-checkout/totals/shipping/utils.ts]: This will not work for third-party collectible rates, we need to check if the method ID is in `collectableRateIds` from the server.

**Review by opr — APPROVED** [review]
I was unable to replicate the bug Niels shared.

I have Local Pickup enabled, I have no shipping zones or fallback rates configured. On the Checkout block I never see the local pickup rates unless I specifically select the local pickup button.

I found a bug in the code where the `pickup_location` string was used, however third-party methods supporting `local-pickup` will not be considered in this, I pushed an update to fix this.

We should also add unit tests for that method.

I will merge this.

**Comment by opr** [comment]
Bumping to 10.1.0 after p1681129771372729/1681128388.500929-slack-C02UBB1EPEF

**Review by nielslange — APPROVED** [review]
I reviewed the PR again and now all testing steps worked as expected. 

@opr I see that both you and @tarhi-saad applied various changes yesterday. Given that @tarhi-saad will be AFK until April 28, shall we merge this PR, if all testing steps are passing for you as well?

**Review by tarunvijwani — CHANGES_REQUESTED** [review]
I'm little hesitant in approving the PR as this still have shipping total error. 
If I select the shipping and don't enter the valid address, it calculates the local pickup cost but doesn't display it in the order summary. 

| Shipping | Local pickup |
|---|---|
|image| image|

**Comment by opr** [comment]
The issue here is that if "Shipping" is selected while an address is not entered, there are no "shipping" rates, so it falls back to the local pickup option, which in this case is $4. This is used to calculate taxes, too.

To fix this, we would need to get the taxes and the current shipping price and manipulate the totals in-place to show the correct value. I don't think there's a way we can correct this on the server, because as far as the server is concerned, there is no difference between a local pickup rate and a shippable rate. We would then need to remove the correct amounts from each tax line, if it's being displayed in an itemized list. This is diffficult as we'd need to know what percent each tax line applies, and subtract the shipping tax from each one.

I think it will be _very_ hard to get the correct totals to display when "shipping" is selected but before the address, and with little benefit.

I propose we add a notice saying totals will be calculated when an address is entered.
image

**Comment by thealexandrelara** [comment]
WooCommerce Blocks 10.1.0 will be released soon. I'm bumping this PR to the next milestone

**Comment by opr** [comment]
@tarunvijwani please could you re-review this? @nielslange please also feel free to give it another look, it incorporates the changes we made in #9171

**Review by nielslange — APPROVED** [review]
I've successfully tested the PR again, so I pre-approved the PR, but I struggled a bit with the testing instructions, see below:

I wonder if we should refine the testing instructions for better efficiency. The complexity arising from the statement, "The order of the test cases is important!" has made testing more challenging. Each step requires recalling the previous ones. For instance, Steps 2 and 4 of Case 4, as well as Step 1 of Case 5, direct users to revisit steps from prior cases. I found this constant back-and-forth mentally exhausting, reducing my ability to effectively conduct the review. In my view, it would be more efficient if test cases were designed to be independent of one another, allowing for streamlined and focused testing. What are your thought on that, @opr?

**Review by tarunvijwani — COMMENTED** [review]
@opr Thank you for adding the notice to the checkout summary. It helps a lot to understand that shipping will be recalculated and avoid confusion. However, I noticed two bugs now:

1. My entered email address get removed automatically when I start entering the shipping address.  
2. Even after adding the correct address, if I select local pickup and select back shipping. It displays the notice, which is not valid anymore. 

Here is the screen recording for your reference: 


https://user-images.githubusercontent.com/11503784/235434644-d8f3aa4c-341d-4572-a9f1-2a7484dd065f.mov

**Comment by opr** [comment]
@tarunvijwani thanks, are you able to reproduce the email issue on trunk? I don't see how that could be caused by this PR.

How long did you wait after switching method, it looks like the `select-shipping-rate` request to the server did not complete. This is on the basis that the selected method is still "Pickup" at the end of your screenshare.

image

**Comment by tarunvijwani** [comment]
>thanks, are you able to reproduce the email issue on trunk? I don't see how that could be caused by this PR

No, I am unable to reproduce it now. It could be a glitch as I'm not able to reproduce it on this branch as well.

>How long did you wait after switching method, it looks like the select-shipping-rate request to the server did not complete. This is on the basis that the selected method is still "Pickup" at the end of your screenshare.

@opr I tried again, I'm getting the same results even if I wait for a couple of minutes.

**Comment by opr** [comment]
Hi @tarunvijwani ok, great well I have not reproduced that and since you can't either I don't think it's anything too problematic, we can keep an eye on this and see if it happens again - the cause will be the server sending a new cart for some reason with the email address missing from the billing address. 

As for the second part, I am not able to reproduce that

https://www.loom.com/share/17fc62458d1b41bcb81686f8d0ab29cb

Would you be able to set up a JN site and have a completely fresh install using the testing zip file?

**Comment by tarunvijwani** [comment]
@opr Here is the JN site: https://mean-platypus.jurassic.ninja/checkout/
I can reproduce both issues on it. 
Steps to reproduce:
1. Add a product to the cart. 
2. Go to the checkout page. 
3. Select the shipping option. 
4. Confirm the notice appears in the Checkout summary.  
5. Enter your email address. 
6. Start entering the address. 
7. Notice email address entered is cleared, and a validation error appears. 
8. After entering the address, enter the email address. 
9. Confirm the notice in the checkout summary block no longer appears. 
10. Select local pickup. 
11. Select shipping again. 
12. Notice appears again in the checkout summary block even with the valid address.

**Comment by tarunvijwani** [comment]
Created a ticket for email address issue: https://github.com/woocommerce/woocommerce-blocks/issues/9321

**Comment by kmanijak** [comment]
PR bumped to the next milestone (10.3.0)

**Review by tarunvijwani — APPROVED** [review]
Thank you for fixing the errors. I have added a note in the PR description that notice will appear for a few seconds until we receive the server's response, even with the valid shipping address, when we change the shipping method.

**Comment by mikejolley** [comment]
Bumping to 10.4.0.

**Comment by ralucaStan** [comment]
@tarhi-saad what is preventing this PR from getting merged?

**Comment by opr** [comment]
> @tarhi-saad what is preventing this PR from getting merged?

Since I worked on this a lot during Saad's AFK, I asked if he could do one final review/test before merging.

**Comment by tarhi-saad** [comment]
Everything works as expected!

> There were two E2E tests that failed in connection to the `Filter by Rating Block`. However, since it has no relation to this block, I will proceed to merge this PR.

It was a flacky test! After running it again it was successful.
