### PR TITLE
Product Gallery: CSS styling tightening up

### LINKED ISSUE #10838: Product Gallery: the block overflows on other column
## Describe the bug

In the specific condition, the block overflows on the other column (see the screenshots).
## To reproduce

1. Open the SIte Editor.
2. Edit the Single Product.
3. Replace the Product Image Gallery with the Product Gallery.
4. Move the thumbnails on the right.
5. See the error.

## Expected behavior

The Product Gallery should not overflow on the other column. 
## Screenshots

image
image

### PR DESCRIPTION
**Pull request by danieldudzic**
## What

The goal of this PR is to ensure the `Product Gallery` block displays correctly in all setting configurations and is not dependent on the neighboring blocks.

Fixes #10838 https://github.com/woocommerce/woocommerce-blocks/issues/10750

## Why

This PR attempts to rectify styling shortcomings that arose from various `Product Gallery` settings being added and adding complexity.

## Testing Instructions

1. Using a block theme, go to `Appearance > Editor`.
2. Go to `Templates > Single Product`.
3. Make sure you are using the blockified template.
4. Add the **Product Gallery** block (replacing the legacy `Product Image Gallery` block).
5. _After completing the below steps, go back to step 4. and insert the `Product Gallery` block just above `Product Details` tabs, so that it doesn't have any neighboring columns._
6. Verify that the `Product Gallery` displays correctly (doesn't overflow etc.) in all possible configurations of the `Thumbnails` Positon setting and the `Next/Prev Buttons` appearance setting, both in the editor and frontend.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|Single_Product_‹_Template_‹_Editor_‹_newproductgallery_—_WordPress-2|Single_Product_‹_Template_‹_Editor_‹_newproductgallery_—_WordPress|

| Before | After |
| ------ | ----- |
|V-Neck_T-Shirt_–_newproductgallery-2|V-Neck_T-Shirt_–_newproductgallery|

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Product Gallery: Fix display issues in the editor and the page.

### CODE REVIEW

**Comment by danieldudzic** [comment]
## Known conflict/limitation

There's one compromise in the below solution for the `outside` `Next/Previous Button` mode:

Due to the fact that the `Sale Badge` supports `margin` Global Styles, and _doesn't_ have an additional wrapper in the editor (such wrapper exists on the frontend and therefore the issue doesn't exist) there's a margin clash:

Single_Product_‹_Template_‹_Editor_‹_newproductgallery_—_WordPress
&nbsp;<br />
I don't see a simple fix.

&nbsp;<br />
The potential 2 fixes I see (without removing the current margin-based styling fix) are:
- Add a wrapper to the Sale Badge in the editor
- Remove the margin support from the Sale Bade (when used in the Product Gallery) - not sure if this is even possible.

**Comment by gigitux** [comment]
Hey @danieldudzic, thanks for your great work on this PR! Now, the Large Image and arrows never overflow! However, I noticed two things that I think that we should address:
- We are targeting `wp-block` classes. We should create a dedicated `wc` classes.
- In the style/editor.scss of a child block, we are using the class `.wp-block-woocommerce-product-gallery[data-next-previous-buttons-position="outsideTheImage"]`, which refers to the main product-gallery block. My primary concern is the complexity this approach introduces, and I believe we could enhance clarity by using SCSS variables for some of the calculations.

As we discussed earlier, we agreed to consolidate all styles affecting multiple child blocks into a dedicated `style.scss` file located in the main `/product-gallery folder`.  Additionally, instead of relying on `.wp-block-woocommerce-product-gallery[data-next-previous-buttons-position="outsideTheImage"]`, we will implement a custom class, `wc-block-product-gallery--has-next-previous-buttons-${position}`, to be applied to the main div of the Product Gallery block.

The new `style.scss` and the logic to add the custom class has been added with [91c67ce](https://github.com/woocommerce/woocommerce-blocks/pull/10867/commits/91c67cec4a22b459883abdd7be83b9d8fa605906).

**Comment by tarhi-saad** [comment]
@danieldudzic, I bumped this issue to the next release!

File: assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/edit.tsx [hunk 1]
```diff
@@ -35,8 +41,33 @@ export const Edit = (): JSX.Element => {
 			templateInsertUpdatesSelection: true,
 		}
 	);
+
+	const previousNextImage = useMemo( () => {
```
Comment (tjcafferkey) [inline assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/edit.tsx:48]: is `useMemo` necessary here? This doesn't appear to be computationally heavy and memoization always comes with a cost which only makes sense when the benefit of using it outweighs the cost.

**Comment by danieldudzic** [comment]
> We are targeting `wp-block` classes. We should create a dedicated `wc` classes.

Would you mind elaborating on why we shouldn't be targeting those? It seems that a lot of block styles in our repo target the `.wp-block-woocommerce-*` classes.

File: assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/edit.tsx (hunk 1 above)
Comment (danieldudzic) [reply assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/edit.tsx:48]: Good point. I have followed the original code from: https://github.com/woocommerce/woocommerce-blocks/blob/b2390ece0c1606a25b84997cc0cf8ac7780c8959/assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image-next-previous/edit.tsx#L46

@gigitux what do you think?

Comment (gigitux) [reply assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/edit.tsx:48]: I don't have a strong opinion, but if we can avoid doing this check at each re-render, why not?

I suggest to read from React documentation: https://react.dev/reference/react/useMemo#:~:text=There%20is%20no,an%20entire%20component.

**Comment by gigitux** [comment]
> > We are targeting `wp-block` classes. We should create a dedicated `wc` classes.
> 
> Would you mind elaborating on why we shouldn't be targeting those? It seems that a lot of block styles in our repo target the `.wp-block-woocommerce-*` classes.

You're right! The wp-block-woocommerce is consumed by WordPress for global styles. I think that every CSS that we write should target a wc-block class: this increases the separation of responsibility and allows us to debug the CSS better.

File: assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/edit.tsx (hunk 1 above)
Comment (tjcafferkey) [reply assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/edit.tsx:48]: Just an FYI more than anything [here's another reference](https://kentcdodds.com/blog/usememo-and-usecallback#whats-the-point)

>Performance optimizations are not free. They ALWAYS come with a cost but do NOT always come with a benefit to offset that cost. Therefore, optimize responsibly.

Comment (gigitux) [reply assets/js/blocks/product-gallery/inner-blocks/product-gallery-large-image/edit.tsx:48]: > Just an FYI more than anything [here's another reference](https://kentcdodds.com/blog/usememo-and-usecallback#whats-the-point)

TIL

Since we invoke `setAttributes` for each settings change, the block could be re-render many times. As I said, I don't have a strong preference. To have a "real" answer we should benchmark and see which solution is better, but in this case, it isn't worth it. Since it is a micro-optimization, it is okay for me both approaches.

**Comment by danieldudzic** [comment]
> > > We are targeting `wp-block` classes. We should create a dedicated `wc` classes.
> > 
> > 
> > Would you mind elaborating on why we shouldn't be targeting those? It seems that a lot of block styles in our repo target the `.wp-block-woocommerce-*` classes.
> 
> You're right! The wp-block-woocommerce is consumed by WordPress for global styles. I think that every CSS that we write should target a wc-block class: this increases the separation of responsibility and allows us to debug the CSS better.

Thanks for explaining. This does make sense.

**Comment by danieldudzic** [comment]
@gigitux We should try to get this merged ASAP, as I can see already that getting this up to date with `trunk` will be a conflict nightmare.

File: src/BlockTypes/ProductGalleryLargeImageNextPrevious.php [hunk 2]
```diff
@@ -132,14 +141,14 @@ protected function render( $attributes, $content, $block ) {
 		}
 
 		$context     = $block->context;
-		$prev_button = $this->get_icons( $block->context )['prev_button'];
-		$next_button = $this->get_icons( $block->context )['next_button'];
+		$prev_button = isset( $this->get_icons( $block->context )['prev_button'] ) ? $this->get_icons( $block->context )['prev_button'] : '';
+		$next_button = isset( $this->get_icons( $block->context )['next_button'] ) ? $this->get_icons( $block->context )['next_button'] : '';
 
 		$alignment_class = isset( $attributes['layout']['verticalAlignment'] ) ? 'is-vertically-aligned-' . $attributes['layout']['verticalAlignment'] : '';
```
Comment (gigitux) [inline src/BlockTypes/ProductGalleryLargeImageNextPrevious.php]: Let's escape this with `esc_attr`

File: src/BlockTypes/ProductGalleryLargeImageNextPrevious.php [hunk 3]
```diff
@@ -132,14 +141,14 @@ protected function render( $attributes, $content, $block ) {
...
 		$position_class  = 'wc-block-product-gallery-large-image-next-previous--' . $this->get_icons( $context )['class'];
```
Comment (gigitux) [inline src/BlockTypes/ProductGalleryLargeImageNextPrevious.php:148]: Same

File: src/BlockTypes/ProductGallery.php [hunk 4]
```diff
@@ -30,16 +23,26 @@ protected function get_block_type_style() {
...
+		$classname_single_image = '';
+
+		if ( count( $product_gallery_images ) < 2 ) {
+			// The gallery consists of a single image.
+			$classname_single_image = 'is-single-product-gallery-image';
+		}
+
 		$classname          = $attributes['className'] ?? '';
-		$wrapper_attributes = get_block_wrapper_attributes( array( 'class' => trim( sprintf( 'woocommerce %1$s', $classname ) ) ) );
+		$wrapper_attributes = get_block_wrapper_attributes( array( 'class' => trim( sprintf( 'wc-block-product-gallery %1$s %2$s', $classname, $classname_single_image ) ) ) );
```
Comment (gigitux) [inline src/BlockTypes/ProductGallery.php:78]: image

`wp-block-woocommerce-product-gallery` and `wc-block-product-gallery` are duplicated. I think that we should remove them on this div.

File: src/BlockTypes/ProductGalleryPager.php [hunk 5]
```diff
@@ -78,11 +87,11 @@ private function render_pager( $pager_display_mode ) {
 	 */
 	private function render_digits_pager() {
 		return sprintf(
-			'<ul class="wp-block-woocommerce-product-gallery-pager__pager">
-				<li class="wp-block-woocommerce-product-gallery__pager-item is-active">1</li>
-				<li class="wp-block-woocommerce-product-gallery__pager-item">2</li>
-				<li class="wp-block-woocommerce-product-gallery__pager-item">3</li>
-				<li class="wp-block-woocommerce-product-gallery__pager-item">4</li>
+			'<ul class="wc-block-product-gallery-pager__pager">
```
Comment (gigitux) [inline src/BlockTypes/ProductGalleryPager.php:90]: I am adding a comment here, but it is for line 51. We should remove `woocommerce` class. What do you think?

image

File: src/BlockTypes/ProductGalleryThumbnails.php
Comment (gigitux) [inline src/BlockTypes/ProductGalleryThumbnails.php:1]: Missing the `wp-*` class:

image

**Review by gigitux — CHANGES_REQUESTED** [review]
Gorgeous work! I added some comments, but they should be easy to address! Just to clarify, it is crucial to add the `wp-*` class in the right place, because this class is used by the Global Styles.

Also, let's change the destination branch to trunk given that this PR includes the fix for https://github.com/woocommerce/woocommerce-blocks/issues/10750 as well.

**Review by gigitux — APPROVED** [review]
Code-wise LGTM. I noticed some regressions that we should address, but since this PR is huge and impacts other PRs, let's merge it and continue the iteration in the next PRs. Please open a dedicated issue for each point:

## Fix Zoom Animation
Currently, the zoom animation is broken: 
https://github-production-user-asset-6210df.s3.amazonaws.com/4463174/269297195-f7e43dd6-736b-4be4-a0c1-2923a5891f66.mp4
## Move classes to the main div and remove the additional wrapper

Currently, there is an unnecessary div that exists because we don't invoke [this function](https://github.com/woocommerce/woocommerce-blocks/pull/10867/files#diff-4c47871a152551ba3bb2008b02bab36f102467a5d3ac728cb14f7264a1d8f71dR51-R55) anymore, otherwise, the layout is broken. We should check why this happens and fix it:

image

## Thumbnail Position

I'm not sure about the thumbnail position:

image

## E2E test fail

I noticed that the `product-gallery-large-image-next-previous.block_theme.side_effects.spec.ts` test failed. We should skip it and fix it in a dedicated PR.

cc @thealexandrelara for awareness.
