### PR TITLE
Mini Cart: Remove deprecated print_inline_script()

### LINKED ISSUE #10004: `WP_Scripts::print_inline_script()` is deprecated since WP 6.3.0
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since https://github.com/WordPress/WordPress/commit/53e7cc3ddf12c2f8def3a02ddc8a7d826726e2be, the method `WP_Scripts::print_inline_script()` is deprecated.

>PHP Deprecated:  Function WP_Scripts::print_inline_script is <strong>deprecated</strong> since version 6.3.0! Use WP_Scripts::get_inline_script_data() or WP_Scripts::get_inline_script_tag() instead. in /wp-includes/functions.php on line 5450

It seems to be used in `Automattic\\WooCommerce\\Blocks\\BlockTypes\\MiniCart::append_script_and_deps_src()`.

### Expected behavior

The log file not being spammed.

### Actual behavior

The log file being spammed.

### Steps to reproduce

1. Update to the latest WP 6.3 alpha.
2. Load any page.
3. View `debug.log` file content.

### WordPress Environment

```
### WordPress Environment ###

WordPress address (URL): localhost
Site address (URL): localhost
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.3-alpha-56045
WP Multisite: –
WP Memory Limit: 256 Mo
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141 PHP/7.4.33 OpenSSL/1.0.2u mod_wsgi/3.5 Python/2.7.18
PHP Version: 7.4.33
PHP Post Max Size: 8 Mo
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.39
Max Upload Size: 8 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: wpll_
Taille totale de la base de données: 7.72MB
Taille de la base de données: 5.87MB
Taille de l’index: 1.85MB
wpll_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpll_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpll_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpll_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpll_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpll_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpll_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpll_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpll_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpll_actionscheduler_actions: Données : 0.05MB + Index : 0.13MB + Moteur InnoDB
wpll_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpll_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpll_actionscheduler_logs: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wpll_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpll_options: Données : 4.44MB + Index : 0.06MB + Moteur InnoDB
wpll_postmeta: Données : 0.14MB + Index : 0.13MB + Moteur InnoDB
wpll_posts: Données : 0.17MB + Index : 0.06MB + Moteur InnoDB
wpll_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_term_relationships: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wpll_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_usermeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpll_wc_admin_notes: Données : 0.08MB + Index : 0.00MB + Moteur InnoDB
wpll_wc_admin_note_actions: Données : 0.06MB + Index : 0.02MB + Moteur InnoDB
wpll_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpll_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_wc_mnm_child_items: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_wc_orders: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wpll_wc_orders_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_wc_order_addresses: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpll_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_wc_order_operational_data: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wpll_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wpll_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wpll_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpll_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpll_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wpll_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpll_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wpll_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wpll_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB

### Post Type Counts ###

attachment: 19
book: 4
et_body_layout: 1
et_template: 1
nav_menu_item: 7
page: 27
pll_temp_type: 1
polylang_mo: 3
post: 10
product: 6
product_variation: 18
revision: 67
shop_order: 10
shop_order_refund: 3
tribe_events: 5
wp_global_styles: 4
wp_navigation: 5
wp_template_part: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Polylang Pro: par WP SYNTEX – 3.4.3
Query Monitor: par John Blackbourn – 3.12.3
Classic Editor: par Contributeurs et contributrices WordPress – 1.6.3
Classic Widgets: par Contributeurs et contributrices WordPress – 0.3
Disable Bloat for WordPress & WooCommerce: par Disable Bloat – 3.2.8
Désactiver les emojis (compatible RGPD): par Ryan Hellyer – 1.7.4
Polylang for WooCommerce: par WP SYNTEX – 1.8
SF Admin Bar Tools: par Grégory Viguier – 4.0
Symlinked Plugin Branch: par Joseph Fusco – 1.1.0
WooCommerce: par Automattic – 7.8.0
WordPress Beta Tester: par WordPress Upgrade/Install Team – 3.4.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### WC Pages ###

Base de la boutique: woocommerce/woocommerce#9 - /
Panier: woocommerce/woocommerce#10 - /panier/
Commander: woocommerce/woocommerce#11 - /commander/
Mon compte: woocommerce/woocommerce#12 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Twenty Twenty-One
Version: 1.8
Author URL: https://fr.wordpress.org/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### WC Pages Translations ###

Base de la boutique: ✔
Panier: ✔
Commande: ❌ Traductions manquantes : Deutsch
English

Mon compte: ✔
Terms and conditions: ❌ Page non définie

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-28 09:20:31 +02:00
Options: ✔
Notes: 113
Onboarding: completed

### Action Scheduler ###

Terminé: 49
Oldest: 2023-06-02 10:16:23 +0200
Newest: 2023-06-26 17:15:28 +0200

Échoué: 11
Oldest: 2022-03-21 13:38:48 +0100
Newest: 2023-05-23 16:38:55 +0200

En attente: 1
Oldest: 2023-06-27 17:06:59 +0200
Newest: 2023-06-27 17:06:59 +0200


### Status report information ###

Generated at: 2023-06-27 13:52:44 +02:00
```

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by danieldudzic**
Mini Cart: Replace the deprecated print_inline_script() with supported get_inline_script_data().

Fixes #10004 

#### User Facing Testing

1. Using a plugin like WordPress Beta Tester enable the latest WordPress 6.3 beta.
2. Set `define( 'WP_DEBUG', true );` in your `wp-config.php`
3. Create a page and add the Mini Cart to it.
4. Visit the page with the Mini Cart and verify there are no visible errors or deprecated function warnings. 

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

**Comment by roykho** [comment]
I believe we need to do a version compare here right because users who are still on WP < 6.3 would get a fatal error since `get_inline_script_data()` doesn't yet exist.

**Comment by danieldudzic** [comment]
> I believe we need to do a version compare here right because users who are still on WP < 6.3 would get a fatal error since `get_inline_script_data()` doesn't yet exist.

Rookie mistake! Good catch, @roykho. Thank you 🙏

File: src/BlockTypes/MiniCart.php [hunk 1]
```diff
@@ -322,11 +322,19 @@ protected function append_script_and_deps_src( $script ) {
 
 		$site_url = site_url() ?? wp_guess_url();
 
+		if ( version_compare( get_bloginfo( 'version' ), '6.2.2', '>' ) ) {
+			$before = $wp_scripts->get_inline_script_data( $script->handle, 'before' );
+			$after  = $wp_scripts->get_inline_script_data( $script->handle, 'after' );
+		} else {
+			$before = $wp_scripts->print_inline_script( $script->handle, 'before', false );
+			$after  = $wp_scripts->print_inline_script( $script->handle, 'before', false );
```
Comment (roykho) [inline src/BlockTypes/MiniCart.php]: The `before` should be `after` here.

Comment (roykho) [reply src/BlockTypes/MiniCart.php]: Also I would flip the if/else and say `if ( version_compare( get_bloginfo( 'version' ), '6.3', '<' ) ) {` so it is abit cleaner. Lastly the variable names `$before/$after` is quite generic perhaps change to `$script_before/$script_after`. Just some suggestions.

File: src/BlockTypes/MiniCart.php [hunk 2]
```diff
@@ -322,11 +322,19 @@ protected function append_script_and_deps_src( $script ) {
 
 		$site_url = site_url() ?? wp_guess_url();
 
+		if ( version_compare( get_bloginfo( 'version' ), '6.2.2', '>' ) ) {
```
Comment (nefeline) [inline src/BlockTypes/MiniCart.php]: This could cause an error if a version such as 6.2.3 is released before 6.3. I coincidentally opened a PR to solve this issue, as I wasn't aware of your fix: https://github.com/woocommerce/woocommerce-blocks/pull/10190. That PR was closed out in favor of this one, but notice how its a slightly different implementation that guards us against this possibility.

Comment (danieldudzic) [reply src/BlockTypes/MiniCart.php]: Right. I see what you mean. Do you think I should update my PR?

I was trying searching through our repo (and WooCommerce) to find similar version checks, to follow the pattern. Seems usually it's a simple check that doesn't involve a regular expression.

Comment (Aljullu) [reply src/BlockTypes/MiniCart.php]: Would something like this work `version_compare( get_bloginfo( 'version' ), '6.3.0', '>=' )`? I think that would prevent any issues in case there is a 6.2.3 release and would keep the code simple.

Comment (danieldudzic) [reply src/BlockTypes/MiniCart.php]: I have found some issues checking against `6.3.0` when running beta versions of WordPress like `6.3-beta4-56226`.

File: src/BlockTypes/MiniCart.php (hunk 1 above)
Comment (danieldudzic) [reply src/BlockTypes/MiniCart.php]: Thanks for catching the incorrect `before`.

I have tried using `if ( version_compare( get_bloginfo( 'version' ), '6.3', '<' ) ) {` but that doesn't work correctly when testing with a beta version like `6.3-beta4-56226`.

Should I be taking that into consideration?

Comment (roykho) [reply src/BlockTypes/MiniCart.php]: Then you could try `if ( version_compare( get_bloginfo( 'version' ), '6.3', '>=' ) ) {`

Comment (roykho) [reply src/BlockTypes/MiniCart.php]: To be honest I don't think we need to account for that as I've not seen us ever doing that even in Woo core.

File: src/BlockTypes/MiniCart.php (hunk 2 above)
Comment (nefeline) [reply src/BlockTypes/MiniCart.php]: > Right. I see what you mean. Do you think I should update my PR?

Sure!

> I have found some issues checking against 6.3.0 when running beta versions of WordPress like 6.3-beta4-56226.

Right: that's the reason I've implemented like this on https://github.com/woocommerce/woocommerce-blocks/pull/10190 , it accounts for the beta version as well:

```php
$current_wp_version = get_bloginfo( 'version' );
if ( preg_match( '/^([0-9]+\.[0-9]+)/', $current_wp_version, $matches ) ) {
	$current_wp_version = (float) $matches[1];
}

if ( version_compare( $current_wp_version, '6.3', 'ge' ) ) {
	$before = $wp_scripts->get_inline_script_data( $script->handle, 'before' );
	$after  = $wp_scripts->get_inline_script_data( $script->handle );
} else {
	$before = $wp_scripts->print_inline_script( $script->handle, 'before', false );
	$after  = $wp_scripts->print_inline_script( $script->handle, 'after', false );
}
```

In general, we shouldn't need the ugly regex, but the `-beta` on specific versions made it a requirement 😬 : open to other ideas/suggestions if folks have any.

Comment (nefeline) [reply src/BlockTypes/MiniCart.php]: I just noticed we have two ongoing discussions on the same topic 😆 . @roykho [mentioned below](https://github.com/woocommerce/woocommerce-blocks/pull/10165#discussion_r1262574561) we may not need to cover the `-beta` use-cases: if we don't support this, the only downside is that it will be difficult for us to test the changes made on this PR before the 6.3 official release (as that's the moment when `-beta` will be dropped).

Comment (roykho) [reply src/BlockTypes/MiniCart.php]: So the reason why this is happening is because `version_compare` uses the semantic versioning. And WP is unorthodox and doesn't follow "semver". Because if they did, the version should look like `6.3.0-beta4-63233` and `version_compare( $version, '6.3', '<' )` would cover that. But it won't cover unconventional `6.3-beta...`

Comment (nefeline) [reply src/BlockTypes/MiniCart.php]: > So the reason why this is happening is because version_compare uses the semantic versioning. And WP is unorthodox and doesn't follow "semver". Because if they did, the version should look like 6.3.0-beta4-63233 and version_compare( $version, '6.3', '<' ) would cover that. But it won't cover unconventional 6.3-beta...

Yep, exactly!

File: src/BlockTypes/MiniCart.php (hunk 1 above)
Comment (danieldudzic) [reply src/BlockTypes/MiniCart.php]: `version_compare( '6.3-beta4-56226', '6.3', '>=' );` is still `false`

File: src/BlockTypes/MiniCart.php (hunk 2 above)
Comment (nefeline) [reply src/BlockTypes/MiniCart.php]: @danieldudzic if there's anything I can help you with the implementation here, just say the word! We will need the regex as demonstrated on https://github.com/woocommerce/woocommerce-blocks/pull/10165#discussion_r1262634275 otherwise it will be impossible to test this PR before the release of WordPress version 6.3 (as that's the only moment when the `-beta` will be dropped from the version number).

Comment (danieldudzic) [reply src/BlockTypes/MiniCart.php]: Thank you for the input @nefeline and @roykho. I will make the update :)

Comment (roykho) [reply src/BlockTypes/MiniCart.php]: @danieldudzic if you're gonna go ahead with the regex path, then I would suggest you make a shared utilities function that can be used throughout the project as I am sure this will happen again and we don't want to have this version compare regex littered all over the place.

Comment (danieldudzic) [reply src/BlockTypes/MiniCart.php]: Great idea. Let me add that now.

**Review by roykho — APPROVED** [review]
LGTM! Good job!
