### PR TITLE
Fix: Make filter block contextual - Editor

### LINKED ISSUE #10985: Make filter blocks contextual
With #10873 merged, we can make all filter blocks contextual in one place, Collection Filter wrapper block. So having one issue for each filter block is no longer needed.

Replaces #10570 #10573 #10572 #10569 

> Based on the two discussions seen https://github.com/woocommerce/woocommerce-blocks/discussions/10678 and https://github.com/woocommerce/woocommerce-blocks/discussions/10691 we've decided to have filters available only in the context of a product collection block. This makes it much easier for us to tackle this issue because now we have direct context access to the product collection block.

> In addition, each filter will also live inside a wrapper container called Collection Filters which the initial draft is created https://github.com/woocommerce/woocommerce-blocks/pull/10726

### PR DESCRIPTION
**Pull request by dinhtungdu**
## What

This PR adds an utility to be used for Edit components of filter blocks. The utility is the JS equivalent of the PHP one implemented in #10919.

Fixes #10985 

## Why

Unlike the #10919, we don't passing any data in this PR, we just provide an utility for filter blocks to consume. The Product Collection query is already available as context.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. On a new page, Add Product Collection block.
2. Add a Collection Filters block inside the Product Collection block.
3. Add Collection Price Filter block inside Collection Filters.
4. See the block shows correct price range.
5. Adjust the setting of Product Collection block to change the min or max price range of products.
6. See the Collection Price Filter block reacts and updates the price range accordingly.
7. Save the page and see changes applied on the front end.

* [x] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

Uploading Screen Recording 2023-10-12 at 13.01.25.mov…

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental
* [ ] N/A

## Checklist

Required:
* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

Conditional:
* [x] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

### CODE REVIEW

**Comment by dinhtungdu** [comment]
pinging @sunyatasattva @samueljseay for review.

**Comment by sunyatasattva** [comment]
Hey @dinhtungdu there is a lot on my plate right now. I'll get to this review tomorrow!

File: assets/js/blocks/collection-filters/utils.ts [hunk 1]
```diff
@@ -0,0 +1,56 @@
+/**
+ * External dependencies
+ */
+import { ProductCollectionQuery } from '@woocommerce/blocks/product-collection/types';
+
+function taxonomyMapper( taxonomy: string ) {
+	const map: Record< string, string > = {
```
Comment (sunyatasattva) [inline assets/js/blocks/collection-filters/utils.ts]: I don't think you need to define this type, right? TS will infer it better if you don't.

File: assets/js/blocks/collection-filters/utils.ts [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+		product_tag: 'tag',
+		product_cat: 'cat',
+	};
+
+	return taxonomy in map ? map[ taxonomy ] : `_unstable_tax_${ taxonomy }`;
```
Comment (sunyatasattva) [inline assets/js/blocks/collection-filters/utils.ts]: How about:

```suggestion
	return map[ taxonomy ] || `_unstable_tax_${ taxonomy }`;
```

File: assets/js/blocks/collection-filters/utils.ts [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+	];
+
+	const mappedParams: { key: keyof ProductCollectionQuery; map: string }[] = [
+		{ key: 'orderBy', map: 'orderby' },
+		{ key: 'pages', map: 'page' },
+		{ key: 'parents', map: 'parent' },
+		{ key: 'perPage', map: 'per_page' },
+		{ key: 'woocommerceStockStatus', map: 'stock_status' },
+		{ key: 'woocommerceOnSale', map: 'on_sale' },
+		{ key: 'woocommerceHandPickedProducts', map: 'include' },
```
Comment (sunyatasattva) [inline assets/js/blocks/collection-filters/utils.ts]: Mm, how about making this consistent with what you did in the `taxonomyMapper` above? Like:

```js
{
  orderBy: 'orderby',
  pages: 'page',
  // ...etc
}
```

File: assets/js/blocks/collection-filters/utils.ts [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+	];
+
+	return Object.assign(
```
Comment (sunyatasattva) [inline assets/js/blocks/collection-filters/utils.ts:65]: Why `Object.assign` instead of just spreading over an empty object?

```js
{
   ...sharedParams.reduce(),
   ...mappedParams.reduce()
}
```

File: assets/js/blocks/collection-filters/utils.ts [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+		...sharedParams.map(
+			( key ) => key in query && { [ key ]: query[ key ] }
+		),
+		...mappedParams.map(
+			( param ) =>
+				param.key in query && { [ param.map ]: query[ param.key ] }
+		),
+		...Object.entries( query.taxQuery ).map( ( [ taxonomy, terms ] ) => ( {
+			[ taxonomyMapper( taxonomy ) ]: terms,
+		} ) ),
```
Comment (sunyatasattva) [inline assets/js/blocks/collection-filters/utils.ts]: What do you think of moving this logic into the `taxonomyMapper` function? So the function accepts a `taxQuery` and does all of this, making this logic a bit easier to read in its intent.

File: assets/js/blocks/collection-filters/utils.ts [hunk 6]
```diff
@@ -0,0 +1,56 @@
+/**
+ * External dependencies
+ */
+import { ProductCollectionQuery } from '@woocommerce/blocks/product-collection/types';
+
+function taxonomyMapper( taxonomy: string ) {
```
Comment (sunyatasattva) [inline assets/js/blocks/collection-filters/utils.ts]: Usual Lucio nitpick… usually you see a noun used to name a `class` rather than a `function`. So, I would expect a `TaxonomyMapper` class, but I'd use a verb to name a function: e.g. `mapTaxonomy`.

**Review by sunyatasattva — CHANGES_REQUESTED** [review]
I have a few super minor comments, also the bot comment mentions that this PR adds 1 TS error.

As usual, code looks good and tests fine.

File: assets/js/blocks/collection-filters/utils.ts (hunk 1 above)
Comment (dinhtungdu) [reply assets/js/blocks/collection-filters/utils.ts]: I wanted to but it screams at me if I don't:

```
return map[ taxonomy ] || `_unstable_tax_${ taxonomy }`;

Diagnostics:
1. Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ product_tag: string; product_cat: string; }'.
     No index signature with a parameter of type 'string' was found on type '{ product_tag: string; product_cat: string; }'. [7053]
```

File: assets/js/blocks/collection-filters/utils.ts [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+	const map: Record< string, string > = {
+		product_tag: 'tag',
+		product_cat: 'cat',
+	};
+
+	return taxonomy in map ? map[ taxonomy ] : `_unstable_tax_${ taxonomy }`;
+}
+
+export function formatQuery( query: ProductCollectionQuery ) {
```
Comment (samueljseay) [inline assets/js/blocks/collection-filters/utils.ts:60]: I think it would be relatively low effort to write a unit test for this, it would describe intent as well which is an added bonus.

**Review by samueljseay — COMMENTED** [review]
Just a suggestion from me to add a unit test

File: assets/js/blocks/collection-filters/utils.ts (hunk 2 above)
Comment (dinhtungdu) [reply assets/js/blocks/collection-filters/utils.ts]: This is actually my first version, I used `in` in attempt to solve TS error when I didn't type `map`. I forgot to change back. Thanks!

File: assets/js/blocks/collection-filters/utils.ts (hunk 7 above)
Comment (dinhtungdu) [reply assets/js/blocks/collection-filters/utils.ts:60]: Yep, let me add some tests here.

File: assets/js/blocks/collection-filters/utils.ts (hunk 3 above)
Comment (dinhtungdu) [reply assets/js/blocks/collection-filters/utils.ts]: I wanted to do it but I was struggling to type it properly. I got this error:
```
	const mappedParams: Record< keyof ProductCollectionQuery, string > = {
		orderBy: 'orderby',
		pages: 'page',
		parents: 'parent',
		perPage: 'per_page',
		woocommerceStockStatus: 'stock_status',
		woocommerceOnSale: 'on_sale',
		woocommerceHandPickedProducts: 'include',
	};

Diagnostics:
1. Type '{ orderBy: string; pages: string; parents: string; perPage: string; woocommerceStockStatus: string; woocommerceOnSale: string; woocommerceHandPickedProducts: string; }' is missing the following properties from type 'Record<keyof ProductCollectionQuery, string>': author, exclude, inherit, offset, and 7 more. [2740]
```

In addition, if I use object like this, I have to use `Object.keys` or `Object.entries` to loop over the object, those function remove the type for the key and just set it as `string` in the call back.

Do you have any suggestion?

File: assets/js/blocks/collection-filters/utils.ts (hunk 4 above)
Comment (dinhtungdu) [reply assets/js/blocks/collection-filters/utils.ts:65]: Because we want to receive a flat object. If we don't use `Object.assign`, then we receive an object of object like this:
```
{
	{ per_page: 10 },
	{ orderby: 'title' },
}
```

**Comment by dinhtungdu** [comment]
@samueljseay @sunyatasattva thanks for the review! I addressed/answered Lucio review as well as added unit tests as Sam suggested! Can either of you give this one another look?

File: assets/js/blocks/collection-filters/utils.ts (hunk 4 above)
Comment (sunyatasattva) [reply assets/js/blocks/collection-filters/utils.ts:65]: Mm, are you sure? It seems to me that if you use spread operator over an object that should be flat, no?

File: assets/js/blocks/collection-filters/utils.ts (hunk 1 above)
Comment (sunyatasattva) [reply assets/js/blocks/collection-filters/utils.ts]: Ah yea, that's because `taxonomy` is a `string` you can either do:

```ts
function taxonomyMapper( taxonomy: 'product_tag' | 'product_cat' )
```

or

```ts
return map[ taxonomy as keyof typeof map ];
```

I think both of those should work. The first one is more elegant, IMHO.

File: assets/js/blocks/collection-filters/utils.ts (hunk 3 above)
Comment (sunyatasattva) [reply assets/js/blocks/collection-filters/utils.ts]: To fix the first issue, you'll need to do:

```ts
const mappedParams: Partial< Record< keyof ProductCollectionQuery, string > >
```

The second issue could be solved like this:

```ts
( Object.keys(map) as Array< keyof typeof map > ).map();
```

**Review by sunyatasattva — APPROVED** [review]
Responded to the comments. Preapproving.

File: assets/js/blocks/collection-filters/utils.ts (hunk 1 above)
Comment (dinhtungdu) [reply assets/js/blocks/collection-filters/utils.ts]: > function taxonomyMapper( taxonomy: 'product_tag' | 'product_cat' )

Besides `product_tag` and `product_cat`, `taxonomy` can be a custom taxonomy. Doing this way makes TS happy and the code still works as expected, but it makes TS and developers think that the function only accepts `product_tag` or `product_cat` as the valid parameter, which is not true. I feel like we're tricking the compiler here.

> return map[ taxonomy as keyof typeof map ];

Do you mean `return map[ taxonomy as keyof typeof map ] || _unstable_tax_${ taxonomy };`? If yes, then I don't think typecasting is more elegant than using the current tbh, when custom taxonomy is passed, it's not a key of the `map`.

File: assets/js/blocks/collection-filters/utils.ts (hunk 4 above)
Comment (dinhtungdu) [reply assets/js/blocks/collection-filters/utils.ts:65]: > Mm, are you sure?

Yes, if you look at the returned value from the map functions, they're arrays of objects: 

```
		...sharedParams.map(
			( key ) => key in query && { [ key ]: query[ key ] }
		),
```

Sure, I can use `reduce` here, but I always find `map` is easier to read than `reduce`.

File: assets/js/blocks/collection-filters/utils.ts (hunk 3 above)
Comment (dinhtungdu) [reply assets/js/blocks/collection-filters/utils.ts]: Thanks for your suggestion, I tried your suggestion but still couldn't make the TS totally happy:

Screen Shot 2023-10-21 at 17 32 14

The code I updated following your suggestion: https://gist.github.com/dinhtungdu/66ea100fefd18316b8f011ae2fd6d7db


> `( Object.keys(map) as Array< keyof typeof map > ).map();`


Comparing this to the current map, I still think the current one is easier to read. Or just becuse I don't like type casting 😄 

```
		...mappedParams.map(
			...
		),
```

File: tests/js/jest.config.json [hunk 8]
```diff
@@ -12,6 +12,7 @@
 		"@woocommerce/atomic-utils": "assets/js/atomic/utils",
 		"@woocommerce/icons": "assets/js/icons",
 		"@woocommerce/settings": "assets/js/settings/shared",
+		"@woocommerce/blocks(.*)$": "assets/js/blocks/$1",
```
Comment (samueljseay) [inline tests/js/jest.config.json]: @dinhtungdu this is breaking module name mapper, I think because blocks(.*) probably matches some other existing packages. for example it would match `@woocommerce/blocks-registry` which is already listed further down.

I don't know if module mapper respects order but you could try placing this at the end as a catch all for the other blocks. Otherwise you'll need a better pattern.

This is one of the many reasons I really hate aliases fwiw. This kinda stuff is not maintainable just to save some `../` that gets autofilled by the editor.

Comment (dinhtungdu) [reply tests/js/jest.config.json]: Nice catch! I will update the pattern.

> This is one of the many reasons I really hate aliases fwiw. This kinda stuff is not maintainable just to save some ../ that gets autofilled by the editor.

Maybe another RFC 😄 ?

**Review by samueljseay — APPROVED** [review]
Pre-approving, thanks for adding tests!

File: assets/js/blocks/collection-filters/utils.ts (hunk 1 above)
Comment (sunyatasattva) [reply assets/js/blocks/collection-filters/utils.ts]: > If yes, then I don't think typecasting is more elegant than using the current tbh, when custom taxonomy is passed, it's not a key of the map.

It is, in a way. Because when it's not, we are in the right side of the operator. It's a bit of a compromise. If you wanted to be fully clean, you can use a type guard or a conditional type. That'd be the 100% clean solution.

File: assets/js/blocks/collection-filters/utils.ts (hunk 4 above)
Comment (sunyatasattva) [reply assets/js/blocks/collection-filters/utils.ts:65]: Ah, yea, I meant to ask if you were sure about that being the result when using `reduce`. Ok, then, if it's your preference, you can use `map`. I personally try to be more explicit, and `reduce` helps me doing that. But that's not a hard recommendation, just an interesting conversation.

**Comment by dinhtungdu** [comment]
@sunyatasattva I updated the PR based on your suggestion, I still see some unresolved conversations, so I'm wondering if you still have other comments/feedback for this PR.

File: assets/js/blocks/collection-filters/utils.ts (hunk 3 above)
Comment (sunyatasattva) [reply assets/js/blocks/collection-filters/utils.ts]: > Comparing this to the current map, I still think the current one is easier to read. Or just becuse I don't like type casting 😄

Unfortunately, with the way some things in TS are designed, sometimes type casting is pretty much unavoidable. If you are concerned with code readability of this piece of code, you could refactor out the type casting so that it is hidden from the implementation. Indeed, as it is, this inline map function is a bit ugly, so I'd probably refactor it out.

As for your code complaining, it is because you are checking whether `param in query`, but not if `param in mappedParams`. So `mappedParams[ param ]` can be `undefined` and that is unassignable to a computed key of an object.

To solve this problem you should check whether that exists. For example:

```ts
(
  Object.keys( mappedParams ) as Array< keyof typeof mappedParams >
).map(
  ( param ) => {
      const key = mappedParams[ param ];
      return key && param in query && {
	[ key ]: query[ param ],
      }
   }
)
```

[TS Playground](https://www.typescriptlang.org/play?#code/PQKhCgAIUhRAPALgUwE4DsCGAbSATZAB2XQPQGMBLZAZyhGHEoFtCB7VRSAb0gEFEiVJQBGAVxQBZZIkx5MsyAF9IAM1RtmkAOQABAO5s25TczTlkwRAE9iNbQG5w4ZPHadIldClSrMFyAAFDTwxckQAYTZsbGRwyjZ0ASFRCVoecABIAEcxNGsALiCQsMjo2PjEgEU81GsnHNrrAEk8IvQxZhE0Btz8qO9XRCKAbSzM7nHMwkwAc2R2zu7UBsylLIBdBpRWbAVkAGVsMVmimhT0WYa8ShpCPesAGUxrNgki4LZQ8KiYuMQEugACK3e4vZ6vCTbOYAOUwZjOFyuWRM6AAbmgUHgAGIaZifb6IGhFERGWKYdBOdYuNwcLgkTqQCFvRAAeUIAMSNAymQA4gAlZpAyAAXh0qli8G0ABosgcACp8CIAaVFOmwt0QMvA1Nc7i4Xh8fgCBNKvwqnOBoIezIkPJsxCKtrZHMBNAaJmOzHQxMgHS6PSyNAAFsJ0ABrX6dH0AfhJZOQFKpzj1dM8g18-mQxS+ZvK-0BNXyPMwEmDHERYeRmVc5GOBErXlmIy2WS8wbQlGGkFJ0UT6EgAB8-WIYg02KpVDQZIsAysshwCKgivLTT985V0KzUEvxzu0AAhQqQVcldd-TfbpdHhozea+-3LW9oQJzBYjue3tjneW2d-nKsGmnTBUHIYNG0uaF4CLOoin5OJFwAHkgACm2lD9lhbSAAD4GkMYxTHMZBWXQA4cHfXtyUpLJQAgTJoEgbFKGwHxIEIM8iR7axIEQDtKFQFDEGMcNBIUMQaAAOiyaBpJgAB1ZjcHmdA0H2HiOzUco2H0JtIAAAzMWQAH0+jqPSClk2T9L0vSrJA1AXgACisyAdHDZBrG0VzvJFbCdCM85hIC2REHE7V6JgVztDRHA8i81zfMgRz7JeABKSAABJAvIcNgrE6caFlCLvO0ExWBA5AvMS7RmhhcKGNSoqGJs2yIsYTJ8LKsxQMOIScoOELxLjQSqxbPCjC6ojkmEcQUBoYbptSKQZDkBRMDGtsaDXMoL0tA9sGE4bKP7caCOYbqLAACQpPBAkoHLkFujj5og5tW11WkPAdbNT1zc8LUBK80DVbRMBocgvOHbQCHBxwaX1Hi-xPbbzQLRIgdQI9RSyKH5BQbQcZ0AFEFiAnMih9hCFHECu08wntAcgFLjh+G02+yAQTuG0XhZeUyREEDPkIbkxUmTIbi58EefeHNCVRzdObBJ5pcQICZEW2baCKRzIAUIRfVfThKBwZCUY3S0NbSbk-PSxK0TYSg8CpJxUy+pGYOsAYhGiIWRZ5UzjzN3bCyaNXEA9y2UG13XBFQA2QIBE3ZbzYPqiaHDIFtvz7cd53nFZjxUXOFDgwq26QPhX0+FQBzrGQ9zXlUZP-rR9APYzsUxkybRa3rSqiu0CcpxkcLB-3VBR+A0Dg21VsC64IuuGYTBCGIcuHOYeOjZNrJ4JMHd648idm52gG0-ydDUMuHDwD80WF3Ho8ijHpcRE8oq7y1nRP-C4hUFfeYz8-5GR-kVTqhEeoDWEgNfKz9sq5XOPlcK4DzpERImRWIz9EgBXIsgiaECro3Tug9J6f0iTPy8HWMQBBtQqDBpAReTh86uy4KoMQFBLSaVQMvcOTQdYBw+BxeWlp27pTFpQJuOsACEkAA6Zx5JkVAMgxAYB4EoBo1JMiLx4rQLgYpWQiAAFb-AkmDGglBZjoGcpkCYSgiqZAko4kMZdDaVwksvQg1ibE6wbvIxKvivCyPTgAMmCTwSAIxIC+I2EUAOkTonKHGI1cYjiJJeMyAY4x4QJINxoDrDxa9XGb3kfQ6utdD6N0RsQY+BTHpFOtuMTO7iV7pJ1jMDefi-KTG8j03pfS+naJEmKWp69K6RPafCSArYbE2KUaFVRIkYxsQrloQJcjQkKJmfEqZsSmjjJWVM+xNj1j9NOd5dYNjkk2NSfMRA8pMDQSaJIFpQT8gSVkI84sVzMi3MjsgD2-CmgSRQRdZAfzuSpSyKlBocyVEDjmqrHU4AgA)

**Comment by sunyatasattva** [comment]
Hey @dinhtungdu ! Sorry, You can totally merge this on my end. I continued the discussion that was open, if you are interested, but it's in no way a requirement or blocker for this PR!

**Comment by dinhtungdu** [comment]
@sunyatasattva I'm merging this PR but keeping our conversation open. I added a link to the conversation in https://github.com/woocommerce/woocommerce-blocks/pull/11218/commits/aeb350edf565e6c488b7f8def4bc57d8c6063f1a so it won't get lost.
