### PR TITLE
Fix Mini Cart missing translations

### LINKED ISSUE #8302: Editor: Mini Cart inner blocks have missing translations
## Describe the bug

Mini Cart inner blocks have missing translations in the inspector in the editor.

This is probably related to https://github.com/woocommerce/woocommerce-blocks/issues/6244, which was fixed in https://github.com/woocommerce/woocommerce-blocks/pull/6737.

## To reproduce

1. Go to your website and install a different language (I used Catalan)
2. Go to the editor of the Mini Cart template part (Appearance > Editor > Template Parts > Mini Cart)
3. Select the Mini Cart Footer inner block
4. Notice that the Inner block is translated, but the inspector title is not

imatge

## Expected behavior

The text is translated in glotpress, so we should use that translation:

imatge

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #8302.

This PR is inspired by #6737.

Note: if testing in the feature plugin, this PR doesn't fix missing translations for languages which don't have WC Blocks translations. In those cases, we fall back to WC core translations for PHP and JS text but it doesn't work for block.json strings.

#### User Facing Testing

1. Set your store language to a language with WC Blocks translations, ie: Spanish.
2. With a block theme (ie: TT3), go to Appearance > Editor > Template Parts and edit the Mini Cart block template part.
3. Open the sidebar list view and navigate to the `Tabla de productos del mini carrito` block. Verify the block name is correctly translated.

Before | After
--- | ---
imatge | imatge

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix Mini Cart block having some translations missing in the editor.

### CODE REVIEW

File: src/BlockTypes/MiniCart.php [hunk 1]
```diff
@@ -363,7 +363,6 @@ protected function get_markup( $attributes ) {
 		$cart_controller     = $this->get_cart_controller();
 		$cart                = $cart_controller->get_cart_instance();
 		$cart_contents_count = $cart->get_cart_contents_count();
-		$cart_contents       = $cart->get_cart();
```
Comment (Aljullu) [inline src/BlockTypes/MiniCart.php:366]: Changes in this file are generic cleanup. Unrelated to the other changes in this PR.

**Review by kmanijak — APPROVED** [review]
All translated as expected:
image

I checked with Polish as well. In this case, all descriptions are in English, so I believe this applies then:
> this PR doesn't fix missing translations for languages which don't have WC Blocks translations. In those cases, we fall back to WC core translations for PHP and JS text

LGTM! 👍

**Comment by Aljullu** [comment]
Thanks for the review, @kmanijak!

> I checked with Polish as well. In this case, all descriptions are in English, so I believe this applies then:

It looks like it's only partially translated, so that might be the reason:

https://translate.wordpress.org/locale/pl/default/wp-plugins/woo-gutenberg-products-block/
