### PR TITLE
Validate coupon usage against customer id AND emails

### LINKED ISSUE #11850: Coupon validation not as exhaustive as in legacy checkout
## Describe the bug

Let's say you have a coupon that can only be used once per user. After it has been used by a logged-in user, a further attempt at using the coupon by a guest user with the same address as the first user will be allowed, effectively bypassing the coupon limit.

Found during testing related to https://github.com/woocommerce/woocommerce/issues/41506.

## To reproduce

1. Make sure Blocks is in use for the checkout page.
2. Go to Marketing > Coupons and create a coupon with any details you like. Make sure it's limited to 1 use per user.
3. In an incognito window, log in as any user on your site and order something with the coupon applied.
4. In a different incognito window, go through checkout (as guest) and enter as billing e-mail address the same from the user in the previous step. Complete checkout with the coupon from step 2 applied.
5. Confirm that order is successful.

## Expected behavior

The second attempt should be prevented since e-mail matches an existing user that has already applied the coupon to an order.

## Additional context

This doesn't occur with the legacy checkout as in that case validation is a bit more robust (see [here](https://github.com/woocommerce/woocommerce/blob/62d21cc03d2302b4fae3d0f4c7c8eaf75a260a50/plugins/woocommerce/includes/class-wc-checkout.php#L425
) and [here](https://github.com/woocommerce/woocommerce/blob/7e55cbd1d739894515acc100e707742deb0fb6c6/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L1132-L1135)).

In the Blocks case, [validation is user ID XOR e-mail address](https://github.com/woocommerce/woocommerce-blocks/blob/77ed854ecd0602f518a2a7eea821d073c375a4b0/src/StoreApi/Utilities/OrderController.php#L435C52-L435C52) but both should probably be taken into consideration.

### PR DESCRIPTION
**Pull request by senadir**
WooCommerce would register coupon usage based on 2 elements, a user id if the customer has one, or the billing email.

There was an edge case in which a coupon can be used twice, once logged in with user id, and once logged out with billing email.

For the purpose of this fix, we consider emails to belong to a single user, so even as guest, it can't be used.

So in this PR, I check the coupon usage against a customer id, their billing email, and the account email (if those last 2 differ).

For a logged out customer, I first check if the email belongs to an existing user, and check its usage as well, as well as the billing email usage.

Fixes #11850

### From logged in to logged out
1. Create a new coupon and limit its usage to 1 per customer.
2. Logged in, with an email you remember, place an order using that coupon, it should pass.
3. Logged out, using the same email, try placing an order with that coupon, you should get a top level error "coupon_name" was removed from the cart. Coupon usage limit has been reached.".

### User email vs billing email
1. Create a new coupon and limit its usage to 1 per customer.
2. Logged in, with an user email you remember, place an order using that coupon, and a different billing email. It should pass.
3. Logged out, using the same user email (not the billing email), try placing an order with that coupon, you should get a top level error "coupon_name" was removed from the cart. Coupon usage limit has been reached.".

### From logged out to logged in
1. Create a new coupon and limit its usage to 1 per customer.
4. Logged out, use the coupon with an email you remember, that email should belong to an existing user.
5. You should be able to place the order fine.
6. Logged in with the user that own that email.
7. Go to checkout, add the coupon, using the same email, try to place the order.
8. You should get a top level error.
9. Change your billing email to something else, add the coupon again.
10. Try to place the order, you should get an error.

### General regression testing
1. Create a new coupon and limit its usage to 1 per customer.
2. Logged in, with an email you remember, place an order using that coupon, it should pass.
3. Logged in again, back to checkout, change your email, and try adding the coupon, you should get an inline error that you can't use the coupon.

* [ ] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## WooCommerce Visibility

Required:

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental
* [ ] N/A

## Checklist

Required:

* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [ ] This PR is assigned to a milestone.

## Changelog

> Enhance validation for limited use coupons and guest users.

### CODE REVIEW

File: src/StoreApi/Utilities/OrderController.php [hunk 1]
```diff
@@ -431,15 +431,83 @@ protected function validate_coupon_usage_limit( \WC_Coupon $coupon, \WC_Order $o
...
+					$emails
+				)
+			)
+		);
+		foreach ( $emails as $email ) {
+			$usage += $data_store->get_usage_by_email( $coupon, $email );
+		}
+		return $usage;
+	}
+
```
Comment (senadir) [inline src/StoreApi/Utilities/OrderController.php]: Those 2 can maybe be reduced to a direct DB call and a `get_tentative_usages_for_user` call, so 2 DB requests in total instead of > 4 calls.

```php
public function get_usage_per_aliases( &$coupon, $aliases ) {
	global $wpdb;
	$aliases = implode( "', '", array_map( 'esc_sql', $aliases ) );
	$usage_count = $wpdb->get_var(
		$wpdb->prepare(
			"SELECT COUNT( meta_id ) FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = '_used_by' AND meta_value IN ('%s');",
			$coupon->get_id(),
			$aliases
		)
	);
	$tentative_usage_count = $this->get_tentative_usages_for_user( $coupon->get_id(), $aliases );
	return $tentative_usage_count + $usage_count;
}
```

This is a modified version of $coupon->data_store->get_usage_per_email.

File: src/StoreApi/Utilities/OrderController.php [hunk 2]
```diff
@@ -431,15 +431,54 @@ protected function validate_coupon_usage_limit( \WC_Coupon $coupon, \WC_Order $o
 		$coupon_usage_limit = $coupon->get_usage_limit_per_user();
 
 		if ( $coupon_usage_limit > 0 ) {
-			$data_store  = $coupon->get_data_store();
-			$usage_count = $order->get_customer_id() ? $data_store->get_usage_by_user_id( $coupon, $order->get_customer_id() ) : $data_store->get_usage_by_email( $coupon, $order->get_billing_email() );
+			$data_store = $coupon->get_data_store();
+			// First, we check a logged in customer usage count, which happens against their user id, billing email, and account email.
+			if ( get_current_user_id() ) {
```
Comment (mikejolley) [inline src/StoreApi/Utilities/OrderController.php]: Why this vs original $order->get_customer_id()?

Comment (senadir) [reply src/StoreApi/Utilities/OrderController.php]: No strong reason, I think `get_customer_id` is better actually as it works if you're placing an order on someones name. Will fix this.

File: src/StoreApi/Utilities/OrderController.php [hunk 3]
```diff
@@ -431,15 +431,54 @@ protected function validate_coupon_usage_limit( \WC_Coupon $coupon, \WC_Order $o
...
+				// We get usage per user id and associated emails.
+				$usage_count = $this->get_usage_per_aliases( $coupon, array( $order->get_billing_email(), get_current_user_id(), wp_get_current_user()->user_email ) );
```
Comment (mikejolley) [inline src/StoreApi/Utilities/OrderController.php]:
```suggestion
				$user_data = get_userdata( $order->get_customer_id() );
				$usage_count = $this->get_usage_per_aliases( 
					$coupon, 
					[
						$order->get_billing_email(), 
						$order->get_customer_id(), 
						$user_data->user_email 
					]
				);
```

File: src/StoreApi/Utilities/OrderController.php [hunk 4]
```diff
@@ -431,15 +431,54 @@ protected function validate_coupon_usage_limit( \WC_Coupon $coupon, \WC_Order $o
...
 
+	/**
+	 * Get the usage count for a coupon based on a list of aliases (ids, emails).
+	 *
+	 * @param \WC_Coupon $coupon Coupon object applied to the cart.
+	 * @param array      $aliases List of aliases to check.
+	 *
+	 * @return integer
+	 */
+	public function get_usage_per_aliases( &$coupon, $aliases ) {
```
Comment (mikejolley) [inline src/StoreApi/Utilities/OrderController.php]: Let's not make this public at this point.

Comment (mikejolley) [inline src/StoreApi/Utilities/OrderController.php]: Why is coupon a pointer?

File: src/StoreApi/Utilities/OrderController.php (hunk 2 above)
Comment (senadir) [reply src/StoreApi/Utilities/OrderController.php]: [014bce6](https://github.com/woocommerce/woocommerce-blocks/pull/11860/commits/014bce602f61349e9edcc66865b2607d058b948f)

File: src/StoreApi/Utilities/OrderController.php (hunk 3 above)
Comment (senadir) [reply src/StoreApi/Utilities/OrderController.php]: [014bce6](https://github.com/woocommerce/woocommerce-blocks/pull/11860/commits/014bce602f61349e9edcc66865b2607d058b948f)

File: src/StoreApi/Utilities/OrderController.php [hunk 5]
```diff
@@ -431,15 +431,54 @@ protected function validate_coupon_usage_limit( \WC_Coupon $coupon, \WC_Order $o
...
+		global $wpdb;
+		$aliases        = array_unique( array_filter( $aliases ) );
+		$aliases_string = "('" . join( "','", array_map( 'esc_sql', $aliases ) ) . "')";
```
Comment (mikejolley) [inline src/StoreApi/Utilities/OrderController.php]:
```suggestion
		$aliases_string = "('" . implode( "','", array_map( 'esc_sql', $aliases ) ) . "')";
```

`join` is an alias. Implode is preferred.

File: src/StoreApi/Utilities/OrderController.php (hunk 4 above)
Comment (senadir) [reply src/StoreApi/Utilities/OrderController.php]: This is how it was used in the core data store function, I don't see a reason why, deleting..

File: src/StoreApi/Utilities/OrderController.php [hunk 6]
```diff
@@ -431,15 +431,54 @@ protected function validate_coupon_usage_limit( \WC_Coupon $coupon, \WC_Order $o
...
+		$usage_count    = $wpdb->get_var(
+			$wpdb->prepare(
+				"SELECT COUNT( meta_id ) FROM {$wpdb->postmeta} WHERE post_id = %d AND meta_key = '_used_by' AND meta_value IN {$aliases_string};", // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
```
Comment (mikejolley) [inline src/StoreApi/Utilities/OrderController.php]: Shouldn't the ignore be above the prepare statement?

File: src/StoreApi/Utilities/OrderController.php [hunk 7]
```diff
@@ -431,15 +431,54 @@ protected function validate_coupon_usage_limit( \WC_Coupon $coupon, \WC_Order $o
...
+				$coupon->get_id(),
+			)
+		);
+
+		$data_store            = $coupon->get_data_store();
+		$tentative_usage_count = $data_store->get_tentative_usages_for_user( $coupon->get_id(), $aliases );
```
Comment (mikejolley) [inline src/StoreApi/Utilities/OrderController.php:531]: Can you add a comment why this is needed in addition to used_by above?

Comment (senadir) [reply src/StoreApi/Utilities/OrderController.php:531]: This is I think a core only thing and shouldn't matter in our use case but added it anyway. adding a comment.

File: src/StoreApi/Utilities/OrderController.php [hunk 8]
```diff
@@ -431,15 +431,70 @@ protected function validate_coupon_usage_limit( \WC_Coupon $coupon, \WC_Order $o
...
+					]
+				);
+			} else {
+				// Otherwise we check if the email doesn't belong to an existing user.
+				$customer_data_store = \WC_Data_Store::load( 'customer' );
+				// This will get us any user ids for this billing email.
+				$user_ids       = $customer_data_store->get_user_ids_for_billing_email( array( $order->get_billing_email() ) );
+				$emails_for_ids = array_map(
+					function( $user_id ) {
+						return get_userdata( $user_id )->user_email;
```
Comment (mikejolley) [inline src/StoreApi/Utilities/OrderController.php]: Just realised this `get_userdata` and the one I added can return `false` so we need to check this.

File: src/StoreApi/Utilities/OrderController.php [hunk 9]
```diff
@@ -431,15 +431,71 @@ protected function validate_coupon_usage_limit( \WC_Coupon $coupon, \WC_Order $o
...
+			// First, we check a logged in customer usage count, which happens against their user id, billing email, and account email.
+			if ( $order->get_customer_id() ) {
+				$user_data = get_userdata( $order->get_customer_id() );
+				// We get usage per user id and associated emails.
+				$usage_count = $this->get_usage_per_aliases(
+					$coupon,
+					[
+						$order->get_billing_email(),
+						$order->get_customer_id(),
+						$user_data->user_email,
```
Comment (mikejolley) [inline src/StoreApi/Utilities/OrderController.php]:
```suggestion
						$user_data ? $user_data->user_email : '',
```

Like this?

File: src/StoreApi/Utilities/OrderController.php [hunk 10]
```diff
@@ -431,15 +431,72 @@ protected function validate_coupon_usage_limit( \WC_Coupon $coupon, \WC_Order $o
 		$coupon_usage_limit = $coupon->get_usage_limit_per_user();
 
 		if ( $coupon_usage_limit > 0 ) {
-			$data_store  = $coupon->get_data_store();
-			$usage_count = $order->get_customer_id() ? $data_store->get_usage_by_user_id( $coupon, $order->get_customer_id() ) : $data_store->get_usage_by_email( $coupon, $order->get_billing_email() );
+			$data_store = $coupon->get_data_store();
```
Comment (mikejolley) [inline src/StoreApi/Utilities/OrderController.php]: I don't think this is being used.

File: src/StoreApi/Utilities/OrderController.php [hunk 11]
```diff
@@ -431,15 +431,71 @@ protected function validate_coupon_usage_limit( \WC_Coupon $coupon, \WC_Order $o
 		$coupon_usage_limit = $coupon->get_usage_limit_per_user();
 
 		if ( $coupon_usage_limit > 0 ) {
```
Comment (mikejolley) [inline src/StoreApi/Utilities/OrderController.php]: We should return early here rather than nest the entire function below.

File: src/StoreApi/Utilities/OrderController.php (hunk 10 above)
Comment (senadir) [reply src/StoreApi/Utilities/OrderController.php]: yeah fixed.

File: src/StoreApi/Utilities/OrderController.php (hunk 11 above)
Comment (senadir) [reply src/StoreApi/Utilities/OrderController.php]: So maybe removing the existing check and doing this?

```
if ( $coupon_usage_limit === 0 ) {
	return;
}
```

early on?

**Review by mikejolley — APPROVED** [review]
✅ Test cases passed
✅ I fixed an issue with the checking of user email as well as billing email. New test case added, as well as updated the test cases for the notice on removal (which I changed to show why the coupon was removed)
✅ Code looks good.

This needs a second reviewer because I pushed some changes.

**Review by opr — APPROVED** [review]
Tests work for me code looks good. The db query looks fine as well, we're escaping each value before using it in the query so I'm happy with that.

**Review by wavvves — APPROVED** [review]
Changes look good and all testing steps checked out.
I also tried logged out vs logged out (new session) with same billing email.
Approving 👍🏼
