### PR TITLE
[Products]: Fix attributes filters that do not update the editor preview correctly

### LINKED ISSUE #8530: Product Query: Attributes filters do not update the editor preview correctly
## Describe the bug

When changing the attributes filter from the inspector controls, the products shown in the preview are not changed accordingly.

## To reproduce

1. Add a “Products (Beta)” block.
2. Add “Product Attributes” filter from “Advanced Filters” in the inspector controls.
3. Add some attribute filters.
4. Notice products don't get updated correctly.

## Additional context

From a cursory look, this seems a regression introduced in https://github.com/woocommerce/woocommerce-blocks/pull/7951

### PR DESCRIPTION
**Pull request by kmanijak**
## Issue
When changing the attributes filter from the inspector controls, the products shown in the preview of Products block did not change accordingly.

## Cause
The issue was caused by additional query component that extended the Products query: `$visibility_query` ([added here](https://github.com/woocommerce/woocommerce-blocks/pull/7951/files#diff-efb947e345af5e501dfaa2980b055b3b31c308b31e8db23049b6b48fecee33d8R132)).

Both: `$attributes_query` and `$visibility_query` have a shape of:

`array( 'tax_query' => [ ... ])`

so by passing `$visibility_query` to the `merge_arrays` function, the previous `tax_query` (from `$attributes_query`) was overridden by the new one and only the latter was passed further.

## Solution
The solution was to merge both `tax_query` params into a single array.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/8530

--- 

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

| Before | After |
| ------ | ----- |
|     https://user-images.githubusercontent.com/20098064/222551633-8761a251-fb8b-4a00-b7d6-63315f2b6198.mov | https://user-images.githubusercontent.com/20098064/222551791-b0d0c617-ed67-4471-bcc1-45d2d6a3a6fb.mov |

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

1. Create new post
2. Add _Products_ block
3. Make sure "Inherit query from template" toggle is disabled
4. Add “Product Attributes” filter from “Advanced Filters” in the inspector controls.
5. Add some attributes filter
6. **Expected**: Preview changes according to the applied attribute

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Products block: Fix attributes filters that do not update the editor preview correctly

### CODE REVIEW

**Review by thealexandrelara — APPROVED** [review]
Great job! Just tested and it is working as expected! LGTM! 🚀

**Comment by kmanijak** [comment]
Added unit tests: [commit](https://github.com/woocommerce/woocommerce-blocks/pull/8611/commits/d05d7133123bd74247ff4efd8585c8e784b67e75).

File: src/BlockTypes/ProductQuery.php [hunk 1]
```diff
@@ -113,6 +113,22 @@ public function update_query( $pre_render, $parsed_block ) {
 		}
 	}
 
+	/**
+	 * Merge tax_queries from various queries.
+	 *
+	 * @param array[] ...$queries Query arrays to be merged.
```
Comment (albarin) [inline src/BlockTypes/ProductQuery.php]: I think you don't need the `[]` here, you can just do `@param array ...`

File: src/BlockTypes/ProductQuery.php [hunk 2]
```diff
@@ -113,6 +113,22 @@ public function update_query( $pre_render, $parsed_block ) {
...
+	 * @return array
+	 */
+	private function merge_tax_queries( ...$queries ) {
```
Comment (albarin) [inline src/BlockTypes/ProductQuery.php:122]: This function works perfectly fine as is, but this is how I would have probably written it 👇 (I usually prefer to use `[]` instead of `array()`).
```php
private function merge_tax_queries( ...$queries ) {
	$tax_query = [];
	foreach ( $queries as $query ) {
		$tax_query[] = $query['tax_query'] ?: [];
	}
	return [ 'tax_query' => $tax_query ];
}
```
Let me know if something doesn't make sense to you 🙏

File: tests/php/BlockTypes/ProductQuery.php [hunk 3]
```diff
@@ -73,6 +73,23 @@ private function initialize_merged_query( $parsed_block = array() ) {
 		return $this->block_instance->build_query( $query );
 	}
 
+	/**
+	 * Build a simplified request for testing.
+	 *
+	 * @param bool  $woocommerce_on_sale WooCommerce on sale.
+	 * @param array $woocommerce_attributes WooCommerce attributes.
+	 * @param array $woocommerce_stock_status WooCommerce stock status.
+	 * @return array
```
Comment (albarin) [inline tests/php/BlockTypes/ProductQuery.php]: I think the return type here should be `WP_REST_Request` instead of `array`.

File: tests/php/BlockTypes/ProductQuery.php [hunk 4]
```diff
@@ -73,6 +73,23 @@ private function initialize_merged_query( $parsed_block = array() ) {
...
+	 */
+	private function build_request( $woocommerce_on_sale = 'false', $woocommerce_attributes = array(), $woocommerce_stock_status = array() ) {
```
Comment (albarin) [inline tests/php/BlockTypes/ProductQuery.php:84]: More array shorthand syntax `$woocommerce_attributes = []`.

File: tests/php/BlockTypes/ProductQuery.php [hunk 5]
```diff
@@ -513,5 +530,80 @@ public function test_merging_multiple_filter_queries() {
...
+				'key'     => '_stock_status',
+				'value'   => array(),
+				'compare' => 'IN',
+			),
+			$updated_query['meta_query'],
+		);
+
+		$this->assertEquals(
+			array(
+				array(
```
Comment (albarin) [inline tests/php/BlockTypes/ProductQuery.php:554]: Same here and the other tests function, I would change all the `array()` by the shorthand syntax.

**Review by albarin — APPROVED** [review]
As requested, here's my very very picky review 😄

File: src/BlockTypes/ProductQuery.php (hunk 2 above)
Comment (kmanijak) [reply src/BlockTypes/ProductQuery.php:122]: I think there's a difference between these two implementations (and the tests caught that! 😄). `$tax_query[] = $query['tax_query'] ?: [];` adds an empty array to the `$tax_query` array. So before returning, `$tax_query` would have to be filtered out. Unless I'm not getting something 😅 

I kept the original implementation for now 🙌

File: tests/php/BlockTypes/ProductQuery.php (hunk 5 above)
Comment (kmanijak) [reply tests/php/BlockTypes/ProductQuery.php:554]: Seems like there are other lint settings in the `tests` directory. Autoformatter changes `[]` to `array()` straight away. Also, considering that all the other tests are written using the `array()` syntax, I would keep it for consistency.

But other than that, I'll be using it for sure! 🙌

Comment (albarin) [reply tests/php/BlockTypes/ProductQuery.php:554]: Ah, that's right, I remember that happened to me too when writing some tests! 👍

File: src/BlockTypes/ProductQuery.php (hunk 2 above)
Comment (albarin) [reply src/BlockTypes/ProductQuery.php:122]: Hey, sorry! That's what happens when you try to be too clever on a Friday and don't try your code ✌️
You are right, the code it's not equivalent, better to keep the original! 😅
I think outside tests you can use the `[]`
