### PR TITLE
Ensure Filter Products by Attribute block reloads the page when interacting with PHP templates

### LINKED ISSUE #6331: Filter Products by Attribute block with Filter button doesn't reload the page in PHP templates
## To reproduce

1. With a block theme, go to Appearance > Site Editor.
2. Go to Templates and edit the Product Catalog template.
3. Above the WooCommerce Classic Template block, add the Filter Products by Attribute block and set its _Filter button_ attribute to true.
4. In the frontend, filter by attribute.
5. Notice the page doesn't reload.

## Expected behavior

The page should reload and the filter should be applied.

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #6331.

Heads-up that there is a follow-up PR which does some code clean-up: #6333.

### Screenshots

https://user-images.githubusercontent.com/3616980/165433571-9a148eb7-ccad-481d-b9db-92a40f885a26.mp4

### Manual Testing

1. With a block theme, go to Appearance > Site Editor.
2. Go to Templates and edit the Product Catalog template.
3. Above the WooCommerce Classic Template block, add the Filter Products by Attribute block (making sure you only have one Filter Products by Attribute block) and set its _Filter button_ attribute to true.
4. In the frontend, filter by attribute.
5. Verify the page reloads and the filter is applied.

### Changelog

> Fix Filter Products by Attribute block not working on PHP templates when Filter button was enabled.

### CODE REVIEW

**Review by tjcafferkey — APPROVED** [review]
Works as expected. The bug only surfaces if you have a single Filter Products by Attribute block on the template so I updated the testing instructions to mention this.

Thanks for fixing 🙌🏻

File: assets/js/blocks/attribute-filter/block.js [hunk 1]
```diff
@@ -268,29 +268,36 @@ const AttributeFilterBlock = ( {
...
+			attributeObject,
+			getSelectedTerms( isChecked ),
+			blockAttributes.queryType === 'or' ? 'in' : 'and'
+		);
+
+		// This is for PHP rendered template filtering only.
+		if ( filteringForPhpTemplate ) {
+			redirectPageForPhpTemplate( query, isChecked.length === 0 );
+		}
+	};
```
Comment (dinhtungdu) [inline assets/js/blocks/attribute-filter/block.js:284]: Using `onClickSubmit` without `useCallback` makes the `<FilterSubmitButton/>` re-render every time an attribute is checked. But I don't think it affects the performance noticeably.

Comment (tjcafferkey) [reply assets/js/blocks/attribute-filter/block.js:284]: Perhaps it can be updated in this PR https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6333 to use `useCallback` unless we can see a reason why it cannot?

Comment (dinhtungdu) [reply assets/js/blocks/attribute-filter/block.js:284]: ~This isn't correct. Same re-render happens on `trunk`.~ Caching issue, I can confirm the `<FilterSubmitButton/>` doesn't rerender on `trunk`.

Comment (dinhtungdu) [reply assets/js/blocks/attribute-filter/block.js:284]: @tjcafferkey Perhaps investigating why it works with two Filter Products by Attribute blocks gives us some clue?

Comment (dinhtungdu) [reply assets/js/blocks/attribute-filter/block.js:284]: FYI, with one Filter Products by Attribute block, at the time the filter button is clicked, `hasSetPhpFilterDefaults` is `false`, which means that `setHasSetPhpFilterDefaults` hasn't been called yet.

Comment (dinhtungdu) [reply assets/js/blocks/attribute-filter/block.js:284]: The issue with the current codebase is, that we're calling `redirectPageForPhpTemplate()` in two places, and clicking the filter button can trigger both function calls (when conditions meet). This makes the behavior of the Filter button unpredictable and hard to debug.

Comment (Aljullu) [reply assets/js/blocks/attribute-filter/block.js:284]: > Using `onClickSubmit` without `useCallback` makes the `<FilterSubmitButton/>` re-render every time an attribute is checked. But I don't think it affects the performance noticeably.

Wasn't that already happening? The onclick `prop` was different all the time because we were passing an arrow function that was created on every render.

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/2fb5c28757099952e236731437eadc0d58a610c1/assets/js/blocks/attribute-filter/block.js#L591

Comment (dinhtungdu) [reply assets/js/blocks/attribute-filter/block.js:284]: > Wasn't that already happening?

I'm not sure why it didn't happen when I test it here https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/6332#discussion_r859569876.

> The onclick prop was different all the time because we were passing an arrow function that was created on every render.

You're right, a closure is passed to `onClick` so it's recreated on every render. I'm sorry for the early conclusion! : (

**Review by dinhtungdu — APPROVED** [review]
LGTM! Tested and found no regression as well. 🚢

**Comment by Aljullu** [comment]
Merging because failing e2e tests don't seem related to this PR.

**Comment by Aljullu** [comment]
Thanks for the reviews! Merging because failing e2e tests don't seem related to this PR.
