### PR TITLE
Hook up checkout validation with context

### LINKED ISSUE #1939: Checkout Context and Validation: Improve `onCheckoutProcessing` event emitter to allow for aborted subscribers.
The `onCheckoutProcessing` event handler in the checkout context will get used by validation routines or processes that _can abort the checkout being processed_.

For reference, see the flow as outlined here:

Image 2020-03-11 at 9 32 28 AM

This means:

- eventEmitter must handle aborting running any subsequent subscribed observers as soon as an observer returns an error object (anything but `true`).
- `onCheckoutProcessing` will handle error objects that are returned from aborted events and update relevant checkout statuses and error states.

## Suggested apis (roughly):

This has the overall idea, but there are still some specifics that likely will need worked out as a part of the implementation.

A subscriber triggering a processing abort would be expected to return an error object in the following shape:

```js
const error = {
    message: 'Main error message',
    validation: {
        propertyFailingValidation: 'error message for field',
        anotherPropertyFailingValidation: 'error message for field',
    }
};
```

The `message` property will be output in an error notice by the checkout context.
The `validation` property is for errors triggered by validation fails. The value is an object where properties correspond to field properties/ids for existing form fields and values correspond to the validation error message to accompany the field error.

Implementation wise, the errors can be exposed on the checkout context and field components can grab that (via context hook) to determine whether there is an error and whether there are any matching validation properties for the field the component outputs.

## Additional considerations

- I don't anticipate there would be a lot of subscribers hooked into the `onCheckoutProcessing` hook, but I do wonder if instead of aborting after a single subscriber fail, if we should accumulate all the error objects and aggregate them? That might be a better customer experience for fixing all the potential issues rather than fixing for one subscriber and then getting hit by the next subscriber after?

### PR DESCRIPTION
**Pull request by Aljullu**
Closes #1939.

### Screenshots
imatge
_(:point_up_2: errors added by the payment method)_

### How to test the changes in this Pull Request:

In order to test it, let's force the payment method to return an error in certain circumstances. In `payment-method-extensions/payment-methods/stripe/payment-method.js` L289, paste something like this:
```JS
if ( billingData.postcode !== 'ABCD' ) {
	paymentStatus
		.setPaymentStatus()
		.error( 'Stripe found an error with your postcode.' );
	const key = billingData.shippingAsBilling
		? 'shipping-postcode'
		: 'billing-postcode';
	return {
		[ key ]: {
			message: 'Postcode must be ABCD.',
		},
	};
}
```
That will make Stripe to return an error if the billing postcode is different from `ABCD`.
1. Go to the _Checkout_ block and enter some data.
2. Feel free to leave some required fields empty or introduce an invalid email. We are testing validation!
3. Click on `Place Order` and verify errors are displayed properly.

### Notes
Currently, not all errors will appear at once: first Checkout validation errors and then, errors created by the payment method. I think this can be worked on in a follow-up and doesn't have to block this PR.

### CODE REVIEW

File: assets/js/base/context/cart-checkout/checkout/processor/index.js [hunk 1]
```diff
@@ -8,36 +8,73 @@ import {
...
+				id: 'payment-method-error',
+			} );
+		} else {
+			removeNotice( 'payment-method-error' );
+		}
+	}, [ errorMessage ] );
+
+	const checkValidation = useCallback( () => {
+		return ! withErrors;
+	}, [ withErrors ] );
```
Comment (nerrad) [inline assets/js/base/context/cart-checkout/checkout/processor/index.js:65]: Genius! I love how this removes the logic from the checkout button component!

File: assets/js/base/context/cart-checkout/checkout/processor/index.js [hunk 2]
```diff
@@ -79,35 +116,39 @@ const CheckoutProcessor = () => {
...
+
+	useEffect( () => {
+		const unsubscribeCompleteError = onCheckoutCompleteError( () => {
+			showAllValidationErrors();
+			scrollToTop( { focusableSelector: 'input:invalid' } );
+		} );
+		return () => {
+			unsubscribeCompleteError();
+		};
+	}, [ onCheckoutCompleteError ] );
```
Comment (nerrad) [inline assets/js/base/context/cart-checkout/checkout/processor/index.js:149]: Nice!

File: assets/js/base/context/cart-checkout/checkout/index.js [hunk 3]
```diff
@@ -45,8 +45,8 @@ export const CheckoutProvider = ( {
 					activePaymentMethod={ initialActivePaymentMethod }
 				>
 					<ShippingDataProvider>
-						{ children }
 						<CheckoutProcessor />
+						{ children }
```
Comment (nerrad) [inline assets/js/base/context/cart-checkout/checkout/index.js:49]: It's odd how you had to move this (I saw the commit message). I would have expected the reverse to be needed...

File: assets/js/base/context/cart-checkout/event-emit/emitters.js [hunk 4]
```diff
@@ -16,11 +16,11 @@
...
 export const emitEvent = async ( observers, eventType, data ) => {
 	const observersByType = observers[ eventType ]
-		? Object.values( observers[ eventType ] )
+		? observers[ eventType ].values()
 		: [];
-	for ( let i = 0; i < observersByType.length; i++ ) {
+	for ( const observer of observersByType ) {
 		try {
-			await Promise.resolve( observersByType[ i ]( data ) );
+			await Promise.resolve( observer( data ) );
```
Comment (nerrad) [inline assets/js/base/context/cart-checkout/event-emit/emitters.js:23]: Oh! nice improvements here!

File: assets/js/base/context/cart-checkout/event-emit/reducer.js [hunk 5]
```diff
@@ -33,19 +33,19 @@ export const actions = {
...
 			return {
 				...state,
-				[ eventType ]: {
-					...state[ eventType ],
-					[ id ]: callback,
-				},
+				[ eventType ]: newEvents,
 			};
 		case TYPES.REMOVE_EVENT_CALLBACK:
+			newEvents.delete( id );
```
Comment (nerrad) [inline assets/js/base/context/cart-checkout/event-emit/reducer.js:45]: I love how switching to `Map` removes a dependency, it seems to make the logic clearer to and reduces some code.

File: assets/js/base/context/cart-checkout/shipping/index.js [hunk 6]
```diff
@@ -165,8 +165,10 @@ export const ShippingDataProvider = ( { children } ) => {
 
 	// dispatch checkout error if there's a shipping error.
 	useEffect( () => {
-		dispatchActions.setHasError( currentErrorStatus.hasError );
-	}, [ currentErrorStatus, dispatchActions.setHasError ] );
+		if ( currentErrorStatus.hasError ) {
+			dispatchActions.setHasError( true );
+		}
+	}, [ currentErrorStatus.hasError, dispatchActions.setHasError ] );
```
Comment (nerrad) [inline assets/js/base/context/cart-checkout/shipping/index.js:171]: A problem with this change is it means if the shipping error is cleared, then the checkout error status won't get cleared. If there is potential for race conditions here, we may have to (not in this pull) add similar treatment for checkout hasError as what I did for the `isCalculating` state (keep count of things causing an error and increment/decrement count on those individual error state changes).

Comment (Aljullu) [reply assets/js/base/context/cart-checkout/shipping/index.js]: Yeah... makes sense. I removed the conditional for now (dc1901580e7812b1eef6585b32d3e5f19ac21a62) and created a follow-up, so we don't block this PR: #2096. I can start working on that one once this PR is merged.

I just wonder what's the benefit on having an error counter with increment/decrement instead of an array of error ids (or even better, a [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)). Both solutions would work, but a set of error ids would make our lives easier when debugging IMO. What do you think?

File: assets/js/base/context/cart-checkout/checkout/index.js (hunk 3 above)
Comment (Aljullu) [reply assets/js/base/context/cart-checkout/checkout/index.js]: Yeah, that's because I moved the `onCheckoutCompleteError` hook to the CheckoutProcessor instead of the CheckoutBlock, so when calling `scrollToTop`, it needed to be on top.

But thinking about it twice, I think that effect belongs more to the block than the processor, so I moved it back in 56164430a05ea5ca5587bd5e2462d453496d43c1.

File: assets/js/base/components/select/validated.js [hunk 7]
```diff
@@ -52,6 +52,13 @@ const ValidatedSelect = ( {
 		validateSelect();
 	}, [ value ] );
 
+	// Remove validation errors when unmounted.
+	useEffect( () => {
+		return () => {
+			clearValidationError( errorId );
```
[the remark this answers is not in the document]
Comment (Aljullu) [reply assets/js/base/components/select/validated.js:58]: Does it make sense leaving this as-is for now and working on this in parallel with #2096?

File: assets/js/base/context/cart-checkout/shipping/index.js (hunk 6 above)
Comment (nerrad) [reply assets/js/base/context/cart-checkout/shipping/index.js]: > Both solutions would work, but a set of error ids would make our lives easier when debugging IMO. What do you think?

Good thoughts, depending on what you end up storing as references for tracking, you may want to use a WeakSet to protect against potential memory leaks (from unmounts etc). The only reason I suggested an error counter is because it's trivial to implement and memory impact is insignificant.

File: assets/js/blocks/cart-checkout/checkout/block.js [hunk 8]
```diff
@@ -126,10 +114,22 @@ const Checkout = ( {
 	);
 	useEffect( () => {
 		if ( shippingAsBilling ) {
-			setBillingData( shippingAddress );
+			setBillingData( { ...shippingAddress, shippingAsBilling } );
+		} else {
+			setBillingData( { shippingAsBilling } );
 		}
 	}, [ shippingAsBilling, setBillingData ] );
```
Comment (senadir) [inline assets/js/blocks/cart-checkout/checkout/block.js:122]: what was the point of adding shippingAsBilling to shipping data? It’s not paired with the backend and I don’t see it being used anywhere else

Comment (Aljullu) [reply assets/js/blocks/cart-checkout/checkout/block.js:122]: It's used in the example above. I thought it would be useful for extensions to know if the shipping and billing addresses are the same. That would also allow them to display the errors messages in the correct fields.
