### PR TITLE
Parse categories coming from the back-end as a json array

### LINKED ISSUE #6347: Reviews by Category block showing reviews from ALL categories instead of the selected category
## Describe the bug

When using the Reviews by Category Block:
* The preview of the page shows reviews from the category chosen in the block
* The published page shows reviews from ALL product categories, not just the ones specified in the block

## To reproduce

Pre-requisite: If you have no product reviews, add reviews to at least two products in different categories. Make sure that these products don't share categories as well.

1. Create a new page from WP-Admin → Pages
2. Add the Reviews by Category block to the page
4. Select only one product category
Markup on 2022-04-29 at 15:09:43

5. Check how the block renders reviews on the edit page: it works as expected and only shows reviews from the selected category
Markup on 2022-04-29 at 15:11:51

7. Publish the page and check how it renders reviews: it works not as expected, and shows reviews from other categories not selected
Markup 2022-04-29 at 15 14 55

## Expected behavior

When the page is published, the Reviews by Category block should only show categories from the selected categories. Presently, it pulls reviews from categories not selected.

### WordPress (please complete the following information):

WordPress version: 5.9.3
WooCommerce version: 6.4.1
WooCommerce REST API package: 6.4.1 
WooCommerce Blocks package: 7.5.0

<br class="Apple-interchange-newline">

### Desktop (please complete the following information):

-   OS: macOS
-   Browser Chrome
-   Version 100.0.4896.127

## Additional context

Originally reported in 5171774-zd-woothemes

### PR DESCRIPTION
**Pull request by albarin**
The goal of this PR is to address a problem occurring when rendering the `Reviews by Category` block in the frontend.
The category ids that come from PHP are in `JSON` array format (e.g. '[40,41]'), so it's necessary to parse them and convert them into a js array before processing them. Otherwise, the API request will fail because the `categoryIds` query param will be `categoryIds=[40,41]` instead of the expected `categoryIds=40,41`.

Fixes https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/6347

#### Manual tests
1. Create two products assigned to two different categories and add one review to each of them.
2. Create a new page and add a `Reviews by Category` block.
3. Select only one category on the block (corresponding to one of the previous products/reviews) and save it.
4. Check that it renders the expected reviews only on the edit mode.
5. Publish the page, go to the frontend and check it renders the same expected reviews.
----
6. Edit the block and select multiple categories.
7. Check that it renders the expected reviews only on the edit mode.
8. Update the page, go to the frontend and check it renders the same expected reviews.
----
9. Edit again the block and deselect all the categories.
10. Check that it renders **all** the reviews only on the edit mode.
11. Update the page, go to the frontend and check it renders also **all** the reviews.

### CODE REVIEW

File: assets/js/base/hocs/with-reviews.js [hunk 1]
```diff
@@ -106,10 +106,14 @@ const withReviews = ( OriginalComponent ) => {
...
-			if ( categoryIds && categoryIds.length ) {
-				args.category_id = Array.isArray( categoryIds )
-					? categoryIds.join( ',' )
-					: categoryIds;
+			const categories = Array.isArray( categoryIds )
+				? categoryIds
+				: JSON.parse( categoryIds );
+
+			if ( categories && categories.length ) {
+				args.category_id = Array.isArray( categories )
```
Comment (tjcafferkey) [inline assets/js/base/hocs/with-reviews.js:114]: If we are checking `categories.length` above, are we not already confident at this point that it is an array?

Comment (tjcafferkey) [reply assets/js/base/hocs/with-reviews.js:114]: Unless `categories` can be a string at this point, which I think it can?

Comment (albarin) [reply assets/js/base/hocs/with-reviews.js:114]: Hmm, in theory, it should always be an array after line `111`.
But, if for some reason the `JSON.parse( categoryIds )` would return a string, we would have an issue.

Comment (albarin) [reply assets/js/base/hocs/with-reviews.js:114]: I've refactored it a bit, we need to check that it has a value, otherwise, it breaks.

**Review by tjcafferkey — APPROVED** [review]
Works as expected and the code LGTM! I've updated the labels on the PR to reflect the work too.
