### PR TITLE
Fix Block Templates being rendered correctly

### LINKED ISSUE #5046: Ensure the correct template is loading on the Frontend and the site editor
Today we discovered that we're not loading the correct template on the Frontend as well as the site editor. This has potentially not surfaced before as we were testing with only one template in the template directory.

The goal of this issue is to ensure the correct template is loading on the Frontend and in the site editor and we'll use this issue to track the time spent investigating and resolving the bug we're seeing.

### PR DESCRIPTION
**Pull request by tjcafferkey**
Copy logic from [Gutenberg](https://github.com/WordPress/gutenberg/blob/trunk/lib/full-site-editing/block-templates.php#L417-L445) to ensure the correct templates are being included in the get_block_templates query

Fixes https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5046

### Manual Testing

How to test the changes in this Pull Request:

**Prerequisite**: Please ensure you have a Block Template Theme activated such as TT1 and also the Gutenberg Plugin installed.

1. Download the [Archive.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/7459684/Archive.zip) file and unzip. Put the containing .html files in `woo-blocks/templates/block-templates/`
2. Load Product Page (e.g. `/product/album/`) and ensure the `single-product.html` template is rendered.
3. Load Taxonomy Page (e.g. `/product-category/clothing/`) and ensure the `taxonomy-product_cat.html` template is rendered
4. Load the Shop/Archive page and ensure the `archive-product.html` template is rendered.
5. Load Site Editor and ensure templates are also present here.

Once you have followed the above steps, add the same template files to your `theme-dir/block-templates` and change the file contents so you can differentiate the Woo Block template and the Theme template. Repeat the above steps starting from Step 2 and confirm the Theme template is preferred over the Woo Blocks template

### CODE REVIEW

File: src/BlockTemplatesController.php [hunk 1]
```diff
@@ -53,10 +53,37 @@ public function add_block_templates( $query_result, $query, $template_type ) {
 			return $query_result;
 		}
 
+		$post_type      = isset( $query['post_type'] ) ? $query['post_type'] : '';
 		$template_files = $this->get_block_templates();
 
+		// @todo: Add apply_filters to _gutenberg_get_template_files() in Gutenberg to prevent duplication of logic.
```
Comment (frontdevde) [inline src/BlockTemplatesController.php:59]: Agreed that ideally, we'd want to prevent code duplication here. That said, this fix unblocks us now which is important. We should keep it on our list to revisit eventually though.

File: src/BlockTemplatesController.php [hunk 2]
```diff
@@ -84,15 +111,14 @@ public function get_block_templates() {
 			}
 
 			$new_template_item = array(
-				'title' => ucwords( str_replace( '-', ' ', $template_slug ) ),
+				'title' => BlockTemplateUtils::convert_slug_to_title( $template_slug ),
```
Comment (frontdevde) [inline src/BlockTemplatesController.php:114]: Thank you, I appreciate you iterating on this! Definitely a nice win from a user perspective 🙂

File: src/BlockTemplatesController.php [hunk 3]
```diff
@@ -137,6 +163,18 @@ public function render_block_template() {
 			$this->default_block_template_is_available( 'single-product' )
 		) {
 			add_filter( 'woocommerce_has_block_template', '__return_true', 10, 0 );
+		} elseif (
```
Comment (frontdevde) [inline src/BlockTemplatesController.php:166]: Correct me if I'm wrong but it looks like we're doing the same in all cases, right?

What are your thoughts on maybe making this a bit more readable with a single `if` and moving the checks to variables? Something along the lines of

```
if ( $show_single_product || $show_taxonomy_product_cat || $show_archive_product ) {
	add_filter( 'woocommerce_has_block_template', '__return_true', 10, 0 );
}
```

File: src/Utils/BlockTemplateUtils.php [hunk 4]
```diff
@@ -128,4 +128,24 @@ public static function gutenberg_get_template_paths( $base_directory ) {
...
+	/**
+	 * Converts template slugs into readable titles.
+	 *
+	 * @param string $template_slug The templates slug (e.g. single-product).
+	 * @return string Human friendly title converted from the slug.
+	 */
+	public static function convert_slug_to_title( $template_slug ) {
+		switch ( $template_slug ) {
+			case 'single-product':
+				return 'Single Product Page';
```
Comment (frontdevde) [inline src/Utils/BlockTemplateUtils.php]: These display names probably need `i18n`, no?

**Review by frontdevde — APPROVED** [review]
Tested as per testing instructions and it tests as expected for me!
Great to see this fixed 🥳

I left a couple of comments but they are optional or could be addressed later and don't have to block this PR.

File: src/BlockTemplatesController.php (hunk 3 above)
Comment (tjcafferkey) [reply src/BlockTemplatesController.php:166]: We could potentially clean this up I agree. Something for a future PR like you suggested so we can merge this in for the other week outstanding.

File: src/BlockTemplatesController.php [hunk 5]
```diff
@@ -53,10 +53,37 @@ public function add_block_templates( $query_result, $query, $template_type ) {
...
 		$template_files = $this->get_block_templates();
 
+		// @todo: Add apply_filters to _gutenberg_get_template_files() in Gutenberg to prevent duplication of logic.
 		foreach ( $template_files as $template_file ) {
-			$query_result[] = BlockTemplateUtils::gutenberg_build_template_result_from_file( $template_file, 'wp_template' );
+			$template = BlockTemplateUtils::gutenberg_build_template_result_from_file( $template_file, 'wp_template' );
+
+			if ( $post_type && ! $template->is_custom ) {
+				continue;
+			}
```
Comment (dinhtungdu) [inline src/BlockTemplatesController.php:65]: @tjcafferkey the `$template` object returned by `BlockTemplateUtils::gutenberg_build_template_result_from_file()` doesn't have `is_custom` property on WP 5.8.1. The `WP_Block_Template` class shipped with 5.8.1 doesn't have that property (the one in Gutenberg does) so I'm getting this warning:

`
Warning: Undefined property: WP_Block_Template::$is_custom in /wp-content/plugins/woocommerce-gutenberg-products-block/src/BlockTemplatesController.php on line 63
`

Comment (tjcafferkey) [reply src/BlockTemplatesController.php:65]: Thanks @dinhtungdu. I will open a PR to fix this by setting the `is_custom` value to `false` in `BlockTemplateUtils::gutenberg_build_template_result_from_file()` seeing as we _know_ this is being loaded from the filesystem so it should be `false`.

`is_custom` templates are ones that have been edited and are being retrieved from the DB.

PR here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5067

Comment (dinhtungdu) [reply src/BlockTemplatesController.php:65]: Resolved in #5067
