### PR TITLE
Default to the first state when selecting a country with states

### LINKED ISSUE #1895: API not returning rates if you ship to a whole country that has states in Woo
**Describe the bug**
So it’s a bit hard to describe this issue in the title alone, this comment from Albert https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1890#pullrequestreview-370506967 and my reply here https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1890#issuecomment-596192712 dives deep into it, but I will explain what I found.

When you set a shipping to a whole country, and that country has states defined in Woo, rates will not show up if you only use country for them (as in, in Checkout, if you select a country only, the response will return empty), you need to define a state for it to work, but for countries without states, it will work.

**To Reproduce**

1. setup shipping rates for two counties, one without states (france, algeria, morococo.....), and one for a country with states (spain, US...).
2. In Chcekout or Cart block, set only the Country
3. for countries without states, rates will show up
4. for countries with states, they wont show up until you select a state

**Expected behavior**
rates should show up for counties with state even if you select the country.

**Screenshots**
in the first linked comment.

### PR DESCRIPTION
**Pull request by senadir**
This PR defaults to the first state when a country with states is selected, it is meant temporarily patch an issue in Woo Core https://github.com/woocommerce/woocommerce/issues/25854

Fixes #1895
Todo introduced: #1920

### How to test the changes in this Pull Request:

1. select a country with states in Checkout or Cart
2. See first state being selected

### CODE REVIEW

File: assets/js/base/components/state-input/state-input.js [hunk 1]
```diff
@@ -28,7 +28,14 @@ const StateInput = ( {
 				name: decodeEntities( countryStates[ key ] ),
 		  } ) )
 		: [];
-
+	// @todo: remove this code block when issue https://github.com/woocommerce/woocommerce/issues/25854 is merged
+	// Defaults to the first state when selecting a country with states, this is here
+	// until a bug in Woo core is fixed.
+	useEffect( () => {
```
Comment (Aljullu) [inline assets/js/base/components/state-input/state-input.js]: We could add a link to the GitHub issue, so if we ever fix this in the code, we will remember to close the issue. :slightly_smiling_face: 
```suggestion
	// see: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1919
	useEffect( () => {
```
