### PR TITLE
Fix currency format in On Sale badge

### LINKED ISSUE #2155: Cart block: `Save %d` doesn't respect currency format
**To Reproduce**
1. In your currency settings, set the decimal separator to comma `,`.
2. Go to the _Cart_ block with a product on sale.
2. Notice the `Save 1.82€!` shows the value separated with a dot instead of a comma.

**Expected behavior**
The value in the save badge should use the correct price format.

**Screenshots**
imatge

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #2155.

### How to test the changes in this Pull Request:

1. In your currency settings, set the decimal separator to comma `,`.
2. Go to the _Cart_ block with a product on sale.
2. Verify the `Save 1,23€!` badge shows the value separated with a comma instead of a dot.

### CODE REVIEW

File: assets/js/base/components/cart-checkout/product-sale-badge/index.js [hunk 1]
```diff
@@ -25,10 +26,16 @@ const ProductSaleBadge = ( { currency, saleAmount } ) => {
 	}
 	return (
 		<div className="wc-block-sale-badge">
-			{ sprintf(
-				/* translators: %s discount amount */
-				__( 'Save %s!', 'woo-gutenberg-products-block' ),
-				formatPrice( saleAmount, currency )
+			{ __experimentalCreateInterpolateElement(
+				__( 'Save <price></price>!', 'woo-gutenberg-products-block' ),
```
Comment (nerrad) [inline assets/js/base/components/cart-checkout/product-sale-badge/index.js:30]: You should be able to just do a self-closing `<price />` here.  Also might be good to add a translators comment just to make it clear that `<price/>` should not be translated.
