### PR TITLE
Set focus on Empty Mini Cart Contents Block

### LINKED ISSUE #4618: Mini Cart block: after removing a product, drawer can't be closed clicking outside
## To reproduce
In branch `add/drawer-component` (#4608):

1. Create a post or page and add a Mini Cart block.
2. Visit that post or page in the frontend and click on the Mini Cart button.
3. In the drawer that appears, remove one of the products from your cart.
4. Click on the overlay and notice the drawer doesn't close.
5. It can be workarounded clicking again somewhere inside the drawer and the outside again.

## Expected behavior
The drawer should close when clicking outside in all cases.

## Screenshots

https://user-images.githubusercontent.com/3616980/130471273-d7e7dbf0-a0e4-4713-925a-864505de6a2f.mp4

## Next steps

The Mini Cart block uses the [`Modal` Gutenberg component](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/modal), which internally uses the [`useFocusOutside()` hook](https://github.com/WordPress/gutenberg/blob/trunk/packages/compose/src/hooks/use-focus-outside/index.js), so the issue might be there.

### PR DESCRIPTION
**Pull request by gigitux**
This PR set the focus on the Empty Mini Cart Contents element: in this way when the user clicks outside the drawer, this latter will close.

Without this PR when the Empty Mini Cart Contents Block is rendered after removing the last product, the active element is the body. This causes that [these callbacks](https://github.com/WordPress/gutenberg/blob/c86a198597fa6d237699b7883bd9de8d1663bbd0/packages/components/src/modal/index.js#L74) aren't being called.

Fixes #4618

### Manual Testing

How to test the changes in this Pull Request:

Check out this branch

1. Create a post or page and add a Mini Cart block.
2. Add a Product to the cart.
3. Visit that post or page in the front and click on the Mini Cart button.
4. Remove the product.
5. Click on the overlay and check that the drawer will close.

### CODE REVIEW

**Review by dinhtungdu — DISMISSED** [review]
Tested and this is working great for me!

File: assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/empty-mini-cart-contents-block/frontend.tsx [hunk 1]
```diff
@@ -16,12 +17,22 @@ const EmptyMiniCartContentsBlock = ( {
 }: EmptyMiniCartContentsBlockProps ): JSX.Element | null => {
 	const { cartItems, cartIsLoading } = useStoreCart();
 
+	const elementRef = useRef< HTMLDivElement >( null );
+
+	useEffect( () => {
+		elementRef.current?.focus();
+	} );
```
Comment (tomasztunik) [inline assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/empty-mini-cart-contents-block/frontend.tsx]: This would trigger it on every re-render/update of the component and we want to focus it only on initial mount/render right? Then empty dependency array is required.

File: assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/empty-mini-cart-contents-block/frontend.tsx [hunk 2]
```diff
@@ -16,12 +17,22 @@ const EmptyMiniCartContentsBlock = ( {
...
+
 	if ( cartIsLoading || cartItems.length > 0 ) {
 		return null;
 	}
 
 	return (
-		<div className="wp-block-woocommerce-empty-mini-cart-contents-block">
+		<div
+			tabIndex={ 0 }
```
Comment (tomasztunik) [inline assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/empty-mini-cart-contents-block/frontend.tsx]: We should consider using `-1` here - It allows focusing with JavaScript but wouldn't allow to focus using TAB and would not interrupt tabbing flow for accessibility.

File: assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/empty-mini-cart-contents-block/frontend.tsx (hunk 1 above)
Comment (tomasztunik) [reply assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/empty-mini-cart-contents-block/frontend.tsx]: or if it's based on if cart is loaded then we should add loaded state as dependency and focus when loaded and ref is set :)

Comment (gigitux) [reply assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/empty-mini-cart-contents-block/frontend.tsx]: > This would trigger it on every re-render/update of the component and we want to focus it only on initial mount/render right? Then empty dependency array is required.

Great catch! Thanks for bringing this up!

**Review by tomasztunik — APPROVED** [review]
Thanks for the tweaks! Looks good 🎉
