### PR TITLE
Cart and Checkout accessibility fixes

### LINKED ISSUE #1538: Cart block - accessibility review and related fixes
Some accessibility issues in the cart line items UX were noted during #1333. This issue covers reviewing the cart UX for any accessibility problems and fixing them.

Note that PRs for cart work should not ignore accessibility – this issue is here to ensure we review the whole block once the UX comes together.

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #1538.

This PR fixes several accessibility issues in the _Cart_ and _Checkout_ blocks.

#### Accessibility

- [x] I've tested using only a keyboard (no mouse)
- [x] I've tested using a screen reader
- [x] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [x] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### How to test the changes in this Pull Request:

I think each commit description is quite self-explanatory of what needs to be tested but...

Instead of testing each individual commit one-by-one, I think it's better just to test the entire block with a screen reader & keyboard navigation. If you find any issue that is not fixed in this PR or has an issue, report it! :slightly_smiling_face:

### CODE REVIEW

File: assets/js/base/context/cart-checkout/validation/index.js [hunk 1]
```diff
@@ -151,12 +151,13 @@ export const ValidationContextProvider = ( { children } ) => {
...
-	 * @param {string} inputId The input css id the validation error is related
+	 * @param {string} errorId The input css id the validation error is related
 	 *                         to.
 	 * @return {string} The id to use for the validation error container.
 	 */
-	const getValidationErrorId = ( inputId ) => {
-		return inputId ? `validate-error-${ inputId }` : '';
+	const getValidationErrorId = ( errorId ) => {
+		const error = getValidationError( errorId );
+		return error && ! error.hidden ? `validate-error-${ errorId }` : '';
```
Comment (senadir) [inline assets/js/base/context/cart-checkout/validation/index.js]: this seems hard to understand and I'm not sure if it will return `validate-error-${ errorId }` or `''` or will return the expression `error && resultOfTernary` 
```suggestion
		return ( error && ! error.hidden ) ? `validate-error-${ errorId }` : '';
```

Comment (Aljullu) [reply assets/js/base/context/cart-checkout/validation/index.js]: Those parentheses are removed by ESLint. I refactored it to avoid using a ternary here, hope it makes code clearer: 5c2ff5597c2eda1c653052640973ebfd1d17cedc.
