### PR TITLE
Push address changes for email, name and address fields

### LINKED ISSUE #8395: Checkout resets First name, last name, address and email fields when changing shipping option
## Describe the bug

The Checkout Block resets the email address, first name, last name and address fields when the shipping option is changed

## To reproduce

1. Add items to your cart and go to the Checkout
3. Type in your email address
4. Type an address
5. Select a different shipping option
6. email, first name, last name and address fields will be emptied

## Expected behavior

None of the form fields should be emptied when selecting a different shipping option

## Screenshots

https://user-images.githubusercontent.com/3966773/217517898-74a59156-3357-48c3-8b1a-5a678054305b.mov

### PR DESCRIPTION
**Pull request by alexflorisca**
This PR will call the `update-customer` StoreApi endpoint for any changed address field, not just the 4 used to calculate shipping rates (country, city, county, postcode). This is because in #8030 we introduced a change that only pushes the data for a changed field. This means that the email address, first name, last name, address and phone number fields never get pushed to the server until the user clicks the Place Order button.

This is problematic because when we change the shipping option, the cart data from the server is synced with the client, and anything that was entered in any field that doesn't sync with the server, will be lost.

Fixes #8395 

#### User Facing Testing

1. Go to Checkout
2. For each of these fields (email, first name, last name, address, phone), do the following:
- Enter an invalid value. Check no network request is made
- Enter a valid value. Check a request to `update-customer` is made
3. Fill in the whole shipping address form
4. Change the shipping option
5. Make sure no values in the form are overwritten

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix a bug where certain checkout fields were being reset when changing the shipping option

### CODE REVIEW

**Review by tarhi-saad — APPROVED** [review]
Thank you, @alexflorisca, for the fix! LGTM 👍

File: assets/js/data/cart/push-changes.ts [hunk 1]
```diff
@@ -27,15 +23,33 @@ type CustomerData = {
...
+			address[ key as keyof BillingOrShippingAddress ].trim();
+	} );
+
+	trimmedAddress.postcode = trimmedAddress.postcode
+		? trimmedAddress.postcode.replace( ' ', '' ).toUpperCase()
+		: '';
+
+	return trimmedAddress;
+};
+
```
Comment (senadir) [inline assets/js/data/cart/push-changes.ts:52]: Why is trimming an address needed?

Comment (alexflorisca) [reply assets/js/data/cart/push-changes.ts:52]: It was done in the `pluckAddress` function, when comparing values it's good practice to `trim` to avoid false negatives
