### PR TITLE
Adjust response method in checkout route to prevent coupon breakage

### LINKED ISSUE #8446: Coupon amount become 0 after checkout using WooCommerce Store API
## Describe the bug

Using WooCommerce Store API, with coupon applied with usage limit per user set to 1. If I checkout with user connected (I'm using JWT Authentication for WP-API plugin to login and use returned token for next requests), coupon amount become 0.

## To reproduce

See https://github.com/woocommerce/woocommerce-blocks/issues/8446#issuecomment-1433433753 for simpler reproduction steps

1. ~~Create any coupon and set **Usage limit per user** to **1**~~
2. ~~Using WooCommerce Store API, add a product to your cart~~
2. ~~Using WooCommerce Store API, apply this coupon to your cart~~
3. ~~Using WooCommerce Store API, checkout~~

## Expected behavior

Coupon amount to not being 0.

## Screenshots

On Get Checkout (/wp-json/wc/store/v1/checkout), its create me a draft order with coupon applied
Capture d’écran 2023-02-15 à 18 05 30

On Post Checkout, order status change to **Pending** with coupon amount = 0
Capture d’écran 2023-02-15 à 18 06 07

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   WooCommerce version: 7.4.0
-   WooCommerce Blocks version: 9.4.3 
-   Site language: en_US
-   Any other plugins installed: JWT Authentication for WP-API | by Enrique Chavez – 1.3.2

### Desktop (please complete the following information):

-   OS: macOS
-   Browser chrome
-   Version 109.0.5414.119

## Additional context

All steps I've done its with a new customer created with 0 orders.

After some research in the code, I found the error coming from $discounts->apply_coupon( $coupon )
Here the stack trace: 

```
Error: 
object(WP_Error)[3720]
  public 'errors' => 
    array (size=1)
      'invalid_coupon' => 
        array (size=1)
          0 => string 'Coupon usage limit has been reached.' (length=36)
  public 'error_data' => 
    array (size=1)
      'invalid_coupon' => 
        array (size=1)
          'status' => int 400
  protected 'additional_data' => 
    array (size=0)
      empty

Stack trace:
(class-wc-totals.php:777) $discounts->apply_coupon( $coupon )
(class-wc-totals.php:654) $this->calculate_discounts()
(class-wc-totals.php:143) $this->calculate_item_totals()
(class-wc-totals.php:134) $this->calculate()
(class-wc-cart.php:1406) new WC_Cart_Totals( $this )
(OrderController.php:52) wc()->cart->calculate_totals()
(AbstractCartRoute.php:221) $this->order_controller->update_order_from_cart( $draft_order )
(AbstractCartRoute.php:115) $this->cart_updated( $request )
(AbstractCartRoute.php:89) get_response
```

### PR DESCRIPTION
**Pull request by mikejolley**
Store API updates draft orders on cart routes because it assumes the cart was modified. This breaks the checkout endpoint when single use coupons are applied because coupons are removed and reapplied, without freeing up usage limits.

We can adjust the checkout route to avoid updates to the cart to prevent this issue occurring.

Fixes #8446

### Testing

Use this to enable PayPal standard:

```php
add_filter( 'woocommerce_should_load_paypal_standard', '__return_true' );
```

1. Create a new coupon with any value, but set the per-user usage limit to 1
2. Add an item to the cart
3. Place an order via PayPal. Once you hit paypal you can close the window-don't pay
4. Edit the order in WP Admin
5. See if the coupons are still applied.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fixed an issue where single use coupons would not apply when checking out via the Checkout Block and Store API.

### CODE REVIEW

File: src/StoreApi/Routes/V1/AbstractCartRoute.php [hunk 1]
```diff
@@ -97,24 +97,25 @@ public function get_response( \WP_REST_Request $request ) {
...
+				$response = $this->get_route_error_response( 'woocommerce_rest_unknown_server_error', $error->getMessage(), 500 );
+			}
 		}
 
 		if ( is_wp_error( $response ) ) {
-			return $this->error_to_response( $response );
+			$response = $this->error_to_response( $response );
 		}
 
 		if ( $this->is_update_request( $request ) ) {
```
Comment (mikejolley) [inline src/StoreApi/Routes/V1/AbstractCartRoute.php:121]: This part is what we don't want to run during checkout. Checkout gets its own method without this line.

**Review by tarhi-saad — APPROVED** [review]
Great work on this PR, @mikejolley! The test was successful, and though I'm not a PHP expert, the code also seems solid. Thank you for your contribution! Feel free to 🚢 it
