### PR TITLE
Fix html in preview of product titles

### LINKED ISSUE #347: Block preview shows HTML markup in product title
**Describe the bug**
Products titles with HTML markup (i.e. `<small>` or `<em>` or `<br>`, etc...) - this markup should be escaped in the back-end preview.

As it presently is, the HTML markup is displayed in the back-end (bug), but not displayed in the front-end (correct).

### PR DESCRIPTION
**Pull request by coderkevin**
Fixes #347

Previously the html wasn't rendered in the preview for product titles.
This renders the html.

#### Accessibility

- [x] I've tested using a screen reader

### Screenshots

html-marquee-product

### How to test the changes in this Pull Request:

1. Add some HTML to a product title.
2. Preview it in any block

### CODE REVIEW

**Review by ryelle — CHANGES_REQUESTED** [review]
Looks good in the grid blocks, but Featured Product needs this change too:

screen shot 2019-02-20 at 4 19 21 pm

**Comment by ryelle** [comment]
@coderkevin Looks like it's still showing escaped HTML on the front end too, can you fix that as well?

**Comment by justinshreve** [comment]
`wp_kses_post( $product->get_name() );` should help with that and escaping properly. [example](https://github.com/woocommerce/woocommerce/blob/c726cd63c74a2f8fb76ec6536b3bbf4d13a2f9ff/templates/content-widget-product.php#L33).

**Comment by coderkevin** [comment]
I'm a little sad that `wp_kses_post` strips out `<marquee>` tags, but otherwise it works.

File: includes/blocks/class-wc-block-featured-product.php [hunk 1]
```diff
@@ -56,7 +56,7 @@ public static function render( $attributes, $content ) {
 
 		$title = sprintf(
 			'<h2 class="wc-block-featured-product__title">%s</h2>',
-			esc_html( $product->get_title() )
+			$product->get_title()
```
Comment (ryelle) [inline includes/blocks/class-wc-block-featured-product.php]: Can you add escaping here (the `wp_kses_post` should be good), or add a note if it's escaped elsewhere?

Comment (coderkevin) [reply includes/blocks/class-wc-block-featured-product.php]: Oops, I already had a local commit that added this that I thought I had pushed up. I rebased and pushed up this extra commit now.

**Review by ryelle — APPROVED** [review]
Looks good now 👍
