### PR TITLE
Select the correct inner button for the "Featured Item" button to update its url

### LINKED ISSUE #6721: Featured Items blocks don't update their inner link when the item is replaced
## Describe the bug

When the Featured Categories block is duplicated from an existing Featured Categories block, then the category changed, the duplicated block doesn't display the updated category - it retains the settings of the original block.

## To reproduce

- Create a new page on a sandbox site.
- Insert a Featured Category block and set it to some category, save.
- Key: Click to duplicate that block setting the duplicated block to another category, save.
- Publish the changes.
- Observe that the second Featured Category block links to the same as the first, did not fully apply the category change that was made in the interface.

I was able to replicate this in my test site here: https://subwoo.mystagingwebsite.com/featured-categories-test/

## Expected behavior

When the category is changed on a duplicated block, those new settings should stick.

## Screenshots

User Submitted Video: https://d.pr/i/WFsX0k+

### WordPress Environment ###

WordPress address (URL): https://gimmethegoodstuff.org
Site address (URL): https://gimmethegoodstuff.org
WC Version: 6.7.0
REST API Version: ✔ 6.7.0
WC Blocks Version: ✔ 7.8.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.20
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.38-41-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.7.0
WC Database Prefix: wp_
Total Database Size: 1354.36MB
Database Data Size: 734.49MB
Database Index Size: 619.87MB
wp_woocommerce_sessions: Data: 24.06MB + Index: 1.20MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.17MB + Index: 0.31MB + Engine InnoDB
wp_woocommerce_order_items: Data: 12.52MB + Index: 5.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 89.63MB + Index: 87.22MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 1.52MB + Index: 0.25MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 4.20MB + Index: 5.41MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.22MB + Index: 3.58MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.33MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 4.52MB + Index: 12.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 1.52MB + Index: 2.33MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.14MB + Index: 0.20MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 6.52MB + Index: 3.02MB + Engine InnoDB
wp_comments: Data: 86.61MB + Index: 50.13MB + Engine InnoDB
wp_dgwt_wcas_index: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_dgwt_wcas_invindex_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dgwt_wcas_invindex_cache_page: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dgwt_wcas_invindex_cache_post: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist: Data: 10.52MB + Index: 11.03MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist_page: Data: 0.25MB + Index: 0.25MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist_post: Data: 7.52MB + Index: 10.00MB + Engine InnoDB
wp_dgwt_wcas_invindex_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist_page: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist_post: Data: 1.52MB + Index: 1.45MB + Engine InnoDB
wp_dgwt_wcas_tax_index: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_dgwt_wcas_var_index: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
wp_dynamic_widgets: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 9.52MB + Index: 8.06MB + Engine InnoDB
wp_postmeta: Data: 229.78MB + Index: 216.61MB + Engine InnoDB
wp_posts: Data: 32.55MB + Index: 14.58MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 4.02MB + Index: 0.97MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.17MB + Index: 0.22MB + Engine InnoDB
wp_redirection_logs: Data: 0.19MB + Index: 0.05MB + Engine InnoDB
wp_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_feed_caches: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.27MB + Index: 0.38MB + Engine InnoDB
wp_terms: Data: 0.19MB + Index: 0.19MB + Engine InnoDB
wp_term_relationships: Data: 1.45MB + Index: 1.48MB + Engine InnoDB
wp_term_taxonomy: Data: 0.19MB + Index: 0.20MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 75.61MB + Index: 82.22MB + Engine InnoDB
wp_users: Data: 9.52MB + Index: 8.55MB + Engine InnoDB
wp_usps_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 2.52MB + Index: 1.97MB + Engine InnoDB
wp_wc_download_log: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.20MB + Index: 0.30MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 11.52MB + Index: 14.06MB + Engine InnoDB
wp_wc_order_stats: Data: 4.52MB + Index: 4.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.17MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.25MB + Index: 0.31MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 2.02MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_tracking_views: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpf_logging: Data: 3.52MB + Index: 0.20MB + Engine InnoDB
wp_yarpp_related_cache: Data: 0.13MB + Index: 0.19MB + Engine InnoDB
wp_yoast_indexable: Data: 64.61MB + Index: 47.22MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 3.52MB + Index: 5.55MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_yoast_seo_links: Data: 9.52MB + Index: 9.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 2.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 9374
aw_workflow: 5
bookable_resource: 1
custom_css: 2
customize_changeset: 20
nav_menu_item: 257
oembed_cache: 387
page: 48
post: 433
product: 1389
product_variation: 3270
qa_faqs: 24
revision: 141
shop_coupon: 293
shop_order: 37383
shop_order_refund: 445
shop_subscription: 876
wc_booking: 13
wp_block: 14
wp_global_styles: 2
wp_navigation: 2
wp_template: 9
wp_template_part: 3
wpcf7_contact_form: 2
wpf_cart: 82

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

FiboSearch - AJAX Search for WooCommerce (Pro): by FiboSearch Team – 1.18.0
Akismet Anti-Spam: by Automattic – 4.2.5
AutomateWoo: by WooCommerce – 5.5.17
WP Engine Smart Plugin Manager: by WP Engine – 5.10.36
Code Snippets: by Code Snippets Pro – 3.1.1
Contact Form 7: by Takayuki Miyoshi – 5.6
Custom Permalinks: by Sami Ahmed Siddiqui – 2.4.0
Klaviyo: by Klaviyo
Inc. – 3.0.3

Redirection: by John Godley – 5.2.3
SMTP Mailer: by naa986 – 1.1.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.22.14

User Switching: by John Blackbourn & contributors – 1.6.0
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.4
WooCommerce All Products For Subscriptions: by WooCommerce – 3.3.1
WooCommerce Bookings: by WooCommerce – 1.15.58
WooCommerce Checkout Add-Ons: by SkyVerge – 2.5.6
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.14.0
WooCommerce Cost of Goods: by SkyVerge – 2.11.1
Print Invoice & Delivery Notes for WooCommerce: by Tyche Softwares – 4.6.5
WooCommerce Stripe Gateway: by WooCommerce – 6.4.3
Pixel Manager for WooCommerce: by SweetCode – 1.17.11
WooCommerce Measurement Price Calculator: by SkyVerge – 3.20.1
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.25
WooCommerce PayPal Payments: by WooCommerce – 1.9.0
WooCommerce Product Bundles: by WooCommerce – 6.16.0
WooCommerce Google Product Feed: by Ademti Software Ltd. – 10.7.3
WooCommerce Quick View: by WooCommerce – 1.6.0
WooCommerce Shipment Tracking: by WooCommerce – 1.7.0
WooCommerce Subscriptions: by WooCommerce – 4.4.0
WooCommerce Waitlist: by Neil Pie – 2.3.2
WooCommerce: by Automattic – 6.7.0
Yoast SEO: by Team Yoast – 19.3
WP Fusion - Abandoned Cart Addon: by Very Good Plugins – 1.7.2
WP Fusion - Enhanced Ecommerce Addon: by Very Good Plugins – 1.18.6
WP Fusion: by Very Good Plugins – 3.40.14
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.6

YITH WooCommerce Frequently Bought Together Premium: by YITH – 1.19.0

### Inactive Plugins (2) ###

Instagram Feed Pro Personal: by Smash Balloon – 6.0.8
Toolbox for WooCommerce Subscriptions: by Shop Plugins – 1.4.24

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (6) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WPE ElasticPress Autosuggest Logger: by WP Engine – 1.0.0
WP Engine Cache Plugin: by WP Engine – 1.0.9
WP Engine Seamless Login Plugin: by WP Engine – 1.5.5
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
configurable (configurable)
downloadable (downloadable)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
virtual (virtual)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4-2)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #4 - /store/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #2318 - /about/store/

### Theme ###

Name: Twenty Twenty-Two
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce Google Product Feed feeds ###

7960d1950f2974b0: Uncategorized
  Type: google
  Category filter: only
  Categories: 2138
7ef02dfd32a56c06: Baby Gear
  Type: google
  Category filter: only
  Categories: 2137
0b2abd8e61c38351: Carpeting
  Type: google
  Category filter: only
  Categories: 2296
4a70b6b9b4297675: Consulting
  Type: google
  Category filter: only
  Categories: 2264
6870134945e35988: Red Light
  Type: google
  Category filter: only
  Categories: 2227
15aa70169e25a1dd: Toys Games Art
  Type: google
  Category filter: only
  Categories: 2089
13834d9f5cf9c91c: Dental
  Type: google
  Category filter: only
  Categories: 1414
b4fde7ac68199f3a: Feeding
  Type: google
  Category filter: only
  Categories: 1460
3f4b17d5dc9df558: Kitchen
  Type: google
  Category filter: only
  Categories: 1380
e06c915b834e6c7d: Clothing
  Type: google
  Category filter: only
  Categories: 553
1ad28873fd752b71: Diapering
  Type: google
  Category filter: only
  Categories: 732
4968f3090a449520: Gifts
  Type: google
  Category filter: only
  Categories: 757
a1b668cad70e0dcd: Bath
  Type: google
  Category filter: only
  Categories: 320
2e0926a754c2042a: Face
  Type: google
  Category filter: only
  Categories: 318
1d6a710f1d762638: Health
  Type: google
  Category filter: only
  Categories: 904
b6e3a0ec724b4e74: Pregnancy
  Type: google
  Category filter: only
  Categories: 324
431ee63c34c3992d: Radiation
  Type: google
  Category filter: only
  Categories: 960
a490fe8b08c4ad9f: Air
  Type: google
  Category filter: only
  Categories: 1020
5c8d4f68811dc3ec: Cleaning
  Type: google
  Category filter: only
  Categories: 573
7f4c6e52fb49cf81: E-books
  Type: google
  Category filter: only
  Categories: 615
d08682e78c04a202: Furniture
  Type: google
  Category filter: only
  Categories: 582
af01c04ca41eb39c: Water
  Type: google
  Category filter: only
  Categories: 572
2ec116cde7cb6d18: Pets
  Type: google
  Category filter: only
  Categories: 1273

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send "item group ID": -
Expanded schema markup: -
Debug key: c4ffd7d9-6fa2-4ec1-80ef-c6e99b532f68

### WooCommerce Google Product Feed fields ###

Title: Pre-populates from product product_title.
Product description: Variation description only
fallback to main description (full preferred)

Availability (in stock products): Defaults to "in stock".
Availability (backordered products): Defaults to "in stock".
Availability (out of stock products): Defaults to "out of stock".
Condition: Defaults to "new".
Brand: Defaults to "Gimme the Good Stuff". Pre-populates from pa_brand taxonomy.
Manufacturer Part Number (MPN): 
Product Type: Defaults to "Health & Beauty".
Google Product Category: Defaults to "Health & Beauty".
Global Trade Item Number (GTIN): 
Gender: 
Age Group: 
Colour: 
Size: 
Bing Category: Defaults to "Health & Wellness".

### WooCommerce Google Product Feed DB status ###

Database version: 15
Active database version: 15
wc_gpf_render_cache: Empty
woocommerce_gpf_google_taxonomy (en-US): 5595 items

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://gimmethegoodstuff.org
Subscription Statuses: trash: 7
wc-active: 85
wc-expired: 95
wc-pending-cancel: 7
wc-pending: 15
wc-on-hold: 437
wc-cancelled: 230

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Pennsylvania

### Subscriptions by Payment Gateway ###

other: trash: 1
wc-active: 5
wc-cancelled: 35
wc-expired: 15
wc-on-hold: 89
wc-pending: 9

Stripe: trash: 6
wc-active: 80
wc-cancelled: 195
wc-expired: 80
wc-on-hold: 347
wc-pending: 3
wc-pending-cancel: 7

### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

PayPal: refunds

### Product Bundles ###

Database Version: 6.16.0
Loopback Test: ✔
Template Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: ✔
Used PayPal Checkout plugin: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-07-18 23:54:23 -04:00
Options: ✔
Notes: 24
Onboarding: completed

### All Products for WooCommerce Subscriptions ###

Template Overrides: –

### Action Scheduler ###

Complete: 10,969
Oldest: 2022-06-17 13:53:20 -0400
Newest: 2022-07-18 13:34:19 -0400

Failed: 418
Oldest: 2017-04-26 07:04:28 -0400
Newest: 2022-07-15 10:28:02 -0400

Pending: 94
Oldest: 2022-07-18 17:05:27 -0400
Newest: 2023-07-12 18:09:23 -0400

### Status report information ###

Generated at: 2022-07-18 13:34:28 -04:00
`

### Desktop (please complete the following information):

-   OS: [e.g. macOS, Windows]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

### PR DESCRIPTION
**Pull request by albarin**
When changing the `product`/`category` of a `Featured Product`/`Featured Category` block the button URL was not updated, this PR fixes that issue by selecting the appropriate inner button block.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/6721

#### User Facing Testing

1. Create a new page and add a `Featured Product` block.
2. Edit the block and select a different product.
3. Make sure the button URL on the block is updated to the new product link.
4. Duplicate the block and change the new block to a different product.
5. Make sure the button URL on the block is updated to the new product link.
6. Repeat 1-5 for the `Featured Category` block.

### WooCommerce Visibility
* [x] WooCommerce Core
* [x] Feature plugin
* [ ] Experimental

### CODE REVIEW

File: assets/js/blocks/featured-items/with-update-button-attributes.tsx [hunk 1]
```diff
@@ -51,7 +51,7 @@ export const withUpdateButtonAttributes =
 		const Block = useSelect( ( select ) => {
```
Comment (gigitux) [inline assets/js/blocks/featured-items/with-update-button-attributes.tsx]: Is it correct that `Block` is CamelCase?

File: assets/js/blocks/featured-items/with-update-button-attributes.tsx [hunk 2]
```diff
@@ -51,7 +51,7 @@ export const withUpdateButtonAttributes =
...
 			return select( 'core/block-editor' ).getBlock( clientId );
 		} );
-		const InnerButton = Block?.innerBlocks[ 0 ];
+		const InnerButton = Block?.innerBlocks[ 0 ]?.innerBlocks[ 0 ];
```
Comment (gigitux) [inline assets/js/blocks/featured-items/with-update-button-attributes.tsx]: Same question for `InnerButton`

**Review by gigitux — APPROVED** [review]
LGTM! I just added two comments, but it's not related to the changes you did. 🚢
