### PR TITLE
Product Archive Template: Fix compatibility Layer with Product Recommendations extension

### LINKED ISSUE #8916: Product Recommendations don't display with the blockified Product Archive Template
### Description
[Product Recommendations](https://woocommerce.com/products/product-recommendations/) uses hooks to render content. Recommendations are not rendered when using blockified Product Archive Template

### Steps to reproduce
1. Install [Product Recommendations](https://woocommerce.com/products/product-recommendations/)
2. Setup Engine as per [instructions here](https://woocommerce.com/document/product-recommendations/store-owners-guide/#configuration)
Example setup:
image

4. Deploy engine in Product Archive [location](https://woocommerce.com/document/product-recommendations/store-owners-guide/#Locations)
Example setup:
image

7. Go to Editor
8. Clear the customizations for Products by Category
9. Go to Products by Category and click "Upgrade to Products block"
10. Save and go to frontend (e.g. `/product-category/clothing/`)
11. **Expected:** Recommendations are displayed at the top of archive
12. **Actual:** Only the title and description are displayed, but no products

### Screenshots
| Classic Template | Blockified Template |
|---|---|
|. Screen Shot 2023-03-31 at 11 46 09 AM |   Screen Shot 2023-03-31 at 11 44 22 AM |

### PR DESCRIPTION
**Pull request by gigitux**
This is an attempt to fix #8916. Currently, we remove all the default hooks to avoid duplicate content. With this PR, we re-add some actions necessary to display a product grid. This approach allows the Product Recommendations to display a grid on the page.

At the same time, avoiding adding actions that create conflicts with the Products block has been necessary (`permanently_removed_actions` array). 

For example, if an extension uses the `woocommerce_pagination` action, the pagination of the extension will not be rendered. Should we add a filter to allow 3rd party developers to enable those actions again? It could be the plugin's responsibility to hide duplicate content. What do you think?

Fixes #8916

#### User Facing Testing

1. Install [Product Recommendations](https://woocommerce.com/products/product-recommendations/)
2. Setup Engine as per [instructions here](https://woocommerce.com/document/product-recommendations/store-owners-guide/#configuration)
Example setup:
image

4. Deploy engine in Product Archive [location](https://woocommerce.com/document/product-recommendations/store-owners-guide/#Locations)
Example setup:
image

5. Go to Editor
6. Clear the customizations for Products by Category
7. Go to Products by Category and click "Upgrade to Products block"
8. Save and go to frontend (e.g. /product-category/clothing/)
9. Be sure that the Product Recommendations are displayed at the top of archive.
10. Test with `After Products` location.
11. Test with `No Products` location. To test this location, you have to create a category without any products and visit it.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Product Archive Template: Fix compatibility Layer with Product Recommendations extension.

### CODE REVIEW

File: src/Templates/ArchiveProductTemplatesCompatibility.php [hunk 1]
```diff
@@ -202,20 +230,28 @@ protected function set_hook_data() {
...
 			'woocommerce_before_shop_loop'            => array(
-				'block_name' => 'core/post-template',
+				'block_name' => '',
 				'position'   => 'before',
 				'hooked'     => array(
 					'woocommerce_output_all_notices' => 10,
 					'woocommerce_result_count'       => 20,
 					'woocommerce_catalog_ordering'   => 30,
 				),
+				'no_readd'   => array(
```
Comment (tjcafferkey) [inline src/Templates/ArchiveProductTemplatesCompatibility.php]: Is this a typo?

File: src/Templates/ArchiveProductTemplatesCompatibility.php [hunk 2]
```diff
@@ -202,20 +230,28 @@ protected function set_hook_data() {
...
+				),
 			),
 			'woocommerce_after_shop_loop'             => array(
-				'block_name' => 'core/post-template',
+				'block_name' => '',
 				'position'   => 'after',
 				'hooked'     => array(
 					'woocommerce_pagination' => 10,
 				),
+				'no_readd'   => array(
```
Comment (tjcafferkey) [inline src/Templates/ArchiveProductTemplatesCompatibility.php]: Is this a typo?

File: src/Templates/ArchiveProductTemplatesCompatibility.php [hunk 3]
```diff
@@ -202,20 +230,28 @@ protected function set_hook_data() {
...
 			'woocommerce_after_shop_loop'             => array(
-				'block_name' => 'core/post-template',
-				'position'   => 'after',
-				'hooked'     => array(
+				'block_name'            => '',
+				'position'              => 'after',
+				'hooked'                => array(
 					'woocommerce_pagination' => 10,
 				),
+				'not_re_addble_actions' => array(
```
Comment (tjcafferkey) [inline src/Templates/ArchiveProductTemplatesCompatibility.php]: I think a better name for this key would be `permanently_removed_actions` or `excluded_actions` and document at the top of the function what this key means for additional context:

"Actions that we do not want to re-add after they have been removed because..."

File: src/Templates/ArchiveProductTemplatesCompatibility.php [hunk 4]
```diff
@@ -202,20 +230,28 @@ protected function set_hook_data() {
...
-				'position'   => 'before',
-				'hooked'     => array(
+				'block_name'            => '',
+				'position'              => 'before',
+				'hooked'                => array(
 					'woocommerce_output_all_notices' => 10,
 					'woocommerce_result_count'       => 20,
 					'woocommerce_catalog_ordering'   => 30,
 				),
+				'not_re_addble_actions' => array(
```
Comment (tjcafferkey) [inline src/Templates/ArchiveProductTemplatesCompatibility.php]: I think a better name for this key would be `permanently_removed_actions` or `excluded_actions` and document at the top of the function what this key means for additional context:

"Actions that we do not want to re-add after they have been removed because..."

File: src/Templates/ArchiveProductTemplatesCompatibility.php [hunk 5]
```diff
@@ -13,7 +13,9 @@ class ArchiveProductTemplatesCompatibility extends AbstractTemplateCompatibility
 	/**
 	 * The custom ID of the loop item block as the replacement of the core/null block.
 	 */
-	const LOOP_ITEM_ID = 'product-loop-item';
+	const LOOP_ITEM_ID                        = 'product-loop-item';
+	const IS_LAST_BLOCK_BEFORE_PRODUCTS_BLOCK = '__wooCommerce_is_last_block_before_products_block';
```
Comment (tjcafferkey) [inline src/Templates/ArchiveProductTemplatesCompatibility.php]: This looks like it isn't used?

File: src/Templates/ArchiveProductTemplatesCompatibility.php [hunk 6]
```diff
@@ -13,7 +13,9 @@ class ArchiveProductTemplatesCompatibility extends AbstractTemplateCompatibility
...
+	const IS_FIRST_BLOCK_AFTER_PRODUCTS_BLOCK = '__wooCommerce_is_first_block_after_products_block';
```
Comment (tjcafferkey) [inline src/Templates/ArchiveProductTemplatesCompatibility.php]: This looks like it isn't used?

**Comment by tjcafferkey** [comment]
We check `$block['attrs']` a lot in the compatibility layers, and doing so means we have to check `isset()` beforehand. This makes the code quite verbose and hard to read/understand. 

Perhaps we can create a utility method on the `AbstractTemplateCompatibility.php` class to make it a bit more readable

```php
protected function check_block_atts( $block, $key, $value ) {
	if ( ! isset( $block['attrs'][ $key ] ) ) {
		return false;
	}
		
	return $block['attrs'][ $key ] === $value;
}
```

Usage:

**Before**
```php
if ( 'core/query' === $block_name && isset( $block['attrs']['namespace'] ) && 'woocommerce/product-query' === $block['attrs']['namespace'] ) {
 // ...
}
```

**After**
```php
if ( 'core/query' === $block_name && $this->check_block_atts( $block, 'namespace', 'woocommerce/product-query' ) ) {
 // ...
}
```

**Comment by tjcafferkey** [comment]
This tests well for me based on the instructions in the PR and I wasn't able to see any regressions. That said, I haven't approved yet as I've just noted a few inline questions and a recommendation to make the overall code more readable/easier to understand but I'm happy for feedback on that.

Also, is there anyone else with experience testing the compatibility layer it might be worth them casting their eyes over it also.

**Comment by gigitux** [comment]
> This tests well for me based on the instructions in the PR and I wasn't able to see any regressions. That said, I haven't approved yet as I've just noted a few inline questions and a recommendation to make the overall code more readable/easier to understand but I'm happy for feedback on that.
> 
> Also, is there anyone else with experience testing the compatibility layer it might be worth them casting their eyes over it also.

Thanks for the review! I addressed your feedback! @xristos3490, could you take a look at this PR?

I noticed a different behavior between Classic Template and the blockified one. We inject the `woocommerce_before_shop_loop` and `woocommerce_after_shop_loop` hooks even if any products are displayed. I created a dedicated issue #9463. 


| Classic Template | Blockified template |
|--------|--------|
|image|image|

**Comment by gigitux** [comment]
I fixed the issue above (https://github.com/woocommerce/woocommerce-blocks/issues/9463) via https://github.com/woocommerce/woocommerce-blocks/pull/9464.

File: src/Templates/ArchiveProductTemplatesCompatibility.php [hunk 7]
```diff
@@ -96,25 +122,47 @@ function( $hook ) {
...
+			/**
+			 * `core/query-no-result` is a special case because it can return two
+			 * different content depending on the context. We need to check if the
+			 * block content is empty to determine if we need to inject hooks.
+			 */
+			if ( empty( trim( $block_content ) ) ) {
+				return $block_content;
+			}
+
+			$block_hooks = array_filter(
```
Comment (xristos3490) [inline src/Templates/ArchiveProductTemplatesCompatibility.php]: It seems this logic is duplicated [here](https://github.com/woocommerce/woocommerce-blocks/pull/9452/files#diff-67e968b526ce5d483df5b3830c9e2519b0adff6a3801648efa025d23d733d2b6R125). Perhaps we could avoid it?

**Review by xristos3490 — COMMENTED** [review]
Product recommendations gets rendered on the "Before products" and "After products" location, corrently! 

I cannot see the "No Products Found" list, tho. Does the `wc_no_products_found` hook get restored? 🤔

File: src/Templates/ArchiveProductTemplatesCompatibility.php (hunk 7 above)
Comment (gigitux) [reply src/Templates/ArchiveProductTemplatesCompatibility.php]: Fixed with c80555e2216dfd62599d03388aecb24cf43d9494

**Comment by gigitux** [comment]
> Product recommendations gets rendered on the "Before products" and "After products" location, corrently!
> 
> I cannot see the "No Products Found" list, tho. Does the `wc_no_products_found` hook get restored? 🤔

I noticed that the testing instructions for the "No products" location weren't clear. I updated them:

```
Test with No Products location. To test this location, you have to create a category without any products and visit it.
```

**Review by xristos3490 — APPROVED** [review]
Everything looks good! 

> Should we add a filter to allow 3rd party developers to enable those actions again? It could be the plugin's responsibility to hide duplicate content. What do you think?

As discussed, if we get any reports from people utilizing the `permanently_removed_actions`, then we can reiterate. It's actually a really rare condition where one would use the legacy loop template parts in a custom product grid when the Products block exists on the _same_ page, and all of these are happening in the _archive_ context.
