### PR TITLE
Filter by Rating Block > Display a notice in the editor if the store has no products with ratings

### LINKED ISSUE #7735: Filter by Rating block should show a notice in the editor if the store has no products with ratings
## Describe the bug

If the store has no reviews with ratings, the Filter by Rating block shows no controls in the editor, making it feel broken. Instead, we should display a notice.

## To reproduce

1. Make sure your store doesn't have any rating.
2. Add the Filter by Rating block.
3. Notice in the editor the heading is displayed, but not the controls.

## Expected behavior

If the store has no reviews, we should display a notice, similar to the one in the Filter by Attribute block:
imatge

## Screenshots

imatge

### PR DESCRIPTION
**Pull request by nefeline**
Fixes #7735

This PR ensures a notice is displayed in the editor whenever the Filter by Rating block is used in a store that has no products with ratings. 

Additionally, per @vivialice's [recommendation](https://github.com/woocommerce/woocommerce-blocks/pull/7763#issuecomment-1337163691), we are now allowing users to preview/update the content, settings, and color for the filter even when the store doesn't have any ratings yet:

| Before | After |
| ------ | ----- |
|  Screenshot 2022-11-28 at 09 22 36  |  Screenshot 2022-12-08 at 12 55 11 |

#### User Facing Testing

1. Make sure your store doesn't have any products with ratings. 
2. Open the editor and add a Filter by Rating block.
3. Make sure a notice is displayed informing there are no products with ratings available, as demonstrated on the screenshot shared here on this PR. Also, ensure the dummy list with default product ratings is displayed below the notice.
4. Now, add a rating to any product in your store.
5. Refresh the editor and make sure the notice is replaced with the expected value:

Screenshot 2022-11-28 at 09 41 39

6. On the front end, ensure the filter by rating works as expected and without any changes.

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> A notice is now displayed in the editor whenever the Filter by Rating block is used in a store that has no products with ratings. Additionally, users can now preview/update the content, settings, and color for the filter even when the store doesn't have any ratings yet.

### CODE REVIEW

**Comment by nefeline** [comment]
Hey @vivialice! Would you please give feedback regarding the copy used here? "There are no products with ratings." is the one currently in use. Thanks!

**Comment by nefeline** [comment]
A note about e2e tests: while working on this issue, I noticed all e2e tests for the filter by rating block (among others) are temporarily disabled ( ref. https://github.com/woocommerce/woocommerce-blocks/issues/7744 ). For now, I'm not adding any tests to cover this new notice, but opening a separate issue to do so as soon as the tests are up and running again.

File: assets/js/blocks/rating-filter/block.tsx [hunk 1]
```diff
@@ -4,6 +4,7 @@
 import { __, sprintf } from '@wordpress/i18n';
 import { speak } from '@wordpress/a11y';
 import Rating from '@woocommerce/base-components/product-rating';
+import { Notice } from '@wordpress/components';
```
Comment (dinhtungdu) [inline assets/js/blocks/rating-filter/block.tsx]: For components that load on the front end, we should use `wordpress-components` instead of `@wordpress/components`.

File: assets/js/blocks/rating-filter/block.tsx [hunk 2]
```diff
@@ -272,6 +273,19 @@ const RatingFilterBlock = ( {
 		[ checked ]
 	);
 
+	if ( isEditor && ! isDisabled && displayedOptions.length === 0 ) {
+		return (
+			<Notice status="warning" isDismissible={ false }>
+				<p>
+					{ __(
+						'There are no products with ratings.',
```
Comment (dinhtungdu) [inline assets/js/blocks/rating-filter/block.tsx]: I think we can be more explicit to merchants here by mentioning that the block won't display on the front end until their store has reviews.

**Review by dinhtungdu — COMMENTED** [review]
Thanks so much for the PR! It's testing well on my end 🎉 . I left a couple of suggestions but otherwise, this is LGTM.

File: assets/js/blocks/rating-filter/block.tsx (hunk 1 above)
Comment (nefeline) [reply assets/js/blocks/rating-filter/block.tsx]: Updated! Thanks for the heads up and also for sharing more details about the reason why we are keeping both dependencies in place.

The context for anyone else following this convo: The newer version of `@wordpress/components` has a performance impact on WooCommerce Blocks, as it includes libraries that increase the bundle size significantly. For this reason, we are relying on `wordpress-components` for now.

File: assets/js/blocks/rating-filter/block.tsx (hunk 2 above)
Comment (nefeline) [reply assets/js/blocks/rating-filter/block.tsx]: Yeah, that's a good call: in fact, I believe we could be more explicit about this on other blocks as well, such as the Filter Attributes. Already tagged @vivialice here earlier: looking forward to hearing her thoughts about this copy.

**Comment by vivialice** [comment]
Hey @nefeline ! Thanks for tagging me in this. I agree with @dinhtungdu, the store not currently having reviews doesn't mean they should feel like they should remove the block so I have a suggestion for improved copy: 

 `Your store doesn't have any products with ratings yet. This filter option will display when a product receives a review.`

Additionally, even if the store doesn't have any ratings I don't think we should hide the UI from them. **I think we should display the notice and an example for the rating checklist as default.** Right now there aren't styling settings available but eventually the user should be able to define these even if their store doesn't have ratings. (eg scenario - brand new store.)

**Comment by nefeline** [comment]
Thanks @vivialice !

> Additionally, even if the store doesn't have any ratings I don't think we should hide the UI from them. I think we should display the notice and an example for the rating checklist as default.

Great call! Just to confirm that we are on the same page, is the following screenshot a correct representation of what you are envisioning here, allowing users to preview/update the content, settings, and color for the filter even when the store doesn't have any ratings yet?

Screenshot 2022-12-05 at 17 55 47

**Comment by vivialice** [comment]
Yes, that's correct 👍  

Just to check, is the vertical spacing between each filter option the same as the other lists? 

And I just noticed another thing! The block name should just be `Filter by Rating`. And the description should be `Enable customers to filter products by their rating.` (as we aren't using the word "grid" to describe multi-product layouts anymore)

**Comment by nefeline** [comment]
> Yes, that's correct 👍

Awesome, thanks for confirming! The component was updated to match this new scope. Additionally, the PR description and testing instructions were updated to match the expected design.

> Just to check, is the vertical spacing between each filter option the same as the other lists?

It looks like we have an extra margin-bottom just for the `.wc-block-components-product-rating`, so when comparing this component with others, such as the filter by attribute block, the spacing differs. If I remove the margin-bottom we end up with something like this:

| Before | After |
| ------ | ----- |
|  Screenshot 2022-12-08 at 13 50 06 | Screenshot 2022-12-08 at 13 49 48
 
Let me know what you think should be the new default here then I'll go ahead and update it ;)

> And I just noticed another thing! The block name should just be Filter by Rating. And the description should be Enable customers to filter products by their rating. (as we aren't using the word "grid" to describe multi-product layouts anymore)

Good call! I'm going ahead and opening a separate PR for this since this one is focusing on the notice.

File: assets/js/blocks/rating-filter/preview.tsx [hunk 3]
```diff
@@ -61,3 +61,26 @@ export const previewOptions = [
...
+	},
+	{
+		rating: 2,
+		count: 1,
+	},
+	{
+		rating: 1,
+		count: 1,
+	},
+];
```
Comment (dinhtungdu) [inline assets/js/blocks/rating-filter/preview.tsx]: Instead of creating a new variable, can we reuse the `previewOptions` above?

File: assets/js/blocks/rating-filter/block.tsx [hunk 4]
```diff
@@ -272,7 +278,11 @@ const RatingFilterBlock = ( {
 		[ checked ]
 	);
 
-	if ( ! filteredCountsLoading && displayedOptions.length === 0 ) {
+	if (
+		! isEditor &&
```
Comment (dinhtungdu) [inline assets/js/blocks/rating-filter/block.tsx]: Why do we need to check for `isEditor` here? In the editor, the `displayedOptions` will be set to preview data if the store has no ratings, so I don't think we need to check for `isEditor`.

File: assets/js/blocks/rating-filter/block.tsx [hunk 5]
```diff
@@ -189,12 +190,16 @@ const RatingFilterBlock = ( {
...
+		const defaultPreviewCounts = isEditor ? editorPreviewOptions : [];
+
 		const orderedRatings =
 			! filteredCountsLoading &&
 			objectHasProp( filteredCounts, 'rating_counts' ) &&
-			Array.isArray( filteredCounts.rating_counts )
+			Array.isArray( filteredCounts.rating_counts ) &&
+			filteredCounts.rating_counts.length > 0
 				? [ ...filteredCounts.rating_counts ].reverse()
-				: [];
```
Comment (dinhtungdu) [inline assets/js/blocks/rating-filter/block.tsx]: I commented on the `preview.tsx` file but want to explain it more here, I think we can reuse the `previewOptions` here by setting the `displayedOptions` to `previewOptions` if the `orderedRatings` is empty (inside the Editor only). We will need another state to track if the store has rating or not to display the notice.

I think by doing so, we can reuse more code and make this PR smaller.

**Review by dinhtungdu — COMMENTED** [review]
Hey @nefeline, the PR is testing well on my end, thanks for your updates! I have some questions about code reuse, please see the review comments for more details.

File: assets/js/blocks/rating-filter/preview.tsx (hunk 3 above)
Comment (nefeline) [reply assets/js/blocks/rating-filter/preview.tsx]: Yes, we can: I initially kept them separated in case we wanted to display different content on preview mode x the editor, but since at this point they don't differ, I've adopted your suggestion here and consolidated both 👍

File: assets/js/blocks/rating-filter/block.tsx (hunk 5 above)
Comment (nefeline) [reply assets/js/blocks/rating-filter/block.tsx]: Makes sense: as mentioned in [my response](https://github.com/woocommerce/woocommerce-blocks/pull/7763#discussion_r1045549717) on the `preview.tsx` file, I initially kept them separated in case we wanted to display different content on preview mode x the editor, but since at this point they don't differ, I've adopted your suggestion here and consolidated both

File: assets/js/blocks/rating-filter/block.tsx (hunk 4 above)
Comment (nefeline) [reply assets/js/blocks/rating-filter/block.tsx]: True that. Earlier I was exploring a different approach for displaying the notice (where the `displayedOptions` wasn't being set to preview data), that's the reason why it was introduced in the first place: updated.

**Comment by nefeline** [comment]
> the PR is testing well on my end, thanks for your updates! I have some questions about code reuse, please see the review comments for more details.

Thanks for the review @dinhtungdu 🙌 ! I initially kept preview mode x editorPreview mode separated in case we wanted to display different content on both, but considering they don't differ atm, I went ahead and adopted the consolidated approach as suggested.

**Review by dinhtungdu — APPROVED** [review]
Thank you so much for your great updates! This is LGTM! 🚀

**Comment by nefeline** [comment]
Thanks again @dinhtungdu 🎉 !

Regarding the vertical spacing between each filter option previously discussed [here](https://github.com/woocommerce/woocommerce-blocks/pull/7763#issuecomment-1342694306):  @vivialice please let me know what you think. IMO, it makes sense for us to ditch the pre-existing margin-bottom for this block and ensure spacing is consistent with other lists: depending on our decision I'll go ahead and open a separate PR to update it if needed 👍 .
