### PR TITLE
Use cart item key instead of index in shipping items

### LINKED ISSUE #8074: item Keys mismatch in cart items & Shipping_rates Object causing 409 error
## Describe the bug

items in cart become invalid when the key of items available in `cart.Shipping_rates[0].items` object and `cart.Items ` differ. this Difference make the item keys invalid since API verifies based on item keys available in shipping_rates Object.

image

## To reproduce

this Behaviour is very tricky. When i add an item in cart then the key of newly added item matches both in shipping_rates Object and Items object as in snap-1. But after some time the item key under main Items object changes. Since all updates are being done based on main Items key in case of mismatch in both keys 409 error is thrown since shipping_rates's item key is only valid key as per snap-2

snap-1
image
snap-2
image

## Expected behavior

if somehow due to change in item , Key is invalidated then both keys remain same.

### WordPress (please complete the following information):

-   WordPress version: [e.g. 5.9]
-   Gutenberg version (if installed): 9
-   WooCommerce version: 7.2.2
-   WooCommerce Blocks version: [e.g. 9.2.0]
-   Site language:PHP
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: chrome

### PR DESCRIPTION
**Pull request by senadir**
In Shipping response, we include an items array, the key in that array was the index of an item, I switched to be the key instead.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/8074

### Testing

1. Add an item to Cart
2. In console, check the network request
3. Match cart.items[].key with shipping_rates[].items[].key, they should match.

* [x] Do not include in the Testing Notes

### CODE REVIEW

File: src/StoreApi/Schemas/V1/CartShippingRateSchema.php [hunk 1]
```diff
@@ -262,7 +262,7 @@ protected function prepare_package_items_response( $package ) {
 		$items = array();
 		foreach ( $package['contents'] as $item_id => $values ) {
```
Comment (wavvves) [inline src/StoreApi/Schemas/V1/CartShippingRateSchema.php]:
```suggestion
		foreach ( $package['contents'] as $values ) {
```

**Review by opr — APPROVED** [review]
When Paulo's suggestion is applied this will be good to go!
