### PR TITLE
Unset default customer state if it doesn't match country

### LINKED ISSUE #8455: "Invalid state" notice shows up before selecting a state
## Describe the bug

In v9.6.0, if:
- there is a default country/state in the checkout and,
- I select a new country, 

then the pre-existing default state is validated against the new country selection and an error shows up: 

https://user-images.githubusercontent.com/25955483/219342793-deeb57e1-8d21-403d-82c3-f94490d6bdc2.mp4

## To reproduce

1. Set US/California as the default shipping destination.
2. Add a product to the cart.
3. Go to the checkout page. 
4. Select a different Shipping Country that has states, e.g. Greece.
5. Fill in the city field.
6. Try to select a state -- an error shows up.

## Expected behavior

I would expect that my state selection would be validated after I selected a new state.

### PR DESCRIPTION
**Pull request by senadir**
WooCommerce core has the option to set customer default country and state to store country and state. This seems to cause a problem in which if you select a different country, it will still try to get the store state and validate against it, this PR clear up the store state when that happens.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/8455

### Testing

1. Set US/California as the default shipping destination.
2. Add a product to the cart.
3. Go to the checkout page. 
4. Select a different Shipping Country that has states, e.g. Greece.
5. Fill in the city field.
6. You should not get a error.
7. Checkout without setting the state.
8. In the admin, you should not see California as the state.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix cases in which Checkout would validate customer coutnry against the wrong state.

### CODE REVIEW

**Review by tarhi-saad — APPROVED** [review]
The user-facing testing did pass successfully! Maybe a second pair of eyes can check the code too. Then we will be good to go!

File: src/StoreApi/Routes/V1/CartUpdateCustomer.php [hunk 1]
```diff
@@ -215,16 +216,23 @@ protected function get_route_post_response( \WP_REST_Request $request ) {
 	 * @return array
 	 */
 	protected function get_customer_billing_address( \WC_Customer $customer ) {
+		$validation_util = new ValidationUtils();
+		$billing_country = $customer->get_billing_country();
+		$billing_state   = $customer->get_billing_state();
+
+		if ( ! $validation_util->validate_state( $billing_state, $billing_country ) ) {
```
Comment (mikejolley) [inline src/StoreApi/Routes/V1/CartUpdateCustomer.php:229]: We need an inline comment here explaining the need for this fix/why core breaks things. Otherwise we'll definitely forget.

File: src/StoreApi/Utilities/ValidationUtils.php [hunk 2]
```diff
@@ -0,0 +1,64 @@
+<?php
+namespace Automattic\WooCommerce\StoreApi\Utilities;
+
+use \Exception;
+use Automattic\WooCommerce\StoreApi\Exceptions\RouteException;
```
Comment (mikejolley) [inline src/StoreApi/Utilities/ValidationUtils.php]: This is unused I think?

**Review by opr — APPROVED** [review]
Looks good, tests well too. Thanks!

File: src/StoreApi/Utilities/ValidationUtils.php [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+ * Helper class which validates and update customer info.
+ */
+class ValidationUtils {
+	/**
+	 * Get list of states for a country.
+	 *
+	 * @param string $country Country code.
+	 * @return array Array of state names indexed by state keys.
+	 */
+	public function get_states_for_country( $country ) {
```
Comment (mikejolley) [inline src/StoreApi/Utilities/ValidationUtils.php:15]: This doesn't appear to be used publicly, only within this class. Can you confirm and change to `protected`?

File: src/StoreApi/Schemas/V1/AbstractAddressSchema.php [hunk 4]
```diff
@@ -95,64 +99,12 @@ public function sanitize_callback( $address, $request, $param ) {
...
 		return $address;
 	}
 
-	/**
-	 * Get list of states for a country.
-	 *
-	 * @param string $country Country code.
-	 * @return array Array of state names indexed by state keys.
-	 */
-	protected function get_states_for_country( $country ) {
```
Comment (mikejolley) [inline src/StoreApi/Schemas/V1/AbstractAddressSchema.php:110]: This is used in `AbstractAddressSchema`. Removing it will break that implementation. TBF this method doens't really do much so feel free to just move the code inline to remove the need for the util in that class.

File: src/StoreApi/Utilities/ValidationUtils.php [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+		return $country ? array_filter( (array) \wc()->countries->get_states( $country ) ) : [];
```
Comment (mikejolley) [inline src/StoreApi/Utilities/ValidationUtils.php:16]: If we're keeping this method just for the context of this class, you might be able to move the `wc_strtoupper` part here too to avoid repetition below.

**Review by mikejolley — CHANGES_REQUESTED** [review]
One bug relating to a moved method and some other feedback. Prefer the validation util over the previous util 👍🏻

File: src/StoreApi/Utilities/ValidationUtils.php (hunk 3 above)
Comment (senadir) [reply src/StoreApi/Utilities/ValidationUtils.php:15]: It's now used in AbstractAddressSchema so we can move it inline in both functions or just leave it public?

File: src/StoreApi/Utilities/ValidationUtils.php (hunk 5 above)
Comment (senadir) [reply src/StoreApi/Utilities/ValidationUtils.php:16]: Done

File: src/StoreApi/Utilities/ValidationUtils.php (hunk 3 above)
Comment (mikejolley) [reply src/StoreApi/Utilities/ValidationUtils.php:15]: Leave it if it's easier public.

File: src/StoreApi/Utilities/ValidationUtils.php [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+	 * @param string $state State name or code (sanitized).
+	 * @param string $country Country code.
+	 * @return string
+	 */
+	public function format_state( $state, $country ) {
+		$states = $this->get_states_for_country( $country );
+
+		if ( count( $states ) ) {
+			$state        = \wc_strtoupper( $state );
+			$state_values = array_map( 'wc_strtoupper', array_flip( array_map( '\wc_strtoupper', $states ) ) );
```
Comment (mikejolley) [inline src/StoreApi/Utilities/ValidationUtils.php]:
```suggestion
			$state_values = array_map( '\wc_strtoupper', array_flip( array_map( '\wc_strtoupper', $states ) ) );
```

**Review by mikejolley — APPROVED** [review]
One suggestion then should be ok. Will need tests in a follow up.
