### PR TITLE
Fix: Handle taxes for local pickup shipping

### LINKED ISSUE #6480: Wrong 'Tax' value when using the 'Local pickup' shipping method
## Describe the bug

> Check [the comment below](https://github.com/woocommerce/woocommerce-blocks/issues/6480#issuecomment-1146221671) for the correct bug description and steps to reproduce
> TL;DR: This isn't a bug related to the [WCS&T](https://woocommerce.com/document/woocommerce-shipping-and-tax/) plugin. It's related to calculating the tax when selecting the local pickup shipping method.
> 
> Note: The taxes should be based on the base store location by default and not the customer's address when selecting the local pickup shipping method.
> 
> The current behavior in C&C Blocks:
> 
> Selecting the local pickup shipping method displays the correct tax value.
> After placing an order from the Checkout Block, the tax is not calculated (or the tax related to the customer address is used instead if it was set up) on the Order received page and in WP admin under Edit Order.
> So, on the C&C blocks, we are displaying the correct tax (i.e., based on the store address) when using the local pickup shipping method. But, after placing an order through the Checkout Block, we are sending the wrong tax (i.e., The tax based on the customer address).

When using the following setup, there is an issue with calculating tax for an order. The issue is that the tax is displayed throughout the checkout until the "Order received" page it is missing from.

When visiting the Edit Order page, the tax name is there but the tax is not applied to the order.

This issue is not present when using the shortcode.

## To reproduce

1. Set up a site using WC 6.5.1 and WC Blocks 7.6.0.
2. Add the Cart block and Checkout block to the respective pages (this is essential) and remove the shortcode.
3. In shipping options, add "Flat rate" for $10 and "Local pickup" for free.
4. Enable automated taxes in settings.
5. Payment options: add Cash on delivery.
6. Set store address to: `123 Test Street, 90210 Beverly Hills, CA, USA`.
7. Add a physical product to the cart.
8. Check out using the following address: `60 29th Street #343, 94110 San Francisco, CA, USA`.
9. Select Local pickup.
10. Note how on the cart and checkout pages the tax rate is present.
11. Complete the order.
12. See tax rate of $0.00 applied on the **Order received** page and in WP admin under **Edit Order**.

## Expected behavior

Tax rate is applied to the created order and displayed on the **Order received** page.

### PR DESCRIPTION
**Pull request by senadir**
This PR fixes an issue in which taxes are calculated against the user address for local pickups orders. A niche issue, but an important one.

Fixes #6480

### Why did this issue happen in Store API

Shortcode Checkout has a function called `process_checkout` that handles submitting an order, that functions passes `$_POST` data around, it also creates an order just when you finish an order. Store API can't that function, because we can't support `$_POST` via a rest api, and because we create an order early on.

For this purpose, Store API has its own `process_checkout` function, the `get_route_post_response` function of /checkout route.

WooCommerce Shortcode also calculates the order totals using `wc()->cart->calculate_totals` it then copies that result to the created order.

Store API augments the order with all correct informations, than calls `WC_Order::calculate_totals`.

The issue here is that those two functions are slightly different, exactly around how they calculate taxes.

The cart version decides on what address it should calculate taxes using the `WC_Customer::get_taxable_address` function.

The order version uses `WC_Abstract_Order::get_tax_location`.

The problem stems from the fact that `WC_Customer::get_taxable_address` checks if the cart has local pickup selected (in which it defaults to `base` location), but `WC_Abstract_Order::get_tax_location` doesn't do any of that, and just checks the value of `woocommerce_tax_based_on` setting.

This is a long standing issue, that is simply hard to discover because most Checkout block users. who have local pickup probably have their customers locations in the same place as the shop, so the taxes are the same.

Good news is that @iamdharmesh discovered the same issue from WooCommerce Admin side and fixed the issue in WooCommerce core https://github.com/woocommerce/woocommerce/pull/33330, the fix will land in **WooCommerce Core 6.8.0** which is still 3 months away for us (we do L-1 for WC core when we can).

This PR does a workaround by calling `WC_Customer::get_taxable_address` instead, and we should remove it once WC Core 6.8.0 is the min version.

#### User Facing Testing

1. Set store address to `123 Test Street, 90210 Beverly Hills, CA, USA`
3. Enable taxes
4. Add a `"Standard" tax rates` in US, CA. Set it to: `10%`
5. Add the following shipping methods: "Flat rate" for $10 and "Local pickup" for free.
6. Add a payment option (e.g., Cash on delivery).
7. Add a physical product to the cart.
8. Use an outside state address on the front-end. (e.g., `60 29th Street #343, 35005 birmingham, AL, USA`)
9. Go to the Cart block and select the `Local pickup` shipping method. Check that we have a tax of 10% applied.
10. Go to the Checkout block and select the `Local pickup` shipping method. Check that we have a tax of 10% applied.
11. Place your order. Check on the `Order received` page that the displayed tax **is actually added to the total.**
12. Go to `Edit Order`. Check that taxes were **applied correctly there as well.**
13. On Checkout again, select flat rate, using the same external address, and make sure taxes are not applied.

### Changelog

> Fix: Correctly calculacte taxes for local pickups.

### CODE REVIEW

File: src/StoreApi/Utilities/OrderController.php [hunk 1]
```diff
@@ -44,6 +44,9 @@ public function create_order_from_cart() {
 	 * @param \WC_Order $order The order object to update.
 	 */
 	public function update_order_from_cart( \WC_Order $order ) {
+		// Ensures Local pickups are accounted for.
+		add_filter( 'woocommerce_order_get_tax_location', array( $this, 'handle_local_pickup_taxes' ) );
```
Comment (senadir) [inline src/StoreApi/Utilities/OrderController.php:48]: We want to limit where we call this logic, this function matters because this is where we call `calculate_totals`.

File: src/StoreApi/Utilities/OrderController.php [hunk 2]
```diff
@@ -434,6 +437,23 @@ public function default_order_status() {
...
+	 */
+	public function handle_local_pickup_taxes( $location ) {
+		$customer = wc()->customer;
+
+		if ( ! empty( $customer ) ) {
+			return $customer->get_taxable_address();
+		}
+
+		return $location;
+	}
```
Comment (senadir) [inline src/StoreApi/Utilities/OrderController.php:456]: `get_tax_location` has a filter in which we're using. In this case, we check if we have a user (we always do at the submit point) and get the address from there (which accounts for local pickup).

**Review by nielslange — APPROVED** [review]
LGTM! ⛴

**Review by tarhi-saad — APPROVED** [review]
Thank you, @senadir, for fixing the local pickup tax calculation bug! You've done an excellent job! I've done multiple tests, including the above user-facing test, and all passed successfully! 🎉 So, it's looking good to me. I think we can ship it. But, please, @nielslange, if you can look into this as well, it would be fantastic! 🙌

EDIT:

Thank you, @nielslange, for looking into this PR!! I will merge it.
