### PR TITLE
Fix: Convert Active Filters Block codebase to TypeScript

### LINKED ISSUE #6494: Convert Active Filters Block codebase to TypeScript

### PR DESCRIPTION
**Pull request by dinhtungdu**
Fixes #6494 

This PR converts the codebase of the Active Filters block to TypeScript. This also adds some type guards for attribute, stock and rating query state.

#### Accessibility

- [ ] I've tested using only a keyboard (no mouse)
- [ ] I've tested using a screen reader
- [ ] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
- [ ] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

#### Other Checks

- [ ] This PR adds/removes a feature flag & I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md) .
- [ ] This PR adds/removes an experimental interfaces and I've updated [this doc](../docs/blocks/feature-flags-and-experimental-interfaces.md)
- [ ] I tagged two reviewers because this PR makes queries to the database or I think it might have some security impact.

### Screenshots

N/A
#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests

#### User Facing Testing

Ensure no regression after the conversion.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [ ] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Performance Impact

N/A
### Changelog

N/A

### CODE REVIEW

**Comment by dinhtungdu** [comment]
Note that among the filter blocks, only `<AttributeFilterBlock>` uses `@wordpress/components`. This PR updates the Filter Products by Attribute block to import from `wordpress-components` instead of `@wordpress/components` as part of #5611.

File: assets/js/types/type-defs/stock-status.ts [hunk 1]
```diff
@@ -0,0 +1,5 @@
+export type StockStatus = 'instock' | 'outofstock' | 'onbackorder';
+
+export type stockStatusOptions = {
```
Comment (gigitux) [inline assets/js/types/type-defs/stock-status.ts]: I guess that it is a typo

```suggestion
export type StockStatusOptions = {
```

File: assets/js/blocks/active-filters/block.tsx [hunk 2]
```diff
@@ -51,30 +61,38 @@ const ActiveFiltersBlock = ( {
 	const [ minPrice, setMinPrice ] = useQueryStateByKey( 'min_price' );
 	const [ maxPrice, setMaxPrice ] = useQueryStateByKey( 'max_price' );
 
-	const STOCK_STATUS_OPTIONS = getSetting( 'stockStatusOptions', [] );
+	const STOCK_STATUS_OPTIONS = getSetting< stockStatusOptions >(
```
Comment (gigitux) [inline assets/js/blocks/active-filters/block.tsx]: This is a suggestion, feel free to skip :)

It would be cool if we will use `getSettingWithCoercion` util. You need to create a type guard for the type `StockStatusOptions`. If the type guard will return true, it will use the settings, otherwise, you will pass a fallback (in this case an empty array). In this way:
- we avoid the casting.
- we have validation at runtime, so less potential errors.

**Review by gigitux — CHANGES_REQUESTED** [review]

**Review by gigitux — APPROVED** [review]
Great work! There is a typo and there is a suggestion, but feel to free to skip :) 

I'm pre-approving the PR 👍

File: assets/js/blocks/active-filters/block.tsx (hunk 2 above)
Comment (dinhtungdu) [reply assets/js/blocks/active-filters/block.tsx]: > This is a suggestion, feel free to skip :)

No, this makes a lot of sense to me. Thanks so much! I applied your suggestion in [d3041a7](https://github.com/woocommerce/woocommerce-blocks/pull/6580/commits/d3041a70525144b58f038612ddac341f5e61c0bb)

File: assets/js/types/type-defs/stock-status.ts (hunk 1 above)
Comment (dinhtungdu) [reply assets/js/types/type-defs/stock-status.ts]: It is. Thanks for spotting it!

File: assets/js/blocks/active-filters/block.tsx (hunk 2 above)
Comment (gigitux) [reply assets/js/blocks/active-filters/block.tsx]: Mmm, you need to replace `getSetting` with [`getSettingsWithCoercion`](https://github.com/woocommerce/woocommerce-blocks/blob/841cd4b6e3b89ae9d25f0d9f58864c8370ee9927/assets/js/settings/shared/utils.ts/#L28-L35) too.

**Comment by dinhtungdu** [comment]
@gigitux E2E tests went so weird this time. I tried to fix some but looks like I will need more time. So I will move on with other tasks in the project and come back to fix this later. I tested and didn't find any regression. Can you please do another manual test so I can merge this one after that?

**Comment by dinhtungdu** [comment]
Merged with 1/2 passing E2E tests workflow.
