### PR TITLE
Mini Cart: Add font size and font family controls

### LINKED ISSUE #6254: Add typography style controls to the Mini Cart block
We would like to allow merchants to set a custom font size and font family for the Mini Cart button block:

Mini Cart button screenshot in the editor

## To reproduce

1. Install a block theme (ie: TT2) and go to Appearance > Editor.
2. Add the Mini Cart block to your header.
3. Try to change the font size or font family of the button.
4. Notice it's not possible.

## Expected behavior

It should be possible to set a custom font size and font family for the button.

### PR DESCRIPTION
**Pull request by danieldudzic**
This PR adds support for Typography options: `Font size` and `Font family` for the `Mini Cart` block.

Fixes #6254 

### Screenshots
|Before|After|
|-|-|
|before_now|after_now|

### Testing
How to test the changes in this Pull Request:

1. Activate a **block** theme, like Twenty Twenty Two
2. Create a new page, and add the Mini Cart block
3. Check if the `Typography` option is available for the block
4. Check if the `Font size` and `Font family` options work correctly both in the editor and on the frontend

2b. After testing the above, try the same with the Mini Cart block added via the FSE editor (for example in the header)

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [ ] Unit tests
  * [ ] E2E tests
  
### User Facing Testing
These are steps for user testing (where "user" is someone interacting with this change that is not editing any code).
* [ ] Same as above

### Changelog

> Add support for `Font size` and `Font family` for the `Mini Cart` block.

### CODE REVIEW

File: assets/js/hooks/style-attributes.ts [hunk 1]
```diff
@@ -65,7 +65,7 @@ export const useTypographyProps = ( attributes: unknown ): WithStyle => {
 			lineHeight: typography.lineHeight,
 			fontWeight: typography.fontWeight,
 			textTransform: typography.textTransform,
-			fontFamily: attributesObject.fontFamily,
+			fontFamily: attributesObject.attributes.fontFamily,
```
Comment (gigitux) [inline assets/js/hooks/style-attributes.ts]: I guess that can we revert this change, right?

File: assets/js/blocks/mini-cart/index.tsx [hunk 2]
```diff
@@ -33,6 +33,10 @@ const settings: BlockConfiguration = {
 		html: false,
 		multiple: false,
 		color: true,
+		typography: {
+			fontSize: true,
+			__experimentalFontFamily: true,
```
Comment (gigitux) [inline assets/js/blocks/mini-cart/index.tsx]: The experimental feature should be enabled only for the featuring plugin. We can do it, in this way:
```suggestion
				...( isFeaturePluginBuild() && {
				__experimentalFontFamily: true,
			} ),
```

**Review by gigitux — CHANGES_REQUESTED** [review]
Good job! Just two tiny comments! 💪

File: assets/js/blocks/mini-cart/index.tsx (hunk 2 above)
Comment (danieldudzic) [reply assets/js/blocks/mini-cart/index.tsx]: Hmm, this actually broke the block. It would no longer show on the list of blocks 🤔

Comment (gigitux) [reply assets/js/blocks/mini-cart/index.tsx]: Mmm, strange. Did you import the function?

Comment (danieldudzic) [reply assets/js/blocks/mini-cart/index.tsx]: Yup. Forgot about the import! :)

**Review by gigitux — APPROVED** [review]
LGTM :shipit:
