### PR TITLE
Products block: tax_query should be calculated only if __woocommerceAttributes is valid

### LINKED ISSUE #8765: ProductQuery->update_rest_query() overwrite tax_query of wp rest request
## Describe the bug

I've been having problems with the rest api of a website using woocommerce. In this website i've made a custom infinite scroll of the product, by category to easily navigate it. 

Problem is, now, Wordpress return over 600 products per categories (categories where there are 20 products max)

I've been digging and found that Automattic\WooCommerce\Blocks\BlockTypes\ProductQuery->update_rest_query() was the culprit. 

this is hooked on rest_product_query, and modify the query, but overrides the "tax_query" parameters. So all my categories fetch return all the products, 

## To reproduce

1. On the front end do a js fetch with the product_cat= parameters
2. receive the result of the query with product not even in this category.

## Expected behavior

The function should not overwrite the tax query, or the hook should only be added for your blocks and not the general rest api.

### WordPress (please complete the following information):

-   WordPress version: 6.1.1
-   Gutenberg version (if installed):
-   WooCommerce version: 7.5.0
-   WooCommerce Blocks version: 9.6.5
-   Site language: fr_CA

### Desktop (please complete the following information):

-   OS:  Windows
-   Browser   firefox
-   Version 111

### PR DESCRIPTION
**Pull request by imanish003**
I've added a check to calculate `$tax_query` only if a valid `__woocommerceAttributes` attribute is present, which resolves issue #8765.

```
$tax_query        = $is_valid_attributes ? $this->merge_tax_queries( $attributes_query, $visibility_query ) : [];
```

Additionally, I've refactored the update_rest_query method in the ProductQuery.php file to enhance code readability. This involves simplifying conditional expressions with variables and using ternary operators to streamline logic.

Fixes #8765 

### Testing
1. Create a new post.
2. Add a Products block to the post.
3. Save and publish the post.
4. In the Editor, open the browser console and run the following code:
```
const fetchProducts = () => {
    const paths = [
        "/wp/v2/product?per_page=100",
        "/wp/v2/product?per_page=100&product_cat=20",
    ];

    Promise.all(paths.map(async path => {
        return new Promise((resolve, reject) => {
            wp.apiFetch({path: path})
            .then(products => {
                resolve({
                    query: path,
                    products: products.map(product => {
                        return {name: product.title.rendered, category: product.product_cat.join(',')};
                    })
                });
            });
        });
    })).then(output => {
        console.log(output);
    });
}
fetchProducts();
```
5. After executing the code above, you will receive an array. Verify that:
     1. The first item in the array contains all the products.
     2. The second item in the array includes only items with the specified category ID, which is `20` in the code above. If you don't have any products with `product_cat=20`, feel free to change the category ID. 
6. Switch to the `trunk` branch and repeat steps 4 and 5. Due to the bug, you will observe that both array items contain all products, meaning that `product_cat=20` won't work for the second query path ("/wp/v2/product?per_page=100&product_cat=20").

* [X] Do not include in the Testing Notes 

### WooCommerce Visibility

* [X] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix: tax_query should be calculated only if __woocommerceAttributes is valid

### CODE REVIEW

File: src/BlockTypes/ProductQuery.php [hunk 1]
```diff
@@ -135,16 +135,19 @@ private function merge_tax_queries( ...$queries ) {
...
-		$woo_stock_status = $request->get_param( '__woocommerceStockStatus' );
-		$on_sale_query    = $request->get_param( '__woocommerceOnSale' ) === 'true' ? $this->get_on_sale_products_query() : array();
-		$orderby_query    = isset( $orderby ) ? $this->get_custom_orderby_query( $orderby ) : array();
-		$attributes_query = is_array( $woo_attributes ) ? $this->get_product_attributes_query( $woo_attributes ) : array();
-		$stock_query      = is_array( $woo_stock_status ) ? $this->get_stock_status_query( $woo_stock_status ) : array();
-		$visibility_query = $this->get_product_visibility_query( $stock_query );
-		$tax_query        = $this->merge_tax_queries( $attributes_query, $visibility_query );
+	public function update_rest_query( $args, $request ): array {
+		$woo_attributes      = $request->get_param( '__woocommerceAttributes' );
+		$is_valid_attributes = is_array( $woo_attributes );
```
Comment (Aljullu) [inline src/BlockTypes/ProductQuery.php:140]: Could we return early at this point? Ie:

```PHP
if ( ! is_array( $woo_attributes ) ) {
  return $args;
}
```

**Review by Aljullu — APPROVED** [review]
Code looks good and it's testing as described, so approving. :rocket:  I only left one comment inline about returning early. Besides that, I see there is no changelog entry in the PR, is that intentional? I think this change might be worth mentioning in the changelog.

File: src/BlockTypes/ProductQuery.php (hunk 1 above)
Comment (imanish003) [reply src/BlockTypes/ProductQuery.php:140]: > Besides that, I see there is no changelog entry in the PR, is that intentional? I think this change might be worth mentioning in the changelog.

To be honest, I wasn't completely certain if this needed a changelog entry. However, I've now added one just in case. 🙂

Comment (imanish003) [reply src/BlockTypes/ProductQuery.php:140]: > Could we return early at this point? Ie:

I considered adding an early return, but I realized we are using three attributes:
- __woocommerceStockStatus
- __woocommerceAttributes
- __woocommerceStockStatus

What if __woocommerceAttributes is null, but the other attributes have correct values? I wanted to avoid this corner case. However, I'm not certain if this situation will ever occur. 🤷🏻‍♂️

Comment (Aljullu) [reply src/BlockTypes/ProductQuery.php:140]: Oh, right, I didn't think that `__woocommerceAttributes` could be undefined while the other could be defined. :sweat_smile:

Comment (imanish003) [reply src/BlockTypes/ProductQuery.php:140]: @Aljullu In my opinion, let's maintain the current implementation for now so we can release the fix. If necessary, I can revisit and make adjustments later. Does that sounds good to you? 🙂

Comment (Aljullu) [reply src/BlockTypes/ProductQuery.php:140]: Sure thing!
