### PR TITLE
Product Gallery: Add a Product Image fallback

### LINKED ISSUE #11940: Product Gallery: Address the edge case when Product Image is not set but Product gallery images are
## Describe the bug

Currently in the following situation:
Edit_product_“Beanie_with_Logo”_‹_newproductgallery_—_WordPress

The Product Gallery block will:
- Hide the Thumbnails
- Still output the Next/Previous Buttons and the Pager
- The first Large Image image will be blank

RMMeTuyymN

## To reproduce

1. With a block theme, open `Appearance > Editor`.
2. Open `Templates > Single Product`.
3. Select `Convert to Blocks` if you are using the Classic Templates.
4. Add the `Product Gallery` block.
5. Edit a product and make sure the Product Image is not set but some Product gallery images are.
6. Notice the broken behavior on the front end.

### PR DESCRIPTION
**Pull request by danieldudzic**
## What

Fixes #11940

## Why

This PR introduces a fallback for scenarios where the Product Image is not set, but some Product Gallery images are present. In such cases, a placeholder image will be displayed as the first image in the Product Gallery.

## Testing Instructions

_Please consider any edge cases this change may have, and also other areas of the product this may impact._

1. With a block theme, open `Appearance > Editor`.
2. Open `Templates > Single Product`.
3. Add the `Product Gallery` block.
5. Open a product page on the frontend with multiple product images set in the product gallery, but **no main Product Image set**. Confirm that the Product Gallery works as expected (Thumbnails, Next Previous Buttons and Pager) and that the first image is correctly set to the placeholder image.

* [x] Do not include in the Testing Notes 
* [ ] Should be tested by the development team exclusively 

## Screenshots or screencast

| Before | After |
| ------ | ----- |
|Moto_Guzzi_v7_–_newproductgallery-4|Moto_Guzzi_v7_–_newproductgallery-3|

## WooCommerce Visibility

Required:

* [ ] WooCommerce Core
* [ ] Feature plugin
* [x] Experimental
* [ ] N/A

## Checklist

Required:

* [x] This PR has either a `[type]` label or a `[skip-changelog]` label.
* [x] This PR is assigned to a milestone.

Conditional:

* [ ] This PR has a UI change and has been cross-browser tested at different viewport sizes on both the frontend and in the editor.
* [ ] This PR has a changelog description (if `[skip-changelog]` label is not present).
* [ ] This PR adds/removes a feature flag & I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR adds/removes an experimental interfaces, and I've updated [this doc](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/blocks/feature-flags-and-experimental-interfaces.md).
* [ ] This PR has been accessibility tested.
* [ ] This PR has had any necessary documentation added/updated.

## Changelog

> Add suggested changelog entry here.

### CODE REVIEW

File: src/BlockTypes/ProductGallery.php [hunk 1]
```diff
@@ -121,12 +121,13 @@ protected function render( $attributes, $content, $block ) {
...
-		$dialog               = isset( $attributes['mode'] ) && 'full' !== $attributes['mode'] ? $this->render_dialog() : '';
-		$post_id              = $block->context['postId'] ?? '';
-		$product              = wc_get_product( $post_id );
-		$product_id           = strval( $product->get_id() );
+		$number_of_thumbnails           = $block->attributes['thumbnailsNumberOfThumbnails'] ?? 0;
+		$classname                      = $attributes['className'] ?? '';
+		$dialog                         = isset( $attributes['mode'] ) && 'full' !== $attributes['mode'] ? $this->render_dialog() : '';
+		$post_id                        = $block->context['postId'] ?? '';
+		$product                        = wc_get_product( $post_id );
+		$product_gallery_first_image_id = reset( ProductGalleryUtils::get_product_gallery_image_ids( $product, 1 ) );
```
Comment (roykho) [inline src/BlockTypes/ProductGallery.php]: `ProductGalleryUtils::get_product_gallery_image_ids( $product, 1 )` has to be assigned to a variable first before using `reset()` on it otherwise you will get "pass by reference warning".

File: src/Utils/ProductGalleryUtils.php [hunk 2]
```diff
@@ -33,17 +33,21 @@ public static function get_product_gallery_images( $post_id, $size = 'full', $at
 				$size = $crop_images ? self::CROP_IMAGE_SIZE_NAME : $size;
 
 				foreach ( $all_product_gallery_image_ids as $product_gallery_image_id ) {
-					if ( $crop_images ) {
-						self::maybe_generate_intermediate_image( $product_gallery_image_id, self::CROP_IMAGE_SIZE_NAME );
+					if ( '0' !== $product_gallery_image_id ) {
```
Comment (roykho) [inline src/Utils/ProductGalleryUtils.php:36]: With this change, it would mean the cropping function won't work for the default placeholder image. I think we need to also account for the placeholder image because it is possible for store owners to use their own which may or may not be a square size.

File: src/Utils/ProductGalleryUtils.php [hunk 3]
```diff
@@ -33,17 +33,21 @@ public static function get_product_gallery_images( $post_id, $size = 'full', $at
...
+						}
+
+						$product_image_html = wp_get_attachment_image(
+							$product_gallery_image_id,
+							$size,
+							false,
+							$attributes
+						);
+					} else {
+						$product_image_html = self::get_product_image_placeholder_html( $attributes );
```
Comment (roykho) [inline src/Utils/ProductGalleryUtils.php:48]: Instead of creating our own function here perhaps use what's already available from WC core. `wc_placeholder_img( 'full', $attributes );`

**Review by roykho — CHANGES_REQUESTED** [review]

File: src/Utils/ProductGalleryUtils.php (hunk 3 above)
Comment (danieldudzic) [reply src/Utils/ProductGalleryUtils.php:48]: I have considered using the core placeholder, but in pdnLyh-4Hz-p2 @jarekmorawski mentioned something regarding updating the placeholder illustrations for images to be more on-brand. So I'm assuming we'd like to have control over the placeholder image.

@jarekmorawski I'd appreciate your thoughts on this.

File: src/Utils/ProductGalleryUtils.php (hunk 2 above)
Comment (danieldudzic) [reply src/Utils/ProductGalleryUtils.php:36]: I think this is a bit of an edge case, at this point, so not high priority (IMO).
We'd also have to then implement a custom cropping function as we wouldn't be able rely on `maybe_generate_intermediate_image`.

**Review by roykho — APPROVED** [review]
The changes look good. Approving but please create a follow up issue to convert all blocks to use WC core placeholder utils function.
