### PR TITLE
Fix price filter for products when stored prices do not match displayed prices (tax settings)

### LINKED ISSUE #1492: Price filter doesn't filter products based on their price with taxes
**To Reproduce**
1. Go to _WooCommerce_ > _Settings_ > _Tax_ > _Display prices in the shop_ and select _Including Tax_. You might need to create tax rates if you hadn't done it before.
2. Create a post with an _All Products_ block and a _Price Filter_.
3. In the frontend use the price slider to select a narrow price range and notice prices are filtered as if they were not showing the tax rate.

**Screenshots & Expected behavior**
imatge
If I select a price range of 15-16 I wouldn't expect products which are 16,5 and 17,6 (notice I have a tax rate of 10%, so they real prices are 15 and 16, that's why they are appearing).

imatge
In this case, I would expect to see the album but not the cap.

### PR DESCRIPTION
**Pull request by mikejolley**
This PR adds support to the price filter block for filtering by displayed prices, which may or may not include or exclude taxes.

The problem occurs when the price display setting (including or excluding tax) differs from the price entered setting (prices input including or excluding tax). Since the values in the database are used for the filtering, the displayed prices may not match up with the price filter.

See https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1492 for instructions on replicating the issue.

Fixes #1492

To summarise what is happening here:

- We know the prices stored in the database must be used for filtering. We cannot dynamically calculate taxes for each product for the filtering.
- If the prices stored do not match the prices displayed, we know we need to add special handling for price filters.
- If we assume the min and max price filter is entered either including or excluding tax, matching the prices shown in the store, we can adjust the filters themselves to match how prices are stored in the database.
- Since products can have different tax amounts depending on `tax class`, we need to apply a different filter per tax class in order to accurately match prices.

**For each tax class we adjust the price filter by either adding or removing tax from it, so it matches prices stored in the database.** 

To prevent costly meta table joins, I added 2 new columns to the product lookup table (tax status, tax class) in this core PR: https://github.com/woocommerce/woocommerce/pull/25428. The fix in this PR won't apply until this is merged to core. There is detection for this so the PR can still be merged to master without side-effects.

### How to test the changes in this Pull Request:

**Pre-requisites:**

1. You need to be running the branch in this core PR https://github.com/woocommerce/woocommerce/pull/25428
2. Follow the steps in https://github.com/woocommerce/woocommerce/pull/25428 to ensure your lookup tables are current

**Testing:**

- Try the test case in https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1492
- In WooCommerce > Settings > Taxes, **choose to enter prices inclusive of tax, but display prices excluding tax.** Test that filters work on products.
- In WooCommerce > Settings > Taxes, **choose to enter prices exclusive of tax, but display prices including tax.** Test that filters work on products.

### Changelog

> Fix price filtering when stored prices do not match displayed prices (determined by tax settings). This fix will apply once WooCommerce 3.10 is released.

### CODE REVIEW

File: src/RestApi/StoreApi/Utilities/ProductQuery.php [hunk 1]
```diff
@@ -288,43 +283,143 @@ public function add_query_clauses( $args, $wp_query ) {
...
+			$or_queries[]          = $wpdb->prepare(
+				'( wc_product_meta_lookup.tax_class = %s AND wc_product_meta_lookup.`' . esc_sql( $column ) . '` ' . esc_sql( $operator ) . ' %f )',
+				$tax_class,
+				$adjusted_price_filter
+			);
+		}
+		// phpcs:disable WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQL.NotPrepared
+		return $wpdb->prepare(
+			' AND (
+				wc_product_meta_lookup.tax_status = "taxable" AND ( 0=1 OR ' . implode( ' OR ', $or_queries ) . ')
```
[the remark this answers is not in the document]
Comment (mikejolley) [reply src/RestApi/StoreApi/Utilities/ProductQuery.php]: Added a check 👍

**Comment by mikejolley** [comment]
Thanks @Aljullu Who else has experience for 2nd pass :)? @nerrad

File: src/RestApi/StoreApi/Utilities/ProductQuery.php [hunk 2]
```diff
@@ -288,43 +283,148 @@ public function add_query_clauses( $args, $wp_query ) {
...
+
+		// We need to adjust the filter for each possible tax class and combine the queries into one.
+		foreach ( $product_tax_classes as $tax_class ) {
+			$adjusted_price_filter = $this->adjust_price_filter_for_tax_class( $price_filter, $tax_class );
+			$or_queries[]          = $wpdb->prepare(
+				'( wc_product_meta_lookup.tax_class = %s AND wc_product_meta_lookup.`' . esc_sql( $column ) . '` ' . esc_sql( $operator ) . ' %f )',
+				$tax_class,
+				$adjusted_price_filter
+			);
+		}
```
Comment (nerrad) [inline src/RestApi/StoreApi/Utilities/ProductQuery.php]: Clever! I was wondering how we'd account for products with different tax classes (or non taxable). So essentially this just ensures that we include the correct min/max amount for products in each registered tax class for the query right?

Comment (mikejolley) [reply src/RestApi/StoreApi/Utilities/ProductQuery.php]: Exactly!

**Comment by mikejolley** [comment]
> This seems like something that should surface as a dev note (likely accompanying the pull in WC core?)

I've referenced this in the other PR.

> Are there any changes in here that would be good to apply to logic in Woo core to expose this logic for use by extensions? Would there be value in introducing ProductQuery as a core api (or do you think that's something that we should hold off on until it has more real time usage under its belt).

It feels fairly niche at the moment. Core widgets could benefit from this handling when the core PR I put in is accepted but testing it in blocks would be wise IMO in case I've missed something.

> It'd be good to see test coverage for the new methods and behaviour (maybe as a followup?)

I was looking at the public methods and unit tests for this would be tricky. We could compare queries but I feel some form of e2e would probably work better so we can test correct prices are displayed for matched products?

If you're happy with the latest change this can be merged I think. Just bare in mind it won't do anything until core implements the lookup table :)
