### PR TITLE
Prevent double triggering select shipping on the same rate

### LINKED ISSUE #8485: Shipping rates mounting can override fields
## Describe the bug

You can sometimes end up overriding existing fields when shipping rates mount for the first time or return a new set of rates.

## To reproduce

1. Set a default location (say US/CA)
2. Add shipping rates to another country (say Greece)
3. On Checkout, you should not see any shipping rates.
4. Fill out your info fine.
5. Once you fill out the country, start filling the city immediately after it.
6. As you fill the country, the client will push, you get shipping rates.
7. Once shipping rates mount, they will trigger a `select-shipping-rate` which will return with server data.
8. Your city (or any field you filled between shipping mounting and now) will be gone.

## Expected behavior

- Fields should not be cleared.

### PR DESCRIPTION
**Pull request by senadir**
Shipping Rates components would trigger a redundant select call on mount, that call would also cause some data entered between the event start and end to be lost.

This PR prevents the redundant select from firing and would return early if the rate you're trying to select is alreay selected.

This does not fix the issue of the useEffect firing twice, unfrountantly I went into a deep rabbit hole,[ with resulted in me removing the local state](https://github.com/woocommerce/woocommerce-blocks/pull/8497/files/152787f033288c9d78dc59f2b16720f49bf13048) and updating the data store directly which I believe is better ([as you shouldn't have a component be controlled and uncontrolled](https://beta.reactjs.org/learn/sharing-state-between-components#controlled-and-uncontrolled-components) at the same time). That was a much better solution but ended up complicating the reducer with the switch logic.

This is something that we might revisit again in the future if needed.

Fixes https://github.com/woocommerce/woocommerce-blocks/issues/8485

### Testing

1. Set your default country to something like US/CA
2. Enable Local Pickup and add 2 locations to it.
3. In your Shipping zones, set shipping for Greece
4. Open Checkout, it should load on Local Pickup selected.
5. Change to regular shipping
6. Change country to Greece and set a city
7. Your City value should persist
8. Switch back to local pickup, it should be selected.
9. Switch back to regular shipping, it should work.

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix an issue in which setting the city/state would not persist in the first time for certain customers.

### CODE REVIEW

File: assets/js/data/cart/actions.ts [hunk 1]
```diff
@@ -384,7 +386,26 @@ export const changeCartItemQuantity =
...
+				( shippingPackage: CartShippingRate ) =>
+					shippingPackage.package_id === packageId
+			)
+			?.shipping_rates.find(
+				( rate: CartShippingPackageShippingRate ) =>
+					rate.selected === true
+			);
+		if ( selectedShippingRate?.rate_id === rateId ) {
+			return;
+		}
```
Comment (senadir) [inline assets/js/data/cart/actions.ts:408]: shipping rate is unique per package

**Review by nielslange — APPROVED** [review]
Pre-approving this PR as it works as expected. I just noticed a minor design flaw. When the shipping location is Greece, the Shipping and Local Pickup selectors have an equal height:
Screenshot 2023-02-24 at 10 48 08

However, when the shipping location is apart from Greece, the two selectors have an unequal height:
Screenshot 2023-02-24 at 10 49 00

I wonder if we should have `<span class="wc-block-checkout__shipping-method-option-price">&nbsp;</span>` within the Local Pickup selector if there's no price. This would lead to the following result:
Screenshot 2023-02-24 at 10 52 32

cc: @elizaan36
