### PR TITLE
Fix image editor in Featured Product/Category blocks on WP 6.2

### LINKED ISSUE #9100: Feature product: JS error when clicking on `Edit product image`
## Describe the bug

When trying to edit the feature product image by clicking on the `Edit product image` button in the toolbar, we get a JS error in the console and the block breaks.

## To reproduce

With WordPress 6.2
1. Create a new page or post.
2. Add a `Feature Product` block.
3. Click on the `Edit product image` button on the toolbar.
Screenshot 2023-04-19 at 12 51 15
4. See the error on the console and on the block editor.
Screenshot 2023-04-19 at 12 52 00
Screenshot 2023-04-19 at 12 52 07

## Expected behavior

There's no error and the block image can be edited.

## Additional context

I tried it with WordPress 6.1 and it works fine. It also happens in the `Feature category` block, since they share the code.

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #9100.

The issue was caused because we were using a Gutenberg component which is no longer available in WP 6.2 (`ImageEditingProvider`), this PR refactors the code so it works without that component.

#### User Facing Testing

0. With WP 6.2:
1. Create a post and add the Featured Category block.
2. Click on the button to edit the image (note: this button is only available if the category has an image, if you don't have any categories with images, go to `wp-admin` > Products > Categories and edit a category to add an image):
imatge
3. Make some changes (rotate, zoom, change aspect ratio, etc.) and apply them.
4. Verify the changes are applied and there are no errors in the browser devtools console (you can open it with <kbd>F12</kbd>).
5. Repeat all the steps above with the Featured Product block.
6. Repeat all steps above with WP 6.1 (you can use [WP Downgrade](https://wordpress.org/plugins/wp-downgrade/)).

* [ ] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### Changelog

> Fix image editor in Featured Product/Category blocks on WP 6.2.

### CODE REVIEW

File: assets/js/blocks/featured-items/image-editor.tsx [hunk 1]
```diff
@@ -45,24 +46,70 @@ type WithImageEditorProps< T extends EditorBlock< T > > =
...
 	backgroundImageSize,
 	backgroundImageSrc,
+	containerRef,
 	isEditingImage,
 	setAttributes,
 	setIsEditingImage,
 }: ImageEditorProps ) => {
-	return (
-		<>
+	const clientWidth = useClientWidth( containerRef, [ align ] );
```
Comment (kmanijak) [inline assets/js/blocks/featured-items/image-editor.tsx:107]: This function could be moved below the fallback for WP 6.1. In that case we don't new to attach the event listeners and make all the computations that happen in scope of `useClientWidth`. What do you think?

**Review by kmanijak — APPROVED** [review]
It works and no errors/warnings are thrown on 6.2 and neither 6.1 👍 

I left one comment with potential improvement, but still pre-approving.

Also, I spotted that the edited (zoomed) image is actually cropped (top image: edited, bottom image: untouched). But I checked and it behaved like that before those changes, so maybe that's expected and definitely, it's not in the scope of this PR.
image

File: assets/js/blocks/featured-items/image-editor.tsx (hunk 1 above)
Comment (Aljullu) [reply assets/js/blocks/featured-items/image-editor.tsx:107]: I don't think we can because it's a React hook so it can't be called conditionally:

https://legacy.reactjs.org/docs/hooks-rules.html

**Comment by Aljullu** [comment]
Thanks for the review, @kmanijak!

> Also, I spotted that the edited (zoomed) image is actually cropped (top image: edited, bottom image: untouched). But I checked and it behaved like that before those changes, so maybe that's expected and definitely, it's not in the scope of this PR.

Good catch! That's because the block has a separate _Image Fit_ option.

imatge

Setting it to _Cover_ makes it expand to the entire available space. I agree that's confusing, but I'm not sure how we could improve it. :thinking:

File: assets/js/blocks/featured-items/image-editor.tsx (hunk 1 above)
Comment (kmanijak) [reply assets/js/blocks/featured-items/image-editor.tsx:107]: Oh, of course. Missed that! 👍
