### PR TITLE
Mini Cart Block and related blocks: now the additional classes are visible on frontend page

### LINKED ISSUE #5881: Mini Cart block: additional classes don't add on the frontend side
## Describe the bug

The addition classes don't render on the frontend side.

## To reproduce

1. Open the FSE editor.
2. Add the Mini Cart block.
3. Get focused on it.
4. On the right sidebar, on the block -> advanced section, add custom classes.
5. Save.
6. On the frontend page, inspect the Mini Cart Block.
7. The custom classes aren't added.

## Expected behavior

The custom classes should be added on the frontend side

## Screenshots
image

### PR DESCRIPTION
**Pull request by gigitux**
With this PR, the additional classes added on the editor side are now rendered on the frontend side.
This PR fixes the scrollbar issue when there are too many products.

Fixes #5881 

### Manual Testing

How to test the changes in this Pull Request:
Check out this branch:

#### Classname problem

1. Open the FSE editor.
2. Add the Mini Cart block.
3. Get focused on it.
4. On the right sidebar, on the block settings -> advanced section, add custom classes.
5. Save.
6. On the frontend page, inspect the Mini Cart Block element.
7. Check that the custom classes are added.
8. Open the FSE editor.
9. Open Mini Cart template editor.
10. Repeat 3-7 steps for each block in the template ( `Mini Cart Contents`, `Filled Mini Cart Contents`, `Mini Cart Title`, `Mini Cart Items`, `Mini Cart Products Table`, `Mini Cart Footer`,  `Empty Mini Cart Contents`, `Mini Cart Shopping Button`)

#### Scrollbar issue
1. Open the FSE editor.
2. Add the Mini Cart block.
3. Save.
4. On the frontend side, add a lot of products to the cart.
5. Open the Mini Cart Block and check that the scroll works well (check the attached gif to see the potential issue).

Screen Capture on 2022-03-03 at 12-08-40

### CODE REVIEW

File: assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx [hunk 1]
```diff
@@ -3,18 +3,22 @@
...
+	className,
+}: FilledMiniCartContentsBlockProps ): JSX.Element | null => {
 	const { cartItems } = useStoreCart();
 
 	if ( cartItems.length === 0 ) {
 		return null;
 	}
 
-	return <>{ children }</>;
+	return <div className={ className }>{ children }</div>;
```
Comment (Aljullu) [inline assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx:21]: For blocks that didn't have any kind of markup like this one, I wonder if instead of adding support for custom class names, maybe we should just set [`supports: { customClassName: false }`](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#customclassname). If users want to add custom class names to be able to add styles, they can still add them to the block which render some markup. What do you think?

**Review by Aljullu — APPROVED** [review]
LGTM, good job adding support for custom class names in all those blocks. :clap: 

I left one question, but besides that, pre-approving.

File: assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx (hunk 1 above)
Comment (gigitux) [reply assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx:21]: Mmmm, good point!


The problem that I see is that the HTML (attached image) generated is different from [the declared template](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/87ccbddfa06bcd5bd0d7fd5398bf201ac6705c55/templates/parts/mini-cart.html#L4). From my experience it seems that every block should have a wrapper.

image

Comment (dinhtungdu) [reply assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx:21]: > If users want to add custom class names to be able to add styles, they can still add them to the block which render some markup.

This approach sounds good to me too. Filled and Empty Mini Cart Contents blocks are always inside the Mini Cart Contents block. Users can add custom classes there to target inner blocks.

Comment (gigitux) [reply assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx:21]: > The problem that I see is that the HTML (attached image) generated is different from [the declared template](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/87ccbddfa06bcd5bd0d7fd5398bf201ac6705c55/templates/parts/mini-cart.html#L4). From my experience it seems that every block should have a wrapper.

What about this? I guess that now, the Gutenberg team is [adding more APIs for container block](https://github.com/WordPress/gutenberg/issues/27324), I prefer to keep the wrapper, in this way we:
- are consistent with the template.
- are future proof, since if we want to add support for the new API from Gutenberg we already have the wrapper (I guess no migration).
- follow the standard (I'm not sure about this point, but as I said above, it seems that every block has a dedicated wrapper).

Comment (Aljullu) [reply assets/js/blocks/cart-checkout/mini-cart-contents/inner-blocks/filled-mini-cart-contents-block/frontend.tsx:21]: Good points. Honestly, I don't have a strong opinion on this, but agree that it makes sense keeping it consistent with other blocks that also have a wrapper div and allow a custom class name. So :shipit: from my side.
