### PR TITLE
Throw an exception if there is no selected shipping method on an item…

### LINKED ISSUE #4705: Order can still be placed when no shipping options are available
## Describe the bug
Order can still be placed when no shipping options are available

## To reproduce
1. Create 2 shipping zones, one with a specific postal/zip code but no shipping method. The second add a country wide catch all with a standard local pickup shipping method.
2. At check out select postal/zip code for 1st shipping zone - no shipping option is displayed, clicking Place Order proceeds.

3. Additional observation: when the postal/zip code is entered in 2. above, the order summary displays ' Shipping $0 via' (i.e. no shipping method listed) followed by the postal/zip code address entered even though shipping there is not allowed.

## Expected behavior
Should stop order being created if no shipping method available

## Environment
* Core version: 5.8.0
* WooCommerce version: 5.6.0
* WooCommerce Blocks version: 5.8.0

### PR DESCRIPTION
**Pull request by tjcafferkey**
### Description

Throw an exception if there is a shipping method required and one isn't selected at the time of placing an order.

Fixes https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4705

#### Automated Tests
* [x] Changes in this PR are covered by Automated Tests.
  * [x] Unit tests
  * [ ] E2E tests
### Manual Testing

How to test the changes in this Pull Request:

1. Set a shipping zone in a country of your choice
2. Add a physical product to your cart and enter a country that **isn't covered** by the shipping zone
3. Clicking "Place Order" should throw an exception which should be displayed in the checkout, whilst preventing you from placing an order.

### Changelog

> Checkout: Throw an exception if there is a shipping method required and one isn't selected at the time of placing an order.

### CODE REVIEW

File: src/StoreApi/Utilities/OrderController.php [hunk 1]
```diff
@@ -406,6 +410,30 @@ protected function validate_coupon_usage_limit( \WC_Coupon $coupon, \WC_Order $o
...
+	public function validate_selected_shipping_methods( $needs_shipping, $chosen_shipping_methods = array() ) {
+		if ( ! $needs_shipping || ! is_array( $chosen_shipping_methods ) ) {
+			return;
+		}
+
+		foreach ( $chosen_shipping_methods as $chosen_shipping_method ) {
+			if ( false === $chosen_shipping_method ) {
+				throw new RouteException(
+					'woocommerce_rest_invalid_shipping_option',
+					__( 'Sorry, this order requires a shipping option', 'woo-gutenberg-products-block' ),
```
Comment (Aljullu) [inline src/StoreApi/Utilities/OrderController.php]: We usually end error messages with a period:
```suggestion
					__( 'Sorry, this order requires a shipping option.', 'woo-gutenberg-products-block' ),
```

File: tests/php/StoreApi/Routes/ControllerTestCase.php [hunk 2]
```diff
@@ -1,6 +1,6 @@
 <?php
 /**
- * OrderController Tests.
+ * ControllerTestCase Tests.
```
Comment (Aljullu) [inline tests/php/StoreApi/Routes/ControllerTestCase.php:3]: :clap:

**Review by Aljullu — APPROVED** [review]
Nice fix! Left a minor comment about the error message not ending with a period, but this is good to go. :shipit:
