### PR TITLE
All Products: fix 'Add to Cart' in IE11

### LINKED ISSUE #1641: All Products block displays an error when adding a product to the Cart in IE11
**To Reproduce**
1. Create a post with the _All Products_ block and open it with IE 11.
2. Add a product to your cart.
3. Notice the error boundary component is shown and there is an error in the console.

**Screenshots**
imatge

The line that is causing the crash seems to be this one:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/atomic/components/product/button/index.js#L130

Might be related to this:

https://developer.mozilla.org/en-US/docs/Web/API/Event/Event#Browser_compatibility

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #1641.

### Screenshots

GIF of the error (without this PR):
Peek 2020-01-23 17-10

### How to test the changes in this Pull Request:
1. Create a post with the _All Products_ block and open it with IE 11.
2. Add a product to your cart.
3. Verify everything is working as expected (the block doesn't crash, it doesn't show an error in the console, etc.).

### Changelog

> Fix error with the All Products block and Internet Explorer 11 when adding products to the cart.

### CODE REVIEW

File: assets/js/atomic/components/product/button/index.js [hunk 1]
```diff
@@ -125,8 +125,8 @@ const ProductButton = ( { product, className } ) => {
 			firstMount.current = false;
 			return;
 		}
-		// Test if we have our Event defined
-		if ( Object.entries( Event ).length !== 0 ) {
+		// In IE, Event is an object and can't be instantiated with `new Event()`.
+		if ( typeof Event === 'function' ) {
```
Comment (nerrad) [inline assets/js/atomic/components/product/button/index.js]: Fix looks fine, but I wonder if we should just default the Event fallback (around line 84) to `null` instead of an empty object too?

Comment (Aljullu) [reply assets/js/atomic/components/product/button/index.js]: Sounds good. Done in e2007514d3513f89d85c863ba5d6c51a8e97288e.
