### PR TITLE
Fix/you do not need lodash

### LINKED ISSUE #8642: Remove lodash dependency from frontend scripts
As Gutenberg is moving away from lodash (https://github.com/WordPress/gutenberg/issues/17025), we should do the same with WC Blocks scripts. At least, with scripts loaded in the frontend, so we avoid loading lodash, which is a heavy dependency, when our blocks are rendered in the frontend.

In addition to that, we should add an ESLint rule to make sure we don't introduce new usages of lodash. Gutenberg has one that we can use as a reference:

https://github.com/WordPress/gutenberg/blob/e72bc18ce7d62bed1d9514e73f5c17631bf7ed07/.eslintrc.js#L45

### PR DESCRIPTION
**Pull request by mikejolley**
This PR removes all usage of `lodash` dependency and replaces lodash functions with native functions, or alternative packages, where possible.

Since this touched a number of files, it will be easier to review each commit separately since I did it function by function and the commits are small. You can mark these off it it helps with the review. 

- [ ] `without` 56ed6ae1900676a20b8dfe13bb8acfa4fb3bf5e1
- [ ] `isNumber` ebec4bc0cd521f3a4b1abedcfd22b9115b21ef28
- [ ] `difference` 380fedbbd7cf60d65ff3fef77811db426b94c8b8
- [ ] `isEmpty` a8dda6ec4d42dbf5b7ce88106555003ea4c65ff5 and e1055c19c07c50f9b8ffc344a29a5c7d6ac1a0eb
- [ ] `isObject` d3cd772316b103796dd0e9e2eefe65c18269bb38
- [ ] `noop` 3d518359bac211bb8da59bf7aafe4eb0aa4c0de9
- [ ] `clamp` 6c43bb4d15c6d7c5dc979bf59573d3c4bee9231f
- [ ] `uniqueId` aae32f2ac297584f5c076b222dd0438b4769d447
- [ ] `range` e4f77e5a69f7f9919c522ec8ca92cc2b40170b97
- [ ] `has` 96faef9855bed57c5615396c2660bba023bebc03
- [ ] `omitBy` afad1d6f220391203cbb3b2609a3ac5397b3b311
- [ ] `isEqual` be07aeee1ee64eb0f0e8aefc9113aa9ddd63d2ec
- [ ] `kebabCase` 2e91696fdd485994dfaf0b3c4f3d89d44041c464
- [ ] `camelCase` f466acc4f1985fc3b771f1d3482690e006007b0a
- [ ] `snakeCase` c10bb11303c7690258962105f7d2f405dc3358f7
- [ ] `keyby` 12e5ab6bf8b466146e0e76327d531ed4c3522236
- [ ] `pick` 8e3bb60527707eec1c9de472a3c87155103b7b4a
- [ ] `cloneDeep` 8bebf8848adf7ae187dd6a1ec2d699bd12929882
- [ ] `sortBy` 75cb6d70ee02de5334422275bbd87c57041d2270
- [ ] `pickBy` 549826b0e44bf8333b9ac509000ee08711a2f535
- [ ] `groupBy` 16c8bbd0943ceed43d3c1ed52e81bbc4f5564008
- [ ] `flatten` and `uniqueBy` 0f5c918fd50e9a454d89c1097bc5c738b8b2e277
- [ ] `setWith` 13ec11332a9fe6a8e981993f8dc989183bc25222

Debounce/throttle was replaced with a mix of custom functions and the `use-debounce` package. We might be able to refactor more to use hooks in the future but I left this to avoid complex refactoring:

- [ ] 8a645a40f2e060e2a232bf7a09c38cdde3c06e24
- [ ] 6541612ff3c5a8a8b54091fe21008e7419a64f5a
- [ ] f3a3b96056f7b63f7da96027cbc5494efc0a2292

To guard against future usage, an ES Lint rule has been added:

- [ ] bb44b4428784ef4766ed5896d570f7d7d14ca14c

Fixes #8642

### Testing

Changes should have a degree of e2e and JS test coverage since a broken replacement would have knock on effect to components using that functionality, so take extra case to make sure tests pass across the board.

Beyond this we should smoke test the critical flows, areas touched include:

- Checkout filling address form and changes being pushed
- Placing the order via checkout
- Inserting product blocks, handpicked products, filter blocks, products by category and checking the editor views work as expected. 

* [x] Do not include in the Testing Notes 

### Changelog

> Performance: Removed lodash dependency on the frontend.

### CODE REVIEW

File: assets/js/data/cart/test/push-changes.ts [hunk 1]
```diff
@@ -46,8 +46,8 @@ jest.mock( '@wordpress/data', () => ( {
 } ) );
 
 // Mocking lodash here so we can just call the debounced function directly without waiting for debounce.
```
Comment (wavvves) [inline assets/js/data/cart/test/push-changes.ts]:
```suggestion
// Mocking the debounce method so we can use the callback directly without waiting for debounce.
```

Comment (wavvves) [reply assets/js/data/cart/test/push-changes.ts]: Code seems fine, tests pass, functionality is preserved, no bad output on the console.. Apart from this forgotten comment, I haven't got anything to add, stellar work @mikejolley 
Green light for approval 👍🏼

**Review by wavvves — APPROVED** [review]
