### PR TITLE
Disable compatibility layer when the WooCommerce Product Grid Block block and WooCommerce Single Product Block are used

### LINKED ISSUE #8505: The `WooCommerce Product Grid Block` block is not visible on the front end when the `Products` block is on the same page.
## Describe the bug

The `WooCommerce Product Grid Block` block is not visible on the front end when the `Products` block is on the same page.

This issue is caused by the Compatibility Layer. Probably, the reason is it [removes default hooks](https://github.com/woocommerce/woocommerce-blocks/blob/f4ab91e00c307c798c05870ed427cc53b9e6818e/src/Templates/BlockTemplatesCompatibility.php/#L270). We should improve the logic and add the Compatibility Layer only when the `WooCommerce Product Grid Block` isn't on the page.

With #8507, we are disabling the Compatibility Layer because WC Blocks 9.6.0 will be included in WC Core, but we should on a "real" fix.

## To reproduce

1. With the [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/) theme installed, go to `Appearance » Editor`.
2. Edit the Product Catalog template, adding the Products block above the WooCommerce Product Grid Block.
3. Save.
4. Go to the front end and verify that the `WooCommerce Product Grid Block` isn't visible.

## Expected behavior

`WooCommerce Product Grid Block` should be visible. 

## Screenshots

https://user-images.githubusercontent.com/4463174/220608565-0912eae2-c337-40bf-b933-a37a20dd6669.mp4

### PR DESCRIPTION
**Pull request by gigitux**
This PR introduces a new filter called `woocommerce_disable_compatibility_layer` that allows disabling the compatibility layer.
At the same time, using the filter, the compatibility layer is disabled when Archive Product templates and Single Product template have the WooCommerce Product Grid Block.

This PR is blocked by https://github.com/woocommerce/woocommerce-blocks/pull/8442

Fixes #8505 

##### Archive Templates

1. With the [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/) theme installed, go to `Appearance » Editor`.
2. Edit the Product Catalog template, adding the Products block above the WooCommerce Product Grid Block.
3. Save.
4. Go to the front end and verify that the `WooCommerce Product Grid Block` is visible.

##### Single Product Template 

1. With the [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/) theme installed, go to `Appearance » Editor`.
2. Edit the Product Catalog template, adding the `Product Image Gallery block` above the WooCommerce Product Grid Block.
3. Save.
4. Go to the front end and verify that the `WooCommerce Product Grid Block` is visible.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [ ] Feature plugin
* [ ] Experimental

### CODE REVIEW

File: src/Templates/AbstractTemplateCompatibility.php [hunk 1]
```diff
@@ -0,0 +1,179 @@
...
+		$this->set_hook_data();
+
+		add_filter( 'render_block_data', array( $this, 'update_render_block_data' ), 10, 3 );
+		add_filter(
+			'render_block',
+			function ( $block_content, $block ) {
+				/**
+				* Filters to disable the compatibility layer for the blockified templates.
+				*
+				* This hooks allows to disable the compatibility layer for the blockified.
```
Comment (Aljullu) [inline src/Templates/AbstractTemplateCompatibility.php]:
```suggestion
				* This hook allows to disable the compatibility layer for the blockified templates.
```

File: src/BlockTemplatesController.php [hunk 2]
```diff
@@ -325,11 +326,22 @@ function( $template ) {
 					$template->description = BlockTemplateUtils::get_block_template_description( $template->slug );
 				}
 
+				if ( in_array( $template->slug, array( 'archive-product', ProductSearchResultsTemplate::SLUG, ProductAttributeTemplate::SLUG, 'taxonomy-product_cat', 'taxonomy-product_tag' ) ) ) {
+
+					if ( ! is_admin() && BlockTemplateUtils::template_has_legacy_template_block( $template ) ) {
+						add_filter( 'woocommerce_disable_compatibility_layer', '__return_true' );
+						return $template;
+					}
```
Comment (Aljullu) [inline src/BlockTemplatesController.php]: Nit: this `if` clause is the same here and in line 339-342. I wonder if it would make sense to move it before their parent if clauses, in line 328, so we avoid repeating it.

File: src/Templates/AbstractTemplateCompatibility.php [hunk 3]
```diff
@@ -0,0 +1,179 @@
...
+				* @since TBD
+				* @param boolean.
+				*/
+				$is_disabled_compatility_layer = apply_filters( 'woocommerce_disable_compatibility_layer', false );
+
+				if ( $is_disabled_compatility_layer ) {
+					return $block_content;
+				}
+
+				$this->inject_hooks( $block_content, $block );
```
Comment (Aljullu) [inline src/Templates/AbstractTemplateCompatibility.php]: Should this value be returned as well?
```suggestion
				return $this->inject_hooks( $block_content, $block );
```

**Review by Aljullu — COMMENTED** [review]
I can confirm this PR removes the compatibility later from the Products block and Single Product Template blocks when the Classic block exists in the page. However, for me it didn't fix https://github.com/woocommerce/woocommerce-blocks/issues/8505. Is this a known issue? I see #8550 fixes it, but I'm not sure to understand the relation between both PRs. :confused: 

I would also update the PR title because currently only makes reference to the Product Grid, but the changes introduced also work in the Single Product template.

Besides that, I just left some small comments below (some of them are applicable to #8550 as well).

**Comment by gigitux** [comment]
> I can confirm this PR removes the compatibility later from the Products block and Single Product Template blocks when the Classic block exists in the page. However, for me it didn't fix #8505. Is this a known issue? I see #8550 fixes it, but I'm not sure to understand the relation between both PRs. 😕
> 
> I would also update the PR title because currently only makes reference to the Product Grid, but the changes introduced also work in the Single Product template.
> 
> Besides that, I just left some small comments below (some of them are applicable to #8550 as well).

Thanks for the review, @Aljullu! I updated the PR title.

Also, I refactored this PR after the work that I did on #8505. In the end, it is the same solution. Also, I changed the destination branch to [add/compatibility-single-product-block](https://github.com/woocommerce/woocommerce-blocks/tree/add/compatibility-single-product-block), so the diff is smaller. When you will approve this PR, I will merge #8442 in the trunk!

**Review by Aljullu — APPROVED** [review]
After your last commits, this PR only includes changes to the docs/comments, is that correct or I'm missing anything?

If so, LGTM, but then maybe we should check `Do not include in the Testing Notes`? :thinking:

**Comment by gigitux** [comment]
Thanks for the review!

> After your last commits, this PR only includes changes to the docs/comments, is that correct or I'm missing anything?
> 

Yep, it is correct. We move these hooks from `BlockTemplatesCompatbility.php` to `AbstractTemplatesCompatbility.php`.

>  If so, LGTM, but then maybe we should check `Do not include in the Testing Notes`? 🤔

👍
