### PR TITLE
Refactor webpack splitting to fix missing translation

### LINKED ISSUE #6391: Translation Compatibility Issue with Preferred Languages
## Describe the bug
see a full description here: https://github.com/swissspidy/preferred-languages/issues/466

1) installed woocommerce & woocommerce blocks from wp repo
2) installed the WP feature plugin "Preferred Languages" (https://wordpress.org/plugins/preferred-languages/) with these settings configured
image

Quick Note of what the plugin solves: (common issue in german language)
_"This plugin lets you select multiple preferred languages in your settings. WordPress then tries to load the translations for the first language that's available, falling back to the next language in your list. This works great when you want to display WordPress in a locale like German (formal) and have it fall back to informal German when there's no translation available."
=> Now as the Swiss Translation is partially there i activated a filter that goes on a string level instead language level.

3) Although this perfectly works on all other plugins i saw for woo blocks i still see some strings in english as f.e. on the cart
"Proceed to checkout" as example
image

4) let's check the flow of the strings.

step a (not found, correct): https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de-ch/informal/?filters%5Bterm%5D=proceed&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

step b (not found, correct): https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de-ch/default/?filters%5Bterm%5D=proceed&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

step c (not found, incorrect): https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de/default/?filters%5Bterm%5D=proceed&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

On Step C the translation should be found and shown.

Same also happens f.e. on "shipping method"
[Step A](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de-ch/informal/?filters%5Bterm%5D=shipping+method&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) -> [Step B](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de-ch/default/?filters%5Bterm%5D=shipping+method&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) -> [Step C](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de/default/?filters%5Bterm%5D=shipping+method&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)

---

Plugin Developer Response

_"As for the missing translation, not sure what's going on at first glance.

But as you can see at https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/woocommerce-gutenberg-products-block.php, which you pointed to, the WooCommerce Blocks plugin has some very custom logic for loading translations.

It is very likely that this custom logic is not compatible with the way Preferred Languages works. Especially if translations otherwise work fine for your other plugins.

In that case I recommend reaching out to them about fixing this."_

## Expected behavior
WooCommerce Blocks allows a compatibility with the wordpress feature project.

Let me know if you need more details for anything :)

### PR DESCRIPTION
**Pull request by senadir**
This PR does a couple of things:

### Webpack
It fixes our webpack config by always omitting consistent and stable output names, previously, webpack would try to generate chunks from the good of its heart, but this would result in very awkward file names like:
- `'cart-blocks/order-summary--checkout-blocks/billing-address--checkout-blocks/shipping-address',`.
- `'product-add-to-cart--product-button--product-category-list--product-image--product-price--product-r--a0326d00.js'`.
This is no longer the case, we now control exactly the output of such files and their naming.
Doing that meant degradation in bundle size, I fixed that by omitting external packages and `wordpress-components` related code into separate chunks, this should make the bundle size better.
It should be noted that the overall bundle size increased a bit, because some wordpress/components related code wasn't fully abstracted out, I plan to address that in a future iteration. 

Part of this PR is also switching from `build/${blockName}/block.json` notation for block.json files to `build/${blockName}.block.json`, this reduces the amount of folders we have. It should be noted that PHP `register_block_type_from_metadata` only support files that are named `block.json` or end with `block.json`.

### Translation
To fix this, I needed to do the webpack work, basically we have two issues here:
- When we shift our files output, or split old files into new files, our translation no longer work, because we manually load translation in the backend, we need to update the hardcoded names to reflect that, we failed to do that when we split the summary block, it's now fixed.
- The second issue is that we now have new files, and json translation is a file-name based translation, so we ended up with missing json files and needing to wait until the next release for them to work, this is fine for people who consume our plugin from wp.org but would break our tests, for this, we added a code that will regenerate all json files each time, reflecting the same result you have if you download from wp.org
- The third issue we had is that some translation terms changed between releases, we fixed that (for now) but I know this will come bite us back later.

### Future work
As to not take an eternity here, and given this PR is already doing two things, we have further future improvements to make:
- [ ] Switch from using Dutch to a custom language file that we build and load in E2E.
    - this ensures we have stable terms, and reduces the complexity of needing to download from an external source, as well as changing terms. @dinhtungdu already started experimenting with this in https://github.com/woocommerce/woocommerce-blocks/pull/6424, we might do a custom json or a custom po, up for debate.
- [ ] Further improve splitChunks and shared code.
    - SplitChunks, will working well, increased the bundle size slightly, there are more gains we can get with wordpress components, that we can explore by tweaking the splitChunks params and checks.
- [ ]  Load chunk names dynamically instead of hard-coding.
    - We currently hard-code chunks names for each block, they're now all stable inside a folder `cart-blocks` `checkout-blocks` `mini-cart-content-blocks`, so we can iterate those folders and load names, this is one less step to forget when splitting blocks in the future or adding new blocks.
- [ ] Support plural terms translation in E2E.
    - One weird bug we run into (that I reported [here](https://github.com/wp-cli/i18n-command/issues/324)) is that when updating a `.po` file, plural translation is gone, for that, we needed to refactor some of our tests, this issue happens when using `wp i18n make-pot --merge`, but isn't present if you do `wp i18n make-json` or `msgmerge`, If the issue above is fixed and we switch to a local language, this is also fixed, apart from that, we need to either switch to merging with `msgmerge`, which would require installing `gettext` on docker, or keeping an eye for plural translations in E2E, which isn't fun.
- [ ] Fetch plugin folder name inside `bin/wp-env-config.sh`.
    - To have wp-env-config work locally and in CI, we can't hardcode the plugin name, for that, we pass it as an arg in `bin/wp-env-pre-config.sh`, this isn't the cleanest solution and I prefer if we can have it as a env param somewhere that is shared easily.

Fixes #6391

#### Automated Tests
* [ ] Changes in this PR are covered by Automated Tests.
  * [] Unit tests
  * [x] E2E tests

### Translation
1. no code testing can happen once we release 7.7.0, for now, you need some code.
2. In your main WordPress folder (the one that contains wp-content, wp-includes, wp-admin), run those commands:
    1. `curl https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/nl/default/export-translations/ --output ./wp-content/languages/plugins/woo-gutenberg-products-block-nl_NL.po`
    2. `php -d memory_limit=2024M "$(which wp)" i18n make-pot ./wp-content/plugins/woo-gutenberg-products-block/ ./wp-content/languages/plugins/woo-gutenberg-products-block-nl_NL-updated.po --merge=./wp-content/languages/plugins/woo-gutenberg-products-block-nl_NL.po --domain=woo-gutenberg-products-block --exclude=node_modules,vendor --skip-audit` **Replace `woo-gutenberg-products-block` with your plugin name if you have something else.**
    3. `mv ./wp-content/languages/plugins/woo-gutenberg-products-block-nl_NL-updated.po ./wp-content/languages/plugins/woo-gutenberg-products-block-nl_NL.po`
    4. `php -d memory_limit=2024M "$(which wp)" i18n make-json ./wp-content/languages/plugins/woo-gutenberg-products-block-nl_NL.po`
5. Visit Cart page, everything should be translated and working fine.
6. Visit Checkout page, everything should be translated and working fine.

### Webpack
1. Run `npm run build` and smoke test Cart/Checkou/Mini Cart and make sure there are no console errors and everything is loading fine.

* [x] Do not include in the Testing Notes 

### WooCommerce Visibility

* [x] WooCommerce Core
* [x] Feature plugin
* [ ] Experimental

### Performance Impact

This increases some of the bundles sizes a bit.

### Changelog

> Fix broken translation in Cart/Checkout blocks.

### CODE REVIEW

File: bin/webpack-configs.js [hunk 1]
```diff
@@ -261,20 +259,20 @@ const getMainConfig = ( options = {} ) => {
...
 						from: './assets/js/blocks/featured-product/block.json',
-						to: './featured-product/block.json',
+						to: './featured-product.block.json',
 					},
 					{
 						from:
 							'./assets/js/blocks/handpicked-products/block.json',
-						to: './handpicked-products/block.json',
+						to: './handpicked-products.block.json',
 					},
```
Comment (senadir) [inline bin/webpack-configs.js]: To reduce the amount of folders we have, I refactored this cc @opr and @albarin

File: bin/webpack-configs.js [hunk 2]
```diff
@@ -367,7 +365,39 @@ const getFrontConfig = ( options = {} ) => {
...
+							}
+						},
+						name: 'cart-checkout/commons.js',
+						automaticNameDelimiter: '--',
+						reuseExistingChunk: true,
+						enforce: true,
+						minSize: 20000,
+						priority: -10,
+					},
+				},
```
Comment (senadir) [inline bin/webpack-configs.js]: This groups all wordpress-components into a single file, I should try to add emotion to this as well.

File: bin/webpack-configs.js [hunk 3]
```diff
@@ -367,7 +365,39 @@ const getFrontConfig = ( options = {} ) => {
...
+							const moduleFileName = module
+								.identifier()
+								.split( '/' )
+								.reduceRight( ( item ) => item );
+							return `vendor/${ moduleFileName }`;
+						},
+						automaticNameDelimiter: '--',
+						minSize: 20000,
+						priority: -20,
+					},
```
Comment (senadir) [inline bin/webpack-configs.js:393]: This moves all shared vendor files into single output, things like Dinero and such.

File: bin/webpack-configs.js [hunk 4]
```diff
@@ -367,7 +365,39 @@ const getFrontConfig = ( options = {} ) => {
 			concatenateModules:
 				isProduction && ! process.env.WP_BUNDLE_ANALYZER,
 			splitChunks: {
-				automaticNameDelimiter: '--',
+				cacheGroups: {
+					default: false,
```
Comment (senadir) [inline bin/webpack-configs.js:380]: In theory, this group would group common shared internal code into a single file, however, it resulted in a very awkward files with tilds and very long folder names.

I think I can make this better by having a minSize here and more controlled name function. One issue stands in which a split file would end up being empty but that's up for testing first.

File: bin/webpack-configs.js [hunk 5]
```diff
@@ -367,7 +365,39 @@ const getFrontConfig = ( options = {} ) => {
 			concatenateModules:
 				isProduction && ! process.env.WP_BUNDLE_ANALYZER,
 			splitChunks: {
-				automaticNameDelimiter: '--',
+				cacheGroups: {
```
Comment (senadir) [inline bin/webpack-configs.js:379]: I didn't test `fallbackCacheGroup` which would probably help with default ones.

**Comment by nielslange** [comment]
I ran a quick test and using es_ES, nl_NL and de_DE. The fix seems to work as expected. However, I noticed that the field `Phone (optional)` resp. `Phone` is remains untranslated in the frontend:

Screenshot 2022-05-17 at 15 39 56

Given that the other shipping and billing fields are translated, I don't have an explanation for that. Given the fact that the translation is visible in the editor, we know that there is a translation available in GlotPress. I can also see the corresponding translation in the the translation file `wp-content/languages/plugins/woo-gutenberg-products-block-es_ES-4c60615efdf3e30abc8707708d3e9c47.json`:

```json
...
"Phone (optional)":["Tel\u00e9fono (opcional)"],
...
"Phone":["Tel\u00e9fono"],
...
```

~Do you have an explanation why this particular field appears untranslated in the frontend?~

I noticed that the junk reference is `"reference":"build\/checkout-blocks\/billing-address--checkout-blocks\/shipping-address-frontend.js"` which you seem to have removed.

**Comment by senadir** [comment]
We will need to:
- Find which built file has that string in it.
- If we're queuing that file's translation.
- It will show up on the next release once translation files are regenerated.

**Comment by senadir** [comment]
Phone (optional) exists in 3 files now, so it should be translated just fine in a future release
image

**Comment by nielslange** [comment]
> Phone (optional) exists in 3 files now, so it should be translated just fine in a future release

Thanks for double-checking this, @senadir!

File: tests/e2e/specs/shopper/mini-cart.test.js [hunk 6]
```diff
@@ -626,9 +626,9 @@ describe( 'Shopper → Mini Cart', () => {
 				);
 
 				await expect( page ).toMatchElement(
-					'.wc-block-mini-cart__title',
+					'.wc-block-mini-cart__footer-cart',
 					{
-						text: 'Je winkelwagen (1 stuk)',
+						text: 'Bekijk mijn winkelwagen',
```
Comment (senadir) [inline tests/e2e/specs/shopper/mini-cart.test.js:631]: Due to an [issue with `wp i18n`](https://github.com/wp-cli/i18n-command/issues/324), plural terms aren't copied when updating a string. We switched to checking for non-plural terms till that issue is fixed.

File: tests/e2e/specs/shopper/cart-checkout/translations.test.js [hunk 7]
```diff
@@ -89,7 +90,7 @@ describe( 'Shopper → Cart & Checkout → Translations', () => {
 		await expect( orderSummary ).toMatch( 'Besteloverzicht' );
 		await expect( orderSummary ).toMatch( 'Subtotaal' );
 		await expect( orderSummary ).toMatch( 'Waardebon code' );
-		await expect( orderSummary ).toMatch( 'Verzendmethoden' );
+		await expect( orderSummary ).toMatch( 'Verzending' );
```
Comment (senadir) [inline tests/e2e/specs/shopper/cart-checkout/translations.test.js:94]: This translation changed in recent releases.

File: tests/e2e/specs/shopper/cart-checkout/translations.test.js [hunk 8]
```diff
@@ -34,12 +34,13 @@ describe( 'Shopper → Cart & Checkout → Translations', () => {
 		const removeLink = await page.waitForSelector(
 			'.wc-block-cart-item__remove-link'
 		);
-		await expect( removeLink ).toMatch( 'Artikel verwijderen' );
+		await expect( removeLink ).toMatch( 'Verwijder item' );
```
Comment (senadir) [inline tests/e2e/specs/shopper/cart-checkout/translations.test.js:38]: This translation changed in recent releases.

File: bin/wp-env-pre-config.sh [hunk 9]
```diff
@@ -1,3 +1,4 @@
 #!/bin/sh
 BASENAME=$(basename "`pwd`")
-npm run wp-env run tests-cli './wp-content/plugins/'$BASENAME'/bin/wp-env-config.sh'
+# We need to pass the blocks plugin folder name to the script, the name can change depending on your local env and we can't hardcode it.
+npm run wp-env run tests-cli './wp-content/plugins/'$BASENAME'/bin/wp-env-config.sh' $BASENAME
```
Comment (senadir) [inline bin/wp-env-pre-config.sh:4]: We need to pass the working dir name, this is needed because it reflects your local folder name, which might not match `woo-gutenberg-products-block`

File: bin/wp-env-config.sh [hunk 10]
```diff
@@ -19,13 +19,19 @@ wp core version --extra
...
+sleep 5
+## We generate a new po file, based on the one we just downloaded, but with updated file paths.
+## This should account for when a file changes location between versions.
+php -d memory_limit=2024M "$(which wp)" i18n make-pot ./wp-content/plugins/$1/ ./wp-content/languages/plugins/woo-gutenberg-products-block-nl_NL-updated.po --merge=./wp-content/languages/plugins/woo-gutenberg-products-block-nl_NL.po --domain=woo-gutenberg-products-block --exclude=node_modules,vendor --skip-audit
+## We remove the po we downloaded.
+rm ./wp-content/languages/plugins/woo-gutenberg-products-block-nl_NL.po
+## And rename the one we just created to that one.
+mv ./wp-content/languages/plugins/woo-gutenberg-products-block-nl_NL-updated.po ./wp-content/languages/plugins/woo-gutenberg-products-block-nl_NL.po
+## We regenerate json translation from the new po file we created.
+php -d memory_limit=2024M "$(which wp)" i18n make-json ./wp-content/languages/plugins/woo-gutenberg-products-block-nl_NL.po
```
Comment (senadir) [inline bin/wp-env-config.sh]: The bulk of this logic is that we want to update the translation files with new paths that might have changed since the last release, basically updating the po/json files, this should avoid E2E failing between releases.

File: src/BlockTypes/Checkout.php [hunk 11]
```diff
@@ -401,17 +401,25 @@ public static function include_token_id_with_payment_methods( $list_item, $token
...
-			'checkout-blocks/billing-address--checkout-blocks/shipping-address',
-			'checkout-blocks/billing-address',
 			'checkout-blocks/shipping-methods',
-			'checkout-blocks/payment',
-			'checkout-blocks/order-note',
-			'checkout-blocks/actions',
 			'checkout-blocks/terms',
-			'checkout-blocks/order-summary',
+			'checkout-blocks/totals',
 		];
```
Comment (senadir) [inline src/BlockTypes/Checkout.php]: I attempted to write a code that traverse the `checkout-blocks` folder to get all files, but my code felt very hacky :/

```php
foreach ( new \DirectoryIterator( dirname( dirname( __DIR__ ) ) . '/build/checkout-blocks' ) as $file ) {
			if ( $file->isFile() ) {
					print $file->getFilename() . "\n";
			}
		}
```

Maybe @dinhtungdu or @wavvves you know a better way without me hardcoding the build file and needing to traverse folders manually up.

**Comment by senadir** [comment]
Failing E2E tests are known to be flacky, and I will look into them later.

File: src/BlockTypes/Checkout.php (hunk 11 above)
Comment (dinhtungdu) [reply src/BlockTypes/Checkout.php]: > needing to traverse folders manually up.

We can use the `Package::get_path()` to avoid traversing folders:

```
foreach ( \Automattic\WooCommerce\Blocks\Package::get_path() . 'build/checkout-blocks' ) as $file ) {
```

Comment (dinhtungdu) [reply src/BlockTypes/Checkout.php]: I think if we only need file paths, we can use `glob()` instead of `DirectoryIterator`.

`glob()` consumes less memory because it doesn't create any object, but the performance difference is negligible IMO.

File: tests/e2e/specs/shopper/cart-checkout/translations.test.js (hunk 8 above)
Comment (dinhtungdu) [reply tests/e2e/specs/shopper/cart-checkout/translations.test.js:38]: @senadir do you see the translation of `Remove item` on your end? In my test, other strings work but the translation of the remove link wasn't loaded. Tested with this PR, `trunk`, and the .org release.

Screen Shot 2022-05-19 at 14 19 25

Comment (gigitux) [reply tests/e2e/specs/shopper/cart-checkout/translations.test.js:38]: I just tested this PR and I see the translation for the remove link 
image

File: bin/webpack-configs.js [hunk 12]
```diff
@@ -367,7 +365,39 @@ const getFrontConfig = ( options = {} ) => {
 			concatenateModules:
 				isProduction && ! process.env.WP_BUNDLE_ANALYZER,
 			splitChunks: {
-				automaticNameDelimiter: '--',
```
Comment (gigitux) [inline bin/webpack-configs.js:381]: Is it intentional to remove this line? 
I'm asking because we are adding the line [here](https://github.com/woocommerce/woocommerce-blocks/pull/6420/files#diff-fe2a96dd06027bb736a2f6e1cbaae6d5174d6aefd9fc1058a2527f810648504aR394)

File: bin/webpack-configs.js [hunk 13]
```diff
@@ -367,7 +365,39 @@ const getFrontConfig = ( options = {} ) => {
...
+								.identifier()
+								.split( '/' )
+								.reduceRight( ( item ) => item );
+							return `vendor/${ moduleFileName }`;
+						},
+						automaticNameDelimiter: '--',
+						minSize: 20000,
+						priority: -20,
+					},
+					'cart-checkout-wp-commons': {
```
Comment (gigitux) [inline bin/webpack-configs.js]: Is correct this name? From what I understand, we are creating a single file for all wordpress-components. What is the relationship with the `cart-checkout`?

File: bin/webpack-configs.js [hunk 14]
```diff
@@ -367,7 +365,39 @@ const getFrontConfig = ( options = {} ) => {
...
+						test: ( module ) => {
+							if (
+								module?.resource?.match(
+									/wordpress-components/
+								)
+							) {
+								return true;
+							}
+						},
+						name: 'cart-checkout/commons.js',
```
Comment (gigitux) [inline bin/webpack-configs.js]: Same here

**Review by gigitux — COMMENTED** [review]
Thanks for working on this!

I added some questions about the webpack configuration. I'm not very expert, so sorry if I didn't catch obvious stuff.
For the rest, I think that this PR is ready!

P.S: There are some conflicts. Could you resolve them?

File: tests/e2e/specs/shopper/cart-checkout/translations.test.js (hunk 8 above)
Comment (senadir) [reply tests/e2e/specs/shopper/cart-checkout/translations.test.js:38]: Tung, in your local branch, did you update your translations by using make-pot and make-json?

File: bin/webpack-configs.js (hunk 12 above)
Comment (senadir) [reply bin/webpack-configs.js:381]: It's now part of the cache group yeah.

**Comment by senadir** [comment]
Addressed feedback, waiting for tests to pass.

**Review by gigitux — APPROVED** [review]
Thanks for working on this!
LGTM 🎉

File: tests/e2e/specs/shopper/cart-checkout/translations.test.js (hunk 8 above)
Comment (dinhtungdu) [reply tests/e2e/specs/shopper/cart-checkout/translations.test.js:38]: > Tung, in your local branch, did you update your translations by using make-pot and make-json?

@senadir Sorry for missing this. In my test, I tested with translations downloaded from wordpress.org.

Tested the `trunk` after merging this branch, and the translation issue is fixed.
