### PR TITLE
Fix filter by stock status dropdown ordering

### LINKED ISSUE #7928: Weird options ordering in Filter by Stock Status dropdown version
The chosen options change the order after applying the filter in the Filter by Stock Status (dropdown version). Check the video below:

https://user-images.githubusercontent.com/4463174/207090261-d20c13ec-7854-48ce-b628-eb67a8adb4d0.mp4

Steps to reproduce:
1. Make sure you have at least one product with the stock status: "In stock", "Out of Stock" and/or "On backorder"
2. In the Editor add:
  - *Filter by Stock* block - set it to Dropdown and Multiple
  - *Products* block
3. In the frontend apply stock status filters: "In stock", "Out of Stock" and/or "On backorder"
4. Refresh the page if it hasn't refreshed itself

**Actual:** Order of the filters stays the same
**Expected:** Order of the filters changes as on the video

_Originally posted by @gigitux in https://github.com/woocommerce/woocommerce-blocks/issues/7831#issuecomment-1346765503_

### PR DESCRIPTION
**Pull request by kirtangajjar**
Fixes #7928 

### Screenshots

**Before** 

https://user-images.githubusercontent.com/8456197/233193490-8cddb289-3de2-47eb-9851-00c4785ada40.mp4

**After**

https://user-images.githubusercontent.com/8456197/233193795-ee257ba5-5d37-4a88-95dc-4a9e3d269ab3.webm

#### User Facing Testing

1. Make sure you have at least one product with the stock status: "In stock", "Out of Stock" and/or "On backorder"
2. In the Editor add:
 * Filter by Stock block - set it to Dropdown and Multiple
 * Products block
3. In the frontend apply stock status filters: "In stock", "Out of Stock" and/or "On backorder"
4. Refresh the page if it hasn't refreshed itself
5. Expected: The order of the options stays the same before the refresh and after the refresh

* [ ] Do not include in the Testing Notes 

### Performance Impact

This will add a positive impact to performance as it reduces one redirect which occurred due to change of order of parameters

### Changelog

> Fix filter by stock status dropdown ordering

### CODE REVIEW

File: assets/js/blocks/stock-filter/utils.ts [hunk 1]
```diff
@@ -23,8 +23,9 @@ export const getActiveFilters = (
 		? params.split( ',' )
 		: ( params as string[] );
 
-	return Object.keys( filters ).filter( ( filter ) =>
```
Comment (kirtangajjar) [inline assets/js/blocks/stock-filter/utils.ts:26]: Here, the filters variable, which is a predefined collection of stock statuses coming from the server used to define the order of status since that's what the filter was applied on. 

I instead put the filter on `parsedParams`, which are the stock statuses selected by the user. This variable also has them in the correct order.

File: assets/js/blocks/stock-filter/utils.ts [hunk 2]
```diff
@@ -23,8 +23,9 @@ export const getActiveFilters = (
...
-		parsedParams.includes( filter )
+	const filter_keys = Object.keys( filters );
+	return parsedParams.filter( ( param ) =>
+		filter_keys.includes( param )
 	);
```
Comment (nefeline) [inline assets/js/blocks/stock-filter/utils.ts]: To ensure we are following the correct naming conventions, I'd recommend updating the variable name to `filterKeys` instead and also updating the format to clear out all JS lint errors.
```suggestion
	const filterKeys = Object.keys( filters );

	return parsedParams.filter( ( param ) => filterKeys.includes( param ) );
	);
```

**Review by nefeline — CHANGES_REQUESTED** [review]
Hi there @kirtangajjar,

Great work! Thank you so much for your contribution! I can confirm the ordering of the stock status is now consistent/correct:

https://user-images.githubusercontent.com/15730971/233214292-3d9157ae-1516-4cc0-a001-45e42ea9388b.mov

I left a recommendation to ensure the correct naming convention is used and to clear out the JS lint errors. With those out of the way, we should be good to go :shipit:

**Comment by kirtangajjar** [comment]
@nefeline Committed your suggestions. Thanks!

File: assets/js/blocks/stock-filter/utils.ts [hunk 3]
```diff
@@ -23,8 +23,9 @@ export const getActiveFilters = (
 		? params.split( ',' )
 		: ( params as string[] );
 
-	return Object.keys( filters ).filter( ( filter ) =>
-		parsedParams.includes( filter )
+	const filterKeys = Object.keys( filters );
+
+	return parsedParams.filter( ( param ) => filterKeys.includes( param ) );
 	);
```
Comment (nefeline) [inline assets/js/blocks/stock-filter/utils.ts]: Just remove this now unnecessary closing round bracket, and we should be all set!
```suggestion
```

**Review by nefeline — CHANGES_REQUESTED** [review]
> @nefeline Committed your suggestions. Thanks!

Excellent, thank you so much! I just left a final recommendation to remove a now unnecessary closing bracket: after this change, we should be good to go 🚢 !

**Review by nefeline — APPROVED** [review]
Excellent work @kirtangajjar !

All tests are now passing successfully, so I'm going ahead and merging this PR.

Thanks again for contributing to Woo Blocks 🎉 !
