### PR TITLE
Price Slider -- Only do instant updates if filter button is disabled

### LINKED ISSUE #1211: Price filter block: changes are applied instantly even when Filter button is visible
**To Reproduce**
1. Add an _All Products_ block and a _Price Filter_ block (with the option _Filter Button_ set to true) to a post.
2. Preview the post.
3. Move the price slider.
4. Notice products update instantly.

**Expected behavior**
If the _Filter Button_ is visible, I expect changes to only be applied when clicking _Go_.

**Screenshots**
Peek 2019-11-18 15-50

### PR DESCRIPTION
**Pull request by mikejolley**
The price filter block has a `useEffect` to track state changes and update the query. This should only run if the filter button is disabled, otherwise query updates should be manual.

Fixes #1211

### How to test the changes in this Pull Request:

1. Test all products with price slider
2. Enable the filter button in block settings
3. Change the range slider. Nothing should update. Click the button. The products should then update.
4. Disable the filter button and ensure original behaviour still exists.

### Changelog

> Fix the price slider filter button.

### CODE REVIEW

File: assets/js/blocks/price-filter/block.js [hunk 1]
```diff
@@ -72,8 +72,10 @@ const PriceFilterBlock = ( { attributes, isPreview = false } ) => {
 
 	// Track price STATE changes - if state changes, update the query.
 	useEffect( () => {
-		debouncedUpdateQuery();
-	}, [ minPrice, maxPrice ] );
+		if ( ! attributes.showFilterButton ) {
+			debouncedUpdateQuery();
+		}
+	}, [ minPrice, maxPrice, attributes ] );
```
Comment (Aljullu) [inline assets/js/blocks/price-filter/block.js]: Instead of setting `attributes` as a dependency you can directly set `attributes.showFilterButton`:
```suggestion
	}, [ minPrice, maxPrice, attributes.showFilterButton ] );
```

Comment (nerrad) [reply assets/js/blocks/price-filter/block.js]: agree with @Aljullu 's suggestion here, and that's also preferable because it reduces the number of times this block will be executed (attributes is a non-primitive so that will more frequently fail the reference equality comparison)
